"""Translate all 228 strings of Demeter in Hades II."""
from pathlib import Path
import sys

ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(ROOT / "tools"))
from hades2_sjson_helper import apply_translation_to_sjson

SRC = ROOT / "games/0100A00019DE0000_Hades2/source/raw_text/en/_LootData_Demeter.en.sjson"
OUT = ROOT / "games/0100A00019DE0000_Hades2/translations/Game/Text/en/_LootData_Demeter.en.sjson"

translations = {
    # Intro / Interaction cues
    "Melinoe_0647": "Ấn ký của băng giá...",
    "Melinoe_1480": "{#Emph}Lạnh buốt...",
    "Melinoe_1481": "Bà ngoại...",
    "Melinoe_0648": "Hiệu trưởng đã kể cho con rất nhiều điều về bà, và giờ cuối cùng chúng ta cũng gặp mặt. {#Emph}Nhân danh Hades! Hỡi Olympus, con xin tiếp nhận thông điệp này!",
    
    # Duo / Family banters
    "Demeter_0099": "Thuở xưa khi các chị em, các dưỡng huynh đệ và ta lật đổ Chronos, bọn ta cũng chỉ trạc tuổi {#Emph}cháu {#Prev}bây giờ, đóa hoa nhỏ ạ. Giờ ta đã già hơn, người ta thường nghĩ sẽ khôn ngoan hơn... dẫu những cuộc cãi vã triền miên và sự trì trệ của bọn ta lại nói lên điều ngược lại.",
    "Zeus_0158": "Gia đình chúng ta ai nấy đều có ý chí kiên định, điều đó Phu nhân Demeter hiểu quá rõ mà. Chúng ta phải đồng lòng tiến lên! Để đạt được sự đồng thuận như vậy đâu phải lúc nào cũng nhanh chóng; nhưng mỗi người đều có thể góp phần thúc đẩy nó.",
    "Demeter_0101": "Gần đây, ngay cả cô em gái rạng ngời của ta cũng phải vấy bẩn đôi bàn tay thanh mảnh vào đủ thứ công việc ngoài chiến địa. Con bé thậm chí bắt đầu quen với nó rồi... đúng không, Nữ hoàng Hera của chúng ta?",
    "Hera_0108": "{#Emph}Ồ{#Prev}, Demeter. Đôi bàn tay này đã nếm trải nhiều điều hơn chị tưởng đấy! Ta chỉ đơn giản là không phô trương những gian khổ mình đã chịu đựng thôi. Người ta {#Emph}hoàn toàn có thể {#Prev}cứng rắn như đá tảng mà chẳng cần phải mang vẻ ngoài thô ráp như nó.",
    "Demeter_0071": "Cháu gái, Poseidon ở đây vừa say sưa kể cho ta nghe về lần những con sóng của chú ấy nuốt trọn nửa mặt đất! {#Emph}Aha{#Prev}, đúng là một trận đại hồng thủy kinh hoàng! Biết đâu sức mạnh của chúng ta có thể kết hợp thêm lần nữa...",
    "Poseidon_0185": "Ồ, chẳng có chữ {#Emph}biết đâu {#Prev}nào ở đây đâu, Demeter! Chúng ta sẽ cùng nhau vượt qua cơn bão này! Ta cũng muốn khuấy động một trận lụt vĩ đại khác để ôn lại chuyện {#Emph}Xưa{#Prev}, chỉ hiềm nỗi... dạo này trần gian lắm phàm nhân quá!",
    "Demeter_0103": "Cháu biết đấy, đóa hoa nhỏ, phàm nhân luôn khao khát được giống như chúng ta ra sao rồi chứ? Nhưng khi làm vậy, họ lại nhiễm phải những thói xấu của ta. Có lẽ đó là lỗi của Thần Apollo, bởi ngài ấy chính là chuẩn mực mà họ luôn hướng tới!",
    "Apollo_0098": "Con có lỡ lời xúc phạm điều gì chăng, Phu nhân Demeter đáng kính? Con biết thời buổi này vô cùng tàn khốc, nhưng sao chúng ta không trút nỗi tàn khốc ấy lên đầu kẻ thù, thay vì cứ đay nghiến lẫn nhau ở đây?",
    "Demeter_0105": "Sự cứu viện từ Olympus có thể mang nhiều hình thái khác nhau... bởi không phải ai trong chúng ta cũng được chuẩn bị hay thậm chí {#Emph}sinh ra {#Prev}để đương đầu với những kiếp nạn gian truân. Lấy ví dụ như, nàng Aphrodite kiều diễm tuyệt trần ở đằng kia...",
    "Aphrodite_0149": "Ôi, Phu nhân Demeter, người thừa biết điều đó là {#Emph}hoàn toàn {#Prev}vô căn cứ mà! Con có thể thích ái tình hơn chiến trận, nhưng không có nghĩa con sẽ không cào nát mặt kẻ thù nếu điều đó khiến chúng phải {#Emph}chùn bước! {#Prev}Giờ sao chúng ta không cho cháu gái người thấy đôi ta hòa thuận thế nào nhỉ?",
    "Demeter_0107": "Đôi khi ngay cả {#Emph}ta {#Prev}cũng cần một chút hơi ấm, đóa hoa nhỏ ạ, thứ mà lò rèn của Hephaestus ở đây mang lại. Có lẽ xem như bù đắp cho sự thiếu vắng {#Emph}hơi ấm gia đình {#Prev}hoàn toàn giữa hầu hết các thành viên chúng ta.",
    "Hephaestus_0128": "{#Emph}À{#Prev}, cứ {#Emph}lắng nghe {#Prev}Phu nhân Demeter mà xem! Ai nấy trên đỉnh núi này cũng tưởng mình {#Emph}sắc sảo ghê gớm{#Prev}, còn {#Emph}bà ấy {#Prev}thì sao? Thẳng thắn thô ráp như chính cây búa của ta vậy. Mà một vài công việc thì luôn cần đến công cụ nặng đô, đúng chứ?",
    "Demeter_0109": "Bà cô Hestia của cháu không hẳn giống như vẻ ngoài của bà ấy {#Emph}đâu. {#Prev}Thuở xa xưa, bà ta chỉ an phận để ngọn lửa của mình bập bùng nơi bếp lò của những mái nhà trần thế. Nhận đi, người chị gái: Chị đã thay đổi rồi.",
    "Hestia_0154": "Còn cô, Demeter, cô chẳng thay đổi chút {#Emph}nào cả! Không một ai {#Prev}trong các người chịu đổi thay! Đó là lý do vì sao các người đang ngập đầu trong {#Emph}rắc rối {#Prev}bây giờ, hay đúng hơn là {#Emph}chúng ta {#Prev}. May mà đứa cháu ngoan của cô đang tới giải cứu chúng ta đấy!",
    "Demeter_0190": "{#Emph}Ôi{#Prev}, Ares. Ngay cả vị thần chiến tranh hăng máu nhất của chúng ta cũng không thể lập tức dập tắt những tai ương mà gia tộc ta đang phải gánh chịu. Ngươi nắm giữ quyền năng vùng đất của mình kém cỏi đến thế sao?",
    "Ares_0163": "Bọn ta đều dốc lòng làm hết sức mình, hỡi Demeter. Về phần ta, ta đảm bảo các cuộc chiến được khơi mào khi cần thiết, và kết cục tất yếu sẽ được an bài. Nhưng ta không thể bảo đảm chính xác thời hạn hay mức độ tàn khốc của chúng, bởi bạo lực tự thân nó là một mãnh lực riêng biệt.",

    # Core narrative & family bonds
    "Demeter_0002": "...Cháu trông giống hệt mẹ mình. Ta sẽ không để mất con bé thêm lần nào nữa. Ta sẵn sàng đóng băng toàn bộ địa ngục nếu điều đó có thể mang con bé trở về. Cháu sẽ giúp ta chứ, cháu gái ngoan?",
    "Demeter_0066": "{#Emph}Ôi{#Prev}, cháu bị thương rồi! Dòng máu nửa người phàm của cháu là nguồn cơn. Và cả ta nữa, khi đã trót đem lòng yêu một chàng nông dân thuở nào...",
    "Demeter_0065": "Có chuyện gì đã xảy ra vậy, cháu gái? Cầu cho lũ khốn nạn dám làm tổn thương cháu phải chịu đày đọa gấp ngàn lần vì những gì chúng đã gây ra.",
    "Demeter_0158": "Đã thương tích đầy mình rồi ư...! Hãy nhớ rằng những nỗi đau ta nếm trải chính là cách để ta tôi luyện và trưởng thành. Và kẻ thù của chúng ta sắp sửa phải nếm trải {#Emph}rất nhiều cay đắng đấy.",
    "Demeter_0159": "Cháu phải đổ máu hằng đêm vì những sai lầm của thế hệ trước. Từ chốn xa xôi này ta không thể chữa lành vết thương cho cháu, nhưng ta {#Emph}có thể {#Prev}nghiền nát lũ kẻ thù thành {#Emph}trăm mảnh vụn{#Prev}, nếu điều đó an ủi được phần nào.",
    "Demeter_0073": "Khi cháu dấn thân vào lần thử thách tiếp theo tưởng chừng bất khả thi này, hãy biết rằng ta luôn sát cánh bên cháu đến cùng trời cuối đất. Ít nhất là dưới hình hài của một lời chúc phúc.",
    "Demeter_0074": "Hãy tiến bước vào gian truân này cùng ân huệ của ta, cháu gái. Ta có linh cảm đêm nay sẽ là một đêm vô cùng băng giá dành cho kẻ thù của chúng ta...",
    "Demeter_0161": "Dẫu đêm nay có đưa cháu xuống tận đáy sâu địa ngục rồi trở lại, ta vẫn nguyện lòng đồng hành. Tiếc thay, đây là điều tốt nhất ta có thể làm từ phương xa.",
    "Demeter_0162": "Thời tiết đêm nay báo hiệu một đợt giá lạnh đột ngột tràn về. Dẫu sao thì cháu cũng đã quá quen với cái lạnh buốt xương rồi, đúng không?",
    "Demeter_0033": "Ta nhớ mẹ cháu khôn nguôi, và cả anh trai cháu nữa. Thằng bé từng là mầm non bé nhỏ của ta. Chronos hẳn đã giam hãm thằng bé cùng những người khác trong Gia môn của phụ thân cháu, cái lão già tàn độc không thể thứ tha...",
    "Demeter_0280": "Anh trai Zagreus của cháu, ta ngờ rằng thằng bé giờ không còn là mầm non bé bỏng ngày nào, mà đã vươn mình thành một Vương tử Âm phủ uy dũng. Việc hai đứa cuối cùng cũng nhận mặt nhau khiến trái tim già cỗi này được an ủi bội phần.",
    "Demeter_0034": "Melinoë... Ta từng đinh ninh cháu đã bỏ mạng. Vừa mới chào đời đã bị Chronos cướp đi, cùng với con gái ta và những người thân thuộc nhất. Nhưng Phù thủy Ngã ba Địa Giới đã cứu cháu thoát khỏi đó sao? Sao bà ta có thể không gửi lấy một lời báo tin...?",
    "Demeter_0035": "Khi Apollo rạng ngời tập hợp chúng ta và thông báo rằng muội muội song sinh của nó, trong lúc săn lùng kẻ thù, đã tình cờ phát hiện một đứa cháu thất lạc bên cạnh Phù thủy Ngã ba Địa Giới, chao ôi... ta vừa vỡ òa vui sướng lại vừa phẫn nộ khôn cùng...",
    "Demeter_0036": "Cháu đã có thể báo tin cho chúng ta; báo cho {#Emph}ta{#Prev}, trong suốt những năm tháng cháu khôn lớn kiên cường dưới sự bảo bọc của Nữ phù thủy. Nhưng nghĩ lại về Hecate... bà ta ắt hẳn coi rủi ro là quá lớn. Ta hiểu được. Ta sẽ cố gắng hiểu...",
    "Demeter_0086": "Lần đầu tiên mẹ cháu mất tích khỏi vòng tay ta... Phù thủy Ngã ba Địa Giới đã bước ra từ bóng tối để soi đường cho ta, khi ta lùng sục khắp chân trời góc bể. Bọn ta chẳng tìm thấy gì; nhưng ít nhất khi ấy ta không hề cô độc...",
    "Demeter_0039": "Cháu biết đấy, ta luôn cảm thấy có mối giao cảm đồng điệu với Hecate, dẫu hiếm khi chạm mặt. Bà ấy dường như chẳng màng tới việc có con cái cho riêng mình. Thế nhưng Số Mệnh lại trao cháu vào tay bà ấy.",
    "Demeter_0269": "Gần đây ta đã liên lạc với Phù thủy Ngã ba Địa Giới... để bày tỏ lòng tri ân sâu sắc, vì bà ấy đã đưa ra quyết định đầy gian khó khi giấu kín cháu suốt ngần ấy năm trời. Ta hiểu bà làm vậy vì sự an toàn của cháu... và để gia tăng cơ hội chiến thắng cho chúng ta.",
    "Demeter_0040": "Ta đã {#Emph}ghê tởm {#Prev}Chronos ngay từ thuở thanh xuân. Gần như căm thù lão ngang ngửa gã cha Titan đê tiện của chính mình. Dẫu vậy bọn ta đã báo thù xong; thanh trừng cả Chronos, Hyperion cùng bè lũ của chúng. Nhưng ta thật ngu ngốc khi ngỡ rằng sẽ chẳng bao giờ phải giáp mặt lại bất kỳ ai trong số chúng nữa...",
    "Demeter_0041": "Chúng ta bị giam hãm trong cuộc chiến với Chronos lâu đến nỗi bắt đầu hoài nghi liệu có điều gì thật sự thay đổi được chăng. Ta tự hỏi, đóa hoa nhỏ... liệu cháu có thể thực sự quét sạch vết nhơ nhơ nhuốc này khỏi thế gian?",
    "Demeter_0097": "Ta đoán là Chronos vẫn lăm lăm mang theo cây lưỡi hái mạ vàng kệch cỡm kia đi khắp chốn chứ gì? Lão tự huyễn hoặc mình là kẻ gặt hái, mở miệng là mùa gặt với hoại diệt; nhưng lão chỉ toàn nói lời sáo rỗng, trong khi {#Emph}ta {#Prev}mới là người nắm giữ sinh sát của mùa màng.",
    "Demeter_0213": "Nếu đúng là cháu đã chạm tới vực sâu Âm giới và hạ sát tên Titan tàn độc kia ở đó, thì {#Emph}tuyệt lắm. {#Prev}Ta biết chừng đó có lẽ vẫn chưa đủ để kết liễu lão, nhưng ắt hẳn cháu đã gieo rắc nỗi đau đớn, và cả sợ hãi vào tim lão. Đó là một khởi đầu tốt.",
    "Demeter_0214": "Cháu lại đánh bại Chronos thêm một lần nữa rồi phải không, đóa hoa nhỏ? Bọn ta luôn biết lão có thể bị hạ gục; chính tay ta từng tận mắt chứng kiến điều đó. Nhưng liệu lão có thể bị tiêu diệt vĩnh viễn không? Phù thủy Ngã ba Địa Giới {#Emph}ắt phải {#Prev}biết câu trả lời...",
    "Demeter_0167": "Prometheus trộm lửa của chúng ta không phải vì nhân loại, mà chỉ vì hắn thèm khát quyền lực ấy cho riêng mình. Giờ thì thứ sức mạnh ấy giúp ích được gì cho hắn, trên đỉnh núi lạnh lẽo giá băng kia?",
    "Demeter_0212": "Ta có thể dập tắt ngọn lửa của tên Prometheus kia... nhưng khi làm vậy, toàn bộ phàm nhân dưới trần gian ắt sẽ chết cóng. Ta chưa sẵn sàng đi xa đến {#Emph}mức ấy{#Prev}, dẫu rằng sức chịu đựng của ta đang bị đẩy tới giới hạn.",
    "Demeter_0226": "Âm mưu này do Chronos vạch ra nhằm cầm chân tất cả chúng ta... ngay cả Prometheus vẫn cứ là một cái gai chướng mắt như trước! Hãy báo cho chúng ta biết ngay nếu cháu nghi ngờ có sự gian trá nào.",
    "Demeter_0216": "Sự xâm lăng của con quái vật gớm ghiếc Typhon... không chỉ là một hiểm họa, đó là một sự {#Emph}sỉ nhục! Ta {#Prev}nắm giữ bốn mùa trong tay, vậy mà hắn {#Emph}dám {#Prev}phủ cơn bão xú uế của mình lên khắp ngọn núi linh thiêng của chúng ta sao?",
    "Demeter_0217": "Nếu Chronos thực sự đứng sau sự trỗi dậy của Typhon, thì lão không chỉ ngạo mạn mù quáng mà đã hoàn toàn phát điên. Lão rêu rao về một Thời Hoàng Kim mới mà lại thả một sinh vật kinh hoàng như thế vào thế giới này ư?",
    "Demeter_0227": "Tuyết lại rơi nhẹ nhàng trên đỉnh Olympus như thuở nào, không còn vương lại chút tàn tích bão tố hôi hám nào của Typhon... hay của {#Emph}phần còn lại {#Prev}của hắn. Nhưng cháu vẫn có thể chạm trán hắn ở một nơi nào đó xa xôi ngoài kia ư...?",
    "Demeter_0218": "Zeus nói rằng cháu đã đóng góp công lao to lớn trong việc đánh bại Typhon trên đỉnh núi của chúng ta. Cảm ơn cháu vì điều đó, đóa hoa nhỏ, nhưng ta tiếc rằng đã không thể có mặt tại hoa viên Cung điện để trực tiếp nói lời cảm ơn. Kẻ thù quá đông đảo, và chúng chẳng hề nương tay.",
    "Demeter_0219": "Con quái vật Typhon dường như vẫn chưa chịu hiểu ra rằng cả hắn lẫn Chronos đều không thể ngăn cản bước chân chúng ta. Nhưng chúng ta sẽ {#Emph}bắt {#Prev}hắn phải hiểu, và sự hiện diện của cháu ở đây chính là bước ngoặt chúng ta hằng mong mỏi.",
    "Demeter_0220": "Giờ đây tên Titan Chronos chính là mục tiêu duy nhất của chúng ta. Đừng tỏ ra khoan nhượng với lão hơn những gì con quái vật lão thả ra từng đối xử với chúng ta. Nhưng hãy cẩn trọng; ta lệnh cho cháu phải bình an trở về.",
    "Demeter_0221": "Dẫu ta vô cùng hả dạ trước chiến thắng lẫy lừng trước Typhon, nhưng việc cuối cùng cũng được hạnh ngộ cùng cháu mới là điều quý giá nhất trên đời đối với ta, đóa hoa nhỏ. Hãy tha thứ nếu ta không quen biểu lộ sự vui mừng, nhất là trong thời buổi loạn lạc này. Cầu mong đôi ta sẽ sớm tương phùng.",
    "Demeter_0155": "Mụ phù thủy Circe mà cháu quen biết. Ả là hậu duệ xa xôi của anh trai Titan Helios của ta, thần Mặt Trời kẻ chẳng dám lộ diện. Sự say mê của ả với đất đai và ngũ cốc nghe thật nịnh tai... dẫu ta cũng phần nào thấu hiểu tâm tình ẩn chứa bên trong.",
    "Demeter_0037": "Ta có biết bao điều muốn thổ lộ cùng cháu, Melinoë... nhưng đây chưa phải thời khắc hay phương thức thích hợp. Ít nhất cháu vẫn nghe thấy tiếng {#Emph}ta{#Prev}, đúng không? Và ta vẫn cảm nhận được hơi ấm của cháu, dẫu mong manh và xa xôi xiết bao.",
    "Demeter_0042": "Hera, Hestia và ta vốn có tâm tính khác biệt nhau muôn trùng, đến mức chẳng mấy khi thân thiết như chị em ruột thịt. Dẫu vậy, cuộc chiến trường kỳ chống lại Chronos đã kéo chúng ta xích lại {#Emph}gần nhau hơn {#Prev}đôi chút, ta đoán thế...",
    "Demeter_0044": "Theo ta được biết, huyết thống của cháu khó lòng sống sót nổi ngoài cõi Âm ti. Thế mà cháu lại đang ở đó, tự do sải bước như thể chẳng hề bị ràng buộc bởi số phận của cha mình. Làm sao có thể như vậy được nhỉ...?",
    "Demeter_0043": "Cháu đã phá tan bóng tối dưới kia để trồi lên bề mặt thế giới của chúng ta rồi sao, đóa hoa nhỏ? Nếu cháu có ý định ghé thăm ngọn núi của ta, chỉ cần lần theo con đường hoang tàn dẫn thẳng tới đây...",
    "Demeter_0168": "Mặt đất dưới chân chúng ta đang rục rịch chuyển mình, và ta nghĩ đó là điềm chẳng lành. Lão Chronos chết tiệt kia rốt cuộc định giở trò gì, toan lật đổ cả ngọn núi hùng vĩ này xuống trần gian chăng?",
    "Demeter_0098": "Đừng lo sợ cho đỉnh núi này, cũng đừng bận lòng cho Trái Đất; bởi Đất Mẹ kiên cường hơn tất cả chúng ta cộng lại. Kẻ thù có thể cày xới {#Emph}từng dấu vết {#Prev}tồn tại của chúng ta, nhưng Mẹ Gaia vẫn sẽ trường tồn và hồi sinh.",
    "Demeter_0225": "Một khu vườn tươm tất phải luôn được chăm sóc kỹ lưỡng. Nơi Âm giới của cháu cũng sẽ như vậy theo cách ta nhìn nhận, đóa hoa nhỏ. Nếu vẫn còn sót lại tàn dư ảnh hưởng nào từ Chronos, chúng ta sẽ nhổ tận gốc rễ.",
    "Demeter_0092": "Cháu đang làm gì ở vùng biển mặn chát tăm tối đó vậy, đóa hoa nhỏ? Ngay cả Poseidon cũng ngoảnh mặt làm ngơ trước những thứ ẩn nấp nơi góc biển ấy. Liệu con đường đó có thực sự dẫn sâu hơn vào cõi địa ngục?",
    "Demeter_0093": "Hành trình đưa cháu băng qua Cánh đồng Bi ai. Ta từng nhìn thấy nơi đó... thật là {#Emph}u ám rùng rợn{#Prev}, vô cùng tận! Tất cả những bông lúa mì ở đó, chúng... ta từng ngỡ chúng sẽ mang lại đôi chút ấm áp...",
    "Demeter_0215": "Chuyến hạ phàm gần đây đã đưa cháu đi sâu hơn cả những rễ cây sâu nhất của ta, đến sát nơi tên Titan Chronos ngự trị... và giam cầm mẹ cháu cùng những người khác. Chẳng có cách nào gửi tin báo cho chúng ta biết chuyện gì đã xảy ra sao?",
    "Demeter_0094": "Không một sinh linh nào có thể tồn tại trong thành phố Ephyra. Và ta sẽ duy trì điều đó cho tới khi hang ổ quái vật lê lết kia bị tiêu diệt sạch bóng! Dẫu vậy, cháu không cần bận tâm chi tiết làm gì; bọn ta đã phái người lo liệu việc đó rồi.",
    "Demeter_0163": "Cháu đang trên đường tới chỗ chúng ta sao, đóa hoa nhỏ? Một cuộc hội ngộ mà mẹ cháu từng thực hiện biết bao mùa xuân... nhưng vào một thời kỳ khác, khi không bị lũ tay sai hung bạo của tên Titan khốn kiếp bủa vây.",
    "Demeter_0052": "Người chú Poseidon của cháu đã tạo ra vực thẳm nước cuộn trào mà cháu thấy trước mắt. Ta từng có ý định đóng băng nó lại, nhưng e rằng kẻ thù vẫn sẽ vượt qua bằng cách này hay cách khác, và chuyến đi của cháu sẽ chỉ thêm phần trắc trở.",
    "Demeter_0095": "Vực nứt Thessaly đó hoàn toàn có thể bị biến thành băng giá một cách dễ dàng, cháu biết đấy. Ta rất muốn xem hạm đội của kẻ thù lướt qua đó {#Emph}ra sao! {#Prev}Nhưng người ta bảo ta phải kiềm chế những trận thiên tai thảm khốc lại một thời gian... phàm nhân và những lời {#Emph}van xin.",
    "Demeter_0045": "Ngay cả trong đêm trăng non tăm tối nhất, khi chính Selene cũng chẳng dám cưỡi cỗ xe băng qua bầu trời đêm lạnh lẽo, ta vẫn tìm thấy cháu nơi đó... và ta sẽ trao cho cháu toàn bộ sức mạnh mà ta có thể sẻ chia.",
    "Demeter_0046": "Cơn mưa rào kia có thể mang lại lợi ích cho cháu; gột rửa sạch mọi nhơ bẩn, làm lộ ra những mầm sống mới. Cháu nghĩ chính Zeus hay Poseidon đã mang cơn mưa tới sao? Đoán lại xem nào...",
    "Demeter_0047": "Những ân sủng của Đất Mẹ... sự sống vẫn đâm chồi nảy lộc ngay cả nơi cháu sinh sống, giữa chốn tử khí bủa vây. Hoa cỏ, rễ cây, thảo mộc và hạt giống; cháu hiểu rõ sức mạnh tiềm ẩn của chúng. Ta để chúng lớn lên là vì cháu.",
    "Demeter_0048": "Cháu đã hái được rất nhiều đóa hoa Moly... những sinh linh bé nhỏ khiêm nhường, đúng không? Chúng cũng chẳng khác nào {#Emph}cháu{#Prev}, bởi chúng mang trong mình quyền năng vượt xa những gì hình hài nhỏ bé kia biểu lộ.",
    "Demeter_0050": "Như cây non phải oằn mình vươn lên, chúng ta cũng phải không ngừng thúc đẩy bản thân để khai phá tiềm năng chân thực nhất. Hãy chiêm ngưỡng quyền năng cai quản sinh tử của ta; mong rằng cháu sẽ tìm thấy sức mạnh của chính mình.",
    "Demeter_0051": "Bốn mùa là một vòng tuần hoàn bất tận của lụi tàn và tái sinh... dẫu có những thời khắc các mùa khẳng định uy quyền mãnh liệt hơn thường lệ; những thời khắc ngặt nghèo như {#Emph}hiện tại.",
    "Demeter_0053": "Có một chút ánh trăng bao bọc lấy cháu, đóa hoa nhỏ, như thể Selene đang soi đường chỉ lối. Giá như Nữ thần Mặt Trăng bận tâm nhiều hơn đến đại cuộc thay vì chỉ mải miết dạo chơi trên bầu trời...",
    "Demeter_0054": "Người anh họ tuấn tú Apollo của cháu nắm giữ thứ ánh sáng mà phàm nhân hằng nâng niu trân quý, bởi nó sưởi ấm cho họ, làm tan chảy lớp tuyết dày của ta. Dĩ nhiên là phải có sự đồng thuận của ta rồi! Quyền năng của nó sẽ trợ lực cho cháu rất nhiều.",
    "Demeter_0055": "Zeus vĩ đại và đầy mưu lược đang trực tiếp tương trợ cháu sao? Vậy thì cháu đích thực là niềm hy vọng lớn nhất còn lại để đập tan dã tâm của tên Titan... bởi Zeus vốn là kẻ cực kỳ ghét việc hạ mình nhờ vả, hay ban phát ân huệ.",
    "Demeter_0056": "{#Emph}Aha{#Prev}, cháu đang mang trên mình phước lành của Poseidon! Chắc chắn một vị thần ồn ào và thích khoa trương như vậy phải có sức mạnh dồi dào tương xứng để chứng minh chứ?",
    "Demeter_0057": "Vậy là Poseidon lại tiếp tục giúp đỡ cháu rồi! Tốt lắm, cầu cho chú ấy phát huy được tác dụng. Ta sẽ tạm hoãn lời đe dọa đóng băng các đại dương của chú ấy lại, tạm thời là thế.",
    "Demeter_0058": "Chà, cháu thậm chí còn khiến vị thần thợ rèn thoắt ẩn thoắt hiện chịu bò ra khỏi hang động của mình. Thật không ngờ cuộc nội chiến thảm khốc với tổ phụ lại chính là thứ kéo gia đình chúng ta xích lại gần nhau hơn.",
    "Demeter_0059": "Xem ra cháu đã chiếm được cảm tình của muội muội Hera của ta rồi! Mà cháu thậm chí còn chẳng cần phải thề ước kết đôi hay sinh nở đứa con nào. Con bé hẳn đang ngày càng mềm lòng rồi!",
    "Demeter_0060": "Hestia đã trao cho cháu món quà ngọn lửa của bà ấy ư? Bình thường mụ già bủn xỉn ấy chẳng thèm đoái hoài tới bất kỳ ai trong chúng ta, kể cả chị em ruột thịt. Nhưng thời thế phi thường luôn đòi hỏi những hành động phi thường.",
    "Demeter_0061": "Bình thường thì quyền năng sắc đẹp của Aphrodite ngọt ngào mang lại vô số trò tiêu khiển thú vị, nhưng ta thật lòng hoài nghi ân huệ của con bé có thể giúp ích được gì trong tình cảnh ngặt nghèo như của chúng ta.",
    "Demeter_0241": "Ta biết thừa tên hiếu chiến Ares sẽ không thể kiềm chế được việc đích thân nhúng tay vào cuộc xung đột này. Dẫu ta đồ rằng hắn sẽ chẳng giúp chấm dứt nó sớm đâu, bởi hắn đang tận hưởng cuộc chiến này một cách cuồng nhiệt.",
    "Demeter_0062": "Cháu hành động thần tốc đấy, đóa hoa nhỏ! Ta dám cá là cháu đã được chính Hermes lanh lợi trợ lực, ngoại trừ việc cậu ta ắt hẳn đang quá bận rộn do thám kẻ thù để có thể giúp cháu được nhiều.",
    "Demeter_0063": "Có lẽ ta đã đánh giá sai về cô em họ sơn dã Artemis của cháu. Không ngờ con bé lại tìm thấy cháu! Ta từng đinh ninh nó chỉ mải rong chơi cùng đám Nymph thay vì làm việc gì có ích.",
    "Demeter_0243": "Trí tuệ trứ danh của Athena có xứng đáng với danh tiếng lẫy lừng không, đóa hoa nhỏ? Ta cứ nghĩ nhà chiến lược bậc thầy của chúng ta không cần phải đích thân cầm vũ khí nơi tiền tuyến chứ. Nhưng ta thì biết gì cơ chứ?",
    "Demeter_0089": "Thành thật mà nói, phụ thân cháu từ thuở thiếu thời đã luôn u uất và khó gần. Mẹ cháu nhìn thấy điều gì ở gã, ta chịu không hiểu nổi. Thế nhưng Kore bé bỏng như ta hằng gọi... con bé lại luôn rạng ngời mỗi khi ở cạnh gã...",
    "Demeter_0090": "Tin báo truyền về rằng cháu đã tìm thấy Hades, đóa hoa nhỏ! Chắc hẳn phụ thân cháu đang sôi sục căm hờn khi bị giam cầm trong hố sâu tuyệt vọng ấy, dẫu ít nhất gã vẫn vẹn nguyên. Còn mẹ cháu thì sao, vẫn bặt vô âm tín ư...?",
    "Demeter_0270": "Chắc chắn gã sẽ không đời nào thừa nhận điều này... nhưng phụ thân cháu đã phải trải qua một kiếp nạn vô cùng khủng khiếp. Tồi tệ hơn bất kỳ ai trong chúng ta. Nhưng gã và mẹ cháu từng cùng nhau vượt qua bao sóng gió trước đây, và sau mỗi lần như thế, họ lại càng thêm gắn kết.",
    "Demeter_0088": "Cháu thừa hưởng mái tóc vàng óng ả của mẹ, và dường như cả ý chí sắt đá của con bé nữa. Cỏ cây hoa lá từng bừng nở sức sống vì con bé... người chết cũng sẽ sống lại nếu họ có thể. Nơi sâu thẳm trong trái tim chưa hoàn toàn băng giá này, ta biết con bé vẫn bình an.",
    "Demeter_0224": "Mẹ cháu từng dành cả tháng trời lên thăm chúng ta, nhưng giờ đây... biết rằng con bé vẫn bình an và đã trở lại ngai vàng Âm phủ, ta không còn mong ước gì hơn. Ít nhất là vào lúc này.",
    "Demeter_0229": "Giờ thì ngay cả những kẻ dệt nên số mệnh dường như cũng biến mất, và chẳng thèm làm gì để bảo vệ tương lai của chính họ sao? Đó là những gì người ta đồn đại trên ngọn núi này, cháu gái. Vậy thì chúng ta thực sự đơn độc... nhưng chúng ta hoàn toàn có thể tự lực cánh sinh.",
    "Demeter_0232": "Chronos rêu rao rằng ngay cả lão cũng không biết Tam Nữ Thần Số Mệnh đang ở đâu, dẫu chính tay lão đã trục xuất họ đi? Hiếm khi ta nghe thấy lời ngụy biện ngu xuẩn đến thế. Thật không ngờ một kẻ lẩm cẩm vụng về như vậy lại có thể suýt lật đổ được chúng ta!",
    "Demeter_0160": "Cháu có một người ông là tên Titan tàn bạo Chronos... và một người ông khác chẳng qua chỉ là một chàng nông dân phàm trần tôn sùng ta. Liệu ta đã yêu hay thương hại chàng, ta cũng chẳng rõ. Ít nhất mẹ cháu sinh ra đã mang thân bất tử...",
    "Demeter_0091": "Cháu gái ngoan, cháu đã ở đâu suốt thời gian qua? Nơi đáy sâu u tối nhất trong lãnh địa của phụ thân cháu chăng! Đánh thẳng vào sào huyệt của kẻ thù. Người ta chỉ có thể hy vọng như thế.",
    "Demeter_0166": "Ta cảm ơn cháu, đóa hoa nhỏ, vì cháu đã khiến quân thù trên đỉnh núi này rơi vào cảnh hỗn loạn hoang mang. Ngay lúc này chúng đang cố gắng tập hợp lại, nhưng với nỗ lực không ngừng nghỉ của cháu, chúng ta có thể đánh bật chúng trở lại.",
    "Demeter_0156": "Đêm nay có điều gì đó thật đáng lo ngại... như thể một ý chí hắc ám nào đó vừa thức tỉnh từ đáy sâu thẳm của Hỗn Độn Chaos. Nhưng {#Emph}cháu {#Prev}sẽ chẳng biết gì về điều này đâu, đúng không?",
    "Demeter_0157": "Quả là một đêm đầy điềm gở! Không khí ngột ngạt mùi chết chóc và lụi tàn từ lãnh địa của phụ thân cháu, cùng sự hoang tàn mà chính ta đã gây ra. Ánh Trăng nhợt nhạt khó lòng xuyên thấu qua...",
    "Demeter_0274": "Cháu có nhìn thấy những đốm trắng li ti chầm chậm rơi từ thiên đàng xuống mặt đất kia không? Ta gọi nó là tuyết, nó tuyệt đẹp nhưng cũng vô cùng giá lạnh. Thần thánh chúng ta lẽ ra cũng nên giống như tuyết vậy.",
    "Demeter_0064": "Ta tự hỏi liệu thứ quả lựu độc địa kia có còn mọc nơi Âm giới của cháu hay không. Nó nắm giữ một quyền năng nơi đó mà ta cực kỳ căm ghét; chỉ một ngụm hạt đỏ như máu của nó thôi cũng có thể mang lại hiểm họa khôn lường.",
    "Demeter_0087": "Chúng ta gắn kết với nhau chẳng khác nào Bó Lúa Mạch mà cháu đang nắm giữ. Từng nhánh cỏ rơm riêng lẻ rất dễ gãy, nhưng kết thành bó thì lại vô cùng vững chắc! Từng nhánh tuy khác biệt, nhưng lại tương đồng biết bao.",
    "Demeter_0222": "Cháu đã làm cái {#Emph}gì thế hả? {#Prev}Tên Titan Chronos đáng lẽ phải bị tiêu diệt tan xương nát thịt, chứ không phải được thu nhận. Sự mục ruỗng đã ăn sâu vào tận linh hồn lão và không thể gột rửa! Nhưng... con gái ta, con bé đã gửi tin báo rằng nó bình an, và... {#Emph}ôi{#Prev}, ta biết phải {#Emph}làm sao {#Prev}với tất cả những điều này đây...",
    "Demeter_0192": "Ôi, cháu gái ngoan... ta biết phải làm sao nếu không có cháu đây. Việc ngọn núi này còn đứng vững đã là một kỳ tích, nhưng rồi... cháu đã tìm lại mẹ cho cả hai chúng ta. Ta không biết lấy gì đền đáp... tình yêu thương mà ta có thể trao đi ắt sẽ phải gánh vác phần nào.",
    "Demeter_0223": "Ta sẽ không bao giờ tha thứ cho Chronos, và ta cũng chẳng bao giờ muốn nhìn thấy bộ mặt gớm ghiếc của lão thêm lần nào nữa. Nhưng nếu câu thần chú cháu ếm lên lão thực sự bóp nghẹt dã tâm của lão, thì đành vậy. Có lẽ chẳng còn con đường nào khác...",
    "Demeter_0233": "Những kẻ dệt nên số mệnh lại một lần nữa trồi lên từ lòng đất! Và thật khéo léo làm sao, ngay sau khi chúng ta dập tắt cuộc nổi dậy của tên Titan mà không cần {#Emph}họ {#Prev}phải nhúng tay can thiệp. Chúng ta chưa từng {#Emph}bao giờ {#Prev}trông cậy được vào Tam Nữ Thần Số Mệnh...",
    "Demeter_0234": "Khi các chị em ta cùng phụ thân cháu và các huynh đệ ngài ấy lần đầu tiên hạ sát Chronos thuở xưa, đó là một chiến thắng đẫm máu nhuốm màu đau thương, nhưng đã mở ra một kỷ nguyên Olympus thống trị. Giờ đây dường như một kỷ nguyên mới lại sắp mở ra... và ta vẫn chưa từng thấy một kỷ nguyên nào hoàn hảo cả.",
    "Demeter_0228": "Chẳng có mấy lý do để vui mừng trên đỉnh Olympus suốt thời gian qua, chí ít là đối với ta. Nhưng được nhìn thấy {#Emph}cháu{#Prev}, đóa hoa nhỏ? Điều đó bù đắp cho biết bao gian truân vất vả. Ta biết có thể sẽ mất một thời gian nữa đôi ta mới lại tương phùng, nhưng hãy nhớ rằng chúng ta {#Emph}sẽ gặp lại.",
    "Demeter_0237": "Thứ đầu lâu cháu đang cầm... là một trong những Khí Giới của Đêm Tối, ta biết, thế nhưng, {#Emph}hình hài ấy... {#Prev}có điều gì đó ở nó, khiến ta... không nghĩ về Nyx, mà là... về {#Emph}con gái ta ư? Ôi{#Prev}, đừng bận tâm tới những lời lẩm cẩm của ta. Cứ tiếp tục đi.",
    "Demeter_0238": "Món thánh vật cháu đang mang... hàn khí toát ra từ nó mãnh liệt đến mức ta có thể cảm nhận được quyền năng của nó từ tận nơi đây. Bất kể nguồn gốc của làn sương giá chết chóc kia là từ đâu, nó chắc chắn không thuộc về cõi trần này...",
    "Demeter_0235": "Đôi khi ta sợ rằng mình đã trở nên lạnh lùng và cay nghiệt, nhưng biến cố này lại như một liều thuốc hồi sinh kỳ diệu... kể từ giây phút hạnh ngộ cùng cháu. Có lẽ ta đã ngủ vùi quá lâu rồi.",
    "Demeter_0230": "Thật kinh tởm khi nghĩ rằng Chronos trên danh nghĩa là ông nội của cháu, cũng như ta là bà ngoại vậy. Chúng ta chẳng có mối liên hệ nào cả, thế mà cây phả hệ gia đình này đã đâm chồi qua bao kỷ nguyên và giờ đây những cành nhánh đã vặn vẹo méo mó...",
    "Demeter_0236": "Dạo gần đây ta cảm thấy mình ngày càng cạn kiệt ngôn từ, đóa hoa nhỏ. Sau ngần ấy nhọc nhằn... ta có thể sẽ thu mình lại khỏi những phép tắc xã giao một thời gian. Dẫu vậy cháu vẫn sẽ nhận được sự ủng hộ bất diệt của ta chừng nào cháu còn cần tới.",

    # Boons / Blessings / Combat remarks
    "Demeter_0003": "Sự báo thù lạnh lùng đang lớn dần nơi sâu thẳm trái tim chúng ta; hãy để nó bùng nở một thời gian.",
    "Demeter_0004": "Ta từng đồ sát vài tên Titan trước đây; giờ xem ra tới lượt cháu nhận lấy vinh dự này rồi.",
    "Demeter_0005": "Ta sẽ không nghỉ ngơi chừng nào mẫu thân Nữ hoàng của cháu chưa được phục hồi ngai vàng danh chính ngôn thuận.",
    "Demeter_0006": "Cầu cho Chronos phải run rẩy khi biết rõ những tội ác của lão sẽ không thoát khỏi sự trừng phạt thích đáng.",
    "Demeter_0007": "Lời chúc phúc của ta, cháu gái ngoan. Cháu hệt như một làn gió đông mát lành.",
    "Demeter_0008": "Cháu mang trong mình sức mạnh của mẹ. Hãy đón nhận cả sức mạnh của ta nữa.",
    "Demeter_0009": "Có lẽ cháu cảm nhận được cái lạnh buốt giá ngay cả từ nơi sâu thẳm đó.",
    "Demeter_0010": "Chúng ta thực sự đang ở giữa một mùa đông tăm tối, hỡi cháu gái của ta...",
    "Demeter_0011": "Sự hoang tàn lụi tàn sẽ giáng xuống những kẻ dám đứng về phía lũ Titan chống lại chúng ta.",
    "Demeter_0012": "Bất cứ điều gì ta có thể trợ giúp cho hành trình của cháu, ta đều sẽ làm, đóa hoa nhỏ.",
    "Demeter_0013": "Cháu có cảm nhận được cái rét cắt da cắt thịt trong không khí không, cháu gái? Nó sẽ càng thêm dữ dội vì cháu.",
    "Demeter_0014": "Biết bao kẻ phản trắc đang chống lại chúng ta lúc này, nhưng chẳng mấy chốc chúng sẽ chỉ còn là đống hoang tàn mục ruỗng.",
    "Demeter_0015": "Xuyên suốt các mùa, ta mang lại sự sống cũng như cái chết; lần này sẽ là điều gì đây?",
    "Demeter_0016": "Ngay cả dòng thần huyết chảy trong huyết quản của một tên Titan cũng có thể bị làm cho đông cứng lại.",
    "Demeter_0017": "Ngày tháng dần tối tăm, dẫu vậy có lẽ chúng sẽ sớm chuyển biến tốt đẹp hơn...",
    "Demeter_0018": "Với phàm nhân, sự sống quý giá bao nhiêu thì ngắn ngủi bấy nhiêu. Những nữ thần như chúng ta có thể dập tắt nó dễ dàng...",
    "Demeter_0019": "Cháu ngày càng kiên cường hơn, đóa hoa nhỏ, và điều đó sưởi ấm trái tim băng giá này.",
    "Demeter_0020": "Đừng để bất kỳ kẻ nào cản bước giữa cháu và khát vọng của mình, cháu gái ngoan.",
    "Demeter_0021": "Cái chết và sự lụi tàn sẽ dành cho kẻ thù của Olympus.",
    "Demeter_0022": "Những kẻ dám ngạo mạn chống lại Olympus sẽ bị tiêu diệt không một chút thương xót.",
    "Demeter_0023": "Lòng kiêu hãnh và sự thịnh nộ ăn sâu vào huyết quản gia đình chúng ta, cháu gái ngoan.",
    "Demeter_0024": "Chronos là dòng máu ruột thịt thì đã sao; chẳng có mối dây liên kết nào là không thể đứt gãy.",
    "Demeter_0025": "Cầu mong cháu sẽ được nếm trải những năm tháng thái bình khi tuổi đời dần cao, nhưng vào lúc này...",
    "Demeter_0026": "Hãy lạnh lùng, tàn nhẫn và triệt để như cái rét của mùa đông giá buốt, Melinoë.",
    "Demeter_0027": "{#Emph}Aha{#Prev}, vòng tuần hoàn bất tận của tử sinh và tái sinh! Chẳng phải nó cũng tuyệt mỹ theo một cách riêng sao?",
    "Demeter_0028": "Giá như mặt đất mang lại khí hậu ôn hòa hơn, đóa hoa nhỏ, nhưng chưa đâu; chưa phải lúc này.",
    "Demeter_0029": "Chúng ta hãy cùng nhau khiến cho Chronos phải gặt hái tất cả những gì lão đã gieo rắc.",
    "Demeter_0030": "Hãy lớn mạnh và vươn mình rực rỡ như ta biết cháu có thể làm được, Melinoë.",
    "Demeter_0031": "Ta nghĩ giờ đây lũ kẻ thù đã chín muồi để chúng ta bước vào mùa thu hoạch rồi.",
    "Demeter_0032": "Xem ta hái được thứ gì dành riêng cho cháu đêm nay này, đóa hoa nhỏ.",
    "Demeter_0185": "Đêm nay dự báo thời tiết khắc nghiệt, kẻ thù của chúng ta tốt nhất nên mặc cho ấm vào.",
    "Demeter_0186": "Vì cháu là cháu gái của ta, cháu hoàn toàn xứng đáng được hưởng trọn vẹn những ân huệ này.",
    "Demeter_0187": "Đất Mẹ sẽ uống cạn máu của kẻ thù; ít nhất là đối với những kẻ {#Emph}biết {#Prev}chảy máu.",
    "Demeter_0188": "Trên này vẫn lạnh giá bất thường, đóa hoa nhỏ. Nhưng có vẻ cháu chẳng hề bận tâm.",
    "Demeter_0189": "Ta sẽ không ngần ngại thanh tẩy chút hơi ấm còn sót lại trong lòng Trái Đất, nếu đó là điều cần thiết.",
    "Demeter_0251": "Chẳng ai hiểu rõ hơn ta về sự tàn nhẫn khôn cùng của sự xoay vần thời tiết bốn mùa.",
    "Demeter_0252": "Ta sẽ rút cạn chút sinh khí còn lại của bất kỳ tên kẻ thù nào còn thoi thóp.",
    "Demeter_0253": "Ngay cả sau sự tàn phá khủng khiếp mà chúng ta chứng kiến, sự sống vẫn có thể tồn tại và hồi sinh.",
    "Demeter_0254": "Từ đống tro tàn của cuộc chiến này, chúng ta rồi sẽ lại đơm hoa kết trái nếu có đủ thời gian.",
    "Demeter_0255": "Thời Gian đe dọa cướp đi tất cả của chúng ta, nhưng chúng ta đã đứng vững, và sẽ luôn như vậy.",
    "Demeter_0084": "Ta chẳng mấy khi thích những điều bất ngờ, đóa hoa nhỏ. Và có lẽ ở điểm này chúng ta khá giống nhau. Dẫu vậy vẫn có một ngoại lệ hiếm hoi được chào đón... như một làn gió thu mát lành thổi qua.",
    "Demeter_0085": "Thật bẽ bàng làm sao, ngay cả Ân huệ của chúng ta cũng phải giấu giếm... kẻo để lộ quá nhiều toan tính và phòng tuyến cho kẻ thù.",
    "Demeter_0075": "Thật đáng xấu hổ khi giờ đây chúng ta phải dùng tới trò lừa bịp tầm thường, nhờ gã Người Lái Đò của cõi Chết lén lút đưa thư từ qua lại.",
    "Demeter_0076": "Đồng tiền của tên Titan mà cháu đã đổi lấy thông điệp này... chúng ta sẽ thu gom tất cả, nung chảy chúng và trả Vàng về đúng nơi nó thuộc về.",
    "Demeter_0082": "Giá như cháu có thể ngắm nhìn những cánh đồng của ta dưới ánh bình minh... tỏa sáng rực rỡ hơn bất kỳ thỏi Vàng nào cháu từng thấy. Kim loại như thế tốt nhất nên nằm sâu trong lòng đất.",
    "Demeter_0083": "Phải hạ mình nhặt nhạnh những lễ vật bèo bọt thế này sao! Lẽ ra cháu phải được sống trong vinh quang trên đỉnh Olympus, nơi mọi thứ cháu mong ước đều sẵn có... phần lớn là vậy.",

    # Rejection & Wrath
    "Demeter_0077": "Cháu dám hắt hủi chính {#Emph}bà ngoại {#Prev}của mình sao? Có lẽ nơi cháu được nuôi dưỡng, lễ nghi phép tắc chưa từng được xem là ưu tiên.",
    "Demeter_0078": "Ngay cả trong những thời khắc hỗn loạn này, thần thánh chúng ta vẫn có lòng tự tôn; lần sau cháu nên khôn ngoan hơn đừng xúc phạm lòng kiêu hãnh của ta như thế.",
    "Demeter_0111": "Cháu là giọt máu nối dõi trực hệ của ta, mà cháu {#Emph}vẫn {#Prev}dám cự tuyệt ta trắng trợn thế này ư?",
    "Demeter_0112": "Sự phẫn nộ trong lòng ta sục sôi đến mức, Melinoë, ta có thừa sự phẫn nộ dành cả cho {#Emph}cháu nữa đấy.",
    "Demeter_0113": "Nếu cháu được dưỡng dục trong Cung điện của phụ thân mình, cháu đã học được thế nào là {#Emph}sự kính trọng.",
    "Demeter_0114": "Hãy hiểu rằng gần đây, ta không có đủ kiên nhẫn cho những trò đùa cợt con nít đâu, cháu gái.",
    "Demeter_0115": "Đừng chống lại ta ngay cả khi chỉ là đùa giỡn, cháu gái; Apollo thích đùa cợt, còn ta thì không.",
    "Demeter_0116": "Hestia {#Emph}trên danh nghĩa {#Prev}là chị cả của ta thì đã sao? Bà ta thậm chí còn chẳng thèm đoái hoài gì tới đỉnh Olympus!",
    "Demeter_0169": "Cháu dám chối bỏ lời chúc phúc của ta, ngay cả khi biết rõ phàm nhân khắp thế gian hằng khao khát nó?",
    "Demeter_0170": "Ta chẳng hề tự hào về những điều ta sắp làm đâu, Melinoë. Nhưng nếu không làm vậy thì làm sao cháu học được bài học đích đáng?",
    "Demeter_0171": "Nếu đây là nỗ lực pha trò của cháu, thì hãy nhớ rằng nó hoàn toàn vô tác dụng với ta.",
    "Demeter_0172": "Nếu cháu đang tự hỏi liệu luồng hàn khí băng giá cắt da cắt thịt cháu đang cảm nhận có phải của ta không, thì {#Emph}đúng là nó đấy.",

    # Reconciliation
    "Demeter_0079": "Ta không còn giận cháu nữa đâu, cháu gái; lúc này chỉ cảm thấy hơi thất vọng đôi chút thôi...",
    "Demeter_0080": "Ôi, ta không thể giận dỗi cháu mãi được, đóa hoa nhỏ. Ta muốn cháu nhìn ta bằng ánh mắt trìu mến hơn là sự khinh thường.",
    "Demeter_0121": "{#Emph}<Sigh> {#Prev}Tâm trạng ta dạo này tồi tệ hệt như thời tiết vậy... thứ lỗi cho sự bộc phát vừa rồi nhé, đóa hoa nhỏ.",
    "Demeter_0122": "Cháu đã vượt qua được cơn giông bão, dẫu rằng cháu hoàn toàn có thể tránh được nó ngay từ đầu...",
    "Demeter_0123": "Giữa hai chúng ta không cần thiết phải có khoảng cách căng thẳng như thế, cháu gái ngoan. Thứ lỗi cho ta. Ta đã quá nóng vội.",
    "Demeter_0124": "Cái gia đình này, và cái {#Emph}lòng tự tôn {#Prev}chết tiệt của chúng ta! Cứ liên miên đấu đá với chính máu mủ ruột thịt! {#Emph}Hừ.",
    "Demeter_0173": "Mẹ cháu từng chọc giận ta theo đúng cái cách này, và nhìn xem điều {#Emph}đó {#Prev}đã dẫn con bé tới đâu.",
    "Demeter_0174": "Bỏ qua chuyện đó đi. Lời khiêu khích của cháu lẽ ra không đáng để ta phải nổi trận lôi đình đến mức ấy.",
    "Demeter_0175": "Chút xích mích nhỏ chẳng làm hại ai. Thay vào đó chúng ta {#Emph}nên {#Prev}tập trung vào cuộc chiến {#Emph}thực sự {#Prev}ngoài kia.",
    "Demeter_0176": "Ta không giận cháu đâu, cháu gái; và ta thừa nhận mình đã hành động hồ đồ.",
    "Demeter_0177": "Ôi, Melinoë, chúng ta không được phép bất hòa! Không phải với nhau, mà phải đồng lòng kề vai sát cánh.",
    "Demeter_0178": "{#Emph}Eo ôi{#Prev}, ta nên {#Emph}chôn vùi {#Prev}những xung động khiến ta hành động theo cảm tính thay vì lý trí.",

    # Gift / Affinity dialogues
    "Melinoe_0961": "Thật không ngờ nữ thần của bốn mùa lại chính là bà ngoại của con. Con vô cùng vinh hạnh được diện kiến bà.",
    "Demeter_0067": "Ta thấy Phù thủy Ngã ba Địa Giới không chỉ dạy cháu sức mạnh mà còn cả sự tao nhã nữa! Ta xin nhận lễ vật của cháu, và cũng có món quà này dành tặng lại cháu.",
    "Melinoe_0962": "Phu nhân Demeter! Con vô cùng biết ơn sức mạnh của bà. Món quà này thật khó lòng sánh được, nhưng xin người hãy nhận lấy.",
    "Demeter_0068": "Xem ra lớp trẻ ngày nay vẫn còn những người biết dành sự kính trọng đúng mực cho thế hệ đi trước. Ta rất hài lòng khi chính cháu gái ta là một tấm gương sáng như thế.",
    "MelinoeField_1769": "Kính dâng lên nữ thần mà quyền năng thực sự là nguồn nhựa sống của thế gian này! Nhờ có ân điển của bà mà giọt Tiên tửu Nectar này mới có thể tồn tại.",
    "Demeter_0069": "Chà, đóa hoa nhỏ, chắc chắn lúc này còn biết bao đại sự đang đè nặng lên vai cháu hơn là việc giữ lễ nghi truyền thống với bề trên chứ? Dẫu vậy, ta thực sự vô cùng trân quý điều này.",
    "MelinoeField_1770": "Bà ngoại, chúng ta còn bao nhiêu điều cần bù đắp cho quãng thời gian lẽ ra đôi ta đã có thể gắn bó bên nhau. Con tin chúng ta sẽ sớm làm được điều đó, còn lúc này, xin dâng người món quà này.",
    "Demeter_0070": "Thật lạ lùng... dẫu ta yêu thương mẹ cháu vô bờ, con bé chưa từng tôn kính ta đến mức này. Có lẽ ta đã quá nuông chiều con bé, hoặc giả thế hệ của cháu biết chu đáo hơn với tiền bối chăng.",
    "MelinoeField_3726": "Con không thể tưởng tượng hết những trọng trách bà gánh vác cho thế gian này, thưa bà. Mọi sinh linh đều trông cậy vào bà và sự tuần hoàn của bốn mùa. Việc bà có thể dành thời gian cho con giữa muôn trùng bận rộn ấy là điều con sẽ không bao giờ xem nhẹ.",
    "Demeter_0164": "Ta cảm ơn vì lễ vật, dẫu lòng ta thường nguội lạnh trước những thứ này. Phàm nhân dạo gần đây chỉ toàn cầu xin, van nài lòng thương xót, không hơn không kém. {#Emph}Xin cho hoa màu của con tươi tốt, Phu nhân Demeter. Xin cứu lấy vụ mùa của con, Phu nhân Demeter! {#Prev}Thật không thể chịu nổi...",
    "MelinoeField_3727": "Nơi con lớn lên, dẫu thiếu thốn đủ điều nhưng chưa từng thực sự cơ cực. Và con hiểu một phần không nhỏ là nhờ có bà, thưa bà ngoại. Hiệu trưởng luôn kính trọng bà hết mực, và con đã hiểu vì sao ngay từ khoảnh khắc đôi ta hội ngộ thế này.",
    "Demeter_0165": "Có lẽ chính ta cũng nên học cách biết ơn nhiều hơn. Ta thường nghĩ quá nhiều về nỗi đau và sự mất mát... làm sao không nghĩ cho được? Thế nhưng ta có cháu, có ngôi nhà trên đỉnh núi này, và nhiều hơn thế. Giá như gánh nặng của tất cả những điều ấy có thể vơi bớt phần nào.",
    "MelinoeField_4167": "Một vò Tiên tửu Ambrosia dâng tặng bà, thưa bà ngoại! Có lẽ món này sẽ khuấy động bầu không khí thêm phần vui vẻ, bởi sắp tới chúng ta sẽ có rất nhiều lý do để ăn mừng. Nhưng trên hết con chỉ muốn tặng bà, vì tất cả niềm hy vọng bà đã truyền cho con.",
    "Demeter_0193": "Cháu bảo {#Emph}ta {#Prev}đã truyền {#Emph}cho cháu {#Prev}hy vọng sao? Ta từng chỉ căm phẫn quyết chiến với tên Titan bằng mọi giá. Nhưng khi gặp cháu... ta bắt đầu nghĩ tới khả năng chúng ta có thể ca khúc khải hoàn. Rồi ta có thể nhìn thấy gương mặt dịu hiền của con gái ta, và cả con gái của {#Emph}con bé{#Prev}. Ta không nghĩ ra được lý do nào xứng đáng hơn thế.",
    "MelinoeField_4168": "Bà ngoại, người đã luôn đứng sau ủng hộ con kể từ khoảnh khắc đầu tiên ta gặp gỡ, và con đã cảm nhận được tình thâm ruột thịt ngay từ đầu. Cầu mong vò Ambrosia này sẽ khắc ghi không chỉ quá khứ mà cả tương lai của đôi ta. Bởi con thấy mình còn quá nhiều điều cần học hỏi về bà, và học hỏi từ bà.",
    "Demeter_0194": "Ta sẽ nhận lấy món này, nhưng không thêm nữa đâu nhé. Hãy nhớ rằng mẹ cháu và ta từng luôn có những bất hòa trắc trở, đóa hoa nhỏ. Chỉ khi con bé tự sống cuộc đời của riêng mình thay vì sống theo khuôn mẫu ta đặt ra, mối dây liên kết rạn nứt của chúng ta mới bắt đầu lành lại. Mong rằng tình cảm giữa ta và cháu sẽ mau chóng vượt qua giai đoạn ấy.",
    "Melinoe_1736": "Một món quà từ Bà ngoại...",

    # Shouts & Call
    "Demeter_0245": "Hãy run rẩy và mục ruỗng đi!",
    "Demeter_0246": "Đóng băng vĩnh cửu!",
    "Demeter_0247": "Cơn giá lạnh tê tái!",
    "Demeter_0248": "Đây thực sự là điều cháu mong muốn sao?!",
    "Demeter_0249": "Cháu giống mẹ mình biết bao!",
    "Demeter_0250": "Như cháu mong muốn, cháu gái ngoan!",
    "Chronos_1259": "Thời tiết lạnh giá bất thường...!",
    "Chronos_1260": "Một luồng {#Emph}hàn khí {#Prev}ngay giữa {#Emph}vực sâu này ư?",
    "Zagreus_0358": "Bà ngoại...?",
    "Zagreus_0359": "Xem ra bà ấy có người được cưng hơn rồi!",

    # Warning
    "Demeter_0117": "Sự kiên nhẫn của ta đã cạn kiệt; không có ngoại lệ, ngay cả với cháu.",
    "Demeter_0118": "Đừng chọc giận ta thêm lần nào nữa, đóa hoa nhỏ, nếu không ta sẽ khiến cháu phải {#Emph}héo úa.",
    "Demeter_0119": "Lũ nữ thần trẻ tuổi các cháu ai nấy đều giống nhau đến phát chán...",
    "Demeter_0120": "Đây không phải là sự phản bội, cháu gái ngoan; đây đơn thuần chỉ là một bài học.",

    # Short picks & accepts
    "Demeter_0139": "Được thôi.",
    "Demeter_0140": "Dĩ nhiên rồi.",
    "Demeter_0141": "Ta rất sẵn lòng.",
    "Demeter_0142": "Lựa chọn của cháu đấy.",
    "Demeter_0143": "Được, xong xuôi.",
    "Demeter_0144": "Như ý cháu.",
    "Demeter_0145": "Chắc chắn rồi.",
    "Demeter_0146": "Dành cho cháu.",
    "Demeter_0133": "Chào cháu, đóa hoa nhỏ!",
    "Demeter_0134": "Chính là ta đây.",
    "Demeter_0135": "Lời chào của ta.",
    "Demeter_0136": "Cháu gái đó ư?",
    "Demeter_0137": "Xem chúng ta có gì ở đây nào?",
    "Demeter_0138": "Thật là một bất ngờ thú vị!",
    "Demeter_0181": "Hãy chiêm ngưỡng đây.",
}

def main():
    source_raw = SRC.read_text(encoding="utf-8-sig")
    OUT.parent.mkdir(parents=True, exist_ok=True)
    
    entries_dict = {
        k: v if isinstance(v, dict) else {"DisplayName": v}
        for k, v in translations.items()
    }
    
    updated_raw = apply_translation_to_sjson(source_raw, entries_dict)
    OUT.write_text(updated_raw, encoding="utf-8")
    sys.stdout.reconfigure(encoding="utf-8")
    print(f"Đã dịch và lưu thành công {len(entries_dict)} chuỗi của Demeter vào: {OUT}")

if __name__ == "__main__":
    main()
