"""Translate Aphrodite's family banter and key Melinoë dialogue."""
from pathlib import Path
import sys

ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(ROOT / "tools"))
from hades2_sjson_helper import apply_translation_to_sjson  # noqa: E402

SRC = ROOT / "games/0100A00019DE0000_Hades2/source/raw_text/en/_LootData_Aphrodite.en.sjson"
OUT = ROOT / "games/0100A00019DE0000_Hades2/translations/Game/Text/en/_LootData_Aphrodite.en.sjson"

translations = {
    "Melinoe_0948": "Tuyệt vời, Aphrodite! Chắc nàng nhận được nhiều lễ vật hơn tất cả thần nam thần nữ khác cộng lại. Dù món này là của ta tặng!",
    "Melinoe_0949": "Ở bên nữ thần Aphrodite, ta ít ngờ vực bản thân hơn. Nàng nhận thêm một lễ vật nữa chứ?",
    "Melinoe_0950": "Ta vẫn biết quá ít về chuyện tình cảm. Chắc ta còn học được nhiều điều từ nữ thần Aphrodite. Thật vinh hạnh khi được gặp nàng.",
    "MelinoeField_1766": "Nữ thần Aphrodite ưu ái ta nhiều đến thế. Giá mà ta có thể đáp lễ! Ngay cả lúc khó khăn nhất, nàng vẫn cho ta sức mạnh và hy vọng.",
    "MelinoeField_1767": "Aphrodite rạng ngời! Nàng thật sự tuyệt mỹ, nhưng lòng can đảm và sự tự tin của nàng còn truyền cảm hứng cho ta hơn nữa. Được ở bên nàng, lại xứng đáng nhận ân huệ của nàng, khiến ta vô cùng cảm kích.",
    "MelinoeField_1768": "Ta luôn nghĩ thế gian thật đẹp... vẻ đẹp hiện diện khắp nơi, ngay cả giữa những cuộc xung đột. Và ta biết đó là nhờ {#Emph}nàng{#Prev}, Aphrodite. Cảm ơn nàng đã giúp ta nhìn thấy tất cả.",
    "MelinoeField_4347": "Aphrodite, sự nhiệt tình chân thành của nàng giữa bao gian khó chính là điều khiến nàng đẹp đẽ và truyền cảm hứng hơn bất kỳ ai. Ta cảm thấy Tiên tửu Ambrosia này tượng trưng cho tất cả tình yêu nàng muốn trao đi.",
    "Melinoe_1738": "Món quà xinh đẹp thế này, sao ta nỡ từ chối chứ.",
    "Chronos_1263": "Ta rất {#Emph}muốn{#Prev} ngươi {#Emph}biến đi!",
    "Chronos_1264": "Ta chẳng dễ bị {#Emph}đánh lạc hướng{#Prev} đến thế đâu.",
    "Zagreus_0362": "Nữ thần Aphrodite...!",
    "Zagreus_0363": "Aphrodite?!",
    "Aphrodite_0066": "Ôi, thật {#Emph}tuyệt vời{#Prev}, lại còn đáng nể vì em đã hiểu cách chúng ta làm rồi! Ta {#Emph}phải{#Prev} đáp lễ mới được, vậy em hãy nhận {#Emph}món này. {#Prev}Ta {#Emph}nhất định!",
    "Aphrodite_0067": "Món quà em dâng lên {#Emph}quý giá{#Prev} biết bao, người thương! Nghĩ lại mới thấy đã lâu lắm rồi chẳng ai hết lời ca ngợi ta.",
    "Aphrodite_0068": "Ôi cưng à, ta mới là người {#Emph}vinh dự{#Prev} chứ! Trong chuyện tình cảm, điều quan trọng nhất là cởi mở. Em đang đi đúng hướng để tìm được sự thấu hiểu mình mong muốn rồi!",
    "Aphrodite_0069": "Em yêu, em quả là {#Emph}đặc biệt{#Prev}, biết không? Hào phóng, biết lựa lời, lại còn {#Emph}xinh đẹp{#Prev} nữa! Ta chẳng biết nên thấy được tâng bốc hay hơi ghen tị đây!",
    "Aphrodite_0178": "Ta chẳng biết nên mong đợi điều gì ở em. Cùng chiến đấu bên nhau đã là tốt lắm rồi? Ta cũng chỉ biết em qua vài lời nhắn, vậy mà chẳng hiểu sao... giờ ta xem em như một người bạn! Một người để tâm sự. Cảm ơn em nhé, người thương!",
    "Aphrodite_0179": "Tiên tửu Nectar em tặng chắc chắn sẽ ngọt ngào hơn mọi vò khác! Khi mây đen kéo đến và hy vọng trong ta dần tắt, ta sẽ nâng chén vì chúng ta. Rồi ta sẽ vui vẻ trở lại ngay!",
    "Aphrodite_0202": "{#Emph}Ôi{#Prev}, em {#Emph}tốt bụng{#Prev} quá đi mất! Mà nghe lời khen mãi cũng chẳng chán. Ta {#Emph}quen{#Prev} được mọi người xuýt xoa vì {#Emph}nhan sắc!{#Prev} Nhưng nếu em nhìn thấy cả {#Emph}vẻ đẹp bên trong{#Prev} của ta, thì em hiểu về tình yêu và sắc đẹp {#Emph}sâu sắc{#Prev} hơn {#Emph}hầu hết mọi người.",
    "Aphrodite_0105": "Ừ-{#Emph}hửm!",
    "Aphrodite_0106": "Ta rất vui lòng.",
    "Aphrodite_0109": "Hãy nghe theo trái tim em.",
    "Aphrodite_0168": "Xong rồi!",
    "Aphrodite_0169": "Được thôi!",
    "Aphrodite_0170": "Tất nhiên rồi!",
    "Aphrodite_0171": "Của em đây!",
    "Aphrodite_0172": "Vì em thì chuyện gì ta cũng làm!",
    "Aphrodite_0173": "Chắc chắn rồi!",
    "Aphrodite_0099": "Họ sẽ thích {#Emph}món này lắm!",
    "Aphrodite_0100": "Ta luôn ở đây vì em, người đẹp!",
    "Aphrodite_0101": "Trái tim nào rồi cũng có thể tan vỡ!",
    "Aphrodite_0242": "Vì em thì chuyện gì ta cũng làm, người thương!",
    "Aphrodite_0243": "Mở to mắt mà ngắm {#Emph}món này đi!",
    "Aphrodite_0244": "Đẹp đến mức ai cũng phải trầm trồ!",
    "Aphrodite_0245": "Vì {#Emph}em{#Prev} thì chuyện gì ta cũng làm, người thương!",
    "Aphrodite_0246": "Ngươi nghĩ mình là {#Emph}ai chứ?",
    "Aphrodite_0247": "Đừng đem trái tim ta ra đùa giỡn!",
    "Aphrodite_0119": "Cơn thịnh nộ của ta còn nhiều lắm đấy.",
    "Aphrodite_0120": "Đừng khiến ta nếm trải điều trái ngược với tình yêu.",
    "Aphrodite_0118": "Đừng đùa cợt với trái tim ta.",
    "Aphrodite_0102": "Chà, chà!",
    "Aphrodite_0103": "{#Emph}Á ha-ha!",
    "Aphrodite_0110": "Ta có món này cho em.",
    "Aphrodite_0115": "Cái này dành cho em.",
    "Aphrodite_0116": "Một món quà nho nhỏ.",
    "Aphrodite_0203": "Ngoài niềm vui tự nhiên khi đánh cho lão Titan đáng ghét một trận, liệu chúng ta còn kế hoạch lớn lao nào khác không? Cậu em thần nhỏ của em sẽ ổn chứ...?",
    "Aphrodite_0225": "{#Emph}Eo ôi{#Prev}, đêm nay có gì đó rất {#Emph}kỳ lạ{#Prev}, mà thành xấu xí {#Emph}Ephyra{#Prev} kia thì {#Emph}đúng là{#Prev} chẳng giúp ích gì. Nhưng có Hephaestus yêu quý, Chúa tể Ares và ta ở đây, em sẽ xoay xở ổn thôi.",
    "Aphrodite_0226": "Đi thuyền lãng mạn thật, nhưng tối nay không khí {#Emph}rõ là{#Prev} kỳ cục... sao em lại {#Emph}đi{#Prev} xa đến thế nhanh {#Emph}vậy?{#Prev} Dù chẳng ai thấy khá nhất, ta vẫn có thể {#Emph}trông{#Prev} thật đẹp!",
    "Aphrodite_0234": "Có bao nhiêu người theo đuổi để lựa chọn, {#Emph}nhỉ?{#Prev} Nhưng nhớ là em chẳng cần chọn ai cả, trừ khi chính em cũng muốn như họ. Trái tim em, những mối quan hệ của em — cứ tự quyết định nhé!",
    "Aphrodite_0130": "Ồ, em đang mang Chiếc Gương Tuyệt Mỹ của ta! Soi vào đó lúc nào em cũng xinh đẹp, nhưng phép màu thật sự của nó là giúp ta tìm em thật nhanh rồi ban cho em điều tốt nhất ta có!",
    "Aphrodite_0097": "Cưng à, em đã thử công thức Tiên tửu Nectar của ta chưa? Với đôi tay {#Emph}khéo léo{#Prev} của em, ta tin nó sẽ chinh phục được gần như bất kỳ ai. Không cần kể ta nghe kết quả đâu; ta có cách riêng để biết mà!",
    "Aphrodite_0174": "Cặp {#Emph}Lửa Âm{#Prev} tuyệt đẹp em đang cầm là gì thế? Chúng sáng như ánh bình minh đầu tiên. Ta không nghĩ hợp với phong cách của em, vậy mà em dùng trông {#Emph}hợp quá{#Prev} đi mất!",
    "Aphrodite_0087": "Lâu lắm rồi mới gặp, người thương! Ta còn thấy hơi {#Emph}lo{#Prev} nữa cơ! Nhưng rồi chú chim nhỏ kể em đã xuống tận những vực sâu kia và còn đạt được chút thành công? Ta nóng lòng muốn nghe hết chuyện hay đây!",
    "Aphrodite_0134": "Em hạ được lão rồi thật sao, người đẹp? Chú chim nhỏ kể ta nghe {#Emph}mọi chuyện{#Prev}: em đánh thẳng xuống tận đáy sâu ghê tởm rồi hạ gục Chronos {#Emph}ra sao!{#Prev} Nhưng lão đã quay lại, còn giận dữ hơn trước, phải không...?",
    "Aphrodite_0088": "Lần trước em đã tạo nên khác biệt lớn ở đây đấy! Ta chẳng nên ngạc nhiên, vậy mà một nữ thần có thể làm nhiều việc đến thế sao? Em đúng là nguồn cảm hứng, người thương! Mà cũng {#Emph}đáng sợ{#Prev} nữa!",
    "Aphrodite_0090": "Tối nay em tươi tắn như mưa xuân, người đẹp! Mới ghé suối nước nóng về, {#Emph}nhỉ?{#Prev} Chẳng gì bằng ngâm mình trong làn nước ấm, {#Emph}nhất là{#Prev} khi có bạn tốt bên cạnh.",
    "Aphrodite_0091": "{#Emph}Ôi{#Prev}, em lại ghé suối nước nóng rồi! Người em rạng rỡ hẳn lên kìa, cưng à. Không biết em tắm cùng ai nhỉ! Chắc chú chim nhỏ sẽ sớm mách ta thôi.",
    "Aphrodite_0096": "Chà, em đang mang theo con vật bé xíu đáng yêu nào thế, người đẹp? Vậy là người thờ phụng em đủ mọi hình dáng kích cỡ nhỉ! Còn ta thì thường chỉ mê hoặc thần linh với phàm nhân thôi.",
    "Aphrodite_0175": "Em đang mặc gì {#Emph}trên người{#Prev} thế, người đẹp? Bộ áo lụa xinh xắn này chắc do Arachne làm, mắt ta không nhìn nhầm đâu! Em với cô nhện nhỏ ấy hẳn đã {#Emph}thân nhau{#Prev} lắm rồi!",
    "Aphrodite_0204": "Người đẹp, em đã thắng {#Emph}cuộc chiến{#Prev} cho chúng ta rồi! Ít nhất ta nghĩ là thắng? Có khi chưa, vì đám Satyr xấu xí vẫn chưa chịu rời đi, nhưng em chắc chắn đã làm được {#Emph}điều gì đó!{#Prev} Ôi, chuyện này thật quá {#Emph}sức!",
    "Aphrodite_0205": "Tên Chronos tráo trở ấy giờ lại đứng về phía chúng ta sao? Ta phải đề phòng những phiên bản xấu xa của lão lúc trẻ và mấy mảnh Typhon vô hình, nhưng cũng đừng sợ {#Emph}quá{#Prev}. Ta từng gặp cảnh éo le hơn, nhưng vụ này cũng {#Emph}sát nút!",
    "Aphrodite_0209": "{#Emph}Ôi{#Prev}, cuối cùng Tam Nữ Thần Số Mệnh cũng {#Emph}chịu xuất hiện{#Prev}, đúng lúc chúng ta vừa quen với cảnh không có họ! Lần này họ mang lời tiên tri cao siêu nào đến đây, {#Emph}nhỉ?{#Prev} Dù là gì, ta tin chúng ta sẽ xoay xở được!",
    "Aphrodite_0210": "Nếu một thời đại mới sắp đến thật thì cứ để nó đến! Tình yêu đích thực chẳng bao giờ đổi thay hay lỗi thời, dù mọi thứ khác có đổi khác đến đâu. Cứ ở bên ta là chúng ta sẽ {#Emph}ổn thôi!",
    "Aphrodite_0235": "Ngôn ngữ tình yêu vượt qua mọi ranh giới... ta đâu cần nói thành lời vẫn hiểu được cảm xúc và mong muốn của nhau. Hay ta thử như thế một lúc nhé, {#Emph}nhỉ?",
    "Aphrodite_0180": "Ta muốn dành cho em một bất ngờ, người thương! Còn gì vui hơn mở chiếc túi bình thường ra rồi thấy {#Emph}ta{#Prev} đứng chờ, dang rộng vòng tay đón em chứ?",
    "Aphrodite_0181": "Em tưởng người đến sẽ kém xinh đẹp hơn nhiều, hay em đã biết đó là {#Emph}ta?{#Prev} Có khi em nghe được tim {#Emph}em{#Prev} đập thình thịch từ tận nơi em đứng ấy chứ!",
    "Aphrodite_0136": "Người lái đò của em làm công việc {#Emph}xấu xí{#Prev} thật: phải lén đưa những ân huệ nhỏ bé như thế này vào tận nơi {#Emph}nguy hiểm nhất{#Prev}... Nhưng bọn ta trả công xứng đáng, cứ yên tâm.",
    "Aphrodite_0137": "{#Emph}Ôi{#Prev}, được chính Người lái Đò đáng sợ mang cứu viện khẩn cấp đến chiến trường thì còn gì bằng, {#Emph}ha!{#Prev} Ai mà chẳng có vài mộng tưởng, người đẹp!",
    "Aphrodite_0138": "Em với Người lái Đò ấy hiểu nhau thật đấy nhỉ? Chàng đúng là người cô độc. Rắn rỏi... cao lớn... thân hình khỏe khoắn. {#Emph}Ừm!",
    "Aphrodite_0139": "Charon đáng tin cuối cùng cũng đưa em đến nơi, vừa kịp lúc để đối mặt với hiểm nguy lớn nhất trên đường. Mong ân huệ của ta đem lại chiến thắng cho em!",
    "Aphrodite_0223": "Phải nói là em với Moros kín tiếng đến lạ về chuyện giữa hai người. Đám chim nhỏ của ta hầu như chẳng thấy {#Emph}dấu vết{#Prev} gì! Nhưng ta vẫn có linh cảm về hai người, mà linh cảm của ta thì {#Emph}chưa bao giờ{#Prev} sai.",
    "Aphrodite_0218": "Nemesis đúng là bạn đồng hành tuyệt vời của em, người đẹp! Cô ấy to lớn, thẳng thừng, trái ngược hẳn với em! Ta mừng hai người sát cánh bên nhau thay vì lao vào đánh nhau!",
    "Aphrodite_0219": "Ta mừng vì em và Nemesis đã hóa giải bất đồng! {#Emph}Ồ{#Prev}, chẳng ai kể ta nghe đâu, người đẹp; ta tự biết mọi chuyện nhờ chính con người mình thôi! Cứ là chính mình, rồi hai người sẽ tìm được điểm cân bằng.",
    "Aphrodite_0086": "Em sống ở Vực Erebus phải không, cưng? Lần gần nhất nghe tin, Arachne thợ dệt tơ cũng ở dưới đó. Nàng ấy dệt nên những món đẹp tuyệt, nhưng từ sau lần cãi vã với Athena thì chẳng bén mảng lên đây nữa!",
    "Aphrodite_0208": "Ta nghe tin cậu em thần nhỏ của em vẫn bình an! Nó lại quay về chiến đấu trong địa ngục mà nó gọi là nhà, ít nhất là {#Emph}một phần{#Prev} cho đến khi Âm phủ được khôi phục. Mong em sớm gặp lại em trai! {#Emph}Sớm nhé!",
    "Aphrodite_0084": "Em gặp gần hết chúng ta rồi, nhưng chắc vẫn chưa gặp Athena kiêu hãnh nhỉ? Nghe nói nàng bận bảo vệ tiền tuyến lắm. Đừng giận nhé; nữ thần ấy vốn đâu nổi tiếng khéo cư xử.",
    "Aphrodite_0192": "Em đã thấy vài màn Athena xuất hiện đầy kịch tính trên chiến trường rồi. Phải công nhận nàng làm tốt khoản đó! Chắc vì đã luyện nhiều qua những vị khách không mời mà đến của chúng ta!",
    "Aphrodite_0089": "Có một điều chắc chắn: dạo gần đây Olympus {#Emph}thiếu hẳn{#Prev} tiệc tùng! Dionysus tội nghiệp chẳng còn là chính mình. Bình thường chàng sẽ là một trong những người đầu tiên chào đón em!",
    "Aphrodite_0230": "Mấy nàng Tiên Cá ở chỗ {#Emph}em{#Prev} đang ra sức cất tiếng hát nhỉ! Có lẽ họ đã tìm thấy nguồn cảm hứng mới, ngoài đám thủy thủ mà họ mê tít.",
    "Aphrodite_0132": "Có chú chim nhỏ kể rằng {#Emph}Eris đáng ghét{#Prev} cứ lượn lờ, xía mũi vào chuyện của mọi người thay vì lo việc mình! Từ trước cả vụ này, chúng ta đã thôi mời cô ta đến {#Emph}mọi{#Prev} buổi tiệc trên Olympus rồi!",
    "Aphrodite_0220": "Em {#Emph}thích{#Prev} có Eris gây chuyện trong đời mình à, {#Emph}nhỉ?{#Prev} Em càng đánh nhau với Eris, ta càng nhận ra có {#Emph}chuyện gì đó{#Prev} giữa hai người. Quả nhiên là vậy! Cô ấy chẳng giống mẫu người em thích, nhưng tình yêu vốn {#Emph}đúng là{#Prev} thế mà!",
    "Aphrodite_0221": "Bóng ma trẻ tuổi bảnh bao với đôi cánh lộng lẫy kia tên Icarus phải không? Ta suýt tưởng cậu ấy là một chú chim nhỏ của ta! Lúc còn sống cậu ấy chẳng có mấy cơ hội yêu đương, nhưng giờ vẫn chưa muộn đâu...!",
    "Aphrodite_0222": "Ta {#Emph}vui mừng{#Prev} biết bao vì những gì em làm cho Icarus! {#Emph}Ôi{#Prev}, cậu ấy vui đến mức như bay lên {#Emph}mặt trăng{#Prev}, trách sao được chứ? Cuối cùng cậu ấy đã thật sự được {#Emph}cảm nhận... {#Prev}đa số phàm nhân còn chẳng có được may mắn ấy, huống chi các {#Emph}bóng ma!",
    "Aphrodite_0133": "Vậy là lão Heracles ục ịch đang lồng lộn dưới đó, gom xác người chết nhân danh các vị thần à? Tính khí lão như bò mộng, chắc mùi cũng chẳng dễ chịu hơn. Ít ra ta còn có {#Emph}trợ thủ tốt{#Prev} để cậy nhờ!",
    "Aphrodite_0194": "Ta thú thật mình có {#Emph}chút{#Prev} mê mẩn kiểu người cao ráo, bí ẩn và trầm tư, nhưng Prometheus khiến ta {#Emph}phát cáu.{#Prev} Hắn đang phá hoại ngọn {#Emph}núi xinh đẹp{#Prev} của chúng ta! Hắn muốn gây ấn tượng với ai vậy?",
    "Aphrodite_0195": "Prometheus mà không cẩn thận thì sẽ tự thiêu vì cứ {#Emph}hừng hực{#Prev} như thế! Hắn luôn miệng nói chẳng {#Emph}quan tâm{#Prev} đến thần nam hay thần nữ nào, nhưng ta {#Emph}nghĩ{#Prev} hắn chỉ đang làm bộ khó gần thôi!",
    "Aphrodite_0232": "Prometheus sướng thật, cứ trút giận lên đầu chúng ta như thể đó là {#Emph}nhiệm vụ chính thức{#Prev} của hắn vậy. Sao hắn nghĩ chúng ta đối xử với phàm nhân tệ thế nhỉ? Đúng là ta có làm tan nát vài trái tim, nhưng cũng sưởi ấm biết bao trái tim khác!",
    "Aphrodite_0196": "Rốt cuộc chúng ta phải làm gì với đỉnh Olympus tội nghiệp đây? Tên Typhon xấu xí ấy đã lên tận đây và phá hỏng {#Emph}mọi thứ. {#Prev}Nhưng chúng ta sẽ {#Emph}không{#Prev} để hắn muốn làm gì thì làm đâu.",
    "Aphrodite_0197": "{#Emph}Eo ôi{#Prev}, tên Typhon xấu xí đó! Dạo này hắn đã chiếm hết sự chú ý, lại còn kháng cự mọi {#Emph}mị lực{#Prev} của ta. Chuyện ấy {#Emph}chưa từng{#Prev} xảy ra! Mà hắn chỉ muốn ngọn núi này, chẳng phải vì tình yêu gì đâu.",
    "Aphrodite_0199": "Em lại đến thăm khuôn viên cung điện xinh đẹp của chúng ta rồi! Tiếc là ta không gặp được em. Chẳng con quái vật xấu xí nào lọt vào đó nếu {#Emph}ta{#Prev} ngăn được. Dù chúng {#Emph}đã{#Prev} đến khá gần rồi. Chúng {#Emph}vẫn{#Prev} chẳng chịu hiểu ý!",
    "Aphrodite_0200": "Em làm được rồi, người đẹp! Con quái vật xấu xí ấy cuối cùng cũng biến mất! Ta chẳng biết hắn có {#Emph}trái tim{#Prev} hay không; trong hắn chẳng có chút tình yêu nào, chỉ toàn ý đồ và ham muốn xấu xa. Bao nhiêu toan tính của hắn cũng {#Emph}tiêu tan!",
    "Aphrodite_0085": "Trong số họ hàng của Chúa tể Zeus, em vẫn chưa gặp Ares, {#Emph}nhỉ?{#Prev} Dạo này Thần Chiến Tranh bận bịu đủ điều. Có người nghi ngờ động cơ của ngài ấy, còn ta thì không. Ta chỉ mong biết ngài ấy đang ở đâu thôi.",
    "Aphrodite_0193": "Chúa tể Ares cuối cùng cũng trở về! Một cuộc chiến chỉ thật sự bắt đầu khi {#Emph}ngài ấy{#Prev} xuất hiện. Trước đây chúng ta từng chiến đấu cùng nhau mà chẳng phải lúc nào cũng thuận lợi, nhưng lần này gần như {#Emph}ai nấy{#Prev} đều có mặt!",
    "Aphrodite_0150": "Thế gian này đôi khi xấu xí biết bao! Đầy rẫy những hiểu lầm tệ hại che khuất vẻ đẹp mà chúng ta thường {#Emph}chẳng biết trân trọng đủ.",
    "Aphrodite_0151": "Ôi, người đẹp. Nếu kiêu hãnh và phù phiếm thật sự là điểm yếu, thì ngay lúc này ta sắp để em thấy mặt yếu đuối nhất của mình đây...",
    "Aphrodite_0152": "Ta cứ tưởng chị em chúng ta có mối giao tình đặc biệt, vậy mà em lại làm những chuyện khiến ta phân vân! Cũng hơi buồn nữa.",
    "Aphrodite_0153": "Ta ban Ân huệ cho em đâu phải để em cất dành như món ăn vặt! Muốn thứ khác thì cứ nói! Em có thể {#Emph}nhận{#Prev} nó.",
    "Aphrodite_0154": "Dù cố thế nào, ta vẫn nhói lòng khi bị khước từ. Ta ghét cảm giác ấy lắm. Vậy giờ ta phải khiến em cũng đau lòng mới được!",
    "Aphrodite_0155": "Có người chấp nhận bị gạt sang bên, nhưng ta thì {#Emph}không{#Prev} làm được đâu, cưng à! Dù cố đến mấy cũng vậy.",
    "Aphrodite_0156": "Ôi, đừng có {#Emph}trêu ghẹo{#Prev} ta chứ! Lần sau ta ban Ân huệ thì nhớ vui vẻ nhận lấy nhé. Còn bây giờ...?",
    "Aphrodite_0157": "Đôi khi ta nghĩ không nên bắt em phải chọn phe, nhưng chắc còn khối chuyện ta nghĩ là không nên làm! Chẳng hạn như nổi giận với {#Emph}em!",
    "Aphrodite_0158": "Em chọn Hephaestus thay vì {#Emph}ta sao?{#Prev} Chắc có nhầm lẫn gì rồi, cưng à! Mà đã vậy thì hẳn phải có một hình phạt {#Emph}nào đó...",
    "Aphrodite_0159": "Em {#Emph}có thể{#Prev} mặc kệ mấy cuộc cãi vã hiếm hoi giữa ta với Hephaestus chăm chỉ. Nhưng nếu em {#Emph}thật sự{#Prev} muốn xen vào thì... {#Emph}được thôi!",
    "Aphrodite_0160": "Cảm xúc vừa rồi nóng lên {#Emph}một chút{#Prev} nhỉ... Tim {#Emph}ta{#Prev} vẫn còn đập thình thịch, mà nếu ta không nhầm thì tim {#Emph}em{#Prev} cũng thế!",
    "Aphrodite_0161": "Thôi làm hòa nhé, người đẹp? Dạo gần đây bao chuyện xảy ra, chắc ai trong chúng ta cũng hơi căng thẳng!",
    "Aphrodite_0162": "Nghĩ lại thì giữa lúc tồi tệ nhất, có một điều gắn kết tất cả chúng ta: ai nấy đều {#Emph}nóng tính{#Prev} cả!",
    "Aphrodite_0163": "Ai cũng biết ta dễ bốc đồng vì đam mê, và ta chẳng muốn đổi tính ấy đâu. Nhưng lần tới em {#Emph}có thể{#Prev} xử sự khác đi đấy!",
    "Aphrodite_0164": "Thú thật nhé, lần đó chính {#Emph}ta{#Prev} gây sự trước, cưng à. Nhưng mỗi lần đôi bên nổi nóng, ta lại thấy tình cảm của chúng ta thêm sâu đậm!",
    "Aphrodite_0165": "{#Emph}Phù!{#Prev} Thấy dễ chịu hơn rồi chứ? Đừng giữ hết cảm xúc trong lòng. Thỉnh thoảng có bùng nổ một chút cũng chẳng sao.",
    "Aphrodite_0166": "Giờ thì bình tĩnh lại, để nhịp tim chậm xuống nào! Ta hết giận rồi, chỉ còn hơi bực một chút thôi...",
    "Aphrodite_0167": "{#Emph}Ừm{#Prev}, nếu có lý do chính đáng để từ chối Ân huệ của ta, nhất là vì đám họ hàng ghen tị, thì ta vẫn chưa nghe thấy đâu!",
    "Aphrodite_0182": "Nhớ nhé, cuộc chiến chống lại cái xấu chẳng bao giờ kết thúc! Nào, chiến đấu tiếp thôi!",
    "Aphrodite_0183": "Đã làm thì phải làm hết mình! Nào, phấn chấn lên đi!",
    "Aphrodite_0184": "Lại đến lúc tận hưởng một đêm {#Emph}tuyệt vời{#Prev} ngoài phố rồi! Dẫn đường đi, người đẹp!",
    "Aphrodite_0185": "Ta sẽ khiến chúng mềm nhũn cả gối. Chỗ khác cũng thế, phòng khi cần.",
    "Aphrodite_0186": "Thế gian có biết bao vẻ đẹp. Nếu ta không chiến đấu bảo vệ chúng thì còn ai làm đây?",
    "Aphrodite_0187": "Ta yêu việc mình làm, nhất là khi được tự tay giải quyết mọi chuyện.",
    "Aphrodite_0188": "Đêm nay lại về chốn yên bình dưới Âm phủ à? Ta sẽ làm nơi đó đẹp lên ngay thôi!",
    "Aphrodite_0189": "Em lại đang tiến về phía {#Emph}chúng ta{#Prev}! Chỉ nghĩ đến thôi tim ta đã đập nhanh hơn rồi!",
    "Aphrodite_0190": "Đêm nay liệu có thể còn tuyệt hơn đêm trước không? Đi tìm câu trả lời nào!",
    "Aphrodite_0043": "Em đã gặp {#Emph}biết bao{#Prev} người trên đỉnh núi này rồi, vậy mà dạo gần đây ta chẳng thấy bóng dáng Artemis đâu! Chẳng lẽ nữ thần săn bắn mải đuổi theo thú rừng đến nỗi không đến giúp chúng ta sao?",
    "Aphrodite_0044": "Anh trai em lúc nào cũng đáng yêu hết mực, cưng à! Rồi một ngày chẳng hiểu sao anh ấy không nhận lời nhắn của ta nữa. Ta đã làm gì phật ý chàng chăng? Mãi sau này mới biết Chronos là thủ phạm, ta nhẹ cả người!",
    "Aphrodite_0045": "Không biết Chronos đã làm gì mà anh trai em và cả nhà em đều mất liên lạc nhỉ? Có khi lão đã {#Emph}trói buộc họ!{#Prev} Dù sao cũng đừng lo quá. Họ là thần mà! Chắc vẫn ổn thôi.",
    "Aphrodite_0046": "Trong đời em có ai đó {#Emph}đặc biệt{#Prev} không? Ngôi sao sáng của Phù thủy Ngã ba Địa giới chắc {#Emph}bận rộn lắm{#Prev}, nên có lẽ câu trả lời là không. Có mặt ở phía trước nhiều chuyện mà cũng chậm hơn người khác...",
    "Aphrodite_0054": "Đam mê thường bùng lên vào lúc chẳng ai ngờ, đưa ta vượt qua giới hạn của chính mình! Hãy đón nhận nó như ta, rồi lên đường cùng mọi Ân huệ từ tận đáy lòng ta!",
    "Aphrodite_0055": "Cưng à, ta thích được như ý lắm. Mà lúc này ta muốn em mở một con đường đẫm máu xuyên qua mọi tên khốn phản bội dám cản bước em. {#Emph}Làm ơn nhé?",
    "Aphrodite_0056": "Ôi trời, tối nay em {#Emph}đẹp đến nghẹt thở{#Prev}! Chính Mặt Trăng {#Emph}đã{#Prev} giúp em tỏa sáng thế này phải không? Ta nhìn ra ngay. Cứ yên tâm, bí mật của em an toàn với ta!",
    "Aphrodite_0057": "Apollo Rạng Ngời đã liên lạc với em rồi, {#Emph}nhỉ?{#Prev} Đúng là nhanh tay giúp các nữ thần xinh đẹp. Tiếc là lúc anh trai em cần giúp đỡ thì chẳng thấy cậu ta đâu!",
    "Aphrodite_0058": "Chúa tể Zeus đã tìm đến em rồi, {#Emph}nhỉ?{#Prev} Dù có là người nhà, nếu ngài ấy ban Ân huệ thì chắc cũng mong được đáp lễ. Chỉ là ngài ấy ngại mở lời nhờ vả thôi.",
    "Aphrodite_0059": "Ta nghe Poseidon khoe đã ban cho em sức mạnh của ngài ấy rồi. Nhưng lỡ em vẫn còn thiếu gì đó sau ngần ấy {#Emph}Ân huệ{#Prev}, thì nhận thêm cái này nhé.",
    "Aphrodite_0060": "Em đã gặp Hephaestus lực lưỡng của ta rồi, {#Emph}nhỉ?{#Prev} Người ta đồn đủ điều chẳng hay về hai chúng ta mà chàng chẳng bận tâm. Giá mà {#Emph}da ta{#Prev} cũng dày được bằng {#Emph}da chàng{#Prev}...",
    "Aphrodite_0061": "Ta nghe bao anh hùng bảo thứ tốt nhất sau vũ khí do Hephaestus rèn chính là Ân huệ của chàng! Nhưng ta nghĩ họ vẫn thích nhận Ân huệ của ta hơn.",
    "Aphrodite_0062": "Ta thấy em đã làm quen với Nữ hoàng Hera rồi! Ta và nàng thường hợp tác, đôi bên đều hiểu ý nhau. Các nữ thần xinh đẹp phải đùm bọc nhau chứ!",
    "Aphrodite_0063": "Vậy là Hestia nóng nảy đã quý mến em rồi, {#Emph}nhỉ?{#Prev} Em nên tự hào đi, thường thì cô ấy chẳng buồn để tâm ai đâu. Cũng chẳng dễ gì làm cô ấy ấn tượng.",
    "Aphrodite_0064": "Ta mừng vì em và bà ngoại lạnh lùng đã có dịp gặp nhau! Ít ra giờ Demeter có thể bớt khắt khe với chúng ta đôi chút chăng?",
    "Aphrodite_0065": "Dạo gần đây, Hermes nhanh nhẹn thường chẳng thấy đâu cả. Ít nhất là không ở đây... nhưng có lẽ đang ở cõi của {#Emph}em{#Prev}, {#Emph}nhỉ?",
    "Aphrodite_0076": "Em đã gặp Hephaestus, hẳn cũng nghe chuyện về chàng rồi. Chàng có trái tim đẹp lắm. Chẳng lẽ chỉ mình ta nhìn ra điều đó? Trong bao người từng theo đuổi ta, chỉ chàng thấy vui khi để ta được là chính mình.",
    "Aphrodite_0078": "Chà, trên người em lấp lánh quả Táo Vàng phải không, người đẹp? Ta biết em có gu mà. Công dụng của chúng nhiều hơn em tưởng: nấu Tiên tửu Nectar thơm ngon, làm xao lòng tình địch xinh đẹp, khơi mào những cuộc chiến vĩ đại... đủ cả!",
    "Aphrodite_0079": "Ta có kể Táo Vàng nấu thành Tiên tửu Nectar được, nhưng chưa nói {#Emph}cách làm!{#Prev} Để ta gửi công thức cho em. Chỉ cần cái nồi sôi, ít gia vị thơm tùy thích và lời khấn cho đúng lúc. Phù thủy như em làm được mà!",
    "Aphrodite_0121": "Có chú chim nhỏ kể em đã đối đầu với các Nàng Tiên Cá dưới đáy biển à? Ta quá rõ tiếng hát mê hoặc của họ. Chắc họ chán cảnh dìm thủy thủ xuống đáy sâu rồi!",
    "Aphrodite_0125": "Chú chim nhỏ kể em đã gặp chàng Narcissus tuấn tú rồi phải không? Hẳn em nghĩ chàng là hình mẫu cho mọi điều ta đại diện... nhưng không đâu! Vì tình yêu lớn nhất là {#Emph}biết sẻ chia{#Prev}, chứ chẳng phải giữ khư khư cho riêng mình.",
    "Aphrodite_0126": "Mong em tránh xa tên Narcissus chẳng ra gì ấy. Những người theo đuổi chàng {#Emph}van nài{#Prev} ta xử lý thói mê bóng mình của chàng, nhưng ta xen vào làm gì một mối tình hòa hợp đến thế? Theo ta, cuối cùng chàng cũng gặp được đối thủ xứng tầm!",
    "Aphrodite_0131": "Em may mắn thừa hưởng những nét đẹp nhất của mẹ đấy, người đẹp! Dĩ nhiên {#Emph}cha em{#Prev} cũng có nét cuốn hút riêng. Nghĩ kỹ thì em chính là minh chứng sống cho điều đó!",
    "Aphrodite_0003": "Gặp lại {#Emph}em{#Prev} thật vui, người đẹp ạ!",
    "Aphrodite_0004": "Chà, ánh bạc làm em {#Emph}rạng ngời{#Prev} biết bao!",
    "Aphrodite_0005": "Các nữ thần chúng ta chúc em hạ gục {#Emph}mọi kẻ {#Prev}cản đường!",
    "Aphrodite_0006": "Chỉ cần trong tim còn tình yêu, em sẽ ổn thôi!",
    "Aphrodite_0007": "Đêm đẹp thế này mà em lại phải làm công việc xấu xí ấy!",
    "Aphrodite_0008": "Dù thời buổi khó khăn, ta vẫn tìm được {#Emph}điều gì đó {#Prev}đáng yêu!",
    "Aphrodite_0009": "Đời sẽ buồn tẻ biết bao nếu thiếu những rắc rối riêng, {#Emph}nhỉ?",
    "Aphrodite_0010": "Ôi, giá mà chỉ cần {#Emph}nhan sắc {#Prev}là đủ giết người, em yêu!",
    "Aphrodite_0011": "Gặp lại em {#Emph}vui quá{#Prev}, cưng à!",
    "Aphrodite_0012": "Ta {#Emph}thích mê{#Prev} những chuyến dạo đêm cùng em!",
    "Aphrodite_0013": "Gia đình chúng ta mà khiến bao người đổ máu, đánh nhau thế này!",
    "Aphrodite_0014": "Chắc phải có {#Emph}cách nào đó{#Prev} giúp được em chứ, người đẹp?",
    "Aphrodite_0015": "Càng khiến chúng mất tập trung, em càng dễ hạ chúng!",
    "Aphrodite_0016": "Ôi, ta mong em đến {#Emph}biết bao{#Prev}, người đẹp!",
    "Aphrodite_0017": "Chỉ hai nữ thần xinh đẹp cùng nhau đi chơi đêm thôi mà!",
    "Aphrodite_0018": "Cứ mặc chúng làm gì thì làm, đừng {#Emph}bao giờ{#Prev} để chúng khiến em nản lòng, cưng nhé.",
    "Aphrodite_0019": "Ta lại tìm thấy em rồi, người đẹp! Ôi, lần nào cũng {#Emph}vui hết ý{#Prev}!",
    "Aphrodite_0020": "Em vốn đã {#Emph}xinh đẹp{#Prev} rồi. Dù vậy, ta {#Emph}vẫn{#Prev} giúp thêm được chút nữa!",
    "Aphrodite_0021": "Ai ở phía đối đầu với {#Emph}em{#Prev}, cưng à, cũng sẽ phải đối đầu với {#Emph}ta{#Prev}.",
    "Aphrodite_0022": "Các phù thủy đúng là {#Emph}kín tiếng{#Prev} thật, nhưng ta biết {#Emph}rõ{#Prev} chỗ tìm em!",
    "Aphrodite_0023": "Cứ đà này, em sẽ làm tan nát nhiều trái tim hơn cả {#Emph}ta!",
    "Aphrodite_0024": "{#Emph}Ừm{#Prev}, các phù thủy được vui chơi {#Emph}thỏa thích{#Prev} nhỉ?",
    "Aphrodite_0025": "Nhớ nghĩ đến ta nhé, cứ phải quanh quẩn mãi trên đỉnh núi này...",
    "Aphrodite_0026": "{#Emph}Cuối cùng em cũng đến!{#Prev} Ta cứ tưởng em cho ta leo cây rồi, người đẹp!",
    "Aphrodite_0027": "Từ buổi hẹn nho nhỏ lần trước, ta đã mong ngày này mãi!",
    "Aphrodite_0028": "Lần này ta có đúng {#Emph}thứ{#Prev} em cần đây, cưng à!",
    "Aphrodite_0029": "{#Emph}Chào em!{#Prev} Mong em nhận được Ân huệ ngọt ngào nhất của ta.",
    "Aphrodite_0030": "Em đi đến đâu cũng có {#Emph}chuyện rắc rối{#Prev} chờ sẵn nhỉ?",
    "Aphrodite_0031": "Mong Ân huệ của ta nâng bước em như lời đường mật thì thầm bên tai.",
    "Aphrodite_0032": "Ta cứ nôn nóng muốn gặp lại em, và cuối cùng em cũng đến!",
    "Aphrodite_0033": "Chúng ta cùng hội cùng thuyền, cưng à, đừng quên điều đó {#Emph}nhé?",
    "Melinoe_0641": "Ấn ký trái tim...",
    "Melinoe_1476": "Aphrodite...",
    "Melinoe_1477": "Nàng ấy trở lại rồi.",
    "Aphrodite_0140": "Tình yêu gắn kết tất cả chúng ta, tiếp sức để ta làm nên những điều không thể tự mình hoàn thành! Em không cần chỉ nghe lời {#Emph}ta {#Prev}đâu, người đẹp. Người chú {#Emph}khôn ngoan {#Prev}và {#Emph}công bằng {#Prev}của em biết rõ cách chia sẻ tình yêu lắm!",
    "Zeus_0160": "Aphrodite thân mến nói rất đúng. Quyền cai trị của ta dựa trên tình yêu dành cho gia đình và cả nhân loại. Nếu không sống theo đam mê, chúng ta chiến đấu vì điều gì?",
    "Aphrodite_0142": "Cư xử {#Emph}thật tốt {#Prev}nhé, người đẹp! Ta xin giới thiệu Nữ hoàng rạng rỡ nhất. Người chẳng lạ gì chiến tranh hay việc diệt trừ cái ác đang âm ỉ trong lòng kẻ xấu! Xin ra mắt {#Emph}Nữ hoàng Hera!",
    "Hera_0110": "Aphrodite, chắc chúng ta không cần nghi thức rườm rà đến thế. Nhưng nhiều nữ thần nên hiểu rằng phải giữ vẻ ngoài chỉn chu ngay cả lúc khó khăn... {#Emph}nhất là {#Prev}khi khó khăn.",
    "Aphrodite_0144": "Trước đây ta cứ nghĩ chú Poseidon của em là gã thô lỗ vô dụng... nhưng sau khi tận mắt thấy chú chiến đấu trong cuộc chiến này, ta mới nhận ra mình sai đến mức nào! Chú chẳng vô dụng chút nào!",
    "Poseidon_0270": "Cảm ơn nàng, Aphrodite! Ta hiểu nàng khó lòng hình dung hết sức mạnh của ta; nói thật, nàng đâu phải nữ thần trí tuệ! {#Emph}Ta cũng chẳng phải! {#Prev}Nhưng chúng ta còn có điểm chung là cùng yêu {#Emph}vẻ đẹp của biển!",
    "Aphrodite_0094": "Olympus có biết bao vẻ đẹp, em yêu! Cứ lấy {#Emph}ta {#Prev}làm ví dụ, hay Apollo rạng ngời kia, {#Emph}hử? {#Prev}Anh họ em phải không? Ta thấy hai người hơi giống nhau đấy!",
    "Apollo_0100": "Nàng nói mới để ý, quý cô Aphrodite. Mái tóc vàng nhạt của ta cũng hơi giống suối tóc bồng bềnh của cô em họ. Vương quốc của nàng hẳn cũng đẹp lắm!",
    "Aphrodite_0148": "Em với bà Demeter hẳn có {#Emph}bao nhiêu {#Prev}chuyện cần hàn huyên! Biết đâu em còn khiến nếp cau mày lạnh lùng của bà tan ra, chứ ta thường sợ nó đã {#Emph}đóng băng vĩnh viễn{#Prev} rồi... Nhưng ta thấy bà đang muốn tự nói với em kìa!",
    "Demeter_0106": "Đừng để tâm lời Aphrodite, con yêu. Nàng ấy quan tâm đến đường nét trên mặt bà hơn là làm việc có ích. Nhưng chuyện chúng ta có nhiều điều cần hàn huyên thì nàng nói đúng...",
    "Aphrodite_0092": "Ta đau lòng phải thừa nhận đôi khi tình yêu không giải quyết được mọi chuyện, mà một lưỡi thép sắc bén lại hữu hiệu hơn. Hephaestus của ta có thể giúp việc đó, phải không chàng yêu?",
    "Hephaestus_0130": "Vì nàng thì {#Emph}lúc nào cũng được. {#Prev}Còn cô phù thủy này thì {#Emph}hầu hết {#Prev}là được! Nào, {#Emph}đi thôi. {#Prev}Ngay cả khi cần dùng thép sắc, nàng vẫn biết cách khiến người ta hiểu ý!",
    "Aphrodite_0146": "Vẻ đẹp chóng tàn chính là điều khiến ta {#Emph}khao khát {#Prev}nó! Nhưng ngay cả người đã mất đi vẻ đẹp {#Emph}bên ngoài{#Prev} vẫn thường có vẻ đẹp {#Emph}bên trong{#Prev} rực sáng! Đúng không, Hestia yêu dấu?",
    "Hestia_0156": "Cẩn thận với lối lý luận đó, Aphrodite. Cô chẳng có mấy vẻ đẹp bên trong, còn vẻ đẹp {#Emph}bên ngoài{#Prev} thì ta có thể nung chảy trong {#Emph}chớp mắt. {#Prev}Tóc cô mọc dài óng ả trở lại chắc cũng mất khối thời gian...",
    "Aphrodite_0213": "Ta vốn cũng là một chiến binh, ngài Ares đây biết rõ. Nhưng ta vẫn bảo chàng rằng những chiến công vĩ đại của tình yêu còn hồi hộp hơn chiến công nơi chiến trận!",
    "Ares_0165": "Ta thích những trận chiến dai dẳng, quý cô Aphrodite. Chinh phục là chinh phục, trên chiến trường hay trong trái tim cũng vậy. Tất cả đều khiến ta xúc động.",
    "Melinoe_0642": "Chắc nàng ta hiểu cả thù hận chứ không chỉ tình yêu. {#Emph}Nhân danh Hades! Olympus, ta xin nhận thông điệp này!",
    "Aphrodite_0129": "Ôi, {#Emph}xin chào{#Prev}, người đẹp! {#Emph}Em {#Prev}trông như có thể khiến bao trái tim tan vỡ mà chẳng cần {#Emph}ta giúp{#Prev}! Anh trai em hẳn tự hào lắm khi biết em đang chiến đấu vì gia đình!",
    "Aphrodite_0048": "Ôi không, tội nghiệp em quá! Trên đường đến đây đã xảy ra chuyện gì vậy? Chắc chắn ta có thể làm gì đó cho tình trạng đáng thương này!",
    "Aphrodite_0049": "{#Emph}Ừm{#Prev}, trông em như vừa trải qua một đêm khốn khổ. Ta hiểu mà, người đẹp; ta chỉ giỏi che giấu thôi!",
    "Aphrodite_0050": "{#Emph}Ôi{#Prev}, em xinh đẹp, em {#Emph}bị thương rồi! {#Prev}Không thể tha thứ được. Kẻ nào dám làm vậy, mong là em đã khiến chúng chết thật đau đớn!",
    "Aphrodite_0051": "Em {#Emph}bị thương{#Prev}, người đẹp! Giá mà ta đến với em sớm hơn. Nhưng đừng buồn! Tim em vẫn còn đập, phải không?",
    "Aphrodite_0052": "Lại được gặp em rồi, người đẹp! Ta không thể chờ thêm nữa nên lần này muốn đồng hành cùng em ngay từ đầu. Em sẵn sàng đón ta chưa, {#Emph}hử?",
    "Aphrodite_0053": "Trực giác mách bảo em sắp lên đường làm một nhiệm vụ trọng đại nữa, nên ta muốn là người đầu tiên tiễn em đi và dành cho em những điều tốt đẹp nhất!",
    "Aphrodite_0176": "Đêm còn dài, mà chúng ta vẫn phải thắng cuộc chiến này, người đẹp! Ta muốn đồng hành từ lúc em bắt đầu lên đường. Sao nào?",
    "Aphrodite_0177": "Đứng lại nào, em yêu! Em định đi vào đêm tối mà không có ta giúp giữ cho em {#Emph}ấm áp rạo rực{#Prev}, còn kẻ địch thì {#Emph}chết chôn dưới đất sao!",
    "Aphrodite_0034": "Giá mà ai cũng có thể theo đuổi đam mê mà chẳng phải trả giá! Nhưng đôi khi thần linh chúng ta cũng quá đà, rồi rơi vào những tình cảnh khó xử nhất...",
    "Aphrodite_0035": "Gia đình này chẳng giỏi buông bỏ nhỉ? Sau bao kỷ nguyên thịnh vượng, mọi thứ ta cùng nhau gây dựng sắp đổ sụp chỉ vì chút {#Emph}hiềm khích {#Prev}nhỏ! {#Emph}Hừ!",
    "Aphrodite_0036": "Nữ thần chúng ta cứ bị cuốn vào chuyện gia đình dù chẳng phải lỗi của mình. Trước đây {#Emph}ta {#Prev}đâu có thù oán với Chronos, vậy mà giờ lại đang chiến tranh với lão!",
    "Aphrodite_0037": "Nói riêng nhé, ta đã sống {#Emph}lâu {#Prev}hơn vẻ ngoài nhiều đấy. Cái gọi là {#Emph}Thời Hoàng Kim {#Prev}mà Chronos muốn khôi phục... chán ngắt, em không thể {#Emph}tưởng tượng nổi!",
    "Aphrodite_0039": "Em sống {#Emph}kín đáo {#Prev}quá đấy, cưng! Phàm nhân còn chẳng biết {#Emph}tên em! {#Prev}Chưa có lấy một ngôi đền dựng lên để {#Emph}tôn vinh em! {#Prev}Ít nhất là {#Emph}chưa thôi{#Prev}, nên cứ theo ta nhé!",
    "Aphrodite_0046": "Trong đời em có ai đó {#Emph}đặc biệt {#Prev}không? Ngôi sao sáng của Phù thủy Ngã ba Địa Giới chắc {#Emph}bận rộn lắm{#Prev}, nên có lẽ câu trả lời là không. Có mặt ở phía trước nhiều chuyện mà cũng chậm hơn người khác...",
    "Aphrodite_0047": "Tin ta đi, nếu em không chắc mình từng yêu chưa thì nghĩa là chưa đâu. Tình yêu như cơn rùng mình tràn qua rồi còn lưu lại thật dịu dàng rất lâu. Mong em sẽ tìm thấy cảm giác ấy hết lần này đến lần khác!",
    "Aphrodite_0122": "Em chiến đấu dữ dội như thể người em yêu đang lâm nguy! Nhưng đó đâu phải động lực của em, đúng không? Em đã tìm thấy nguồn sức mạnh từ điều khác! Đó là {#Emph}gì nhỉ?",
    "Aphrodite_0201": "Ta hiểu vì sao em là học trò xuất sắc của Phù thủy Ngã ba Địa Giới rồi, cưng... chỉ trong thời gian ngắn mà em đã hiểu nhiều về tình yêu, lại chỉ cần ta {#Emph}khuyên một chút{#Prev}! Trái tim em đặt đúng chỗ rồi.",
    "Aphrodite_0123": "Tình yêu đích thực có thể vĩnh cửu, dù đam mê thường phai nhạt. Ân Huệ của chúng ta cũng vậy! Tình yêu cần được nuôi dưỡng, niềm tin của chúng ta dành cho em cũng cần được bồi đắp, như thế này đây!",
    "Aphrodite_0071": "Ngắm em dưới ánh trăng rạng ngời kìa! {#Emph}Chào mừng{#Prev}, người đẹp, đến mặt đất xinh đẹp của chúng ta! Cứ ở lại bao lâu tùy thích! Hoặc bao lâu em chịu được. Dạo này nơi này hơi khắc nghiệt...",
    "Aphrodite_0072": "Em chắc lên đây là lựa chọn tốt chứ? Ta nghe nói người Âm phủ không thể ở lâu trên mặt đất. Xin em {#Emph}đừng {#Prev}gắng sức quá vì chúng ta!",
    "Aphrodite_0073": "Cưng à, em trông hoàn toàn {#Emph}như chính mình vậy! {#Prev}Ngay trên mặt đất này! Ta tưởng em không chịu nổi nơi đây, vậy mà giờ em sải bước trên vùng đất chiến tranh như thể nó vốn thuộc về em!",
    "Aphrodite_0083": "Thật đáng tiếc khi thành phố Ephyra bị nguyền rủa lại là nơi đầu tiên em thấy trên mặt đất, người đẹp. Thành phố từng được dựng để tôn vinh cha mẹ em, cho đến khi Chronos ra tay! Nghĩ đến thôi ta vẫn giận.",
    "Aphrodite_0080": "Ta muốn mời em đến chơi, nhưng Olympus đang bị vây hãm nên chuyến đi có lẽ chẳng đáng đâu. Ngọn núi này khác hẳn khi chúng ta {#Emph}bị mắc kẹt{#Prev}. Tiệc tùng và vui chơi đều giảm hẳn. Ôi, ta nhớ những ngày ấy quá...",
    "Aphrodite_0081": "Tuyệt quá, cuối cùng em cũng được tận mắt thấy ngọn núi của chúng ta! Nhưng đón khách vào lúc này thật xấu hổ; chúng ta đang bận tiếp đón kẻ địch!",
    "Aphrodite_0082": "Một ngày nào đó em sẽ thấy Olympus là nơi tuyệt đẹp. Mọi thú vui trần thế đều có ở đây! Mà ta thề là nơi này không lạnh như lời đồn đâu.",
    "Aphrodite_0074": "Ôi người đẹp, ta gần như chẳng còn nhìn thấy em nữa! Thật đáng tiếc cho {#Emph}ta{#Prev}. Mà em đang ở đâu vậy? Mắc kẹt tận dưới đáy biển sao?! Vương quốc của cha em rộng lớn thật.",
    "Aphrodite_0135": "{#Emph}A{#Prev}, em đã đến khe nứt mà ngài Poseidon {#Emph}chu đáo {#Prev}xẻ ngang vùng quê xinh đẹp của chúng ta... giúp quân địch tập hợp chống lại chúng ta còn {#Emph}nhanh hơn {#Prev}cả đi bộ! Mau lên nhé, {#Emph}hử?",
    "Aphrodite_0075": "Có chú chim nhỏ kể ta nghe Tam Nữ Thần Số Mệnh gặp chuyện... họ không còn ở đây để làm đời ta rắc rối nữa sao? Thảo nào ngày tháng của ta {#Emph}dễ đoán{#Prev} đến thế! Nhưng nếu Chronos thật sự đứng sau thì có lẽ ta nên lo...",
    "Aphrodite_0077": "Ngọn núi xinh đẹp của chúng ta rồi sẽ ra sao, em yêu? Gần đây có những trận rung chuyển mà ta chưa từng trải qua. Ban đầu ta tưởng Poseidon lại làm đất trời chao đảo, nhưng chỉ cần nhìn {#Emph}chàng ấy{#Prev} là ta biết không phải.",
    "Aphrodite_0124": "Đêm nào cũng bò qua những ngóc ngách sâu nhất Âm phủ chắc chẳng dễ chịu gì. Nhưng nơi nào cũng có vẻ đẹp! À, {#Emph}hầu hết {#Prev}mọi nơi. Chỗ em thì ta không dám chắc.",
    "Aphrodite_0127": "{#Emph}Ồ{#Prev}, ta biết về em ngày càng {#Emph}nhiều {#Prev}{#Emph}hơn {#Prev}, người đẹp. Mấy chú chim nhỏ của ta kể {#Emph}mọi chuyện!{#Prev} Chúng {#Emph}ở khắp nơi{#Prev}, chẳng gì thích hơn việc báo tin cho ta. {#Emph}Chúng{#Prev} vui khi {#Emph}ta{#Prev} vui, mà ta thì thích biết hết mọi chuyện!",
    "Aphrodite_0128": "Chiến tranh cũng có những lúc phấn khích đấy chứ! Đã lâu rồi ta chưa ra trận, làm kẻ địch choáng ngợp trước vẻ rực rỡ của ta rồi đâm xuyên chúng, để những phút cuối đời ngập trong sắc đẹp và {#Emph}đau đớn! {#Prev}Dù chiến tranh cũng khiến mọi thứ bừa bộn...",
    "Aphrodite_0040": "Em có sự dữ dội của cha mình đấy, người đẹp. Dù ta chưa từng biết ông ấy rõ lắm! Nghĩ lại thì ta cũng chẳng nghe kể nhiều về ông... ông ấy vốn không thích trò chuyện.",
    "Aphrodite_0041": "Vậy {#Emph}em là {#Prev}học trò xuất sắc của Hec vĩ đại! Chú chim nhỏ kể ta nghe cô ấy đang đào tạo một thiên tài. Ai ngờ người đó lại là Công chúa Âm phủ mất tích! Quả là chuyện {#Emph}động trời!",
    "Aphrodite_0042": "Chú chim nhỏ kể ta nghe {#Emph}chính Vận Mệnh Diệt Vong {#Prev}đã xuất hiện ở nơi em sống...? Chuyện đó chẳng lành cho em, có lẽ cho tất cả chúng ta nữa... nhưng ít nhất anh ấy đẹp trai thật, phải không?",
}

source = SRC.read_text(encoding="utf-8-sig")
OUT.parent.mkdir(parents=True, exist_ok=True)
mapped = {key: {"DisplayName": value} for key, value in translations.items()}
OUT.write_text(apply_translation_to_sjson(source, mapped), encoding="utf-8")
sys.stdout.reconfigure(encoding="utf-8")
print(f"Đã dịch {len(translations)} câu thoại Aphrodite.")
