# -*- coding: utf-8 -*-

translations_300_400 = {
  "Potion_CreatureBreedingNormal_desc": "Chất kích thích có mùi hăng nồng giúp thú nuôi sinh sản.",
  "Potions": "Độc Dược",
  "Potions_Desc": "Nghiên cứu về các hỗn hợp ma thuật và cách thức pha chế chúng.",
  "Potions_Sub_ChoppingTables": "Bàn Cắt Thái",
  "Potions_Sub_HoppingPots": "Nồi Nhảy Nhót",
  "Potions_Sub_Stations": "Bàn Chế Độc Dược",
  "PotionsCategory": "Độc Dược",
  "PotionsCategory_desc": "Các vật phẩm dùng để pha chế độc dược.",
  "PotionsClass": "Độc Dược",
  "PotionsClass_desc": "Môn học tại Hogwarts chuyên giảng dạy kỹ nghệ pha chế các loại độc dược.",
  "PotionsClassVignetteObject": "Vật Thể Họa Tiết Lớp Học Độc Dược",
  "PotionsScholar": "Học Giả Độc Dược",
  "Potionstation_classroom": "Đã mở khóa Bàn Chế Độc Dược",
  "Protego": "Bùa Khiên Che Chắn (Protego)",
  "Protego_desc": "Bùa chú này có thể ngăn chặn sát thương từ các loại bùa chú và đòn đánh vũ khí. Nhấn {AM_Protego} để thi triển. Thi triển Bùa Khiên Che Chắn (Protego) vào khoảnh khắc ngay trước khi đòn đánh chạm tới sẽ tạo thành Khiên Hoàn Hảo, gây sát thương lên kẻ tấn công cận chiến và dội ngược các vật thể bay, phá hủy khiên của kẻ địch.",
  "Protego_gameplay_desc": "Bùa chú này có thể ngăn chặn sát thương từ các loại bùa chú và đòn đánh vũ khí. Nhấn {AM_Protego} để thi triển. Thi triển Bùa Khiên Che Chắn (Protego) vào khoảnh khắc ngay trước khi đòn đánh chạm tới sẽ tạo thành Khiên Hoàn Hảo, gây sát thương lên kẻ tấn công cận chiến và dội ngược các vật thể bay, phá hủy khiên của kẻ địch.",
  "Recipe_AMFillPotion": "Công Thức Thuốc Tập Trung",
  "Recipe_AMFillPotion_desc": "Công thức độc dược giúp giảm thời gian hồi chiêu của bùa chú sau khi uống.",
  "Recipe_AutoDamagePotion": "Công Thức Thuốc Sấm Sét Thunderbrew",
  "Recipe_AutoDamagePotion_desc": "Công thức chế tạo một loại độc dược sát thương uy lực.",
  "Recipe_InvisibilityPotion": "Công Thức Thuốc Tàng Hình",
  "Recipe_InvisibilityPotion_desc": "Công thức chế tạo độc dược giúp tàng hình gần như tuyệt đối sau khi uống.",
  "Recipe_Transfiguration_Sanc_PlanterSmall1_Potioneer": "Bản Vẽ Biến Hình Bàn Trồng Trọt (Chậu Nhỏ)",
  "Recipe_Transfiguration_Sanc_PlanterSmall1_Potioneer_desc": "Mở khóa khả năng biến hình Bàn Trồng Trọt Nhỏ. Các chậu trên bàn có thể dùng để gieo trồng nhiều loại thực vật ma thuật.",
  "Recipe_Transfiguration_Sanc_PotionStationMedium": "Bản Vẽ Biến Hình Bàn Chế Độc Dược Vừa",
  "Recipe_Transfiguration_Sanc_PotionStationMedium_desc": "Mở khóa khả năng biến hình Bàn Chế Độc Dược Cỡ Vừa. Đáp ứng hoàn hảo mọi nhu cầu pha chế độc dược của bạn.",
  "Recipe_Transfiguration_Sanc_PotionStationSmall_Potioneer": "Bản Vẽ Biến Hình Bàn Chế Độc Dược Nhỏ",
  "Recipe_Transfiguration_Sanc_PotionStationSmall_Potioneer_desc": "Mở khóa kỹ năng biến hình Bàn Chế Độc Dược Cỡ Nhỏ. Đáp ứng hoàn hảo mọi nhu cầu pha chế độc dược của bạn.",
  "Recipe_Transfiguration_Sanc_PotionStationT": "Bản Vẽ Biến Hình Bàn Chế Độc Dược Chữ T",
  "Recipe_Transfiguration_Sanc_PotionStationT_desc": "Mở khóa khả năng biến hình Bàn Chế Độc Dược Chữ T. Đáp ứng hoàn hảo mọi nhu cầu pha chế độc dược của bạn.",
  "Reparo": "Bùa Sửa Chữa (Reparo)",
  "Reparo_desc": "Cho phép bạn nhanh chóng khôi phục các đồ vật bị gãy vỡ về trạng thái nguyên vẹn ban đầu.",
  "Reparo_gameplay_desc": "Cho phép bạn nhanh chóng khôi phục các đồ vật bị gãy vỡ về trạng thái nguyên vẹn ban đầu.",
  "Revelio": "Bùa Hiện Hình (Revelio)",
  "Revelio_desc": "Làm nổi bật các mục tiêu hữu ích hoặc vật thể có thể tương tác trong môi trường xung quanh, bao gồm các đồ vật ẩn giấu, đạo cụ giải đố, chiến lợi phẩm và mục tiêu nhiệm vụ. Nhấn {RevelioButton} để thi triển.",
  "Revelio_gameplay_desc": "Làm nổi bật các mục tiêu hữu ích hoặc vật thể có thể tương tác trong môi trường xung quanh, bao gồm các đồ vật ẩn giấu, đạo cụ giải đố, chiến lợi phẩm và mục tiêu nhiệm vụ. Nhấn {RevelioButton} để thi triển.",
  "Revelio_Title": "Bùa Hiện Hình (Revelio)",
  "Sanc_PotioneerTools_Wall": "Giá Treo Dụng Cụ Bậc Thầy Độc Dược",
  "Sanc_PotioneerTools_Wall_01": "Giá Treo Dụng Cụ Bậc Thầy Độc Dược",
  "Sanc_PotioneerTools_Wall_01_desc": "Chiếc giá này chứa đầy đủ mọi dụng cụ cần thiết cho một phù thủy pha chế độc dược đầy hoài bão.",
  "Sanc_PotioneerTools_Wall_Desc": "Chiếc giá này chứa đầy đủ mọi dụng cụ cần thiết cho một phù thủy pha chế độc dược đầy hoài bão.",
  "Sanc_PotioneerTools_Walls_01": "Giá Treo Dụng Cụ Bậc Thầy Độc Dược",
  "Sanc_PotioneerTools_Walls_01_desc": "Chiếc giá chứa đầy đủ các dụng cụ của bậc thầy độc dược.",
  "Sanc_PotionStationMedium": "Bàn Chế Độc Dược Cỡ Vừa",
  "Sanc_PotionStationMedium_01_Dwiz": "Bàn Chế Độc Dược Cỡ Vừa Gothic",
  "Sanc_PotionStationMedium_01_Dwiz_desc": "Bàn chế độc dược cỡ vừa kiểu Gothic, được trang bị hai bếp lò để pha chế độc dược.",
  "Sanc_PotionStationMedium_01_Hbgst": "Bàn Chế Độc Dược Cỡ Vừa Thực Vật",
  "Sanc_PotionStationMedium_01_Hbgst_desc": "Bàn chế độc dược cỡ vừa phong cách thảo mộc, được trang bị hai bếp lò để pha chế độc dược.",
  "Sanc_PotionStationMedium_01_Mzoo": "Bàn Chế Độc Dược Cỡ Vừa Đa Dạng",
  "Sanc_PotionStationMedium_01_Mzoo_desc": "Bàn chế độc dược cỡ vừa phong cách sinh vật huyền bí, được trang bị hai bếp lò để pha chế độc dược.",
  "Sanc_PotionStationMedium_01_Potnr": "Bàn Chế Độc Dược Cỡ Vừa Giả Kim",
  "Sanc_PotionStationMedium_01_Potnr_desc": "Bàn chế độc dược cỡ vừa phong cách thuật giả kim, được trang bị hai bếp lò để pha chế độc dược.",
  "Sanc_PotionStationMedium_Desc": "Bàn chế độc dược cỡ vừa, được trang bị hai bếp lò để pha chế độc dược.",
  "Sanc_PotionStationSmall": "Bàn Chế Độc Dược Cỡ Nhỏ",
  "Sanc_PotionStationSmall_01_Dwiz": "Bàn Chế Độc Dược Cỡ Nhỏ Gothic",
  "Sanc_PotionStationSmall_01_Dwiz_desc": "Bàn chế độc dược cỡ nhỏ kiểu Gothic, được trang bị một bếp lò để pha chế độc dược.",
  "Sanc_PotionStationSmall_01_Hbgst": "Bàn Chế Độc Dược Cỡ Nhỏ Thực Vật",
  "Sanc_PotionStationSmall_01_Hbgst_desc": "Bàn chế độc dược cỡ nhỏ phong cách thảo mộc, được trang bị một bếp lò để pha chế độc dược.",
  "Sanc_PotionStationSmall_01_Mzoo": "Bàn Chế Độc Dược Cỡ Nhỏ Đa Dạng",
  "Sanc_PotionStationSmall_01_Mzoo_desc": "Bàn chế độc dược cỡ nhỏ phong cách sinh vật huyền bí, được trang bị một bếp lò để pha chế độc dược.",
  "Sanc_PotionStationSmall_01_Potnr": "Bàn Chế Độc Dược Cỡ Nhỏ Giả Kim",
  "Sanc_PotionStationSmall_01_Potnr_desc": "Bàn chế độc dược cỡ nhỏ phong cách thuật giả kim, được trang bị một bếp lò để pha chế độc dược.",
  "Sanc_PotionStationSmall_desc": "Bàn chế độc dược cỡ nhỏ, được trang bị một bếp lò để pha chế độc dược.",
  "Sanc_PotionStationT": "Bàn Chế Độc Dược Chữ T",
  "Sanc_PotionStationT_desc": "Bàn chế độc dược hình chữ T, được trang bị ba bếp lò để pha chế độc dược.",
  "Sanc_PotionStationTshape_01_Dwiz": "Bàn Chế Độc Dược Chữ T Gothic",
  "Sanc_PotionStationTshape_01_Dwiz_desc": "Bàn chế độc dược hình chữ T kiểu Gothic, được trang bị ba bếp lò để pha chế độc dược.",
  "Sanc_PotionStationTshape_01_Hbgst": "Bàn Chế Độc Dược Chữ T Thực Vật",
  "Sanc_PotionStationTshape_01_Hbgst_desc": "Bàn chế độc dược hình chữ T phong cách thảo mộc, được trang bị ba bếp lò để pha chế độc dược.",
  "Sanc_PotionStationTshape_01_Mzoo": "Bàn Chế Độc Dược Chữ T Đa Dạng",
  "Sanc_PotionStationTshape_01_Mzoo_desc": "Bàn chế độc dược hình chữ T phong cách sinh vật huyền bí, được trang bị ba bếp lò để pha chế độc dược.",
  "Sanc_PotionStationTshape_01_Potnr": "Bàn Chế Độc Dược Chữ T Giả Kim",
  "Sanc_PotionStationTshape_01_Potnr_desc": "Bàn chế độc dược hình chữ T phong cách thuật giả kim, được trang bị ba bếp lò để pha chế độc dược.",
  "Sanc_PotionStationTshape_desc": "Bàn chế độc dược hình chữ T, được trang bị ba bếp lò để pha chế độc dược.",
  "SettingsControl_AM_Protego": "Bùa Khiên Che Chắn (Protego)",
  "SettingsControl_AM_Revelio": "Bùa Hiện Hình (Revelio)",
  "SettingsControl_AM_SpellButton1": "Thi Triển Bùa Chú 1",
  "SettingsControl_AM_SpellButton2": "Thi Triển Bùa Chú 2",
  "SettingsControl_AM_SpellButton3": "Thi Triển Bùa Chú 3",
  "SettingsControl_AM_SpellButton4": "Thi Triển Bùa Chú 4",
  "SettingsControl_AM_Stupefy": "Thi Triển Cơ Bản",
  "SettingsControl_UMGAccioActivityRules": "Mở Rộng Luật Chơi",
  "SettingsControl_UMGSpellMinigameOption1": "Tùy Chọn 1",
  "SettingsControl_UMGSpellMinigameOption2": "Tùy Chọn 2",
  "SettingsControl_UMGSpellMinigameOption3": "Tùy Chọn 3",
  "SettingsControl_UMGSpellMinigameOption4": "Tùy Chọn 4",
  "SettingsControl_UMGStartSpellMiniGame": "Bắt Đầu",
  "SettingsControl_UMGViewSpellVideo": "Xem Đoạn Phim Bùa Chú",
  "SettingsControls_AccioActivity": "Triệu Tập Tỉ Thí (Accio)",
  "SettingsControls_PotionsAndHerbologyStations": "Bàn Độc Dược & Thảo Dược Học",
  "SettingsControls_SpellMinigame": "Trò Chơi Nhỏ Bùa Chú",
  "SettingsControls_SpellsActions": "Bùa Chú & Thao Tác",
  "SettingsControls_WingardiumLevioso": "Bùa Bay Lơ Lửng (Wingardium Leviosa)",
  "Spell_Accio": "Bùa Triệu Tập (Accio)",
  "Spell_Alohomora": "Bùa Mở Khóa (Alohomora)",
  "Spell_Alohomora_L2": "Bùa Mở Khóa (Alohomora) II",
  "Spell_Alohomora_L3": "Bùa Mở Khóa (Alohomora) III",
  "Spell_ArrestoMomentum": "Bùa Hãm Đà (Arresto Momentum)",
  "Spell_AvadaKedavra": "Lời Nguyền Chết Chóc (Avada Kedavra)",
  "Spell_Confringo": "Bùa Nổ Súng (Confringo)"
}

if __name__ == '__main__':
    print(f"Loaded {len(translations_300_400)} keys.")
