# -*- coding: utf-8 -*-

translations_600_end = {
  "TUT_LeviosoPC_Part1_desc2": "Nhấn phím được gán để thi triển \"Bùa Bay Lơ Lửng (Levioso)\" <img src=\"Levioso\"/>.",
  "TUT_PotionUsage": "Sử Dụng Độc Dược",
  "Tut_PracticeAccio": "Bùa Triệu Tập (Accio)",
  "TUT_Protego": "Bùa Khiên Che Chắn (Protego)",
  "TUT_Reparo": "Bùa Sửa Chữa (Reparo)",
  "TUT_Reparo_desc": "Đây là phần hướng dẫn Bùa Sửa Chữa (Reparo).",
  "TUT_SlottingSpells_Part1": "Trang Bị \"Bùa Bay Lơ Lửng (Levioso)\"",
  "TUT_SlottingSpells_Part1_desc": "Trước khi thi triển \"Bùa Bay Lơ Lửng (Levioso)\", trước tiên bạn cần phải trang bị bùa chú này vào bộ bùa chú.\n\nNhấn {UMGActionScreenToggle} để mở menu chọn bùa chú.",
  "TUT_SlottingSpells_Part2": "Chọn Bùa Chú",
  "TUT_SlottingSpells_Part2_desc": "Để sử dụng một thao tác, trước tiên bạn phải trang bị nó trong bộ bùa chú. Hãy thêm \"Bùa Bay Lơ Lửng (Levioso)\" vào bộ bùa chú của bạn.\n\nChọn \"Bùa Bay Lơ Lửng (Levioso)\" và giữ {SpellModifierButton}.",
  "TUT_SlottingSpells_Part3_desc": "Nhấn {UMGFaceButtonRight} để đóng menu chọn bùa chú.",
  "TUT_SlottingSpells_Part4": "Trang Bị Bùa Chú",
  "TUT_SlottingSpellsAccio_Part1_desc": "Trước khi thi triển Bùa Triệu Tập (Accio), trước tiên bạn cần phải trang bị bùa chú này vào bộ bùa chú.\n\nNhấn {UMGActionScreenToggle} để mở menu chọn bùa chú.",
  "TUT_SlottingSpellsAccio_Part2": "Chọn Bùa Chú",
  "TUT_SlottingSpellsAccio_Part2_desc": "Giao diện chọn bùa chú sẽ hiển thị tất cả các thao tác khả dụng của bạn. Để sử dụng một thao tác, trước tiên bạn phải trang bị nó trong bộ bùa chú.\n\nChọn Bùa Triệu Tập (Accio) và giữ {SpellModifierButton}.",
  "TUT_SlottingSpellsAccio_Part3_desc": "Bây giờ bạn đã có thể thi triển Bùa Triệu Tập (Accio).\n\nNhấn {UMGFaceButtonRight} để đóng menu chọn bùa chú.",
  "TUT_SlottingSpellsItems": "Đặt Bùa Chú Vào Ô",
  "TUT_Stupefy": "Thi Triển Cơ Bản",
  "TUT_Stupefy_desc": "Trong thời gian \"Bùa Khiên Che Chắn (Protego)\" <img src=\"Protego\"/> có hiệu lực, giữ {Protego} để tung đòn phản công bằng \"Bùa Choáng Váng (Stupefy)\" <img src=\"Stupefy\"/> làm choáng kẻ địch.",
  "TUT_ZZC_AccioSpell": "Bùa Triệu Tập (Accio)",
  "TUT_ZZC_AccioSpell_desc": "Bùa triệu tập \"Bùa Triệu Tập (Accio)\" <img src=\"Accio\"/> có thể kéo mục tiêu lại gần người thi triển. Giữ {SpellModifierButton} và nhấn phím được gán để thi triển \"Bùa Triệu Tập (Accio)\" và kéo mục tiêu lại gần. Thả {SpellModifierButton} để ngừng niệm chú.",
  "TUT_ZZC_AccioSpellPC_desc": "Bùa triệu tập \"Bùa Triệu Tập (Accio)\" <img src=\"Accio\"/> có thể kéo mục tiêu lại gần người thi triển. Nhấn phím được gán để thi triển \"Bùa Triệu Tập (Accio)\" và kéo mục tiêu lại gần. Nhấn lại phím đó một lần nữa để ngừng niệm chú.",
  "VendorCategory_PotionRecipes": "Công Thức Độc Dược",
  "VendorCategory_TransfigurationSpellcrafts": "Bản Vẽ Biến Hình",
  "WET_01_01_SpellPractice_Journal": "Giáo sư Weasley vẫn còn một chuyện nữa muốn thảo luận với tôi.",
  "WET_01_SpellPractice_QuestAvailalbe_Journal": "Giáo sư Weasley muốn gặp tôi tại phòng học của bà, căn phòng nằm ngay bên ngoài Sân Biến Hình, giữa Khu Phụ Cận Thư Viện và Khu Vực Thiên Văn. Hy vọng cô ấy có tin tức về việc thay thế những đồ dùng tôi đã làm mất.",
  "WET_01_SpellPractice_QuestAvailalbe_JournalRollover": "Giáo sư Weasley muốn gặp tôi ở Lớp Học Biến Hình.",
  "WET_01_SpellPractice_QuestAvailalbe_TaskObj01": "Gặp Giáo sư Weasley ở Lớp Học Biến Hình",
  "WET_01_SpellPractice_QuestComplete_Journal_Natty": "Tôi đã gặp Giáo sư Weasley, bà đã sắp xếp để tôi cùng một người bạn đồng hành đi đến Làng Hogsmeade. Tôi quyết định mời Natsai Onai, vì cô ấy có vẻ là một phù thủy rất đáng tin cậy khi ở bên cạnh. Trước khi đi, bà yêu cầu tôi hoàn thành một bài tập cho Giáo sư Ronan.",
  "WET_01_SpellPractice_QuestComplete_Journal_Seb": "Tôi đã gặp Giáo sư Weasley, bà đã sắp xếp để tôi cùng một người bạn đồng hành đi đến Làng Hogsmeade. Tôi quyết định mời Sebastian Sallow, vì cậu ấy có vẻ là một phù thủy rất thích hợp để đồng hành. Trước khi đi, bà yêu cầu tôi hoàn thành một bài tập cho Giáo sư Ronan.",
  "ZSB_01_BombardaSide_Title": "Bài Tập Của Giáo Sư Howin",
  "ZSD_01_PotionsAssignment1_QuestActive_StepJournal01": "Giáo sư Sharp muốn tôi kiểm tra năng lực của bản thân sau khi uống Thuốc Tối Đại Maxima và Thuốc Cường Hóa Edurus. Ngoài ra, giáo sư còn muốn tôi thử nghiệm hiệu quả của Thuốc Tập Trung trong thực chiến. Tiệm Độc Dược J. Pippin có thể cung cấp các loại độc dược và công thức tôi cần. Cẩm Nang Phù Thủy sẽ không hướng dẫn tôi hoàn thành bài tập này, nhưng bản đồ của tôi vẫn sẽ phát huy tác dụng.",
  "ZSD_01_PotionsAssignment1_QuestActive_StepJournal02": "Tôi đã hoàn thành xong bài tập giáo sư giao. Bây giờ tôi cần trở lại Phòng Học Độc Dược và học \"Bùa Đẩy Lùi (Depulso)\" từ Giáo sư Sharp.",
  "ZSD_01_PotionsAssignment1_QuestActive_StepJournal03": "Tôi cần nói chuyện với Giáo sư Sharp. Tiếp theo thầy ấy sẽ dạy tôi một bùa chú mới.",
  "ZSD_01_PotionsAssignment1_QuestActive_TaskObj01a": "Lấy Thuốc Tối Đại Maxima cùng Thuốc Cường Hóa Edurus, sau đó cùng lúc thử nghiệm hiệu quả của cả hai loại độc dược này trong thực chiến <img src=\"Map_Vendor_PippinsPotions\"/>",
  "ZSD_01_PotionsAssignment1_QuestActive_TaskObj01b": "Lấy Thuốc Tập Trung và thử nghiệm hiệu quả độc dược trong thực chiến <img src=\"Map_Vendor_PippinsPotions\"/>",
  "ZSD_01_PotionsAssignment1_QuestActive_TaskObj02": "Quay lại gặp Giáo sư Sharp",
  "ZSD_01_PotionsAssignment1_QuestAvailable_Journal": "Giáo sư Sharp muốn giao cho tôi một bài tập ngoại khóa bổ sung. Sau khi hoàn thành xong các bài tập này, Giáo sư Sharp hứa sẽ dạy tôi Bùa Xua Đuổi \"Bùa Đẩy Lùi (Depulso)\", một bùa chú có thể dùng lực cực mạnh để hất tung mục tiêu.",
  "ZSD_01_PotionsAssignment1_QuestAvailable_StepJournal": "Tôi cần hoàn thành bài tập do Giáo sư Sharp giao.",
  "ZSD_01_PotionsAssignment1_QuestComplete_Journal": "Theo yêu cầu của Giáo sư Sharp, tôi đã thử nghiệm thành công hiệu quả của Thuốc Tối Đại Maxima, Thuốc Cường Hóa Edurus và Thuốc Tập Trung trong thực chiến. Để tưởng thưởng, Giáo sư Sharp đã dạy tôi cách thi triển Bùa Xua Đuổi \"Bùa Đẩy Lùi (Depulso)\", bùa chú có thể vận dụng một lực cực lớn để hất tung đối thủ của tôi.",
  "ZSG_01_GlaciusSide_Title": "Bài Tập Của Phu Nhân Kogawa",
  "ZSR_01_01_ReparoSide_Journal": "Giáo sư Ronan đã giao cho tôi một số bài tập bổ sung, và nói rằng sau khi tôi hoàn thành, thầy ấy sẽ dạy tôi bùa phục hồi \"Bùa Sửa Chữa (Reparo)\".",
  "ZSR_01_01_ReparoSide_Title": "Bài Tập Của Giáo Sư Ronan",
  "ZZC_01_02_AccioGame_EquipAccio_Task": "Trang bị Bùa Triệu Tập (Accio) vào bộ bùa chú của bạn",
  "ZZC_01_02_AccioGame_Journal": "Trong tiết học, Giáo sư Ronan đã tổ chức một trò chơi nhỏ tương tự như đá Gobstone, nhằm kiểm tra mức độ thuần thục Bùa Triệu Tập (Accio) của cả lớp. Tôi nên cố gắng hết sức để giành chiến thắng.",
  "ZZC_01_02_AccioGame_Round1_Task1": "Hoàn thành vòng luyện tập",
  "ZZC_01_02_AccioGame_Round2_Task2": "Tranh tài Triệu Tập Tỉ Thí (Accio) với Natsai",
  "ZZC_01_02_AccioGame_Round3_Task3": "Tranh tài vòng thứ hai với Natsai",
  "ZZC_01_02_AccioGame_StepComplete_Journal": "Tôi đã so tài cùng Natsai trong trận đấu Bùa Triệu Tập (Accio) do Giáo sư Ronan chủ trì.",
  "ZZC_01_02_ParticipateLesson__PracticeAccio_Task": "Luyện tập Bùa Triệu Tập (Accio)",
  "ZZC_01_EquipAccio_StepJournal": "Giáo sư Ronan đã tổ chức một trò chơi nhỏ để luyện tập bùa triệu tập. Tôi cần đảm bảo rằng bản thân đã có thể vận dụng thuần thục Bùa Triệu Tập (Accio).",
  "ZZN_01_01_PotionsSide_Title": "Bài Tập Của Giáo Sư Sharp",
  "ZZP_01_01_BoilandTrouble_AttendPotionsClass_Task": "Tham dự Lớp Học Độc Dược",
  "ZZP_01_01_PotionsClass1_Journal": "Tiếp theo tôi cần phải tham dự tiết học môn Độc Dược. Giáo sư Sharp là giáo viên phụ trách môn học này.",
  "ZZP_01_01_PotionsClass1_Title": "Lớp Học Độc Dược",
  "ZZP_01_02_UsePotionsTable_BrewaPotion_Task": "Pha chế một phần Thuốc Cường Hóa Edurus",
  "ZZP_01_02_UsePotionsTable_Journal": "Tôi cần phải pha chế một phần Thuốc Cường Hóa Edurus tại bàn chế độc dược.",
  "ZZP_01_PotionClass1_QuestAvailable_Journal": "Là một \"học sinh năm thứ năm mới chuyển đến\", tôi còn rất nhiều điều phải học hỏi, đặc biệt là trong bộ môn Độc Dược. Để theo kịp tiến độ, tôi cần phải khiêm tốn thỉnh giáo Giáo sư Sharp. Tôi tin chắc bản thân sẽ học hỏi được rất nhiều điều từ môn học này.",
  "ZZP_01_PotionClass_LineComplete_Journal": "Trong tiết học Độc Dược của Giáo sư Sharp, tôi đã tận dụng nguyên liệu mà thầy cung cấp để pha chế thành công một phần Thuốc Cường Hóa Edurus.",
  "ZZP_01_PotionClass_QuestTitle": "Lớp Học Độc Dược",
  "ZZZ_EquipAccio": "Trang bị Bùa Triệu Tập (Accio) vào bộ bùa chú của bạn"
}

if __name__ == '__main__':
    print(f"Loaded {len(translations_600_end)} keys.")
