# -*- coding: utf-8 -*-

translations_400_500 = {
  "Spell_Conjuration": "Bùa Biến Hiện (Conjuration)",
  "Spell_Crucio": "Lời Nguyền Tra Tấn (Crucio)",
  "Spell_Depulso": "Bùa Đẩy Lùi (Depulso)",
  "Spell_Descendo": "Bùa Đập Xuống (Descendo)",
  "Spell_Diffindo": "Bùa Cắt Sâu (Diffindo)",
  "Spell_Disillusionment": "Bùa Tàng Hình (Disillusionment)",
  "Spell_Expelliarmus": "Bùa Giải Giới (Expelliarmus)",
  "Spell_Expulso": "Bùa Nổ Công Phá (Bombarda)",
  "Spell_Finishers": "Phép Thuật Cổ Xưa",
  "Spell_Flipendo": "Bùa Lộn Nhào (Flipendo)",
  "Spell_Glacius": "Bùa Đóng Băng (Glacius)",
  "Spell_Imperius": "Lời Nguyền Độc Đoán (Imperio)",
  "Spell_Incendio": "Bùa Lửa (Incendio)",
  "Spell_Levioso": "Bùa Bay Lơ Lửng (Levioso)",
  "Spell_Lumos": "Bùa Phát Sáng (Lumos)",
  "Spell_Oppugno": "Ném Phép Thuật Cổ Xưa",
  "Spell_Protego": "Bùa Khiên Che Chắn (Protego)",
  "Spell_Reparo": "Bùa Sửa Chữa (Reparo)",
  "Spell_Revelio": "Bùa Hiện Hình (Revelio)",
  "Spell_Transfiguration": "Biến Hình",
  "Spell_Transformation": "Bùa Biến Đổi",
  "Spell_Vanishment": "Bùa Biến Mất (Evanesco)",
  "Spell_Wingardium": "Bùa Bay Lơ Lửng (Wingardium Leviosa)",
  "SpellMinigame_Start": "Bắt Đầu",
  "Spells_Vul": "Yếu thế trước hầu hết các loại bùa chú",
  "SpellType_CrowdControl": "Khống Chế",
  "SpellType_DarkArts": "Lời Nguyền Không Thể Tha Thứ",
  "SpellType_Forceful": "Lực Đẩy",
  "SpellType_HeavyDamage": "Sát Thương",
  "SpellType_Standard": "Tiện Ích",
  "SpellType_Transfiguration": "Biến Hình",
  "Stupefy": "Thi Triển Cơ Bản",
  "Stupefy_desc": "Gây một lượng sát thương nhỏ lên kẻ địch và đồ vật. Nhấn liên tục {Stupefy} để thi triển.",
  "Stupefy_gameplay_desc": "Làm choáng váng kẻ địch, khiến chúng dễ bị tổn thương hơn trước các bùa chú khác. Bùa chú này không trực tiếp gây sát thương, nhưng kẻ địch bị choáng sẽ phải chịu thêm sát thương, biểu thị bằng các con số màu vàng kim. Bùa chú này còn có thể phá vỡ bùa khiên chắn của kẻ địch (ngoại trừ độ khó Khó). Sau khi dùng \"Bùa Khiên Che Chắn (Protego)\" chặn đòn tấn công thành công, giữ {AM_Protego} để phóng đòn phản công \"Bùa Choáng Váng (Stupefy)\" vào bất kỳ kẻ địch nào bạn đang nhắm tới.",
  "StupefySpecial_Send": "Bùa Choáng Váng (Stupefy)",
  "StupefySpecial_Send_desc": "Làm choáng váng kẻ địch, khiến chúng dễ bị tổn thương hơn trước các bùa chú khác. Bùa chú này không trực tiếp gây sát thương, nhưng kẻ địch bị choáng sẽ phải chịu thêm sát thương, biểu thị bằng các con số màu vàng kim. Bùa chú này còn có thể phá vỡ bùa khiên chắn của kẻ địch (ngoại trừ độ khó Khó). Sau khi dùng \"Bùa Khiên Che Chắn (Protego)\" chặn đòn tấn công thành công, giữ {AM_Protego} để phóng đòn phản công \"Bùa Choáng Váng (Stupefy)\" vào bất kỳ kẻ địch nào bạn đang nhắm tới.",
  "Talent_Core_ProtegoAM": "Hấp Thu Năng Lượng (Protego)",
  "Talent_Core_ProtegoAM_desc": "Đỡ đòn thành công bằng Bùa Khiên Che Chắn (Protego) sẽ nạp đầy thanh năng lượng Phép Thuật Cổ Xưa.",
  "Talent_Core_ProtegoAM_requirements": "Không có yêu cầu tiên quyết",
  "Talent_Core_ProtegoBlast": "Thông Thạo Bùa Khiên Che Chắn (Protego)",
  "Talent_Core_ProtegoBlast_desc": "Cú đỡ đòn \"Bùa Khiên Che Chắn (Protego)\" hoàn hảo sẽ giải phóng một vụ nổ hủy diệt, phá tan khiên của kẻ địch.",
  "Talent_Core_ProtegoBlast_requirements": "Điều kiện mở khóa tài năng: Đạt cấp độ tối thiểu 30.",
  "Talent_Core_ProtegoReflect": "Chuyên Sâu Bùa Khiên Che Chắn (Protego)",
  "Talent_Core_ProtegoReflect_desc": "Chặn bùa chú bằng cú đỡ \"Bùa Khiên Che Chắn (Protego)\" hoàn hảo sẽ dội ngược hai quả cầu ma thuật về phía kẻ địch.",
  "Talent_Core_ProtegoReflect_requirements": "Không có yêu cầu tiên quyết",
  "Talent_Core_RevelioUpgrade": "Thông Thạo Bùa Hiện Hình (Revelio)",
  "Talent_Core_RevelioUpgrade_desc": "Mở rộng phạm vi tác dụng của Bùa Hiện Hình (Revelio).",
  "Talent_Core_RevelioUpgrade_requirements": "Không có yêu cầu tiên quyết",
  "Talent_Core_StupefyAOE": "Chuyên Sâu Bùa Choáng Váng (Stupefy)",
  "Talent_Core_StupefyAOE_desc": "Bùa Choáng Váng (Stupefy) sẽ gây sát thương trực tiếp khi đánh trúng mục tiêu.",
  "Talent_Core_StupefyAOE_Requirements": "Không có yêu cầu tiên quyết",
  "Talent_Core_StupefyStun": "Thông Thạo Bùa Choáng Váng (Stupefy)",
  "Talent_Core_StupefyStun_desc": "Kéo dài thời gian choáng váng của kẻ địch bị Bùa Choáng Váng (Stupefy) đánh trúng.",
  "Talent_Core_StupefyStun_Requirements": "Không có yêu cầu tiên quyết",
  "Talent_Curse_AvadaKedavra": "Thông Thạo Lời Nguyền Chết Chóc (Avada Kedavra)",
  "Talent_Curse_AvadaKedavra_desc": "Dùng Lời Nguyền Chết Chóc (Avada Kedavra) tiêu diệt một kẻ địch sẽ đồng thời đoạt mạng tất cả kẻ địch đang bị dính lời nguyền.",
  "Talent_Curse_AvadaKedavra_Requirements": "Điều kiện mở khóa tài năng: Học cách sử dụng Lời Nguyền Chết Chóc (Avada Kedavra).",
  "Talent_Curse_Crucio": "Thông Thạo Lời Nguyền Tra Tấn (Crucio)",
  "Talent_Curse_Crucio_desc": "Tấn công kẻ địch đang quằn quại dưới tác dụng của \"Lời Nguyền Tra Tấn (Crucio)\" sẽ phóng ra một luồng ma thuật nguyền rủa kẻ địch xung quanh.",
  "Talent_Curse_Crucio_Requirements": "Điều kiện mở khóa tài năng: Học cách sử dụng Lời Nguyền Tra Tấn (Crucio).",
  "Talent_Curse_CurseStupefy": "Lời Nguyền Choáng Váng",
  "Talent_Curse_CurseStupefy_desc": "Bùa Choáng Váng (Stupefy) sẽ giáng lên kẻ địch hiệu ứng tương đương một lời nguyền. Kẻ địch bị nguyền rủa sẽ chịu thêm sát thương.",
  "Talent_Curse_CurseStupefy_Requirements": "Không có yêu cầu tiên quyết",
  "Talent_Curse_Imperio": "Thông Thạo Lời Nguyền Độc Đoán (Imperio)",
  "Talent_Curse_Imperio_desc": "Nếu một kẻ địch bị kiểm soát bởi Lời Nguyền Độc Đoán (Imperio) của bạn, kẻ đó sẽ ếm lời nguyền lên các mục tiêu khác sau mỗi đòn tấn công.",
  "Talent_Curse_Imperio_Requirements": "Điều kiện mở khóa tài năng: Học cách sử dụng Lời Nguyền Độc Đoán (Imperio).",
  "Talent_Sanc_AMPotion": "Hiệu Năng Thuốc Tập Trung",
  "Talent_Sanc_AMPotion_desc": "Trong thời gian tác dụng, thi triển bất kỳ bùa chú nào từ bộ bùa chú sẽ kéo dài thời gian hiệu lực của Thuốc Tập Trung.",
  "Talent_Sanc_AMPotion_Requirements": "Điều kiện mở khóa tài năng: Có thể sử dụng Thuốc Tập Trung.",
  "Talent_Sanc_AutoDamagePotion": "Hiệu Năng Thuốc Sấm Sét Thunderbrew",
  "Talent_Sanc_AutoDamagePotion_desc": "Tăng đáng kể tầm tác dụng và lượng sát thương của độc dược.",
  "Talent_Sanc_AutoDamagePotion_Requirements": "Điều kiện mở khóa tài năng: Có thể sử dụng Thuốc Sấm Sét Thunderbrew.",
  "Talent_Sanc_EdurusPotion": "Hiệu Năng Thuốc Cường Hóa Edurus",
  "Talent_Sanc_EdurusPotion_desc": "Thuốc Cường Hóa Edurus sẽ đưa bạn vào trạng thái bất khả xâm phạm và phản ngược các vật thể phóng tới về phía kẻ tấn công.",
  "Talent_Sanc_EdurusPotion_Requirements": "Điều kiện mở khóa tài năng: Có thể sử dụng Thuốc Cường Hóa Edurus.",
  "Talent_Sanc_InvisibilityPotion": "Hiệu Năng Thuốc Tàng Hình",
  "Talent_Sanc_InvisibilityPotion_desc": "Kéo dài thời gian hiệu lực của Thuốc Tàng Hình.",
  "Talent_Sanc_InvisibilityPotion_Requirements": "Điều kiện mở khóa tài năng: Có thể sử dụng Thuốc Tàng Hình.",
  "Talent_Sanc_MaximaPotion": "Hiệu Năng Thuốc Tối Đại Maxima",
  "Talent_Sanc_MaximaPotion_desc": "Sau khi uống Thuốc Tối Đại Maxima, các đòn tấn công sẽ gây thêm sát thương và có thể phá vỡ khiên chắn của kẻ địch.",
  "Talent_Sanc_MaximaPotion_Requirements": "Điều kiện mở khóa tài năng: Có thể sử dụng Thuốc Tối Đại Maxima.",
  "Talent_Spell_Accio": "Thông Thạo \"Bùa Triệu Tập (Accio)\"",
  "Talent_Spell_Accio_desc": "\"Bùa Triệu Tập (Accio)\" sẽ đồng thời kéo cả những kẻ địch xung quanh mục tiêu lại gần.",
  "Talent_Spell_Accio_Requirements": "Điều kiện mở khóa tài năng: Học cách sử dụng \"Bùa Triệu Tập (Accio)\".",
  "Talent_Spell_Arresto": "Lời Nguyền Chậm Trễ",
  "Talent_Spell_Arresto_desc": "Bùa Hãm Đà (Arresto Momentum) sẽ giáng lên kẻ địch hiệu ứng tương đương một lời nguyền. Kẻ địch bị nguyền rủa sẽ chịu thêm sát thương.",
  "Talent_Spell_Arresto_Requirements": "Điều kiện mở khóa tài năng: Học cách sử dụng Bùa Hãm Đà (Arresto Momentum).",
  "Talent_Spell_Bombarda": "Thông Thạo \"Bùa Nổ Công Phá (Bombarda)\"",
  "Talent_Spell_Bombarda_desc": "\"Bùa Nổ Công Phá (Bombarda)\" sẽ tạo ra một vụ nổ có phạm vi ảnh hưởng cực kỳ rộng lớn.",
  "Talent_Spell_Bombarda_Requirements": "Điều kiện mở khóa tài năng: Học cách sử dụng \"Bùa Nổ Công Phá (Bombarda)\".",
  "Talent_Spell_Confringo": "Thông Thạo \"Bùa Nổ Súng (Confringo)\"",
  "Talent_Spell_Confringo_desc": "Sau khi đánh trúng đích, \"Bùa Nổ Súng (Confringo)\" sẽ bắn ra những mũi tên lửa tự tìm mục tiêu kẻ địch.",
  "Talent_Spell_Confringo_Requirements": "Điều kiện mở khóa tài năng: Học cách sử dụng \"Bùa Nổ Súng (Confringo)\".",
  "Talent_Spell_Depulso": "Thông Thạo \"Bùa Đẩy Lùi (Depulso)\"",
  "Talent_Spell_Depulso_desc": "Khi thi triển \"Bùa Đẩy Lùi (Depulso)\", một làn sóng xung kích bổ sung sẽ phóng ra xung quanh bạn.",
  "Talent_Spell_Depulso_Requirements": "Điều kiện mở khóa tài năng: Học cách sử dụng \"Bùa Đẩy Lùi (Depulso)\".",
  "Talent_Spell_Descendo": "Thông Thạo \"Bùa Đập Xuống (Descendo)\"",
  "Talent_Spell_Descendo_desc": "\"Bùa Đập Xuống (Descendo)\" sẽ tạo ra một làn sóng xung kích gây sát thương xung quanh mục tiêu của bạn.",
  "Talent_Spell_Descendo_Requirements": "Điều kiện mở khóa tài năng: Học cách sử dụng \"Bùa Đập Xuống (Descendo)\".",
  "Talent_Spell_Diffindo": "Thông Thạo \"Bùa Cắt Sâu (Diffindo)\""
}

if __name__ == '__main__':
    print(f"Loaded {len(translations_400_500)} keys.")
