"""Translate the remaining Ares and related character lines."""
from pathlib import Path
import sys

ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(ROOT / "tools"))
from hades2_sjson_helper import apply_translation_to_sjson  # noqa: E402

TR = ROOT / "translations/0100A00019DE0000_Hades2/Game/Text/en/_LootData_Ares.en.sjson"
translations = {
    "Ares_0055": "Tin ngươi đánh bại Titan Thời Gian đêm qua truyền đến tai chúng ta, ai nấy đều khâm phục. Nhưng ta cứ tự hỏi trước khi chết, lão có phải chịu nỗi đau tột cùng không. Có lẽ cuối cùng cũng có cách khiến lão nản chí.",
    "Ares_0056": "Khi các bậc cha ông đánh bại Titan Chronos lần đầu, ta còn chưa ra đời... đêm qua ta cũng không tận mắt thấy lão bị ngươi khuất phục. Nhưng trí tưởng tượng của ta đủ phong phú để hình dung.",
    "Ares_0136": "Tối nay ta cứ nghĩ sẽ gặp ngươi ở đó. Titan Chronos còn choáng váng sau thất bại gần đây, quân của lão trên mặt đất hẳn cũng dao động và dễ bị tấn công hơn.",
    "Ares_0053": "Người nhà của ta, đẩy lùi Cha của Muôn Loài Quái Vật là thành tựu phi thường. Nhưng chiến tranh chưa thắng! Nghĩa là những chiến công còn vang dội hơn đang chờ ta, có lẽ xen cả vài thất bại chẳng vẻ vang gì.",
    "Ares_0054": "Typhon đúng là quái vật khổng lồ... chậm chạp, to lớn, ngoan cố bò lên đỉnh cao nhất, lòng đầy báo thù và cuồng nộ...! Xét vài khía cạnh, ta cũng ngưỡng mộ hắn. Nhưng mừng là ngươi đã dập tắt hy vọng của hắn.",
    "Ares_0044": "Ta thích những cuộc chiến có lúc lên lúc xuống... khi giành được thế thượng phong thật khó, nhưng để mất lại quá dễ! Giờ lợi thế thuộc về ngươi, người nhà của ta. Giữ lấy đi.",
    "Ares_0171": "Trong chiến tranh, kẻ chiến thắng là người mạnh nhất hoặc tàn nhẫn nhất. Ta cũng có chút ảnh hưởng, và {#Emph}giờ sẽ ban chính sức mạnh ấy cho ngươi.",
    "Ares_0051": "Typhon khổng lồ còn nguy hiểm hơn ta tưởng, người nhà của ta! Ta từng ghen tị khi nghe các bậc trưởng bối kể chuyện họ đẩy lùi Cha của Muôn Loài Quái Vật... giờ tất cả chúng ta được tận mắt chứng kiến cơn cuồng nộ của hắn!",
    "Ares_0052": "Ta chẳng thể gọi trận chiến gần đây với Typhon là chiến thắng, nhưng cuối cùng chúng ta cũng đẩy lùi được hắn sau khi ngươi buộc phải rút lui. Vậy mà giờ hắn lại chậm rãi leo lên...",
    "Ares_0189": "Cha của Muôn Loài Quái Vật bị tiêu diệt! Nghe tin ta còn chẳng tin nổi, nhưng phụ vương và mẫu hậu yêu quý đều khẳng định đó là thật. Có vẻ ngươi sở hữu sức mạnh {#Emph}đáng sợ hơn nhiều{#Prev}, {#Emph}thậm chí còn hơn{#Prev} cả kẻ địch đã bị đánh bại.",
    "Ares_0188": "Người nhà của ta, tiếc rằng lúc ngươi ở đây ta không thể đến chào hỏi. Việc xử lý những kẻ xâm nhập cấp bách hơn. Mong rằng sau này chúng ta vẫn còn dịp gặp lại.",
    "Ares_0138": "Đã lâu ta không chứng kiến chuyện diễn ra dưới lòng đất; chỉ nhận Ân Huệ thì chẳng nhìn thấy được bao nhiêu. Có những nơi tối tăm ngươi tàn phá mà ta gần như chẳng thấy gì.",
    "Ares_0194": "Bao giờ cha ngươi mới mở lại lối đi qua cổng Âm phủ? Có lẽ vương quốc của ông ấy chưa sẵn sàng đón quá nhiều cư dân mới cùng lúc. Thôi vậy, chuyện gì rồi cũng đến lúc.",
    "Ares_0143": "Đau đớn và cái chết chứa đựng biết bao điều bí ẩn, người nhà của ta. Mỗi Satyr, mỗi Harpy ngươi hạ gục đều để lại bài học. Ngươi học hỏi thật say mê; mong rằng chúng ta còn tiếp tục nghiên cứu thật lâu.",
    "Ares_0073": "Đêm nay bầu không khí ngập tràn nỗi kinh hoàng. Cứ như nữ thần Nyx chạm vào trái tim những kẻ chống lại chúng ta, khiến chúng càng cuồng chiến. Trận này sẽ khó khăn đây!",
    "Ares_0074": "Người nhà của ta, ngươi có cảm nhận nỗi sợ lơ lửng trong không khí đêm nay không? Ta nghĩ là có; có khi chính ngươi gây ra nó... một nữ thần không chỉ cai quản Âm phủ mà còn cả ác mộng.",
    "Ares_0071": "Tối nay không khí có gì đó khác lạ... ngươi cũng cảm nhận được chứ? Một khả năng cổ xưa vĩ đại đang trỗi dậy. Hãy dùng sức mạnh áp đảo để biến nó thành hiện thực.",
    "Ares_0072": "Ta thừa nhận ngay cả thần linh cũng có thể chịu tác động của những thế lực ngoài tầm hiểu biết hay kiểm soát. Ta đang cảm thấy chúng... khiến cuộc chiến lớn này thêm dữ dội, thôi thúc chúng ta hành động.",
    "Ares_0187": "Thế lực nào đã đưa ngươi đi xa đến mức này chỉ trong chớp mắt? Có lẽ dưới Âm phủ còn những vị thần mà ngay cả chúng ta cũng không thể phát hiện, những liên minh ta chưa cần biết đến.",
    "Ares_0035": "Chuôi Kiếm ngươi mang từng thuộc về một chiến binh đổ rất nhiều máu kẻ khác trước khi chính mình gục ngã. Hình dáng vốn bình thường, nhưng đã trải qua vô số trận chiến khiến ta thấy gắn bó; có lẽ ngươi cũng vậy.",
    "Ares_0177": "Đến giờ, Chuôi Kiếm ta tặng đã chứng kiến ngươi đổ biết bao máu kẻ địch. Chủ nhân cũ hẳn sẽ hài lòng! Ít nhất {#Emph}ta {#Prev}thì chắc chắn rồi, vừa được góp sức {#Emph}vừa {#Prev}được chứng kiến.",
    "Ares_0178": "Ta cảm nhận được ngươi đang giữ một cổ vật của chính Vận Mệnh Diệt Vong! Ta từng gặp ngài Moros nhiều lần; lĩnh vực của ta thường cần đến ngài ấy. Chắc đây là quãng thời gian thú vị với ngài ấy!",
    "Ares_0032": "Ta vừa trở về sau chuyến công cán; công việc của ta chẳng bao giờ hết. Thật mừng khi thấy mọi chuyện ở đây được lo liệu chu đáo, nhiều mặt còn tốt hơn lúc ta rời đi. Công lớn thuộc về ngươi, phải không?",
    "Ares_0061": "Phải thú nhận ban đầu ta không muốn can dự. Chiến tranh phải diễn ra trọn vẹn; ta thường khởi đầu mọi chuyện rồi đứng ngoài quan sát công tâm. Nhưng cuộc chiến này lại thành ngoại lệ.",
    "Ares_0034": "Chiến tranh phức tạp biết bao. Ta có thể khơi mào, nhưng chẳng mấy chốc nó tự phát triển theo ý mình; cũng giống nuôi nấng một đứa trẻ! Đứa trẻ chúng ta đang đối phó giờ hơi ngỗ nghịch rồi.",
    "Ares_0062": "Đây chẳng phải lần đầu gia đình ta vướng vào chiến tranh. Nhưng trước nay chưa lần nào cuốn nhiều người trong nhà vào đến vậy! Nghĩ đến giờ ta vẫn hơi xúc động...",
    "Ares_0046": "Ta biết những vũ khí ngươi đang dùng; chính Nyx rạng ngời đã kể cho ta nghe! Ta khao khát tri thức ấy không nguôi, cũng như Vũ Khí Màn Đêm chẳng thể yên khi vương quốc của ngươi còn lâm nguy.",
    "Ares_0179": "Với tính cách của Hephaestus, anh ấy có thể gọi tên từng vũ khí bóng tối của ngươi! Còn ta nhận ra công dụng và hình dáng của chúng, và muốn thấy chúng gây ra mức hủy diệt nào.",
    "Ares_0180": "Đúng là vũ khí tinh xảo! Chùy Sư Tử Đá có lịch sử đẫm máu lẫy lừng, rồi ngươi sẽ viết tiếp huyền thoại ấy. Ta không biết nó cũng là một dạng của Vũ Khí Màn Đêm...",
    "Ares_0181": "Hoa văn trên vũ khí của ngươi gợi ta nhớ đến nữ thần Nyx. Ta biết bà giám sát việc rèn Vũ Khí Màn Đêm, nhưng chẳng phải chính bà cũng từng sử dụng chúng sao...?",
    "Ares_0182": "Ta nhận ra lưỡi hái chạm trổ tinh xảo kia; lẽ ra nó phải nằm trong tay chính Thần Chết! Nhưng ngươi cầm cũng gần như vậy. Nghĩ mà xem, ngay cả Thanatos cũng bị Titan bắt đi mà chẳng hay biết.",
    "Ares_0186": "{#Emph}Ồ{#Prev}, thành phố Ephyra nồng nặc mùi chết chóc! Ta gần như ngửi thấy từ đây. Giờ chỉ còn khốn khổ và tuyệt vọng; tất cả có lẽ đều chẳng thể cứu vãn.",
    "Ares_0047": "Gần đây bổn phận buộc ta phải đi xa; từ ngọn núi biệt lập này ta chỉ làm được chừng ấy. Nhưng giờ ở nhà có quá nhiều chuyện cần lo!",
    "Ares_0176": "Dạo gần đây ngày càng có nhiều cuộc chiến dữ dội diễn ra trên biển, người nhà của ta. Xét một khía cạnh, ngươi đang dẫn đầu sự đổi thay trong nghệ thuật chiến tranh!",
    "Ares_0063": "Dù là con trai đầu lòng của Đức Vua và Nữ hoàng, ta chẳng có thêm chút quyền lực nào. Ai cũng góp ý, nhưng lời ai được nghe theo thì ai mà biết? Chiến tranh luôn nhắc ta rằng ngoại giao rất quan trọng.",
    "Ares_0058": "Đến giờ ngươi đã hạ ít nhất một nghìn Satyr trong chiến dịch; một mình tiêu diệt cả đội quân! Mà đó chỉ là {#Emph}một phần nhỏ{#Prev} trong toàn bộ cảnh hủy diệt ngươi gây ra!",
    "Ares_0070": "Chúng ta cãi nhau xem ngươi chọn ban phước cho ai trước ư? Một màn phô trương vừa phá hoại vừa vô nghĩa! Chúng ta gây chiến với nhau để giải quyết bất đồng. Gần như thành truyền thống rồi!",
    "Ares_0190": "Sau chiến tranh, cảm xúc lẫn lộn là chuyện thường tình! Chúng ta không được giải quyết khốn cảnh bằng bạo lực... dù theo ta biết, phía trước vẫn còn bạo lực.",
    "Ares_0195": "Khó có cuộc chiến nào sau này sánh được với cuộc chiến vừa qua; một phần vì các vị thần chúng ta ở ngay tâm điểm. Nhưng ta tin rồi sẽ có cuộc khác vượt qua nó. Thế nào cũng có.",
    "Ares_0191": "Chúng ta sẽ tiếp tục giao chiến với Titan Chronos ở những {#Emph}thời điểm {#Prev}khác nhau sao? Hay nói đúng hơn là trong hoàn cảnh khác... nếu trước đó ngươi thất bại. Một trận chiến không hồi kết... {#Emph}ôi{#Prev}, người nhà của ta.",
    "Ares_0192": "Ngươi nghĩ chúng ta phải đối phó bao nhiêu kẻ giả mạo Chronos? Rồi ta sẽ tiêu diệt từng tên một. Nhưng chẳng trận chiến nào giống trận nào!",
    "Ares_0193": "Ta nghe nói ngươi vẫn có thể đối đầu Cha của Muôn Loài Quái Vật ở đây! Vậy linh hồn cuồng nộ của hắn vẫn tồn tại trong góc tối nào đó của thời gian. Giá mà ta được tận mắt nhìn thấy!",
    "Ares_0196": "Vậy là cuối cùng cũng tìm thấy Tam Nữ Thần Số Mệnh? Họ định tạm dừng những trò thao túng xưa nay sao? Ta chưa tin hẳn, nhưng... chiến tranh sẽ phấn khích biết bao nếu kẻ thắng không được định sẵn.",
    "Ares_0077": "{#Emph}A! {#Prev}Có vẻ thông điệp đã được chuyển đi hoàn toàn bí mật! Chúng ta nên đề phòng như thế thường xuyên hơn, dù có lẽ sẽ khiến ngươi khó lập kế hoạch.",
    "Ares_0078": "Ngươi không cần ngạc nhiên khi thấy ta ở đây. Gia đình ta thường chọn cách trực diện hơn, nhưng ta cũng chẳng ngại lẩn vào bóng tối; thật ra ta khá thích thế.",
    "Ares_0174": "Trong chiến tranh, phải chuẩn bị cho {#Emph}mọi {#Prev}tình huống. Lẽ ra một người nhà khác có thể ban Ân Huệ cho ngươi, nhưng ta đã nhanh chóng quyết định thay họ.",
    "Ares_0175": "Ân Huệ của chúng ta khó mà cưỡng lại, phải không? Dù chưa biết mình sẽ nhận được gì, hay của vị thần nào, ngươi vẫn sẵn lòng trả phí cho người lái đò.",
    "Ares_0075": "Người lái đò sông giờ không còn đưa linh hồn xuống Âm phủ, nhưng lại rất có ích cho chiến cuộc. Anh ấy dùng mái chèo thành thạo lắm!",
    "Ares_0076": "Có những lần ta tự trả phí cho người lái đò, vì một lượt ta đưa xuống Âm phủ quá nhiều linh hồn! Đúng là thời hoàng kim.",
    "Ares_0172": "Đường tiếp tế mà bị gián đoạn quá lâu thì chiến tranh không thể kéo dài; vì vậy ta luôn biết ơn người lái đò của ngươi. Không có anh ấy, ta đã chẳng đến được đây.",
    "Ares_0173": "Vàng là kim loại thú vị, phải không? Phàm nhân từng đánh nhau, giết chóc chỉ vì nó. Trong vương quốc của cha ngươi, chỉ đá quý hiếm nhất mới hấp dẫn họ hơn!",
    "Ares_0083": "Người nhà của ta, ngươi hiểu chuyện này có nghĩa gì rồi chứ? Ta tin chẳng cần nói thành lời.",
    "Ares_0084": "Đôi khi người ta gây chiến cay đắng chỉ vì chuyện nhỏ hơn thế; thật ra chẳng vì điều gì đáng kể.",
    "Ares_0085": "Có lẽ đây chỉ là hiểu lầm, dù ta thường mặc định rằng đối phương có ác ý.",
    "Ares_0086": "Những người nhà khác đôi lúc cũng gạt ta sang bên, và ngươi thấy {#Emph}họ {#Prev}nhận được gì rồi đấy.",
    "Ares_0087": "Nếu ngươi thật sự muốn giao chiến với ta, ta sẵn lòng chiều ý.",
    "Ares_0088": "Ta thật lòng thông cảm, người nhà của ta; ngươi chẳng còn cách nào khác ngoài chọn phe rồi chịu kết quả.",
    "Ares_0089": "Nếu nói ta chẳng vui chút nào khi phải làm điều này thì là nói dối, người nhà của ta.",
    "Ares_0090": "Ta không trách quyết định của ngươi; trái lại còn rất biết ơn, vì nhờ thế ta mới làm được {#Emph}chuyện này.",
    "Ares_0091": "Anh trai yêu quý của ta từng được chọn thay ta rồi, và khi ấy ta cũng chẳng vui vẻ gì.",
    "Ares_0092": "Nếu ở vị trí ngươi, có lẽ ta cũng chọn như vậy, nhưng ta vẫn tự ái đấy.",
    "Ares_0093": "Chọn đứng về phía Aphrodite là khôn ngoan, dù giờ ngươi đã biến {#Emph}ta thành kẻ thù.",
    "Ares_0094": "Có lẽ là một lựa chọn đầy tính toán. Nhưng nó sẽ kéo theo hậu quả đẫm máu.",
    "Ares_0099": "Màn trình diễn tuyệt vời, xứng với dòng dõi chúng ta! Ngươi sẽ được thưởng vì tất cả những điều đó.",
    "Ares_0100": "Đôi khi ta muốn giúp bên thua cuộc, để gieo cho họ chút hy vọng hão huyền.",
    "Ares_0101": "Ngươi nghĩ lũ địch ngu ngốc kia tưởng chúng đã tóm được ngươi sao?",
    "Ares_0102": "Thỉnh thoảng tỏ vẻ thù địch chính là cách chúng ta khẳng định bản thân, người nhà của ta.",
    "Ares_0103": "Biết bao trận chiến đang chờ, đôi lúc ta thật chẳng thể kiềm lòng...",
    "Ares_0104": "{#Emph}A{#Prev}, tuyệt vời lắm, dù có lẽ màn hay nhất đêm nay vẫn còn ở phía trước.",
    "Ares_0105": "Ngươi đã thỏa mãn cơn khát báo thù của ta, hay ít nhất là cơn khát máu. Tạm thời thôi.",
    "Ares_0106": "Ta cảm nhận rằng chẳng ai sống sót sau trận đó ngoài ngươi. Kết cục thật mỹ mãn.",
    "Ares_0107": "Phần thưởng dành cho người chiến thắng. Còn ta được chứng kiến một màn trình diễn ngoạn mục.",
    "Ares_0108": "Đôi khi công việc buộc ta phải chống lại người nhà. Ngươi hiểu mà, phải không?",
    "Ares_0109": "Đó chỉ là một cuộc giao tranh nhỏ nhặt, vậy mà vẫn khiến ta vô cùng thích thú.",
    "Ares_0110": "Kẻ địch tưởng chúng có cơ hội thắng; sự lạc quan ấy khiến ta thích thú vô cùng.",
    "MelinoeField_2962": "Thưa ngài Ares, ta biết các chiến binh phàm nhân thường dâng lễ vật cho ngài trước trận chiến sinh tử. Ta cũng xin được bày tỏ lòng kính trọng. Không khoan nhượng với kẻ địch!",
    "Ares_0036": "Ta không thể nhận vinh dự mà chẳng đáp lễ, nhất là từ người hiểu rõ việc ta làm. Một vũ khí sống như ngươi xứng đáng nhận {#Emph}món này.",
    "MelinoeField_2964": "Ta không thể quyết định mình còn phải tham gia bao nhiêu trận chiến; nhưng biết ngài sẽ ủng hộ khiến ta vững lòng hơn nhiều. Mong chúng ta sớm hoàn thành mọi mục tiêu, thưa ngài.",
    "Ares_0037": "Mật hoa thường được giữ lại đến khi chiến thắng. Nhưng theo nhiều cách, ta thấy chúng ta đã thắng rồi! Ít nhất là ta. Ta sẽ tìm lúc thích hợp để thưởng thức món này.",
    "MelinoeField_2965": "Chiến tranh nào rồi cũng kết thúc, nhưng chúng ta mãi là gia đình, phải không thưa ngài? Món quà nhỏ này nhắc rằng giữa chúng ta còn nhiều điều gắn kết hơn niềm vui chiến đấu.",
    "Ares_0038": "Ngươi đã tặng ta những món quà quý hơn cả Mật hoa tuyệt hảo này, dù ta vẫn rất trân trọng nó. Nhưng cảnh tàn sát ngươi gây ra đến nay... thật chưa ai sánh bằng.",
    "MelinoeField_3378": "Có lúc niềm phấn khích trong chiến trận gần như nuốt chửng ta; trước đây ta từng cố kìm nén cảm giác ấy. Giờ ta hiểu nó dẫn đến chiến thắng... và cả {#Emph}ngài{#Prev}, thưa ngài.",
    "Ares_0140": "Ta từng nghĩ chẳng ai trong nhà có chung mối bận tâm với mình. Thật mừng vì ta đã lầm. Bất cứ khi nào ngươi muốn gieo cái chết, hãy biết rằng ta sẽ có mặt.",
    "MelinoeField_3669": "Trước khi gặp ngài, ta chẳng biết phải mong đợi điều gì, ngài Ares... nhưng ta nhận ra ngài thẳng thắn hơn nhiều người. Cảm ơn ngài lúc nào cũng nói rõ với ta.",
    "Ares_0141": "Ta phải thừa nhận rằng tính cách của mình khiến ít người dâng lễ vật. Nhiều kẻ quá {#Emph}dễ dàng {#Prev}bối rối trước sự thật và đủ loại cảm xúc; còn ngươi thì không, người nhà của ta.",
    "MelinoeField_3670": "Thưa ngài Ares, khi phàm nhân ở hai phe đối địch đều cầu xin ngài ban chiến thắng, ngài chọn giúp ai? Mong món quà này không khiến ngài khó xử.",
    "Ares_0142": "Ta nhận quà đến một mức nào đó thôi. Phàm nhân nghĩ có thể khiến ta ưu ái họ, nhưng chính ý chí chiến đấu mới quyết định họ chết nhanh đến đâu. Ta trân trọng việc ngươi để tâm đến những điều nhỏ nhặt này!",
    "MelinoeField_3671": "Xin nâng chén mừng mọi chiến thắng đã qua và sắp tới, ngài Ares! Nhưng Ambrosia này không chỉ dành cho điều đó... ta biết ngài cũng học hỏi từ những thất bại và mất mát đau đớn. Ta thấy mình và ngài giống nhau nhất ở điểm này.",
    "Ares_0144": "Ta cũng có cảm giác ấy, người nhà sinh ra từ địa ngục. Gia đình ta thường chỉ chăm chăm vào chiến thắng, chẳng dám nhìn thẳng vào thất bại, nơi có thể tìm thấy hiểu biết sâu sắc hơn. Ở điểm này và nhiều điều khác, ngươi thật khác biệt.",
    "MelinoeField_2963": "Ta xin nhận món quà này, thưa ngài.",
    "Ares_0111": "Tất cả sẽ phải chịu khổ!",
    "Ares_0112": "Hãy để {#Emph}chiến tranh bùng nổ!",
    "Ares_0113": "Bạo lực và hủy diệt!",
    "Ares_0204": "Hãy cùng đổ {#Emph}máu!",
    "Ares_0205": "Thật {#Emph}đồi bại làm sao!",
    "Ares_0206": "Ngươi chẳng có chút {#Emph}phép tắc nào sao?",
    "Ares_0207": "Có giỏi thì cứ {#Emph}chế giễu ta!",
    "ErisField_0477": "Đó có phải {#Emph}Ares không?!",
    "ErisField_0478": "{#Emph}Ares{#Prev}, đúng là {#Emph}anh sao?!",
    "Chronos_1269": "Tên thần chiến tranh tàn bạo...",
    "Chronos_1270": "Ta sẽ cho Ares biết chiến tranh thực sự là thế nào...",
    "Zagreus_0368": "Ares, là {#Emph}em đây!",
    "Zagreus_0369": "{#Emph}Thôi nào{#Prev}, Ares...!",
    "Ares_0096": "Ngươi hoặc theo phe ta, hoặc chống lại ta, người nhà của ta; không có chuyện đứng giữa.",
    "Ares_0097": "Chắc ngươi nghĩ cuộc chiến nhỏ này sẽ diễn ra theo {#Emph}ý ngươi{#Prev}.",
    "Ares_0098": "Ta vốn chẳng biết khoan dung; ta nói vậy đủ rõ chưa?",
    "Ares_0126": "Chắc chắn rồi.", "Ares_0127": "Dĩ nhiên.", "Ares_0128": "Được thôi.", "Ares_0129": "Theo ý ngươi.", "Ares_0130": "Như ngươi mong muốn.", "Ares_0131": "Phải.", "Ares_0132": "Xong rồi.", "Ares_0133": "Thế này à?",
    "Ares_0120": "Ta chào ngươi.", "Ares_0121": "{#Emph}À{#Prev}, phải rồi.", "Ares_0122": "Cuối cùng.", "Ares_0123": "Ngươi đây rồi.", "Ares_0124": "Ngươi vẫn khỏe chứ?", "Ares_0125": "Xin gửi lời thăm hỏi.",
}

source = TR.read_text(encoding="utf-8-sig")
mapped = {key: {"DisplayName": value} for key, value in translations.items()}
TR.write_text(apply_translation_to_sjson(source, mapped), encoding="utf-8")
sys.stdout.reconfigure(encoding="utf-8")
print(f"Đã bổ sung {len(translations)} câu còn lại của Ares.")
