"""Translate an initial context-reviewed batch of Hera dialogue."""
from pathlib import Path
import sys

ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(ROOT / "tools"))
from hades2_sjson_helper import apply_translation_to_sjson  # noqa: E402

SRC = ROOT / "working/0100A00019DE0000_Hades2/raw_text/en"
TR = ROOT / "translations/0100A00019DE0000_Hades2/Game/Text/en"

translations = {
    "MelinoeField_1749": "Huy hiệu Nữ hoàng...",
    "Melinoe_1472": "Là bà ấy.",
    "Melinoe_1473": "Nữ hoàng Hera...",
    "MelinoeField_3123": "Nữ hoàng Hera...!",
    "Melinoe_0170": "Gia đình ta đã đoàn kết vì mục tiêu chung... {#Emph}Nhân danh Hades! Olympus, con xin nhận thông điệp này!{#Prev}",
    "Hera_0004": "Ân huệ dành cho {#Emph}cháu{#Prev}, lời nguyền giáng lên kẻ thù, cháu yêu quý.",
    "Hera_0015": "Thật lạ khi cuộc xung đột xé rời gia đình lại khiến chúng ta gần gũi hơn, {#Emph}nhỉ?",
    "Hera_0009": "Chronos là lão già khờ, thời của hắn đã qua từ lâu.",
    "Hera_0005": "Hẳn có Ân huệ nào của ta hợp với cháu chứ?",
    "Hera_0006": "Đừng tỏ ra yếu đuối, cũng đừng nương tay, cô gái.",
    "Hera_0007": "Nhìn nhà ta xem, cô gái! Gia đình rối ren thật, vậy mà vẫn cùng nhau xoay xở được đấy.",
    "Hera_0008": "Hera sẽ chống lưng cho cháu, cô gái; chẳng bao lâu nữa, kẻ thù sẽ ước gì mình chưa từng được sinh ra.",
    "Hera_0010": "Bà cô của cháu trở lại rồi, cháu yêu quý. Đêm nay ta hãy vui một phen nào.",
    "Hera_0011": "Cùng nhau tiêu diệt kẻ thù đúng là cách giúp gia đình thêm gắn bó, {#Emph}nhỉ?",
    "Hera_0012": "Lại bất ngờ gặp cháu ở đúng nơi ta đoán trước rồi.",
    "Hera_0013": "Nào, cháu gái, để ta ngắm cháu một chút xem có thể giúp được gì.",
    "Hera_0014": "Có lẽ gia đình ta đáng phải chịu cảnh này, nhưng dù vậy, chúng ta vẫn sẽ chống trả.",
    "Hera_0016": "Thì ra chỉ cần một mối đe dọa sống còn là gia đình này cuối cùng cũng chịu đoàn kết!",
    "Hera_0017": "Ngẩng cao đầu lên, cháu gái! Mọi chuyện có khi còn tệ hơn bây giờ nhiều.",
    "Hera_0018": "Các Số Mệnh có thể nguyền rủa gia đình ta, nhưng chúng ta biết cách chiến đấu.",
    "Hera_0019": "Kẻ thù nhiều đến nỗi ta nguyền rủa không xuể! Nhưng ta {#Emph}có thể {#Prev}ban phúc cho {#Emph}cháu.",
    "Hera_0020": "Muốn nắm chút quyền năng sinh tử không? Cả cái chết nữa, ta cũng lo được.",
    "Hera_0021": "Ta phải thú nhận là mình bắt đầu thích những chuyến đi chơi cùng cháu rồi đấy.",
    "Hera_0022": "Lớn lên dưới Âm phủ mà cháu còn đoan trang, thanh nhã hơn cả đám trên này.",
    "Hera_0023": "Dạo này hình như cháu gần như là người duy nhất ta có thể tin cậy, cô gái à.",
    "Hera_0024": "Giờ ta đang không vui, vậy nên chọn nhanh rồi đi đi.",
    "Hera_0025": "Cháu yêu à, truyền thống nhỏ này đã thành điều ta mong đợi mỗi lần gặp nhau.",
    "Hera_0026": "Các Số Mệnh chẳng ban cho ta cô con gái nào, nhưng ít ra họ đã đưa cháu đến bên ta.",
    "Hera_0027": "Đời người thỉnh thoảng vẫn có những quãng thời gian khốn khổ, nhờ vậy lúc vui mới càng đáng quý.",
    "Hera_0028": "Người Olympus chúng ta thù dai lắm đấy, cháu gái.",
    "Hera_0029": "Ước gì vài người ta quen cũng có được dù chỉ một phần quyết tâm như cháu.",
    "Hera_0030": "Số phận của chúng ta là phải gánh nhiều hơn phần mình đáng phải gánh, cháu gái à.",
    "Hera_0031": "Cháu chẳng biết đã bao lâu rồi ta chưa tin cậy ai trong dòng dõi của mình đâu.",
    "Hera_0032": "Kẻ thù đã khinh miệt gia đình ta; chúng ta sẽ khiến hắn hối hận vì ngày hắn sinh ra, phải không?",
    "Hera_0033": "Ta có thừa quyền năng, nên vui lòng chia cho cháu một ít lúc này.",
    "Hera_0034": "Cháu có phong thái hoàng gia hơn ta tưởng đấy...",
    "Hera_0183": "Đêm nay không thuận lợi sao...? Vết thương rồi sẽ lành, cháu yêu. Còn lòng tự trọng của cháu thì ta không dám chắc đâu.",
    "Hera_0053": "Nào, cùng thoát khỏi cảnh bế tắc này nhé, cô gái. Đây là thứ tốt nhất ta có lúc này. Nhớ tận dụng cho tốt đấy.",
    "Hera_0113": "Ta cần nhắc lại rằng ta chẳng ưa những kẻ quay lưng với mình sao?",
    "Hera_0114": "Thật {#Emph}đáng thất vọng{#Prev}, nhưng cũng chẳng lạ! Đến lượt ta rồi.",
    "Hera_0115": "Ngươi nghĩ ta là ai? Tưởng ta sẽ nằm im chịu trận sao?",
    "Hera_0116": "Có lẽ cháu đúng là người Olympus, dám hỗn xược với ta như thế kia mà.",
    "Hera_0117": "Cẩn thận chọc giận ta đấy, cháu yêu. Ta có trí nhớ {#Emph}tuyệt vời{#Prev} lắm.",
    "Hera_0170": "Trước mặt ta thì liệu mà giữ ý. {#Emph}Đây! {#Prev}Để ta nhắc cho nhớ.",
    "Hera_0171": "Trong lòng ta coi trọng ý kiến bất đồng, còn ngoài mặt thì... {#Emph}không.",
    "Hera_0172": "Phải giữ phép tắc; chúng ta không thể dung thứ sự chống đối trắng trợn như vậy.",
    "Hera_0173": "Nếu cháu nhất quyết chống lại ta, ta sẽ khiến {#Emph}cháu{#Prev} phải hối hận.",
    "Hera_0118": "Các nữ thần chúng ta lẽ ra phải đoàn kết hơn {#Emph}thế này.",
    "Hera_0119": "Chồng ta vốn quen muốn gì được nấy; cháu không cần chiều theo ông ấy đâu.",
    "Hera_0120": "Thằng con da ngăm này hấp dẫn cháu hơn ta sao? {#Emph}Ha ha ha!",
    "Hera_0254": "Lần tới nếu vợ chồng ta bất đồng đôi chút, hãy {#Emph}đứng về phía ta nhé.",
    "Hera_0255": "Chắc thằng con hiếu chiến của ta gây ra chuyện này, vậy mà cháu lại chọn {#Emph}nó sao?",
    "Hera_0256": "Em gái ta có thể không còn trẻ, nhưng bù lại rất sáng suốt, đúng không?",
    "Hera_0125": "Tha thứ quý như thuốc chữa lành; phải dùng thật dè sẻn.",
    "Hera_0126": "Được rồi! Vậy thôi. Kiểu cãi vã này chẳng xứng để hai ta bận tâm.",
    "Hera_0127": "Cháu muốn thử sức ta thì ta cũng sẽ thử sức cháu, cháu yêu. Nhớ lấy điều đó.",
    "Hera_0128": "{#Emph}Đủ {#Prev}rồi! Đây là Ân huệ đáng lẽ cháu đã nhận được {#Emph}mà không cần{#Prev} đánh nhau!",
    "Hera_0129": "Trò vật lộn của cháu chỉ mua vui cho ta được một lúc thôi. Biến đi, cô gái.",
    "Hera_0130": "Nhìn hai ta xem, cãi nhau chẳng khác gì vợ chồng già! Hay là bỏ qua chuyện này nhé?",
    "Hera_0174": "Coi như cháu vừa bị khiển trách nhé. Lần này cháu thoát nhẹ đấy.",
    "Hera_0175": "Chà, ta đã có đủ kẻ thù rồi, {#Emph}chẳng cần{#Prev} thêm nữa đâu.",
    "Hera_0176": "Chúng ta là hoàng tộc, cháu yêu. Phải cư xử cho ra dáng quý tộc chứ, đúng không?",
    "Hera_0177": "{#Emph}Chậc! {#Prev}Ta nên xây dựng liên minh vững mạnh, đâu phải chĩa móng vuốt vào nhau.",
    "Hera_0257": "Sao chúng ta lại đánh nhau chứ? Cháu đúng là {#Emph}người nhà ta{#Prev} nên mới chọc ta giận đến vậy.",
    "Hera_0258": "Chà! Đâu thể cứ dồn nén {#Emph}mọi{#Prev} cơn giận mãi; nhưng cũng phải biết để dành một ít.",
    "Melinoe_0506": "Nữ hoàng Hera, giữa bao việc cần lo, Người lại chọn giúp con. Con vô cùng vinh dự và sẽ tìm cách đáp lại tấm lòng của Người.",
    "Melinoe_0507": "Nữ hoàng Olympus vĩ đại! Con vô cùng cảm kích khi được Người ưu ái, và sẽ làm hết sức để không phụ lòng Người!",
    "Hera_0070": "Cháu chưa thành hôn mà đã khen ta vậy sao? Ta phải nói là cháu đầy bất ngờ đấy, cháu yêu. Hoặc chỉ là chẳng biết gì. Có khi cả hai!",
    "MelinoeField_0644": "Người không cần phải làm vậy đâu, thưa Bệ hạ.",
    "Hera_0131": "Ta thích một cuộc chia tay ầm ĩ!",
    "Hera_0132": "Hãy chứng kiến cơn thịnh nộ của Nữ hoàng!",
    "Hera_0133": "Chúng sẽ ước gì mình chưa từng được sinh ra!",
    "Hera_0262": "Trỗi dậy và hầu hạ chủ nhân của các ngươi!",
    "Hera_0263": "Hỡi người chết, hãy tái sinh!",
    "Hera_0264": "Gia đình ta ngày càng đông!",
    "Hera_0259": "Cháu định trêu chọc {#Emph}ta, cô gái?",
    "Hera_0260": "Xem ra quanh ta cũng có người thông minh đấy!",
    "Hera_0261": "Chà, ta chẳng thấy lý do gì để {#Emph}từ chối!",
    "Heracles_0541": "Nữ hoàng...?",
    "Heracles_0542": "Nữ hoàng Hera...!",
    "Heracles_0543": "Mẹ kế...!",
    "Chronos_1255": "Cái gọi là {#Emph}Nữ hoàng đó á?!",
    "Chronos_1256": "Người vợ yêu dấu của con trai ta sao?",
    "Zagreus_0354": "Vừa rồi là {#Emph}Nữ hoàng sao?",
    "Zagreus_0355": "Nữ hoàng Hera...?",
    "Hera_0121": "Cháu có thể là công chúa, nhưng nhớ cho kỹ: {#Emph}ta{#Prev} mới là Nữ hoàng.",
    "Hera_0122": "Ở vị trí của ta, e rằng phải nghiêm khắc đôi chút.",
    "Hera_0123": "Thần Olympus nổi tiếng nóng giận; chúng ta phải thế thôi.",
    "Hera_0124": "Ta cũng chẳng vui gì đâu, cô gái. Cùng lắm là vui được chút xíu.",
    "Hera_0152": "Tuyệt vời.",
    "Hera_0153": "Được lắm.",
    "Hera_0154": "Vậy đi.",
    "Hera_0155": "Được chấp thuận.",
    "Hera_0156": "Hoàn hảo!",
    "Hera_0157": "{#Emph}À{#Prev}, phải rồi.",
    "Hera_0158": "Vậy thì, đây.",
    "Hera_0159": "Nếu cháu muốn.",
    "Hera_0146": "Ta đây.",
    "Hera_0147": "Hãy nhìn Nữ hoàng của các ngươi đây.",
    "Hera_0148": "Chào buổi tối, cháu yêu.",
    "Hera_0149": "Thật bất ngờ dễ chịu!",
    "Hera_0150": "Ồ, xin chào.",
    "Hera_0151": "Chào cháu, cháu yêu!",
    "Hera_0097": "{#Emph}Ái chà! {#Prev}Nhìn kìa, cháu yêu! Chồng yêu dấu của ta đến rồi. Đức {#Emph}Vua các vị thần Olympus{#Prev}, người sẽ cứu chúng ta khỏi mớ hỗn độn này. Thế nào rồi, con trai Chronos, có tin gì không?",
    "Zeus_0154": "Em yêu nói đúng đấy, hôn nhân quả thực có lúc chẳng khác gì công việc! Ngày đầu thì dễ dàng biết bao, nhưng trách nhiệm của chúng ta ngày một lớn, phải không?",
    "Hera_0103": "Ta lo cho thế hệ trẻ. Sinh ra chỉ thừa hưởng thói xấu của chúng ta mà chẳng có chút ưu điểm nào thì làm được gì? Cứ nhìn Apollo đáng mến ở đây... thằng bé y hệt cha nó.",
    "Apollo_0094": "Mẹ kế à, chẳng phải vị thần nào trong bọn con cũng mong được như chồng mẹ sao? Con rất vui vì mẹ khen! Cô em họ xinh đẹp của con hẳn cũng thừa hưởng những nét hay nhất của cha cô ấy!",
    "Hera_0107": "Cũng như cha cháu từng trông coi toàn bộ người chết, chúng ta phải chịu trách nhiệm với phần còn lại của thế giới! Thời buổi đã tối tăm, nhưng... ta có thể {#Emph}khôi phục. {#Prev}May mà có em gái Demeter của ta...",
    "Demeter_0102": "Thời khắc hồi phục rồi sẽ đến như mùa xuân vậy. Nhưng giờ ta đang trải qua mùa đông dài chưa thấy điểm cuối. Thưa Nữ hoàng, đừng bận tâm điều gì khác.",
    "Hera_0109": "Sâu thẳm bên trong, ngay cả Titan lẫn thần linh cũng mong manh như ai. Tất cả đều bị chi phối bởi một thứ vô cùng nhạy cảm, có thể khơi dậy cảm xúc hoặc đẩy ta vào tuyệt vọng; Aphrodite thân mến hiểu rõ điều đó.",
    "Aphrodite_0143": "Nào, thưa Nữ hoàng! Trái tim là thứ mạnh nhất, bền bỉ hơn vẻ ngoài! Chúng ta đã chịu bao phen trên ngọn núi này mà vẫn trụ được, còn chịu được nhiều hơn nữa. Nhất là khi mọi trái tim {#Emph}cùng {#Prev}đập chung nhịp!",
    "Hera_0111": "Ta biết khi cả lối sống đang bị đe dọa thì chẳng thể giữ phép tắc mãi! Nhưng con trai yêu quý Hephaestus của ta đâu cần phải {#Emph}thô lỗ{#Prev} trong mọi dịp như thế chứ?",
    "Hephaestus_0122": "Mẹ có bao giờ dạy con phép tắc đâu. May mà không cần mẹ hay cha làm gương, con vẫn học được đôi điều! Cứ {#Emph}chờ xem{#Prev}. Cả con nữa, phù thủy!",
    "Zeus_0098": "{#Emph}Ha ha ha! {#Prev}Nào, Hera yêu quý, em cứ trêu ta như thế, nhưng người không quen với lối hài hước khô khan, sắc sảo của em có thể hiểu lầm đấy! Thấy chưa, Melinoë? Tiếng cười là sợi dây gắn kết hôn nhân bền chặt!",
    "Hera_0099": "Gia đình ta đoàn kết chẳng phải chuyện dễ dàng. Tất cả phải cùng vun đắp để những mối dây gắn bó không sờn đứt, như đã từng xảy ra với Chronos. Đức lang quân của ta hiểu điều này hơn ai hết, đúng không Zeus?",
    "Hera_0101": "Tiếc là cháu chưa từng biết cha mình... nhưng ít ra giờ cháu đã gặp người em trai tốt bụng Poseidon của ông ấy! Cứ tưởng tượng một người như ông ta, nhưng bớt nụ cười ngốc nghếch, bớt lời lẽ khiếm nhã, tóc đẹp hơn và vóc dáng cũng bảnh bao hơn.",
    "Poseidon_0268": "{#Emph}Ái chà, ha ha ha! {#Prev}Thấy gia đình chúng ta gắn bó thế nào chưa, cháu gái?! Dù trải qua thảm họa nào, Nữ hoàng vẫn có thể pha trò, lại còn nhằm vào ta nữa. Nhưng {#Emph}dù sao đi nữa!",
    "Hera_0105": "Các nữ thần chúng ta đôi khi quá kiêu hãnh để cầu cứu! Ta thì chẳng đời nào hạ mình như thế. Cần gì phải cầu xin, khi cô em gái cứng đầu Hestia của ta kiểu gì cũng nhảy vào giúp? Ngay lúc này đây, {#Emph}khi ta đang nói!",
    "Hestia_0148": "Thứ lỗi nhé, nhưng Nữ hoàng chẳng biết điều gì {#Emph}tốt{#Prev} cho mình đâu! Đôi khi, những người không thể mở miệng nhờ giúp đỡ lại là người cần {#Emph}nhất! {#Prev}Nào, chi bằng làm {#Emph}gương{#Prev} cho thành viên mới vừa gia nhập gia đình một cách đường đột này đi?",
    "Hera_0242": "Ít ra giờ Ares đã trở về, ta càng {#Emph}dễ{#Prev} để mắt {#Emph}đến nó{#Prev}. Nào, con trai, chỉnh tề lại chút đi, cho cháu gái ta thấy nào.",
    "Ares_0157": "Thần xin làm theo ý Nữ hoàng. Thần rất vinh dự khi Người tìm đến, và tin rằng gia đình ta sẽ biết ơn Người — hiện thân cho toàn bộ cơn thịnh nộ của chúng ta.",
    "Hera_0081": "Cuối cùng cũng được gặp cháu, cháu yêu quý! Chán mặt đất rồi, phải không? {#Emph}Hừm{#Prev}, ta đã hứa với gia đình rằng khi cháu chứng tỏ được quyết tâm, ta sẽ bảo bọc cháu. Ta {#Emph}luôn{#Prev} giữ lời.",
    "Hera_0080_B": "Cuối cùng cũng được gặp cháu, cháu yêu quý! Chào mừng đến với mặt đất của chúng ta, dù nơi này chẳng còn như xưa. Ta đã hứa với gia đình rằng khi cháu chứng tỏ quyết tâm, ta sẽ bảo bọc cháu... và ta {#Emph}luôn{#Prev} giữ lời.",
    "Hera_0035": "{#Emph}Ôi{#Prev}, cha đáng thương của cháu. Hẳn cháu từng là báu vật trong mắt ông ấy, vậy mà lại bị cướp khỏi vòng tay ông... Ông ấy hẳn sẽ tự hào lắm. À mà, có lẽ không hẳn là {#Emph}tự hào{#Prev}; nghĩ lại thì ông ấy chẳng mấy khi thể hiện điều đó. Ít ra thì {#Emph}ta{#Prev} tự hào về cháu!",
    "Hera_0084": "Đây đâu phải lần đầu ta phải can thiệp vì {#Emph}nhánh gia đình cháu{#Prev}. Ta đã giữ vững lập trường! Hai bên không thể cứ xen vào chuyện của nhau mãi. Nhưng cháu đã đến bảo vệ chúng ta, vậy lần này ta sẽ phá lệ...",
    "Hera_0290": "Cháu đã thấy chúng ta đâu phải lúc nào cũng thuận hòa. Nhưng sống với đám này đủ lâu rồi cháu cũng sẽ thành người nhà thôi. Nhẫn nhịn cũng phải luyện tập! Dù sao, phần lớn thời gian chúng ta vẫn thương nhau...",
    "Hera_0036": "Ân huệ ta và người nhà ban xuống cũng giống như con cái vậy... Cháu đâu phải lúc nào cũng nhận được thứ mình muốn, nhưng nếu khéo xoay xở thì vẫn dùng được!",
    "Hera_0043": "Ta luôn muốn có một cô con gái. Ai ngờ lại sinh ra Ares. Hephaestus. {#Emph}Eo ôi! {#Prev}Hai cô con gái Athena và Artemis của Zeus thì tránh xa ta, còn Aphrodite ấy à, nàng muốn làm gì thì làm. Gia đình gì kỳ cục thế này.",
    "Hera_0046": "Gia đình đông vui của chúng ta giờ chắc chỉ bằng một phần nhỏ nếu không nhờ những cuộc phiêu lưu tình ái của chồng ta! Đổi lại, ta có biết bao đứa trẻ đáng yêu trong đời.",
    "Hera_0274": "Cháu có từng nghĩ đến chuyện sinh con chưa, cháu yêu? Sau {#Emph}chuyện này{#Prev}, có lẽ cháu sẽ phải nghĩ lại. Nhưng chẳng mấy chốc chúng ta cần một thế hệ mới! Tốt nhất là phải có dòng dõi tốt.",
    "Hera_0275": "Cháu nên tìm một người bạn đời biết khen mình cho tử tế, cô gái à! Đức lang quân của ta thỉnh thoảng gọi ta là {#Emph}Hera Mắt Bò{#Prev}! Ông ấy bảo mắt ta to đẹp như một con {#Emph}bò{#Prev}; lãng mạn ghê chưa!",
    "Hera_0038": "Titan Chronos không phải cha ta. Nhưng {#Emph}cha cháu{#Prev} là con của hắn, cũng như chồng ta và Poseidon. Vậy là cả nhà ta bị cuốn vào chuyện gia đình này rồi!",
    "Hera_0039": "Ước gì ta có thể tự tay bắn thêm một mũi tên vào giữa hai mắt Chronos, nhưng tiếc là cháu ở gần hắn hơn còn ta thì mắc kẹt ở đây. Giết hắn giúp ta nhé?",
    "Hera_0057": "Có một điều ta học được, cháu yêu: {#Emph}mãi mãi {#Prev}là quãng thời gian rất dài. Dường như chẳng điều gì còn {#Emph}thật sự {#Prev}bền vững mãi nữa. Có lẽ vì thế mà chúng ta mới lâm vào tình cảnh này.",
    "Hera_0065": "Ta có nghĩa vụ với cha cháu ở đây. Mỗi người phàm qua đời lại làm dân số Âm phủ tăng lên mà! Ta đã cố góp sức để hạn chế dòng người ấy. Cháu có biết người phàm sinh con vất vả đến mức nào không?",
    "Hera_0165": "Nếu cháu từng thắc mắc đám {#Emph}khốn khổ {#Prev}trong Âm phủ từ đâu ra, thì có những người phàm cho rằng bảo vệ {#Emph}chúng{#Prev} là trách nhiệm của {#Emph}chúng ta! {#Prev}Cháu tin nổi không?",
    "Hera_0092": "Ta chẳng trách họ, nhưng {#Emph}một số {#Prev}người phàm đã hoài nghi cách chúng ta cai quản. Họ bày ra cái gọi là {#Emph}vận may... {#Prev}những vận hội tự nhiên từ trên trời rơi xuống! Toàn chuyện {#Emph}ngẫu nhiên vô nghĩa{#Prev}, chẳng liên quan gì đến thần linh hay Tam Nữ Thần Số Mệnh.",
    "Hera_0241": "Chà, người phàm hẳn xem chúng ta là một đám suốt ngày cãi vã, dù chẳng ai dám nói ra. Ta phải tìm cách giữ thể diện mới được. Để ta nhờ Demeter ban thêm những mùa màng sung túc vậy.",
    "Hera_0037": "Nhớ lấy, cô gái, thế giới này vốn thuộc về chúng ta. Chính các Số Mệnh đã định như thế! Vậy mà giờ Chronos muốn lật đổ ngai vàng của chúng ta sao? Hắn đã có cơ hội trị vì rồi. Chẳng thể quay lại như trước đâu.",
    "Hera_0044": "Chuyện Chronos này... có lẽ thật khó chấp nhận khi một bậc cha mẹ lại oán ghét chính con mình. Nhưng nghe ta nói này, cô gái: đôi lúc ta {#Emph}gần như{#Prev} đồng cảm với hắn.",
    "Hera_0045": "Cháu yêu, có lẽ nghe ta nói thì lạ lắm, nhưng từ nữ thần này sang nữ thần khác: đừng vội kết hôn! Dù ý tưởng ấy có vẻ tuyệt vời đến đâu. Cứ nhìn gương ta mà xem; ta còn là chính nữ thần hôn nhân chết tiệt đây!",
    "Hera_0047": "Ta nghe nói cháu đã gặp Heracles vĩ đại! Gã to con, đầu óc đơn giản ấy à? Cháu không được giúp hắn làm việc, nghe chưa? Hắn đang trải qua cái mà người Olympus chúng ta gọi là {#Emph}hành trình khám phá bản thân.",
    "Hera_0072": "{#Emph}Ôi! {#Prev}Cháu tả tơi quá, thứ lỗi vì ta nói thẳng nhé, cô gái! Cháu gần chết thế này thì ta giúp sao nổi! Ít nhất là chẳng giúp được bao nhiêu.",
    "Hera_0073": "Sinh lực của cháu đâu mất hết rồi? Quý giá biết bao! Vậy mà cháu làm đổ máu khắp nơi, còn {#Emph}gan{#Prev} vác bộ dạng này đến gặp ta.",
    "Hera_0182": "Dù đã luyện tập nhiều đến đâu, rõ ràng vẫn {#Emph}chưa đủ{#Prev}, nếu cháu {#Emph}đã{#Prev} bị {#Emph}đánh tơi tả{#Prev} trước cả khi ta kịp bảo vệ cháu!",
    "Hera_0093": "Đêm nào cũng mở ra một khởi đầu mới, phải không cháu yêu? Và chính vào đêm {#Emph}này{#Prev}, {#Emph}ta{#Prev} sẽ đồng hành cùng cháu từ đầu... cho đến tận phút cuối.",
    "Hera_0094": "Âm phủ của cháu đã thất thủ từ lâu, nhưng Olympus của chúng ta vẫn đứng vững. Cháu đến đây là đúng, vì ngay lúc này cháu có thể tạo nên khác biệt {#Emph}thật sự{#Prev}. Và chẳng mấy chốc {#Emph}ta{#Prev} cũng sẽ ra tay!",
    "Hera_0181": "Chỉ cần một chiến binh tài ba đánh vào sườn quân địch đang sơ hở là {#Emph}đúng{#Prev} thứ chúng ta cần để đẩy lùi chúng. Tối nay xem ra {#Emph}cháu{#Prev} đảm nhận được việc này!",
    "Hera_0095": "Ta và chồng đã tranh luận {#Emph}sôi nổi{#Prev} về cách giúp cháu bảo đảm chiến thắng cho chúng ta. Ông ấy quá kiêu hãnh để tìm cháu trên đỉnh núi, còn ta thì sẵn lòng chào đón cháu, vậy nên... đi thôi!",
    "Hera_0180": "Cháu mới bắt đầu hành trình xuống Âm phủ, nhưng ta sẽ đồng hành ngay từ những bước đầu tiên. Ta thích thế hơn tất cả nghĩa vụ khác cộng lại, nói cháu nghe đấy!",
    "Hera_0292": "{#Emph}À{#Prev}, ngoan lắm, cuối cùng cháu cũng chú ý đến Âm phủ rồi! Những gì xảy ra ở đây khiến chúng ta mất mặt quá. Ít ra ta cũng phải tự dọn dẹp chứ.",
    "Hera_0079": "{#Emph}Ái chà! {#Prev}Cháu {#Emph}lại{#Prev} đây rồi, cháu yêu! Tiếc là toàn gặp nhau trong tình cảnh thế này. Nhưng gia đình nào chẳng lúc thăng lúc trầm, phải không? Để ta giúp cháu giúp cả nhà.",
    "Hera_0078": "Nói thật nhé, cô gái, ta không biết cháu có đủ sức ngăn Titan không. Nhưng giờ chúng ta còn lựa chọn nào khác? Ta sẽ tạm tin cháu một lần.",
    "Hera_0066": "Ta luôn biết Chronos sẽ trở lại. Zeus cứ bảo ta lo hão! Dù sao chúng ta đã chôn lão già khốn ấy sâu dưới Vực Tartarus rồi. Nhưng hắn là Titan bất tử. Có vẻ {#Emph}Thời Gian{#Prev} đã tuột khỏi tay chúng ta...",
    "Hera_0168": "Là Typhon chết tiệt, cô gái! Quái vật khủng khiếp nhất cháu có thể tưởng tượng. Chronos đánh thức hắn khỏi giấc ngủ chết chóc rồi sai hắn đến tấn công {#Emph}chúng ta! {#Prev}Bất tử thì đã sao, chúng ta vẫn có thể gặp tai họa...",
    "Hera_0230": "Đêm qua lão Typhon bị ngã một cú, nhưng Hermes báo hắn đã bắt đầu cựa quậy. Rõ ràng mục tiêu của hắn là đỉnh núi chúng ta... giá mà hắn dễ ngăn chặn như dễ đoán.",
    "Hera_0231": "Cháu thật sự đã trừ khử Typhon {#Emph}chết tiệt{#Prev} ấy. Chúng ta chưa từng đối mặt với mối đe dọa nào khủng khiếp đến thế, mà {#Emph}chỉ{#Prev} có thể cầm chân hắn! Giờ chúng ta chiếm thế thượng phong nhờ {#Emph}cháu{#Prev}, cháu yêu.",
    "Hera_0291": "Cháu có sức mạnh phi thường, cháu yêu... bất kể đã làm gì với Typhon, hãy giữ kín bí mật ấy. Cứ để chúng ta cất giữ giúp! Kho báu của ta chưa {#Emph}từng{#Prev} bị đột nhập. Cứ suy nghĩ đi nhé.",
    "Hera_0041": "Chồng ta tuy có nhiều thói xấu nhưng vẫn là đối thủ đáng gờm. Nếu không thì cháu nghĩ vì sao chúng ta trị vì suốt bao kỷ nguyên? Zeus hẳn có kẻ thù, nhưng chẳng mấy ai đủ gan hoặc dại dột để công khai điều đó.",
    "Hera_0042": "Ta và Zeus đã bên nhau lâu lắm rồi. Đúng là một đôi vợ chồng già! Vậy mà người ta cứ nói những điều tồi tệ về chúng ta. Ta cố bỏ ngoài tai! Chẳng cặp đôi nào hoàn hảo, nhất là cặp đã bên nhau lâu như chúng ta.",
    "Hera_0050": "Ta cũng biết đôi chút về thuật phù thủy, cô gái. Đó là nghệ thuật kín đáo, và sức mạnh nằm chính ở đó. Người ta dễ phủ nhận, cho là trùng hợp. Nhưng quyền năng thật sự chẳng cần phô trương.",
    "Hera_0052": "Trên mặt đất có nhiều nguyên liệu phép thuật mạnh mẽ, nếu biết tìm ở đâu! Trong mắt người thường chúng chỉ là rễ cây với hoa lá, nhưng vào tay cháu, nhất là trong Vạc Thần, chúng sẽ giúp cháu thi triển phép thuật chưa từng có.",
    "Hera_0162": "Có thể chúng ta không thích chuyện ấy, nhưng bị xem thường mãi cũng có cái lợi, phải không cô gái? Cứ để họ nghĩ sao thì nghĩ; Ân huệ của ta đâu chỉ dành cho các cặp sắp cưới.",
    "Hera_0067": "Chào mừng cháu đến với mặt đất của chúng ta, cháu yêu! Lần đầu đến đây à? Rộng lớn lắm! Đủ kiểu khí hậu, văn hóa người phàm và bao điều khác. Đừng để ấn tượng ban đầu làm cháu mất niềm tin; nơi này không phải lúc nào cũng thảm họa đâu!",
    "Hera_0068": "Người phàm than phiền rằng thần linh bỏ mặc thành Ephyra, vậy mà giờ chúng ta đến đây rồi! Đúng là lũ vô ơn. Dạo này chẳng có mấy đám cưới, cũng ít tang lễ... dù chết chóc, tàn phá thì nhiều!",
    "Hera_0083": "Người ta bảo cháu không thể lên mặt đất! Rằng lời nguyền Âm phủ đang kìm chân cháu... Ta chẳng tin lời đồn ấy chút nào, và quả nhiên ta đã đúng. Có lẽ họ chỉ sợ tiềm năng của cháu thôi.",
    "Hera_0164": "Gần đây Olympus rung chuyển khiến chúng ta lo lắng. Ý ta là rung chuyển {#Emph}thật sự{#Prev}! Ngay cả Poseidon cũng bất ngờ vì động đất. Chronos định làm cả ngọn núi đổ sụp sao?",
    "Hera_0074": "{#Emph}Eo ôi{#Prev}, trong màn sương mù kia ta đã khó tiếp cận cháu rồi, giờ cháu còn ở xa hơn nữa. Đây là rìa ngoài cõi của cha cháu sao? Đường này... đâu phải lối thường dẫn xuống Âm phủ...",
    "Hera_0090": "Cháu đã thấy Cánh Đồng Than Khóc dưới Âm phủ rồi, phải không? Khá nhiều cư dân ở đó là nạn nhân của những cuộc hôn nhân đổ vỡ... thường là do chính họ. Ta ban phúc cho mọi đôi uyên ương có thể, nhưng cũng chỉ làm được đến thế.",
    "Hera_0085": "Aphrodite hớn hở kể rằng {#Emph}cháu{#Prev} và vài người bạn đã trở nên thân thiết. Nếu rồi chuyện tiến xa hơn và cháu muốn gắn bó nghiêm túc, ta sẽ {#Emph}vô cùng{#Prev} vui lòng giúp cháu thành đôi!",
    "Hera_0249": "Một cô gái xinh đẹp như cháu hẳn có khối người theo đuổi! Nếu tránh được thì đừng vội kết hôn nhé. Người phàm thường tự trói mình vào hôn nhân cả đời, mà có khi còn chẳng giữ nổi lời thề. Còn {#Emph}đời{#Prev} họ thì ngắn ngủi lắm!",
    "Hera_0062": "Apollo Vàng đã đề nghị giúp cháu rồi sao? Lúc nào nó cũng sốt sắng làm vừa lòng người khác. Ta thấy nó cứ chăm chăm quan tâm thật phiền... nhưng chắc cháu kiên nhẫn hơn ta.",
    "Hera_0137": "{#Emph}Chậc{#Prev}, ít ra Hephaestus cũng {#Emph}cố gắng{#Prev} giúp ích! Thứ lỗi cho cậu con trai được nuông chiều của ta nhé, cô gái. Nó thích gõ búa suốt ngày trong lò rèn hơn là giao du cho phải phép.",
    "Hera_0064": "Ta mừng vì cháu và Hestia hòa thuận, cháu yêu. Tính khí của bà ấy với ta chẳng mấy hợp nhau, nhưng ta kính trọng trí tuệ và cả khả năng thiêu rụi mọi thứ nếu cần.",
    "Hera_0271": "Hầu hết chúng ta đều thích bạo lực đôi chút, cô gái, nhưng con trai ta, Ares, lại đẩy chuyện đó đến mức {#Emph}khá{#Prev} quá trớn. Có lúc nó hữu dụng, nhưng đừng để nó quá khích.",
    "Hera_0089": "Chẳng lạ khi Hiện Thân Xung Đột lại xuất hiện, đúng như thói quen của ả. Eris từng trêu đùa chúng ta ra trò! Hẳn ả nghĩ chúng ta ngu ngốc, dễ bắt nạt. Cháu sẽ dạy cho ả một bài chứ?",
    "Hera_0163": "Chronos rồi đến Prometheus, cả hai lại quay về ám chúng ta chỉ vì trước kia ta đã không trừ khử chúng khi còn cơ hội. Không biết tiếp theo là ai? Các phù thủy phải tìm cách tiêu diệt bọn bất tử mới được.",
    "Hera_0273": "Đức lang quân của ta và Prometheus chẳng mấy hòa thuận. Titan ấy cũng nói rõ hắn nghĩ gì về các thần, cả nam lẫn nữ. Vậy mà giờ chúng ta lại dung túng cho hắn dọn đống hỗn độn do chính hắn góp phần gây ra sao? Thật nực cười...",
    "Hera_0091": "Các Số Mệnh biến mất rồi sao? Hermes nói vậy à? Nếu đúng thì thật không may. Nhưng nếu Chronos quyết báo thù, hắn nhắm vào {#Emph}họ{#Prev} chứ không chỉ {#Emph}chúng ta.",
    "Hera_0238": "Ta phải tin là Chronos {#Emph}thật sự không{#Prev} nhớ mình đã để Tam Nữ Thần Số Mệnh ở đâu sao? Chính những {#Emph}người dệt nên số phận{#Prev} lại bị bỏ quên như mấy món {#Emph}đồ lặt vặt! {#Prev}Có khi họ còn {#Emph}mừng{#Prev} vì thoát khỏi tất cả chúng ta.",
    "Hera_0289": "Ta chẳng hiểu {#Emph}sao{#Prev} cháu cứ đi đường này, trong khi {#Emph}Âm phủ của cháu{#Prev} mới cần giúp hơn. Ngọn núi vẫn {#Emph}ổn! {#Prev}Ít ra là gần ổn, trừ đám tàn quân Titan vẫn quấy rầy chúng ta...",
    "Hera_0040": "Ta và hai em gái Demeter, Hestia có cha là Titan tên Hyperion. Ít nhất thì cũng {#Emph}đúng danh nghĩa{#Prev} là cha. Giờ chẳng ai còn nhắc đến {#Emph}ông ấy{#Prev} nữa! Dù sao, chúng ta lẽ ra phải xử Chronos từ lâu rồi.",
    "Hera_0076": "Chúng ta nhận được tin cháu đã xuống đến tầng sâu nhất! Ta cứ tưởng cháu thắng rồi... nhưng có vẻ chưa. Dù sao cũng là tiến triển tốt! Cứ tiếp tục nhé.",
    "Hera_0077": "Cháu đã đến gần đỉnh núi của chúng ta hơn bao giờ hết! Ta cứ hy vọng cuối cùng cũng được gặp cháu, nhưng... giờ cả hai ta đều có việc cấp bách hơn phải lo.",
    "Hera_0096": "Đêm nay có điều gì đó rất kỳ lạ; mà theo kinh nghiệm của ta, điềm báo như thế {#Emph}không bao giờ{#Prev} nên xem nhẹ. Có lẽ những thế lực kỳ lạ kia chỉ do cháu niệm chú thôi! Cẩn thận đấy, cô gái.",
    "Hera_0278": "Đêm nay khiến ta bất an; nhiều kẻ thù của chúng ta đang ngày càng táo tợn. Người phàm sợ hãi khi tính mạng bị đe dọa, nhưng cảm giác này không thể chỉ là {#Emph}thế được!",
    "Hera_0279": "Cảm giác đáng sợ trong không khí... vậy là do cháu gây ra {#Emph}thật{#Prev} sao, cô gái? Ta chẳng hiểu chọc giận kẻ thù thì giúp ích {#Emph}gì{#Prev} cho chúng ta. Đi giải quyết chúng ngay đi!",
    "Hera_0082": "Đêm trước, khi có cơ hội, cháu đã đứng về phía người nhà ta và từ chối Ân huệ ta hào phóng ban đầu. Chuyện cãi vã nhỏ ấy qua rồi, nhưng ta {#Emph}không{#Prev} chấp nhận bị coi thường như thế. Ta nói rõ rồi chứ?",
    "Hera_0055": "Dạo này nhiệm vụ của cháu thế nào, cháu yêu? Mong là khá hơn tình hình trên này. À, chúng ta vẫn ổn, chỉ là bị vây hãm nên phải sống chen chúc hơn ta muốn. Chẳng có lấy một phút yên thân!",
    "Hera_0056": "Nghe ta này, cháu yêu: đừng nghe theo trái tim. Ta biết khó lắm, vì cái thứ chết tiệt ấy thường gào lên rất lớn. Nhưng nghe theo nó thì thường sẽ dẫn cháu thẳng đến sai lầm.",
    "Hera_0054": "Tâm trạng ta lại u ám rồi, cháu yêu, nhưng có lẽ nhờ vậy ta hào phóng hơn. Đây, Ân huệ tốt nhất của ta! Cứ đi mà kết đôi cho thiên hạ nhé.",
    "Hera_0049": "Xem ra Phù thủy Ngã ba Địa Giới đã nuôi dạy cháu tốt! Đám trẻ ở đây chẳng có cá tính, phép tắc thì {#Emph}chẳng ra sao{#Prev}. Cứ như thế hệ {#Emph}ta{#Prev} đã làm gương tệ lắm vậy!",
    "Hera_0048": "Cháu biết Heracles là con trai Zeus chứ. {#Emph}Vinh quang thay Hera! {#Prev}Ta nên thấy vinh dự mới phải. Hắn chỉ là thêm một cái miệng phải nuôi, mà lại ăn khỏe nữa. Nhưng ta sẽ khiến hắn bận rộn. Chúng ta cần mọi sự giúp đỡ có thể.",
    "Hera_0246": "Nếu Heracles không đáp ứng kỳ vọng, cháu sẽ nói chúng ta biết chứ? Nói riêng nhé, khi mọi chuyện yên ổn, có lẽ chúng ta sẽ mời hắn ở lại lâu dài. Hắn lao động đủ rồi, mà chúng ta cũng cần thêm cơ bắp.",
    "Hera_0075": "Cháu đã đối đầu Polyphemus rồi à? Đó chính là kiểu {#Emph}tay sai{#Prev} Chronos dùng. Đồ ngốc rỗng tuếch! Nhưng phải công nhận là khỏe. Ta e chẳng thể lẻn qua {#Emph}hắn{#Prev} đâu. Chúng ta thử rồi...",
    "Hera_0059": "{#Emph}À! {#Prev}Ta thấy đức lang quân đáng kính đã gặp cháu trước rồi. Phòng khi ông ấy không làm tia lửa bắn ra {#Emph}đúng{#Prev} như cháu mong đợi, ta cũng có thứ dành riêng cho cháu.",
    "Hera_0060": "Lại là Đức Zeus đến gặp cháu trước sao? {#Emph}Hừm. {#Prev}Con trai cao quý của Chronos đúng là nhanh như chớp! Đôi khi cháu chẳng tưởng tượng nổi ông ấy chạy khỏi {#Emph}ta{#Prev} nhanh đến mức nào đâu.",
    "Hera_0061": "Biết Poseidon khỏe mạnh đã ghé thăm cháu trước, ta hẳn đã đến sớm hơn. Biển cả chẳng đáng tin, còn mối gắn bó của ta thì mãi mãi. Ít ra là theo nghĩa bóng!",
    "Hera_0135": "Mối thù lạnh lẽo... ta cảm nhận được từ xa. Có lẽ em gái Demeter của ta mất mát nhiều hơn bất cứ ai trên ngọn núi này. Kẻ thù sẽ phải hối hận vì đã đối đầu với em ấy.",
    "Hera_0063": "Nữ thần tình yêu lúc nào cũng đi trước ta một bước. Cháu nghĩ có bao nhiêu người phàm sẽ tìm ta để ban phúc cho lời thề hôn nhân, nếu Aphrodite chưa dùng {#Emph}mị lực{#Prev} với họ? Xem ra sức mạnh của chúng ta bổ trợ cho nhau.",
    "Hera_0287": "Con trai ít nói Hephaestus nghĩ ta đôi khi {#Emph}quá cay nghiệt. {#Prev}Có lẽ nó nói đúng! Cháu tưởng mẹ ta yêu thương {#Emph}ta{#Prev} lắm sao? Mẹ {#Emph}cháu{#Prev} cũng thế thôi. Thế gian khắc nghiệt lắm, cô gái. Chẳng ai được hỏi có muốn sinh ra hay không.",
    "Hera_0282": "Chúng ta đã cử Artemis trẻ tuổi đến gần biên giới giữa hai cõi. Cần có thêm người quan sát ở đó, và cháu cũng sẽ được yểm trợ từ xa. Đôi khi ta nhớ cảm giác tự tay giương cung...",
    "Hera_0136": "Lúc cần thì {#Emph}Hermes{#Prev} biến đâu mất rồi? Gần đây cháu có gặp nó không, cô gái? Lúc nào cũng {#Emph}thoắt ẩn thoắt hiện{#Prev}, chẳng thể giữ chân. {#Emph}Eo ôi. {#Prev}{#Emph}Giờ này còn tin tức gì mà chuyển chứ?",
    "Hera_0058": "Cháu biết không, lúc nãy ta thấy ánh sáng trên trời chập chờn, như thể ánh trăng vừa đổi khác. Nhưng giờ ánh sáng ấy lại tỏa ra từ {#Emph}cháu. {#Prev}Cháu đã gọi Selene xuống! Ít ai có thể gọi mà nàng đáp lời đấy.",
    "Hera_0281": "Athena tài trí đang giữ vững tiền tuyến, nhưng có lẽ chúng ta cần thêm cả chục người {#Emph}giỏi{#Prev} ngang nàng. Nàng khiến quân đột kích của Titan khiếp sợ, nhưng... ngay cả nàng cũng không thể chặn hết tất cả.",
    "Hera_0184": "Ta biết cháu hiểu Lời Nguyền Chạng Vạng mà. Phép thuật biến hình này có thể đổi một dạng sống thành dạng khác! Ta vốn rất thích nó; chỉ còn cách việc tự biến hình một bước. Khả năng thì vô hạn.",
    "Hera_0169": "Cháu có vẻ rất giỏi giữ khoảng cách với kẻ thù. Ta từng xuất sắc trong việc này, dù ta thích bắn tên xuyên tim hơn phép thuật, thứ ta thấy chẳng đáng tin lắm. Nhưng cách nào hiệu quả là được!",
    "Hera_0247": "Ồ, chiếc quạt óng ánh của ta đây rồi, ngay trong đêm vẫn sáng rực! Nhờ nó ta dễ dàng nhận ra cháu ở bất cứ đâu. Khi cần ta giúp ngay, cứ phất quạt lên là được.",
    "Hera_0236": "Cháu vẫn luôn là một trong những hy vọng lớn nhất của chúng ta, cháu yêu. Nhưng nói thật, ta chẳng tin chúng ta sẽ thắng, dù {#Emph}có{#Prev} cháu hay không. Lần này ta mừng vì mình đã lầm, và sẽ không quên những gì cháu làm đâu.",
    "Hera_0229": "Cuối cùng cũng gặp cháu đàng hoàng rồi, cháu yêu! Cháu đã giúp ngọn núi này cầm cự thêm một thời gian, nên chúng ta đang củng cố phòng tuyến hết sức... vì vậy ta khẩn khoản mong cháu mau quay lại!",
    "Hera_0235": "{#Emph}Chậc{#Prev}, cháu còn chưa được thấy chính điện của ta, cháu yêu. Giờ nơi ấy chẳng thể tiếp khách. Có lẽ khi Nhà của cha cháu được chỉnh trang xong thì cung điện của ta cũng vậy! Nhất định ta sẽ mời cháu đến.",
    "Hera_0250": "Phương án cuối cùng ấy lẽ ra đã dùng để chống Typhon nếu cháu không tìm được cách xử lý có mục tiêu hơn... chỉ là thứ Hephaestus làm dở dang. Nó sẽ khiến con trai ta mất lò rèn yêu quý, và còn {#Emph}nhiều hơn thế!",
    "Hera_0233": "Cháu định xuống thăm cha mẹ à, cháu yêu? Nhà Hades hẳn cần cháu giúp một tay. Giá mà {#Emph}các con{#Prev} ta cũng biết quan tâm như vậy. Dù ta nghĩ chúng vẫn đang giúp cháu...",
    "Hera_0234": "Cháu lại đi đường này {#Emph}nữa{#Prev} sao, cháu yêu? Hẳn là muốn kiểm chứng mớ lý thuyết vô lý của ông ngoại Titan. Nếu phát hiện dù chỉ một chút dối trá, nhớ nói ta biết. Dù có thể khoan dung, chúng ta cũng không được khờ khạo.",
    "Hera_0245": "Cháu đã thấy ngọn núi đáng thương của chúng ta ra sao rồi đấy. Mấy phát minh đáng xấu hổ của Hephaestus hoành hành chẳng kém gì kẻ thù! Một số người đành ở lì trong Điện Zeus cho yên thân. Ở đây cũng dễ chịu lắm!",
    "Hera_0244": "Hạm đội đang tiến đến thật đáng sợ... Lần gần nhất ta thấy một hạm đội lớn thế này, những con tàu ấy đang tiến về đây để tôn vinh ta, chứ không phải chống lại quê nhà.",
    "Hera_0232": "Cháu gái à, cháu đã đưa Chronos bất lực, phải cúi đầu đến ngay trước mặt chúng ta, sau khi tiêu diệt Typhon... hết chiến công phi thường này đến chiến công khác, ngay cả với một nữ thần có dòng dõi như cháu. Chúng ta biết đền đáp cháu thế nào đây?",
    "Hera_0239": "Tìm thấy các Số Mệnh rồi! Thật nhẹ nhõm khi vận mệnh của chúng ta đã trở lại tay họ. Ta bắt đầu sợ rằng tương lai mãi mãi sẽ do {#Emph}chúng ta{#Prev} định đoạt. Có lẽ khi trưởng thành và có trách nhiệm hơn, ta sẽ nghĩ khác.",
    "Hera_0240": "Một kỷ nguyên mới sắp mở ra, {#Emph}thật{#Prev} vậy sao? Các Tam Nữ Thần Số Mệnh đã đảm bảo điều đó, còn lại ta muốn làm gì cũng được! Được thôi. Nếu người phàm nghĩ họ sống được mà không cần {#Emph}chúng ta{#Prev} can thiệp, ta muốn xem họ làm được đến đâu!",
    "Hera_0251": "Chuyến hành trình này quả {#Emph}đúng là{#Prev} đáng nhớ, phải không cháu yêu? Từ nay ta có thể sẽ ít nói hơn vì ngày càng có nhiều việc cần lo. Nhưng cháu cần bao lâu, ta sẽ ban Ân huệ cho cháu bấy lâu.",
    "Hera_0088": "Chúng ta không thể để sơ suất, cô gái. Chẳng hạn, nếu giúp cháu và chúng ta chiến thắng thì Ân huệ của ta có được chuyển đến như bưu kiện bình thường {#Emph}cũng chẳng sao{#Prev}.",
    "Hera_0253": "Thừa nhận đi, cô gái! Lúc này cháu sẽ nhận bất kỳ Ân huệ nào, dù từ {#Emph}ta{#Prev} hay người nhà ta. Và theo ý các Số Mệnh, cháu sẽ nhận được thứ tốt nhất.",
    "Hera_0086": "Ta và người lái đò của cháu đã hợp tác lâu năm. Ta ban sự sống cho người phàm rồi tác thành hôn nhân cho họ; còn ông ấy đưa họ sang cõi của cháu! Ít ra trước kia là thế.",
    "Hera_0087": "Giàu có đâu thể chỉ đo bằng tiền xu! Nghĩ vậy thật nực cười; thế mà cháu vẫn trả tiền mua bán như thể Chronos đã thắng đến nơi rồi!",
    "Hera_0178": "Ở nơi sâu thẳm ấy, chúng ta không phải lúc nào cũng tìm được cháu, vậy mà người lái đò của cháu chẳng gặp khó khăn gì. Ông ấy lặng lẽ, tự lo cho mình... ta khá thích ông ấy đấy!",
    "Hera_0179": "Ít ra chuyến giao hàng này của người lái đò đáng tin cậy cũng ngắn hơn việc kéo Ân huệ của chúng ta xuống tận Âm phủ. Dù có lẽ ông ấy thích ở dưới đó hơn...",
    "Hera_0069": "Ta nên hỏi ngày cưới của cháu chưa, hay cháu chỉ rộng rãi với ta thôi? Dù sao, mỗi khi có người dâng quà cho ta thì luôn có ẩn ý. Đây, nhận lấy!",
    "MelinoeField_1771": "Chai Tiên tửu Nectar vàng này chẳng là gì so với vẻ lộng lẫy của Người, Nữ hoàng Hera; nhưng đây là món tốt nhất ở quê nhà con. Kính chúc Người mãi xinh đẹp, duyên dáng và sáng suốt!",
    "Hera_0071": "Cháu không cần nịnh ta đâu. Ta giúp cháu không phải vì yêu quý, mà vì cần thiết. Nếu có điều gì muốn dạy, thì đó là cháu phải luôn cảnh giác.",
    "MelinoeField_2241": "Kính chúc Nữ hoàng Olympus trường trị! Mong triều đại của Người thịnh vượng và thái bình, cho gia đình tận tụy, thần dân và chính Người!",
    "Hera_0134": "Nói đi, cô gái. Cả hai ta đều biết ta không thật sự là Nữ hoàng của cháu. Cháu còn chẳng phải thần Olympus, vậy nên đừng diễn nữa. Nếu không diễn thì tỉnh táo lên. Thế giới này phức tạp lắm.",
    "MelinoeField_2242": "Nữ hoàng Hera, những lần trò chuyện giữa chúng ta vốn chẳng thể kéo dài, nhưng con biết ơn từng khoảnh khắc Người dành cho con. Gia đình cần Người, Olympus cũng cần Người... và lòng tận tụy của Người với cả hai đều rất rõ ràng.",
    "Hera_0166": "Chà, cháu yêu, nếu nghề phù thủy chẳng đem lại tương lai thì cháu có thể thử làm diễn viên! Ta suýt tin từng lời cháu nói đấy. Gia đình ta vốn chẳng nổi tiếng thật thà, nhưng dù sao ta khen cháu đã cố gắng.",
    "MelinoeField_2243": "Thưa Nữ hoàng, Người có thể không tin lời con, nhưng món Tiên tửu Nectar này chứng minh con không hề giả dối hay có ý đồ mờ ám. Với con, Người không chỉ là hoàng tộc... Người còn là bà cô của con. Và Người vĩ đại đúng như con hằng tưởng tượng.",
    "Hera_0167": "Cháu nghiêm túc thật sao? Nghe này, cô gái. Cháu chẳng hiểu sống trên ngọn núi này thế nào đâu. Không được phép sai sót; chỉ một bước hụt cũng không xong! Có lẽ cháu cũng từng nếm trải kiểu {#Emph}áp lực{#Prev} ấy...",
    "MelinoeField_4166": "Cảm ơn Nữ hoàng Hera đã giữ gia đình ta đoàn kết qua những thời khắc gian nan nhất, và tin rằng con có thể tạo nên khác biệt! Mong vị ngọt của chai Ambrosia này giúp xoa dịu ký ức về những tháng ngày cay đắng.",
    "Hera_0237": "Cháu thật tử tế, cháu yêu. Nhưng trí nhớ của ta vừa {#Emph}dài lâu{#Prev} vừa {#Emph}sắc bén{#Prev}; ta sẽ chẳng để nó phai mờ, dù vô tình hay cố ý. Ký ức tiếp thêm can đảm và giúp ta không lặp lại sai lầm. Tạ ơn các Số Mệnh, ta đã không nhìn lầm cháu.",
}

source = (SRC / "_LootData_Hera.en.sjson").read_text(encoding="utf-8-sig")
result = apply_translation_to_sjson(source, {k: {"DisplayName": v} for k, v in translations.items()})
target = TR / "_LootData_Hera.en.sjson"
target.parent.mkdir(parents=True, exist_ok=True)
target.write_text(result, encoding="utf-8")
sys.stdout.reconfigure(encoding="utf-8")
print(f"_LootData_Hera: {len(translations)} câu đã dịch")
