"""Complete the remaining Hermes dialogue strings with source tags intact."""
from pathlib import Path
import sys

ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(ROOT / "tools"))
from hades2_sjson_helper import apply_translation_to_sjson  # noqa: E402

TR = ROOT / "translations/0100A00019DE0000_Hades2/Game/Text/en/_LootData_Hermes.en.sjson"
translations = {
    "MelinoeField_2002": "Hermes...!",
    "Hermes_0214": "Chúng ta thật sự hạ được hắn rồi, M! Ý ta là Typhon! Ta thấy hắn lăn xuống sườn núi tối om rồi rơi cái {#Emph}ầm! {#Prev}Sau đó lại thấy hắn từ từ đứng dậy, gầm lên giận dữ hơn bao giờ hết. Nhưng mà!",
    "Hermes_0036": "Olympus từng bị vây hãm rồi! Thường thì chẳng đáng ngại lắm. Nhưng lần này ông Chronos có mưu tính khác. Vài người ở đây sợ xanh mặt rồi!",
    "Hermes_0215": "M, cô thấy đống hàng chúng ta cất trên đỉnh núi cho cô rồi chứ? Chỗ đó hơi xa với cộng sự làm ăn của ta, nhưng bọn ta sẽ tiếp tế đầy đủ!",
    "Hermes_0037": "Ta quen Hec lâu rồi, chẳng ghen tị với ai trong hai người đâu. Cô ấy không thể đẩy cô đi đối phó ông Chronos trước khi cô sẵn sàng! Chắc cô đã {#Emph}ghét cay ghét đắng {#Prev}quãng thời gian phải chờ. Ta thì biết cảm giác đó!",
    "Hermes_0040": "Hec vẫn bảo cô học nhanh lắm. Quả đúng vậy, lần nào ta ghé qua cũng thấy cô bên chiếc vạc, luyện phép mới. Vậy thì {#Emph}đến lúc rồi! {#Prev}Hãy dùng phép thuật giúp cả nhà chúng ta!",
    "Hermes_0041": "Titan Thời Gian đúng là khó chơi! Ta chưa từng gặp ông Chronos, nhưng cũng tưởng tượng được lão ra sao. Trước đây ta cứ thắc mắc sao bố ta với các chú đôi khi lại lươn lẹo thế. Giờ thì biết họ học từ ai rồi!",
    "Hermes_0042": "Tưởng Titan Thời Gian phải biết sống cho hiện tại chứ, vậy mà cứ mắc kẹt trong quá khứ, ôm mộng về {#Emph}Thời Hoàng Kim {#Prev}khi {#Emph}lão {#Prev}còn cai trị và phàm nhân chẳng phải lo nghĩ gì? Biết quan tâm cũng đâu có gì xấu!",
    "Hermes_0077": "Cô chưa thể hạ ông Chronos ngay được đâu, nhưng việc cô đuổi theo lão đúng lúc đã giúp chúng ta có thời gian làm xáo trộn kế hoạch của lão. Nên là {#Emph}cạn ly!",
    "Hermes_0217": "Vài vị thần nghĩ Eris lại đến gần núi chúng ta gây rối vì cô đấy, M! Họ đâu biết ta gần như đã {#Emph}van xin {#Prev}cô lên đây cứu viện. Cứ để họ nghĩ Hec ra lệnh đi! Giờ chúng ta gặp rắc rối to rồi...",
    "Hermes_0102": "M, rắc rối với các Titan nhiều hơn ta tưởng. Nếu ông Chronos lôi kéo được Prometheus, ai biết lão còn dụ được ai nữa. Chúng ta làm phật ý khối người rồi!",
    "Hermes_0269": "Hóa ra Prometheus với Heracles thân thiết với nhau à? Trận ẩu đả của cô với họ bị bóng tối che khuất, nhưng ta cũng thấy loáng thoáng vài đoạn. Ta cần biết những chuyện này, nhưng không có nghĩa ta sẽ kể đâu!",
    "Hermes_0207": "Lần trước cô suýt lên đến tận đỉnh rồi. Ta không muốn phá hỏng bất ngờ, nhưng cô {#Emph}nên {#Prev}biết kẻ chúng ta đang đối đầu là Typhon, Cha của Muôn Loài Quái Vật! Tuyệt quá nhỉ...? M, chúng ta cần cô quay lại đây.",
    "Hermes_0208": "Tin tốt là giờ ta biết chắc ông Chronos định làm gì. Tin xấu là đó là Typhon, mà hắn thì to khủng khiếp. Nhưng bố ta từng đánh bại hắn một lần, nên chắc cũng không khó lắm đâu...?",
    "Hermes_0209": "M, cô nghĩ ai sẽ lên đỉnh Olympus trước, cô hay lão Typhon? Cô phải đi xa hơn thật, nhưng chắc chắn cô nhanh hơn! Hoặc sắp nhanh hơn rồi!",
    "Hermes_0264": "Typhon biến mất mãi mãi rồi sao?! Bố ta vẫn chưa tin nổi, nhưng từ lần cuối cô giao chiến với con quái vật ấy, trên này chẳng thấy bóng dáng hắn nữa! Nhưng sao ta phải {#Emph}ngạc nhiên{#Prev}? Ta biết nếu có ai làm được chuyện đó thì chính là {#Emph}cô!",
    "Hermes_0084": "Hec kể Moros, con trai Nyx, đang ở chỗ cô một thời gian à? Ta cứ tưởng anh ấy lúc nào cũng ở bên Tam Nữ Thần Số Mệnh. Có chuyện gì đó đang xảy ra, M, mà ta chẳng thích chút nào.",
    "Hermes_0085": "Cô tìm thấy cha mình dưới đó rồi, M! Ta chưa bao giờ đến đủ gần để gặp ông ấy; mong ông vẫn ổn. Mong {#Emph}mọi người{#Prev} đều bình an! Chúng ta sẽ đưa họ trở về, cứ tiếp tục cố gắng nhé.",
    "Hermes_0173": "Tối qua cô gặp quý cô Circe trên đường à, M? Phép thuật của bà ấy quả là tài tình. Bà ấy thích biến phàm nhân thành đủ thứ! Theo ta thì hơi {#Emph}ác {#Prev}đấy!",
    "Hermes_0078": "Chính thức thì ta đang theo dõi cô, nhưng cô không được biết chuyện đó nhé. Ta kể với Olympus {#Emph}mọi {#Prev}diễn biến mới nhất, không có gì quá riêng tư đâu; rồi kể với {#Emph}cô {#Prev}nhiều hơn nữa! Chắc là ta theo dõi tất cả mọi người thôi!",
    "Hermes_0083": "Mấy đêm từ khi cô bắt đầu hành trình đến giờ, ta chỉ xác nhận được ông Chronos đã lôi kéo một kẻ mà lão tin sẽ giúp mình chiếm ưu thế. Giờ lão đang chuẩn bị bước tiếp theo trong kế hoạch đánh sập ngọn núi này! Ta phải đi đây.",
    "Hermes_0043": "Mẹ cô thường đi đi về về giữa Olympus và Điện của cha cô, còn {#Emph}ta {#Prev}may mắn được tháp tùng bà! Rồi một ngày bà không đến. Ta biết ngay có chuyện chẳng lành...",
    "Hermes_0044": "Chuyện này làm ta nhớ lần ta giúp anh trai cô đi tìm mẹ! Đúng là lúc ấy ta cũng có lợi ích riêng. Nhưng rồi chẳng biết từ bao giờ, ta thật sự quan tâm đến họ! Chúng ta sẽ tìm cách giúp gia đình cô, phải không M?",
    "Hermes_0045": "Artemis với ta trước đây không thân lắm, ai cũng chỉ lo việc riêng. Nhưng cùng làm việc với cô và Hec đã kéo chúng ta lại gần nhau! Bọn ta lén lút nhiều đến nỗi thật tốt khi biết có thể thôi phải lén lút với nhau!",
    "Hermes_0100": "Cô gặp Artemis rồi, tốt lắm! Cô ấy với ta không thường trò chuyện, cả hai cứ chạy khắp nơi, phải kín đáo đủ điều. Nhưng đôi lúc bọn ta vẫn trao nhau ánh mắt ngầm hiểu!",
    "Hermes_0046": "Nếu cô gặp người lái đò Âm phủ đang chèo thuyền đâu đó thì nhắn ta gửi lời chào nhé! Dạo này bọn ta ít hợp tác hơn trước. Ta nhớ những ngày ấy!",
    "Hermes_0047": "Người lái đò vẫn ổn chứ? Tốt quá! Ta biết anh ấy đã trông nom Hec và mọi người một thời gian rồi. Cô cũng nhớ để mắt đến anh ấy nhé?",
    "Hermes_0063": "Cô gặp Heracles to xác rồi à? Mẹ kế ta lại giao cho anh ta một chiến công nào đó. Ta có cảm giác anh ấy chẳng còn thiết tha nữa. Nhưng mà anh ấy khỏe lắm! Chúng ta cần người như vậy.",
    "Hermes_0079": "Vậy là ông Chronos bắt được Tam Nữ Thần Số Mệnh rồi! Tệ thật, M, ta chẳng biết phải làm gì. Ít nhất giờ mọi người trên Olympus đều biết; ta nghĩ đã đến lúc nói ra. Ai cũng hơi lo, dù che giấu khá giỏi!",
    "Hermes_0038": "Ít ra giờ gia đình cũng biết về cô rồi! Ta đã muốn thông báo mãi: {#Emph}Tin nóng từ Olympus! Persephone và Hades có thêm con! Cô bé vẫn bình an! {#Prev}Nhưng Hec bảo phải chờ, mà cô ấy biết nhiều chuyện lắm! Nên ta đành giữ kín.",
    "Hermes_0039": "Nghĩ lại mới thấy trước kia ngày nào ta cũng đưa những người phàm vừa chết xuống cõi của cha cô! Chẳng bao lâu ta cũng thích công việc ấy, nên cả sau khi ông Chronos xuất hiện, ta vẫn lén ghé thăm mỗi khi có dịp!",
    "Hermes_0080": "M, cô lên được đây rồi! Ta sẽ giúp cô đi nhanh hơn, chỉ có điều khí hậu nơi này sẽ {#Emph}khắc nghiệt lắm. {#Prev}Dân Âm phủ các cô không hợp với không khí mặt đất nhỉ! Chắc phải có cách khắc phục chứ...?",
    "Hermes_0252": "Được rồi, ta hiểu lên mặt đất khó khăn với cô, nhưng đừng bỏ cuộc nhé M. Ta biết cô {#Emph}chẳng bao giờ {#Prev}làm thế đâu. Chắc chỉ đang tìm vài nguyên liệu phép thuật cần thiết thôi nhỉ?",
    "Hermes_0081": "Chào M! Ta không rõ cô đã làm gì, hay Hec đã làm gì, nhưng cô trông giống mình hơn hẳn lần trước ta gặp. Tốt quá! Muốn đi xa đến vậy, cô sẽ cần {#Emph}từng {#Prev}chút sức lực. Và cả {#Emph}tốc độ nữa!",
    "Hermes_0082": "Chào M! Cô đến rồi! Tuyệt quá! Hec bảo cô đã hóa giải lời nguyền huyết thống Âm phủ, nên giờ có thể chạy đường dài rồi. Cẩn thận chướng ngại trên đường nhé; nếu được ta sẽ giúp cô vượt qua thật nhanh!",
    "Hermes_0062": "Đáng lẽ người chết khắp Ephyra được yên nghỉ dưới sự chăm nom của cha cô. Nhưng ông Chronos đóng cửa mọi thứ, mở toang cổng Âm phủ, thành ra mới có cảnh này. Nếu ta chết chắc ta cũng tức điên lên.",
    "Hermes_0059": "Cuối cùng cô cũng thấy trên này ra sao rồi! Phần lớn mọi người đang cố thủ trên đỉnh Olympus, còn {#Emph}cô {#Prev}chính là viện binh. Khi nào được thì quay lại nhé!",
    "Hermes_0060": "Cô đang chọn đường vòng phong cảnh để xuống Điện của cha mình đấy à! Ông Chronos phong tỏa các vùng chính của Âm phủ rồi, vậy nên... nghĩ lại thì cũng hợp lý thật!",
    "Hermes_0172": "Giá mà ta có thể đưa cô băng qua khe biển Poseidon tạo ra. Nhưng chúng ta {#Emph}không được {#Prev}để ai phát hiện đang hợp tác quá thân thiết. Với lại, mỗi lần cô lau boong tàu là lại giúp chúng ta! Nên {#Emph}cạn ly!",
    "Hermes_0061": "Ông Chronos đưa quân đến Olympus thì ta có thể tống chúng về chỗ cũ dễ như chơi. Nhưng lão còn toan tính chuyện khác, mà chắc chắn không nhỏ đâu. Biết được gì thì báo Hec ngay nhé.",
    "Hermes_0098": "Tối nay cô gặp bố ta rồi chứ, M? Ông ấy lúc nào cũng bận rộn nhưng chẳng bao giờ mệt. Giờ cô có sức mạnh sấm chớp của ông rồi, muốn thêm chút {#Emph}tốc độ {#Prev}sấm sét không?",
    "Hermes_0221": "Ta nghĩ mẹ kế ta khá quý cô đấy! Đừng xem nhẹ chuyện đó! Dù rất giỏi chăm sóc người khác, ta có cảm giác Nữ hoàng Hera không thích trẻ con lắm.",
    "Hermes_0220": "Ân Huệ của chú Poseidon giúp cô được gì chưa, M? Chú ấy cứ bảo nó khiến cô gần như bất khả chiến bại. Nhưng đây là chút bảo hiểm cho khách du hành, phòng khi cần!",
    "Hermes_0174": "Apollo đang thắp sáng cuộc đời cô à? Bình thường anh ấy chẳng bao giờ muốn nhúng tay vào việc khó nhọc, nhưng thời thế này thì chắc cũng chẳng còn lựa chọn!",
    "Hermes_0099": "Sau bao chuyện, ta mừng vì cuối cùng cô cũng gặp Demeter, dù chỉ qua Ân Huệ. Đôi lúc bà thể hiện tình cảm hơi kỳ quặc, nhưng bà {#Emph}luôn {#Prev}thương mẹ cô rất nhiều. Bà sẽ chiến đấu đến cùng để đưa mẹ cô về.",
    "Hermes_0223": "M, Aphrodite ban phước cho cô à? Đáng nể đấy, ân sủng của nàng đang được {#Emph}rất {#Prev}nhiều người săn đón! Nàng thích xen vào chuyện riêng tư, nhưng trường hợp của cô chắc đặc biệt lắm!",
    "Hermes_0096": "Cô khiến Hephaestus chịu bước ra khỏi vỏ ốc rồi! Ta chỉ nhận được lệnh làm việc: {#Emph}đem thêm đồng đến đây{#Prev}, rồi đủ thứ khác! Mừng là cô tận dụng được thành quả lao động của anh ấy!",
    "Hermes_0097": "Hephaestus làm giáp {#Emph}đỉnh {#Prev}lắm, mà anh ấy còn làm dép cũng tuyệt nữa. Ta đi suốt! {#Emph}Giày dép{#Prev}, M! Ta tin mốt này sẽ thịnh hành!",
    "Hermes_0222": "Hestia gặp cô rồi à? Dù có tuổi nhưng cô ấy vẫn nhanh nhẹn thật. Lại còn thích đùa với lửa nữa! Tâm hồn vẫn trẻ thơ... kiểu trẻ thơ hơi đáng sợ ấy!",
    "Hermes_0226": "M, cô gặp Ares rồi à? Cứ hễ có trận hỗn chiến đẫm máu, ai nấy nổi nóng là anh ấy tìm mọi cách để mọi chuyện kéo dài thêm! Tình thế này chắc khiến anh ấy khó xử lắm.",
    "Hermes_0225": "Athena đang chỉ huy chiến lược phòng thủ tiền tuyến. Bọn ta thường tránh đường nhau. Nhưng phải công nhận, những lúc thế này cô ấy luôn giữ được bình tĩnh!",
    "Hermes_0224": "Vài người họ hàng chẳng muốn can dự. Dionysus thì tiệc nào cũng đến, nhưng đánh nhau thì không! Anh ấy cứ bảo {#Emph}sao tất cả không sống hòa thuận{#Prev} với nhau. Nghĩ lại... cũng đâu phải ý tồi!",
    "Hermes_0095": "Ồ, Selene gặp cô rồi, M! Con Mắt Màn Đêm có tầm nhìn tuyệt thật! Nàng luôn dõi theo cô và tất cả chúng ta. Chiến mã của nàng cũng chạy nhanh lắm!",
    "Hermes_0093": "Có ai gọi dịch vụ Giao Hàng Thượng Hạng không, M? Đây là món {#Emph}tốt nhất {#Prev}ta có, giúp cô đi xa và nhanh! Ta {#Emph}bảo đảm!",
    "Hermes_0094": "Tươi rói từ đỉnh Olympus, dịch vụ {#Emph}Giao Hàng Thượng Hạng! {#Prev}Ân Huệ tốt nhất, nhanh nhất, dành riêng cho khách hàng sành sỏi. Chính là {#Emph}cô!",
    "Hermes_0167": "M, nghe thấy không? Đó là tiếng {#Emph}Giao Hàng Thượng Hạng{#Prev} đấy! Lúc nào cũng mang đến cho {#Emph}cô {#Prev}những món tốt nhất. Tận dụng cho đáng nhé!",
    "Hermes_0227": "Lần này ta mang món tốt nhất ra cho cô chọn, M. Dù sao thì cô {#Emph}lúc nào cũng {#Prev}nên mong đợi hàng chất lượng từ ta! Chỉ là hôm nay còn nhiều hơn thường lệ thôi!",
    "Hermes_0218": "Đêm nay đáng sợ thật đấy, M. Cô có nhúng tay vào phải không? Tim ta cứ đập thình thịch! Không biết cô đang làm gì ở Ngã ba Địa Giới, nhưng mong là mọi chuyện suôn sẻ!",
    "Hermes_0101": "Ta thích thấy cô theo dõi kỷ lục của mình! Cứ làm việc gì đó thật tốt, rồi làm tốt hơn một chút và nhanh hơn một chút, rồi lại {#Emph}nhanh hơn nữa{#Prev}; chẳng mấy chốc cô sẽ giống {#Emph}ta! Gần được thôi!",
    "Hermes_0219": "M, ta nhận ra cô không còn bấm giờ nữa. Đau lòng thật đấy. Nói vậy thôi! Cứ tìm nhịp độ của mình, nhưng nếu muốn biết nhanh đến đâu thì chỉ có một cách để khám phá.",
    "Hermes_0090": "Ta đã đoán sớm muộn gì cũng gặp cô ở đây. Cứ như có thứ gì đó trong không khí vậy. Ta nôn nóng lắm, chỉ muốn làm mọi việc {#Emph}nhanh hết mức{#Prev} có thể!",
    "Hermes_0075": "Cô đang tiến nhanh lắm, M! Có Giọt Kim Loại bên mình lúc nào cũng có ích. Ít nhất là đến khi nó hết tác dụng trong đêm! Không thể chạy hết tốc lực mãi, nhưng {#Emph}cứ thử xem!",
    "Hermes_0228": "Trùng hợp thật, là cô đấy à, mà cô {#Emph}đã {#Prev}nhanh sẵn rồi! Nhưng lúc nào cũng có thể nhanh hơn chút nữa! Trừ ta ra nhé.",
    "Hermes_0216": "Ta biết cô đang mong Apollo, M, anh ấy nhanh thật! Nhưng ta còn nhanh hơn, lần nào cũng có thể đến trước anh ấy {#Emph}mọi lần {#Prev}nếu ta nhỏ nhen hơn một chút! Anh ấy sắp đến rồi.",
    "Hermes_0089": "Cây trượng đầu rắn của cô đẹp đấy, M. Chắc đang là mốt nhỉ! Mấy con rắn {#Emph}của ta {#Prev}là quà Apollo tặng, nhắc ta nhớ đến gia đình. Dù da chúng chẳng dày, lại hay cáu kỉnh... ta vẫn quý chúng lắm.",
    "Hermes_0076": "Cô tìm thấy Đền Thờ đặc biệt của ta rồi, tốt lắm! Có phàm nhân cầu xin ta đi đường bình an lẫn được đồ miễn phí. Gần như {#Emph}miễn phí{#Prev} thôi. Tính thêm chút phụ phí, cộng sự của ta phải có phần chứ.",
    "Hermes_0166": "Đem theo bạn đồng hành là lựa chọn sáng suốt! Ta thích những người trầm tính, tự lập. Rùa nhỏ Chellen của ta đi đâu cũng thấy như ở nhà!",
    "Hermes_0249": "Hec bảo cô sắp tìm ra bước đột phá trong chuyện ông Chronos với Typhon rồi. Ta không muốn giục cô đâu, M, nhưng ta vốn {#Emph}là ta mà! {#Prev}Đôi khi không nhịn được!",
    "Hermes_0274": "Ta định nói không thể tin cô làm được, nhưng thế thì chẳng khác nào ta không tin cô; mà ta {#Emph}có tin{#Prev}, nên ta {#Emph}không nói vậy đâu! {#Prev}Nhưng ta {#Emph}sẽ {#Prev}nói rằng: cảm ơn cô vì {#Emph}tất cả! {#Prev}Có thể mọi chuyện chưa kết thúc hẳn, nhưng nếu áp lực đã vơi đi đôi chút thì tốt quá.",
    "Hermes_0278": "Đến giờ ta thích ông Chronos mới này {#Emph}hơn nhiều {#Prev}so với lão Chronos độc ác trước kia. Khi nào rảnh cô kể ta nghe đã đảo lộn thế giới của lão ra sao nhé. Hec chẳng hé lời nào!",
    "Hermes_0283": "Cha cô đã trở về đúng nơi của mình, mẹ cô cũng vậy. Ta mừng vì họ lại được bình an bên nhau, M. Cô sẽ có thời gian bù đắp những năm tháng đã mất, từ giờ trở đi!",
    "Hermes_0284": "Vẫn còn phải giải quyết chuyện Tam Nữ Thần Số Mệnh. Ông Chronos đày họ đi rồi mất dấu luôn sao? Nếu {#Emph}lão {#Prev}còn chẳng tìm ra, thì {#Emph}chúng ta {#Prev}tìm kiểu gì...?",
    "Hermes_0285": "M, cô tìm thấy họ rồi! Tam Nữ Thần Số Mệnh! Chính họ kể ta nghe, nên ta truyền tin luôn, đúng nghề sứ giả mà. Cô biết không? Họ {#Emph}nói đúng! {#Prev}Có vẻ thời gian xa cách đã khiến họ đổi ý...",
    "Hermes_0286": "Nghe nói từ nay các Nữ Thần Số Mệnh không còn quyết định mọi chuyện nữa, trừ việc lớn như mở ra kỷ nguyên mới? Ta chẳng biết {#Emph}làm sao {#Prev}phân biệt được chuyện nào đã định sẵn bởi {#Emph}họ {#Prev}và chuyện nào do chúng ta tự quyết...",
    "Hermes_0389": "Vậy là một kỷ nguyên mới sắp mở ra. Chắc cô đã nghe tận tai chuyện đó rồi, M. Mọi thứ sẽ đến trước khi ta kịp nhận ra thôi! Chúng ta sẽ sẵn sàng; còn nếu chưa thì cứ hành động thật nhanh.",
    "Hermes_0295": "M, ta sợ một ngày nào đó Thời Gian còn chạy nhanh hơn {#Emph}ta{#Prev}. Nhớ hồi cô còn bé xíu không? {#Emph}Vèo! {#Prev}Cô đã {#Emph}lớn{#Prev} rồi, chỉ trong {#Emph}chớp mắt!",
    "Hermes_0003": "Cả hai ta đều có việc phải làm, để ta đưa cô lên đường nào!",
    "Hermes_0004": "Ta ghé xem cô thế nào, mọi việc ổn chứ? Tốt rồi!",
    "Hermes_0005": "Tình hình giờ không mấy sáng sủa, nhưng có thể nhanh chóng đổi khác!",
    "Hermes_0006": "Đúng là Thời Gian trôi nhanh! Nhưng ta nghĩ chúng ta theo kịp được!",
    "Hermes_0007": "Ta tình cờ đi ngang, vừa hay có mấy Ân Huệ cho cô chọn đây!",
    "Hermes_0008": "Nhanh nhẹn và lặng lẽ nhé, M! Cô làm được mà, phải không?",
    "Hermes_0009": "Ta đang hơi vội, M, vậy bắt đầu thôi nào!",
    "Hermes_0010": "{#Emph}Giao hàng đặc biệt cho Công chúa Âm phủ đây!",
    "Hermes_0011": "Chào M, cần đi nhờ không? Ta có thể đưa cô đi. Thật ra là ba chuyến!",
    "Hermes_0012": "Ta đang xoay xở cầm cự. Cô cũng thế chứ? Vậy cùng ráng vượt qua nhé!",
    "Hermes_0013": "Người ta bảo đừng hấp tấp, nhưng họ biết gì chứ, nhỉ?",
    "Hermes_0014": "Sống nhanh hoặc chẳng sống gì cả, phải không M? Chọn đi nào!",
    "Hermes_0015": "Ta sẽ đưa cô lên đường ngay thôi!",
    "Hermes_0016": "Ta đoán đúng lúc này cô sẽ đến đó!",
    "Hermes_0017": "Đừng nghĩ nhiều, chọn nhanh một món rồi đi thôi!",
    "Hermes_0018": "Có vẻ đêm nay lại bận rộn đây!",
    "Hermes_0019": "{#Emph}Nhanh lên, M, kẻo không kịp! {#Prev}Ta thích nói câu đó lắm.",
    "Hermes_0020": "Ta có món này giúp cô bước đi thoăn thoắt hơn đấy!",
    "Hermes_0021": "Nào M, để ta giúp {#Emph}cô {#Prev}tăng tốc một chút!",
    "Hermes_0022": "Ồ chào! Ta ghé qua để đưa cô một món nhỏ đây!",
    "Hermes_0023": "Chúng ta đang chạy đua với Thời Gian, và dù có chuyện gì, chúng ta nhất định thắng!",
    "Hermes_0024": "Đêm đẹp thế này đi chạy bộ một chút nhỉ, M?",
    "Hermes_0025": "Chào! Ta có chuyến giao hàng đặc biệt cho cô đây, M!",
    "Hermes_0026": "Khách quý như cô chỉ xứng đáng với dịch vụ tốt nhất và nhanh nhất!",
    "Hermes_0027": "Cô cũng định đi lên đó à? Có khi lát nữa ta gặp lại!",
    "Hermes_0028": "Muốn đi nhanh thì ta có đúng món cô cần đây!",
    "Hermes_0029": "Nhiều việc quá! Ta chạy ngược chạy xuôi cả đêm rồi!",
    "Hermes_0030": "Không cuộc tấn công tai họa nào nhằm vào gia đình ta làm chậm chân chúng ta được!",
    "Hermes_0031": "Ta cần kiểm tra vài chuyện, nhưng trước hết nhận món này đã!",
    "Hermes_0032": "Chào chào, M! Một tiếng chào là của Artemis đấy.",
    "Hermes_0033": "Chào chào, M! Một tiếng chào là của Selene đấy.",
    "Hermes_0068": "Dạo này lẻn xuống Âm phủ khó hơn trước nhỉ! May là ta quen một chuyên gia chuyện đó. Cô cũng quen, {#Emph}ta thấy rồi{#Prev}!",
    "Hermes_0069": "Cảm ơn cô đã mua hàng, thay mặt cộng sự làm ăn cũ của ta! Thật vui khi lại được hợp tác. Cô nhắn với anh ấy là ta nói {#Emph}ưrghhh!",
    "Hermes_0170": "Người lái đò lúc nào cũng thu phí, luật là vậy! Nhưng lợi ích nhận được {#Emph}còn {#Prev}đáng giá hơn số tiền bỏ ra, ta bảo đảm!",
    "Hermes_0171": "Cô đoán cộng sự làm ăn của ta làm gì với đống xu đó? Anh ấy vẫn chẳng nói gì. Có khi đang xóa dấu vết để ông Chronos không lần ra được!",
    "Hermes_0275": "Cô nghĩ phải mất bao lâu mới tiêu hết đống Vàng Chronos đó? Thêm một {#Emph}kỷ nguyên {#Prev}nữa chăng? Không phải cô chậm đâu, chỉ là lão đúc quá nhiều xu trong thời gian ngắn!",
    "Melinoe_0957": "Ta rất mừng vì ngài ở đây, Hermes. Thật vinh dự khi cuối cùng được cùng ngài hợp tác. Chúc chúng ta chiến thắng thật nhanh!",
    "Hermes_0066": "Ồ, chào! Lâu lắm rồi ta mới nhận được lễ vật! Cảm ơn nhé, M, dù cô không cần phải tặng đâu. Nhưng ta có món này cho cô!",
    "Melinoe_0958": "Hermes, nếu có ai giúp ta chạy đua với Thời Gian thì đó là ngài. Xin hãy nhận món quà này, để cảm ơn dịch vụ nhanh chóng và đáng tin cậy của ngài.",
    "Hermes_0067": "M, cô tốt bụng quá, nhưng ta {#Emph}thật sự {#Prev}phải đi ngay. Ta vào thẳng phần Ân Huệ nhé?",
    "MelinoeField_2005": "Nếu không có tốc độ và lòng dũng cảm của ngài, Hermes, chúng ta đã chẳng có cơ hội chống lại kẻ thù. Ta không biết bao giờ mới đền đáp hết ơn này, nhưng sẽ cố gắng!",
    "Hermes_0091": "M, cô khách sáo quá. Ta không quen nhận tiền boa, mà chúng ta còn nhiều việc cấp bách phải lo, phải không? Dù sao ta thật lòng cảm kích.",
    "MelinoeField_2006": "Ta biết gần đây ngài vô cùng bận rộn. Xin cho ta tạm ngắt quãng công việc thường ngày để gửi ngài món quà nhỏ này. Không nhiều đâu, nhưng dưới đây thì đây là thứ tốt nhất chúng ta có.",
    "Hermes_0092": "Dạo này cô tìm đâu ra {#Emph}thời gian {#Prev}để làm vậy, ta chẳng biết nữa. Dù sao cũng cảm ơn cô đã nghĩ đến ta! Giờ vào việc thôi nhé? Ta còn khối chuyện phải {#Emph}làm!",
    "MelinoeField_3722": "Không có ngài thì chúng ta biết xoay xở ra sao, Hermes? Ngài đã giúp chúng ta chuẩn bị thật nhiều để vượt qua gian khó. Công sức của ngài đôi khi chẳng ai để ý, nhưng Hội Khuất Mặt thì có.",
    "Hermes_0168": "M, được làm việc với cô thật vui. Đây đúng là một trong những điều tươi sáng giữa tất cả chuyện này! Ta luôn ngẩng cao đầu, phải nhìn đường phía trước chứ. Cảm ơn cô đã khiến mọi việc dễ dàng hơn!",
    "MelinoeField_3723": "Kính tặng vị thần nhanh nhất, cũng là người bạn đồng hành lâu năm thân thiết nhất của ta. Ngài Hermes đã phụng sự cả Olympus lẫn Âm phủ, chứng kiến mọi chuyện. Gia đình chúng ta còn nhiều điều phải học từ ngài. Ta cũng vậy.",
    "Hermes_0169": "Ta đi đây đi đó suốt, từng đến nhiều nơi và gặp đủ hạng người. Nhưng cô biết không? Cô vẫn là tuyệt nhất, M, ta nói thật đấy. Cô không {#Emph}nhanh nhất{#Prev} đâu, đừng mơ ôm hết mọi thứ. Nhưng cô với ta? Cũng sát nút lắm!",
    "MelinoeField_4212": "Chuyến giao hàng đặc biệt dành cho ngài Hermes! Ngài đã giúp ta vô số lần và luôn khích lệ ta trên từng chặng đường. Nếu không có ngài, ta chẳng thể đi xa đến vậy trong thời gian ngắn như thế.",
    "Hermes_0256": "Chào! Rượu thần Ambrosia! Đúng thứ ta hằng mong muốn! Dạo này hiếm thấy món này, cả những bữa tiệc đi kèm nữa. Nhưng đà này chắc sắp có thêm đấy! Ý ta là {#Emph}tiệc tùng{#Prev}, mà bữa tiệc đó nên tổ chức để vinh danh cô.",
    "MelinoeField_4213": "Kính tặng Sứ giả đáng kính, cũng là người bạn quý mến của ta! Ngài không chỉ giữ cho mối liên kết giữa Âm phủ và Olympus không đứt gãy, mà còn làm điều đó thật nhanh chóng, lặng lẽ. Ngài gần như là một vị thần Âm phủ rồi!",
    "Hermes_0257": "M, lời đó có ý nghĩa với ta lắm, cảm ơn nhé. Ta thích làm mọi việc thật nhanh, nhưng điều ta thích {#Emph}hơn {#Prev}cả là làm thật tốt. Các vị thần không phải lúc nào cũng cần vất vả, nhưng cha cô thì luôn chăm chỉ, và cô cũng vậy. Ta mừng vì mình không đơn độc.",
    "MelinoeField_0643": "Trao quà nhanh gọn thế này thật tuyệt!",
}

source = TR.read_text(encoding="utf-8-sig")
mapped = {key: {"DisplayName": value} for key, value in translations.items()}
TR.write_text(apply_translation_to_sjson(source, mapped), encoding="utf-8")
sys.stdout.reconfigure(encoding="utf-8")
print(f"Đã bổ sung {len(translations)} câu Hermes.")
