"""Translate reviewed Hades II epilogue and credits strings."""
from pathlib import Path
import sys

ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(ROOT / "tools"))
from hades2_sjson_helper import apply_translation_to_sjson  # noqa: E402

SRC = ROOT / "working/0100A00019DE0000_Hades2/raw_text/en"
TR = ROOT / "translations/0100A00019DE0000_Hades2/Game/Text/en"

translations = {
    "_DeathLoopData.en.sjson": {
        "Melinoe_4475": {"DisplayName": "Mong rằng mọi chuyện rồi sẽ thành như vậy, Homer. Nhưng giờ nhiệm vụ đã hoàn tất, ta biết làm gì tiếp đây? Thôi... chắc ta có cả cõi vĩnh hằng để nghĩ ra câu trả lời."},
        "Melinoe_1164": {"DisplayName": "Ngẩng cao đầu, đừng để lộ điểm yếu..."},
        "Melinoe_2950": {"DisplayName": "{#Emph}A! {#Prev}Mọi người cứ tiếp tục đi. Ta ổn mà."},
        "Melinoe_2425": {"DisplayName": "Ồ, xin chào...!"},
        "Melinoe_2426": {"DisplayName": "Ta thật sự ổn mà!"},
        "Melinoe_2427": {"DisplayName": "Không cần lo cho ta đâu!"},
        "Melinoe_2428": {"DisplayName": "Thứ lỗi cho ta nhé, các Linh Hồn."},
        "Melinoe_2429": {"DisplayName": "Chúc mọi người buổi tối an lành...!"},
        "Melinoe_2430": {"DisplayName": "Cảm ơn mọi người đã đợi..."},
        "Melinoe_2431": {"DisplayName": "Vậy thì đi thôi...!"},
        "Melinoe_2432": {"DisplayName": "Để ta xem quanh đây nào."},
        "Melinoe_2820": {"DisplayName": "Giờ vạc đã sẵn sàng cho ta rồi..."},
        "Melinoe_1585": {"DisplayName": "Đó là... gì vậy?"},
        "Melinoe_4693": {"DisplayName": "Ngài Moros vừa ở đây..."},
        "Melinoe_2439": {"DisplayName": "Đây là những gì...?"},
        "Melinoe_1900": {"DisplayName": "Đi nào, Mel. Lối ra ở phía bên kia..."},
        "Storyteller_0234": {"DisplayName": "{#Emph}Ngã ba Địa Giới: chốn trú ẩn khuất giữa mặt đất và Âm phủ, nơi che chở những kẻ vẫn trung thành với ngài Hades, vị vua chính thống của cõi chết."},
        "Melinoe_2959": {"DisplayName": "Chúng ta sẽ cùng giành lại vương quốc của cha ta."},
        "Storyteller_0078": {"DisplayName": "{#Emph}Chiếc lều bài trí giản dị của Công chúa Melinoë dũng mãnh được sắp xếp ngăn nắp và giữ gìn sạch sẽ đến không tì vết."},
        "Melinoe_0032": {"DisplayName": "Ta không sống bừa bộn đâu."},
        "Storyteller_0121": {"DisplayName": "{#Emph}Nàng Công chúa Bóng Tối chỉ thổ lộ nỗi sợ sâu kín nhất với một chú lưỡng cư già điềm đạm, kẻ đã nhảy vào lều nàng từ lâu... rồi cả vào trái tim nàng."},
        "Melinoe_1684": {"DisplayName": "Chỉ có những nỗi sợ sâu thẳm nhất dành cho cậu thôi, Frinos!"},
        "Storyteller_0340": {"DisplayName": "{#Emph}Hiện thân của Giấc Ngủ say giấc triền miên trong khu rừng nhỏ riêng tư, thỉnh thoảng được Công chúa Âm phủ ghé thăm mỗi khi nàng cần thời gian suy ngẫm và lập kế hoạch."},
        "Melinoe_4070": {"DisplayName": "Hoặc chỉ để xem anh ấy thế nào."},
        "Storyteller_0502": {"DisplayName": "{#Emph}Sau khi vội vã rời Ngã ba Địa Giới, hiện thân của Giấc Ngủ vốn chìm trong cơn mê suốt một thời gian dài đã đem vài món đồ đến tỏ lòng biết ơn, và... có lẽ còn hơn thế nữa..."},
        "Melinoe_5435": {"DisplayName": "Ta đã chấm dứt những giấc mơ của anh ấy, và theo một cách nào đó, anh ấy cũng chấm dứt giấc mơ của ta."},
        "Storyteller_0341": {"DisplayName": "{#Emph}Gương mặt được tạc tinh xảo của vị vua Âm phủ bị phế truất khơi dậy trong lòng bất kỳ ai dám nhìn vào đôi mắt đá vô hồn ấy sự trầm tư lặng lẽ và ý chí kiên định."},
        "Melinoe_4071": {"DisplayName": "Xin cha dõi theo con..."},
        "Storyteller_0012": {"DisplayName": "{#Emph}Ngã ba Địa Giới che giấu kế hoạch và hành tung của nữ phù thủy gieo ác mộng cùng các đồng minh, nhưng liệu nơi này còn giữ được bí mật bao lâu?"},
        "Melinoe_0403": {"DisplayName": "Đủ lâu."},
        "Storyteller_0345": {"DisplayName": "{#Emph}Hiện thân Bất Hòa với đôi cánh đen bất kham muốn bay đến đâu tùy ý, nhưng gần đây nàng ta cứ chắn đường Công chúa Âm phủ."},
        "Melinoe_4075": {"DisplayName": "Cạn ly nhé, Eris..."},
        "Eris_0133": {"DisplayName": "{#Emph}Hả?"},
        "Storyteller_0080": {"DisplayName": "{#Emph}Di nguyện cuối cùng của Tam Nữ Thần Số Mệnh, những kẻ ẩn dật định đoạt mọi điều sẽ đến, giờ nằm trong tay Công chúa Âm phủ."},
        "Melinoe_1682": {"DisplayName": "Có họ giúp sức, chúng ta có thể còn cơ hội."},
        "Storyteller_0122": {"DisplayName": "{#Emph}Ngay cả mưu mẹo và kế sách của Odysseus, kẻ cướp thành tài ba, có lẽ cũng chưa đủ để khuất phục Titan Thời Gian..."},
        "Melinoe_1685": {"DisplayName": "Người ta bảo đừng bao giờ xem thường ông ấy..."},
        "Odysseus_0123": {"DisplayName": "{#Emph}Ha{#Prev}, thôi nào."},
        "Storyteller_0134": {"DisplayName": "{#Emph}Nữ thần Báo Ứng bất mãn đưa mắt phán xét tất cả những ai ở Ngã ba Địa Giới; nàng bảo vệ nơi này vừa vì bổn phận, vừa vì lòng cay cú."},
        "Melinoe_1687": {"DisplayName": "Tốt nhất đừng chọc giận Nem..."},
        "Nemesis_0120": {"DisplayName": "Sao cũng được."},
        "Storyteller_0135": {"DisplayName": "{#Emph}Hiện thân Vận Mệnh Diệt Vong bị muôn loài căm ghét và khiếp sợ luôn đi theo con đường Tam Nữ Thần Số Mệnh dệt nên; ngoài họ ra, chẳng ai đoán được lúc hắn xuất hiện."},
        "Melinoe_1688": {"DisplayName": "Anh ta biết cách xuất hiện thật ấn tượng..."},
        "Moros_0093": {"DisplayName": "Công chúa?"},
        "Storyteller_0136": {"DisplayName": "{#Emph}Một số Linh Hồn mãi lang thang vô định; số khác thậm chí chẳng còn ý chí, chỉ lặng lẽ nấn ná tại một chỗ."},
        "Melinoe_1689": {"DisplayName": "Dora đúng là nên ra ngoài thường xuyên hơn..."},
        "Dora_0118": {"DisplayName": "Mơ đi."},
        "Storyteller_0344": {"DisplayName": "{#Emph}Hecate, Phù thủy Ngã ba Địa Giới, có vô vàn trọng trách: người quan sát vô hình giữa các cõi, đồng thời giữ chìa khóa mở những lối đi mà ngay cả mắt thần bất tử cũng không thấy."},
        "Melinoe_4074": {"DisplayName": "Và là Hiệu trưởng của chúng ta."},
        "Storyteller_0346": {"DisplayName": "{#Emph}Những con vật trung thành phục vụ Phù thủy Ngã ba Địa Giới thường truyền cảm hứng cho các loài thú khác tìm đến nơi trú ẩn bình yên giữa các cõi này."},
        "Melinoe_4076": {"DisplayName": "Chúng ta còn nhiều điều phải học từ loài vật."},
        "Storyteller_0129": {"DisplayName": "{#Emph}Sau khi Chronos mưu mô chiếm lấy Điện Hades, các Linh Hồn cư ngụ nơi đó đều tản mác đến tận cùng thế giới."},
        "Melinoe_1679": {"DisplayName": "Các Linh Hồn đều được chào đón và an toàn ở đây."},
        "Storyteller_0238": {"DisplayName": "{#Emph}Lịch sử chứa nhiều bài học, miễn là ta chịu tìm hiểu điều ẩn sau những lời kể; đó cũng là công việc theo đuổi cả đời."},
        "Melinoe_2961": {"DisplayName": "Vẫn chưa ai biết tương lai sẽ ra sao..."},
        "Storyteller_0239": {"DisplayName": "{#Emph}Từng có một phòng hành chính ở Âm phủ, nơi các Linh Hồn cẩn thận ghi chép từng chi tiết; đến nay vẫn còn vài người theo đuổi nghề ấy."},
        "Melinoe_2962": {"DisplayName": "Chắc công sức ấy được trả công hậu hĩnh lắm."},
        "Storyteller_0301": {"DisplayName": "{#Emph}Món quà âm nhạc Apollo rạng ngời ban cho phàm nhân có thể khuấy động tâm hồn hơn bất cứ điều gì, dù tâm hồn ấy thuộc về người sống hay kẻ chết."},
        "Melinoe_3750": {"DisplayName": "Vậy thì khuấy động tâm hồn nào!"},
        "Storyteller_0342": {"DisplayName": "{#Emph}Ánh trăng thường rọi sáng nhất một góc yên bình của Ngã ba Địa Giới, nơi Công chúa Âm phủ có thể gạt bỏ ưu phiền và tìm chút bình yên."},
        "Melinoe_4072": {"DisplayName": "Và lắng nghe tiếng ếch kêu."},
        "Storyteller_0343": {"DisplayName": "{#Emph}Giọng ca vang vọng của nữ thần săn bắn lấp đầy khoảng đất trống như tia trăng, lay động những Linh Hồn vĩnh cửu đang cư ngụ nơi đây."},
        "Melinoe_4073": {"DisplayName": "Cô ấy hát cũng hay đấy chứ?"},
        "Storyteller_0130": {"DisplayName": "{#Emph}Hy vọng và niềm vui nơi Ngã ba Địa Giới thường chóng tàn, nhưng chút ít còn sót lại hay tụ về quán rượu nhỏ ở đó."},
        "Melinoe_1680": {"DisplayName": "Chẳng có thời gian nghỉ ngơi..."},
        "Storyteller_0241": {"DisplayName": "{#Emph}Nước mắt than khóc tuôn chảy trên sông Cocytus, nhưng ngay cả dòng nước tuyệt vọng ấy cũng có sinh vật học được cách sống và sinh sôi."},
        "Melinoe_2964": {"DisplayName": "Ta {#Emph}có {#Prev}cảm giác vài con trong số chúng muốn thoát ra..."},
        "Storyteller_0240": {"DisplayName": "{#Emph}Một suối nước nhỏ lấy hơi nóng từ sâu trong lòng đất; làn nước tinh khiết đến mức có thể gột rửa cả thể xác lẫn tâm hồn."},
        "Melinoe_2963": {"DisplayName": "Nếu xuống đó, có khi ta chẳng muốn lên nữa..."},
    },
    "InGameCredits.en.sjson": {
        "AboutScreen_Title": {"DisplayName": "Đội ngũ thực hiện"},
        "Credits_Heading_Supergiant": {"DisplayName": "Supergiant Games"},
        "Credits_Heading_AdditionalCredits": {"DisplayName": "Thông tin bổ sung"},
        "Credits_Heading_Contributors": {"DisplayName": "Đội ngũ đóng góp"},
        "Credits_Heading_VoiceCast": {"DisplayName": "Dàn diễn viên lồng tiếng"},
        "Credits_Heading_Translators": {"DisplayName": "Đội ngũ dịch thuật"},
        "Credits_Heading_MusicProduction": {"DisplayName": "Sản xuất âm nhạc"},
        "Credits_Heading_LanguageQA": {"DisplayName": "Kiểm định bản địa hóa"},
        "Credits_Title_CastingServices": {"DisplayName": "Dịch vụ tuyển chọn diễn viên"},
        "Credits_SubHeading_Proofreader": {"DisplayName": "Hiệu đính"},
        "Credits_Heading_Community": {"DisplayName": "Cộng đồng đóng góp"},
        "Credits_SubHeading_Discord": {"DisplayName": "Điều hành viên Discord"},
        "Credits_SubHeading_BetaTesters": {"DisplayName": "Người chơi thử bản beta"},
        "Credits_Heading_Acknowledgements": {"DisplayName": "Lời cảm ơn"},
        "Credits_Description_Acknowledgements": {"DisplayName": "( Sẽ bổ sung nội dung )"},
        "Credits_Heading_SupergiantSalutes": {"DisplayName": "Supergiant Games gửi lời tri ân"},
        "Credits_SubHeading_ScyllaBand": {"DisplayName": "Ban nhạc Scylla & the Sirens {#InlineCreditTitle}Ca sĩ"},
        "EndCredits_SubHeading_ScyllaBand": {"DisplayName": "Ban nhạc Scylla & the Sirens {#EndCreditsInlineCreditTitle}Ca sĩ"},
        "Credits_SubHead_Choir": {"DisplayName": "Dàn hợp xướng London Voices"},
        "Credits_Heading_SpecialThanks": {"DisplayName": "Đặc biệt cảm ơn"},
        "Credits_Heading_VerySpecialThanks": {"DisplayName": "Vô cùng cảm ơn"},
        "Credits_Heading_Other": {"DisplayName": "Và những đóng góp khác"},
        "Credits_Title_Design": {"DisplayName": "Thiết kế"},
        "Credits_Title_EngineeringDesign": {"DisplayName": "Kỹ thuật & Thiết kế"},
        "Credits_Title_WritingDesign": {"DisplayName": "Biên kịch & Thiết kế"},
        "Credits_Title_DesignWriting": {"DisplayName": "Thiết kế & Biên kịch"},
        "Credits_Title_Engineering": {"DisplayName": "Kỹ thuật"},
        "Credits_Title_MusicSound": {"DisplayName": "Âm nhạc & Âm thanh"},
        "Credits_Title_MusicAudio": {"DisplayName": "Âm nhạc & Thu âm"},
        "Credits_Title_Art": {"DisplayName": "Mỹ thuật"},
        "Credits_Title_VO": {"DisplayName": "Lồng tiếng"},
        "Credits_Title_UIVFX": {"DisplayName": "Hiệu ứng hình ảnh & Hoạt ảnh giao diện"},
        "Credits_Title_Ops": {"DisplayName": "Vận hành"},
        "Credits_Title_EnvironmentArt": {"DisplayName": "Mỹ thuật môi trường"},
        "Credits_Title_OfficeSupport": {"DisplayName": "Văn phòng & Hỗ trợ"},
        "Credits_Title_Publishing": {"DisplayName": "Phát hành"},
        "Credits_Title_DesignQA": {"DisplayName": "Kiểm định thiết kế"},
        "Credits_Title_QA": {"DisplayName": "Kiểm định chất lượng"},
        "Credits_Title_ProductionQA": {"DisplayName": "Kiểm định sản xuất"},
        "Credits_Title_3DModeling": {"DisplayName": "{$CreditsData.NumericTokens.Three}D Modeling"},
        "Credits_Title_Animation": {"DisplayName": "Hoạt ảnh"},
        "Credits_Title_Finance": {"DisplayName": "Tài chính"},
        "Credits_Title_TechArt": {"DisplayName": "Mỹ thuật kỹ thuật"},
        "Credits_Title_PlatformsQA": {"DisplayName": "Kiểm định các nền tảng"},
        "Credits_Title_AdtlOfficeSupport": {"DisplayName": "Hỗ trợ văn phòng bổ sung"},
        "Credits_Title_AdtlMusicVocals": {"DisplayName": "Ca sĩ bổ sung"},
        "Credits_Title_AdtlSetDressing": {"DisplayName": "Trang trí bối cảnh bổ sung"},
        "Credits_Title_AdtlMapBeautification": {"DisplayName": "Tô điểm bản đồ bổ sung"},
        "Credits_Title_AdtlAnimation": {"DisplayName": "Hoạt ảnh bổ sung"},
        "Credits_Title_AdtlModeling": {"DisplayName": "Tạo mô hình {$CreditsData.NumericTokens.Three}D bổ sung"},
        "Credits_Title_AdtlUIArt": {"DisplayName": "Mỹ thuật giao diện bổ sung"},
        "Credits_Title_AdtlQA": {"DisplayName": "Kiểm định chất lượng bổ sung"},
        "Credits_Title_AdtlRigging": {"DisplayName": "Gắn khung xương {$CreditsData.NumericTokens.Three}D bổ sung"},
        "Credits_Title_AdtlConceptArt": {"DisplayName": "Mỹ thuật ý tưởng bổ sung"},
        "Credits_Title_AdtlSoundEditing": {"DisplayName": "Biên tập âm thanh bổ sung"},
        "Credits_Title_AdtlVFXConcepts": {"DisplayName": "Ý tưởng hiệu ứng hình ảnh bổ sung"},
        "Credits_Title_AnimatedTrailers": {"DisplayName": "Trailer hoạt họa"},
        "Credits_Title_AdtlVideoProduction": {"DisplayName": "Sản xuất video bổ sung"},
        "Credits_Title_AdtlMarketingArt": {"DisplayName": "Mỹ thuật tiếp thị bổ sung"},
        "Credits_Title_AdtlUIAnimation": {"DisplayName": "Hoạt ảnh giao diện bổ sung"},
        "Credits_Title_Illustration": {"DisplayName": "Minh họa"},
        "Credits_Title_Flute": {"DisplayName": "Sáo"},
        "Credits_Title_FluteSoloist": {"DisplayName": "Độc tấu sáo - {#InlineCreditH3}The Necropolis"},
        "EndCredits_Title_FluteSoloist": {"DisplayName": "Độc tấu sáo - {#EndCreditsInlineCreditH3}The Necropolis"},
        "Credits_Title_FluteSoloist_B": {"DisplayName": "Độc tấu sáo - {#InlineCreditH3}Winged Apprentice"},
        "EndCredits_Title_FluteSoloist_B": {"DisplayName": "Độc tấu sáo - {#EndCreditsInlineCreditH3}Winged Apprentice"},
        "Credits_Title_SaxophoneSoloist": {"DisplayName": "Độc tấu saxophone - {#InlineCreditH3}Sightless Shepherd"},
        "EndCredits_Title_SaxophoneSoloist": {"DisplayName": "Độc tấu saxophone - {#EndCreditsInlineCreditH3}Sightless Shepherd"},
        "Credits_Title_SaxophoneSoloist_B": {"DisplayName": "Độc tấu saxophone - {#InlineCreditH3}Lap of Luxury"},
        "EndCredits_Title_SaxophoneSoloist_B": {"DisplayName": "Độc tấu saxophone - {#EndCreditsInlineCreditH3}Lap of Luxury"},
        "Credits_Title_GuitarSoloist": {"DisplayName": "Độc tấu guitar - {#InlineCreditH3}Reflection Affection"},
        "EndCredits_Title_GuitarSoloist": {"DisplayName": "Độc tấu guitar - {#EndCreditsInlineCreditH3}Reflection Affection"},
        "Credits_Title_DrumSoloist": {"DisplayName": "Độc tấu trống - {#InlineCreditH3}The End of Time"},
        "EndCredits_Title_DrumSoloist": {"DisplayName": "Độc tấu trống - {#EndCreditsInlineCreditH3}The End of Time"},
        "Credits_Title_GuitarSoloists": {"DisplayName": "Các nghệ sĩ guitar - {#InlineCreditH3}The Unseen Ones"},
        "Credits_Title_Vocalist_ArtemisSong": {"DisplayName": "Ca sĩ - {#InlineCreditH3}Moonlight Guide You"},
        "EndCredits_Title_Vocalist_ArtemisSong": {"DisplayName": "Ca sĩ - {#EndCreditsInlineCreditH3}Moonlight Guide You"},
        "Credits_Title_Vocalist_ApolloSong": {"DisplayName": "Ca sĩ - {#InlineCreditH3}Fated Glory"},
        "EndCredits_Title_Vocalist_ApolloSong": {"DisplayName": "Ca sĩ - {#EndCreditsInlineCreditH3}Fated Glory"},
        "Credits_Title_Vocalist_EndTheme": {"DisplayName": "Ca sĩ - {#InlineCreditH3}Time Belongs to Us"},
        "EndCredits_Title_Vocalist_EndTheme": {"DisplayName": "Ca sĩ - {#EndCreditsInlineCreditH3}Time Belongs to Us"},
        "Credits_Title_Conductor": {"DisplayName": "Nhạc trưởng & Đồng sáng tác"},
        "Credits_Title_Harp": {"DisplayName": "Đàn hạc"},
        "Credits_Title_Percussion": {"DisplayName": "Nhạc cụ gõ"},
        "Credits_Title_FlutePiccolo": {"DisplayName": "Sáo / Sáo piccolo"},
        "Credits_Title_Oboe": {"DisplayName": "Kèn oboe"},
        "Credits_Title_OboeCorAnglais": {"DisplayName": "Kèn oboe / Kèn cor anglais"},
        "Credits_Title_Clarinet": {"DisplayName": "Kèn clarinet"},
        "Credits_Title_ClarinetBassClarinet": {"DisplayName": "Kèn clarinet / Clarinet trầm"},
        "Credits_Title_PrincipalViolin": {"DisplayName": "Violin chính"},
        "Credits_Title_Violin": {"DisplayName": "Đàn violin"},
        "Credits_Title_PrincipalViola": {"DisplayName": "Viola chính"},
        "Credits_Title_Viola": {"DisplayName": "Đàn viola"},
        "Credits_Title_PrincipalCello": {"DisplayName": "Cello chính"},
        "Credits_Title_Cello": {"DisplayName": "Đàn cello"},
        "Credits_Title_PrincipalDoubleBass": {"DisplayName": "Contrabass chính"},
        "Credits_Title_DoubleBass": {"DisplayName": "Đàn contrabass"},
        "Credits_Title_Bassoon": {"DisplayName": "Kèn bassoon"},
        "Credits_Title_BassoonContrabassoon": {"DisplayName": "Kèn bassoon / Contrabassoon"},
        "Credits_Title_FrenchHorn": {"DisplayName": "Kèn cor Pháp"},
        "Credits_Title_3DModeling": {"DisplayName": "Tạo mô hình {$CreditsData.NumericTokens.Three}D"},
        "Credits_Title_TenorTromboneBassTrombone": {"DisplayName": "Kèn trombone tenor / Kèn trombone bass"},
        "Credits_Title_OrchestraLeader": {"DisplayName": "Trưởng dàn nhạc / Violin chính"},
        "Credits_Title_AdditionalMusicEditing": {"DisplayName": "Biên tập âm nhạc bổ sung"},
        "Credits_Title_AssistantRecordingEngineer": {"DisplayName": "Trợ lý kỹ sư thu âm"},
        "Credits_Title_MidiTranscription": {"DisplayName": "Chuyển soạn MIDI / Chuẩn bị phối khí"},
        "Credits_Title_OrchestralSessionAssistant": {"DisplayName": "Trợ lý buổi thu âm dàn nhạc"},
        "Credits_CastTitle_DarrenChars": {"DisplayName": "Schelemeus, Narcissus, Zagreus & các vai lồng tiếng khác"},
        "Credits_CastTitle_DarrenCharsAlt": {"DisplayName": "Schelemeus & các vai lồng tiếng khác"},
        "Credits_CastTitle_GregChars": {"DisplayName": "Hypnos & các vai lồng tiếng khác"},
        "Credits_Name_026_B": {"DisplayName": "Ashley Barrett {#InlineCreditTitle}- Roxy"},
        "EndCredits_Name_026_B": {"DisplayName": "Ashley Barrett {#EndCreditsInlineCreditTitle}- Roxy"},
        "Credits_Name_042_B": {"DisplayName": "Judy Alice Lee {#InlineCreditTitle}- Jetty"},
        "EndCredits_Name_042_B": {"DisplayName": "Judy Alice Lee {#EndCreditsInlineCreditTitle}- Jetty"},
        "Credits_Name_044_B": {"DisplayName": "Erin Yvette {#InlineCreditTitle}- Scylla"},
        "EndCredits_Name_044_B": {"DisplayName": "Erin Yvette {#EndCreditsInlineCreditTitle}- Scylla"},
        "Credits_Name_065": {"DisplayName": "Tina Carter {#InlineCreditTitle}- Nhà sản xuất"},
        "EndCredits_Name_065": {"DisplayName": "Tina Carter {#EndCreditsInlineCreditTitle}- Nhà sản xuất"},
        "Credits_Name_083_B": {"DisplayName": "Beatriz Esteban Agustí {#InlineCreditTitle}- Hiệu đính"},
        "EndCredits_Name_083_B": {"DisplayName": "Beatriz Esteban Agustí {#EndCreditsInlineCreditTitle}- Hiệu đính"},
        "Credits_Name_095": {"DisplayName": "Nina Sinigaglia {#InlineCreditTitle}- Dịch thuật bổ sung"},
        "EndCredits_Name_095": {"DisplayName": "Nina Sinigaglia {#EndCreditsInlineCreditTitle}- Dịch thuật bổ sung"},
        "Credits_Name_109": {"DisplayName": "Keiko Fukuichi {#InlineCreditTitle}- Biên dịch"},
        "EndCredits_Name_109": {"DisplayName": "Keiko Fukuichi {#EndCreditsInlineCreditTitle}- Biên dịch"},
        "Credits_Legal_01": {"DisplayName": "© Supergiant Games, LLC 2025. Bảo lưu mọi quyền."},
        "Credits_Legal_02B": {"DisplayName": "Hades II © Supergiant Games, LLC {$CreditsData.NumericTokens.TwentyTwentyFive}. Bảo lưu mọi quyền."},
        "Credits_Legal_03": {"DisplayName": "Hades là nhãn hiệu đã đăng ký của Supergiant Games, LLC."},
        "Credits_Legal_04": {"DisplayName": "Mọi mã nguồn, mỹ thuật, âm nhạc, lồng tiếng và thiết kế trò chơi © Supergiant Games."},
        "Credits_License_01": {"DisplayName": "Sử dụng FMOD Studio, © Firelight Technologies {$CreditsData.NumericTokens.NineteenNinetyFour}-{$CreditsData.NumericTokens.TwentyTwentyFive}"},
        "Credits_License_02": {"DisplayName": "Sử dụng Bink Video, © {$CreditsData.NumericTokens.NineteenNinetySeven}-{$CreditsData.NumericTokens.TwentyTwentyFive} của Epic Games Tools LLC"},
        "Credits_AbbeyRoad": {"DisplayName": "Dàn nhạc & hợp xướng được thu âm tại Abbey Road Studios, Phòng thu 1"},
        "Credits_Message_AIDisclosure_01": {"DisplayName": "Trò chơi này được con người tạo ra một cách có chủ đích."},
        "Credits_Message_AIDisclosure_02": {"DisplayName": "Không sử dụng AI tạo sinh để tạo ra"},
        "Credits_Message_AIDisclosure_03": {"DisplayName": "hình ảnh, giọng lồng tiếng hay bất kỳ nội dung nào khác."},
        "Credits_Message_Thanks_EarlyAccessPlayers": {"DisplayName": "Cộng đồng người chơi Truy cập sớm"},
        "Credits_Message_Thanks_DiscordMods": {"DisplayName": "Các điều hành viên Discord"},
        "Credits_Message_Thanks_BetaPlayers": {"DisplayName": "Cộng đồng chơi thử bản beta"},
        "Credits_Message_Thanks_FriendsFamily": {"DisplayName": "Những người thân yêu luôn hết lòng ủng hộ chúng tôi"},
        "Credits_Message_Thanks_HadesDevTeam": {"DisplayName": "Tất cả những người đã tạo nên phần {#Prev}{#InlineCreditName}Hades {#Prev}đầu tiên"},
        "EndCredits_Message_Thanks_HadesDevTeam": {"DisplayName": "Tất cả những người đã tạo nên phần {#Prev}{#EndCreditsInlineCreditName}Hades {#Prev}đầu tiên"},
        "Credits_Message_Thanks_Gods": {"DisplayName": "Các vị thần và anh hùng thần thoại đã truyền cảm hứng cho chúng tôi"},
        "Credits_Message_Thanks_Time": {"DisplayName": "Chronos, vì khoảng thời gian chúng ta có"},
        "Credits_Message_Thanks_Closing": {"DisplayName": "hãy bước đi trong thầm lặng, và mong ánh trăng soi đường cho bạn"},
    },
}

for filename, entries in translations.items():
    source = (SRC / filename).read_text(encoding="utf-8-sig")
    target = TR / filename
    target.parent.mkdir(parents=True, exist_ok=True)
    target.write_text(apply_translation_to_sjson(source, entries), encoding="utf-8")
    sys.stdout.reconfigure(encoding="utf-8")
    print(f"{filename}: {len(entries)} trường đã dịch")
