# -*- coding: utf-8 -*-

translations_200_300 = {
  "Hogwarts_PotionsClassroom_SharpOfficeNote_desc": "Một bức thư ghi nhớ của Bộ Pháp Thuật gửi tới Borgin và Burkes.",
  "Imperio": "Lời Nguyền Độc Đoán (Imperio)",
  "Imperio_desc": "Tạm thời ép buộc kẻ địch chiến đấu vì bạn như một đồng minh. Những kẻ địch khác sẽ gây ít sát thương hơn lên mục tiêu bị bạn kiểm soát, giúp kẻ đó \"trung thành\" với bạn lâu hơn. Ngoài ra còn khiến nạn nhân bị nguyền rủa và chịu thêm sát thương.",
  "Imperio_gameplay_desc": "Tạm thời ép buộc kẻ địch chiến đấu vì bạn như một đồng minh. Những kẻ địch khác sẽ gây ít sát thương hơn lên mục tiêu bị bạn kiểm soát, giúp kẻ đó \"trung thành\" với bạn lâu hơn. Ngoài ra còn khiến nạn nhân bị nguyền rủa và chịu thêm sát thương.",
  "Incendio": "Bùa Lửa (Incendio)",
  "Incendio_desc": "Tầm thi triển ngắn đòi hỏi phải tiếp cận ở cự ly gần với mục tiêu. Bùa chú này gây ra lượng lớn sát thương và có thể thiêu đốt các vật thể nhất định. Kẻ địch bị đánh trúng bởi đòn tấn công hệ lửa sẽ liên tục nhận sát thương trong vài giây, nếu chịu va đập mạnh trong khoảng thời gian này sẽ kích hoạt bùng nổ ngọn lửa.",
  "Incendio_gameplay_desc": "Tầm thi triển ngắn đòi hỏi phải tiếp cận ở cự ly gần với mục tiêu. Bùa chú này gây ra lượng lớn sát thương và có thể thiêu đốt các vật thể nhất định. Kẻ địch bị đánh trúng bởi đòn tấn công hệ lửa sẽ liên tục nhận sát thương trong vài giây, nếu chịu va đập mạnh trong khoảng thời gian này sẽ kích hoạt bùng nổ ngọn lửa.",
  "InputAction_AM_Protego": "{AM_Protego}",
  "InputAction_AM_Revelio": "{AM_Revelio}",
  "InputAction_AM_SpellButton1": "{AM_SpellButton1}",
  "InputAction_AM_SpellButton2": "{AM_SpellButton2}",
  "InputAction_AM_SpellButton3": "{AM_SpellButton3}",
  "InputAction_AM_SpellButton4": "{AM_SpellButton4}",
  "InputAction_AM_Stupefy": "{AM_Stupefy}",
  "InputAction_CastBottomSpell": "{CastBottomSpell}",
  "InputAction_CastLeftSpell": "{CastLeftSpell}",
  "InputAction_CastRightSpell": "{CastRightSpell}",
  "InputAction_CastTopSpell": "{CastTopSpell}",
  "InputAction_Protego": "{Protego}",
  "InputAction_RevelioButton": "{RevelioButton}",
  "InputAction_SpellButton_Bottom": "{SpellButton_Bottom}",
  "InputAction_SpellButton_Left": "{SpellButton_Left}",
  "InputAction_SpellButton_Right": "{SpellButton_Right}",
  "InputAction_SpellButton_Top": "{SpellButton_Top}",
  "InputAction_SpellModifierButton": "{SpellModifierButton}",
  "InputAction_Stupefy": "{Stupefy}",
  "InputAction_UMGAccioActivityRules": "{UMGAccioActivityRules}",
  "InputAction_UMGSpellMinigameOption1": "{UMGSPellMinigameOption1}",
  "InputAction_UMGSpellMinigameOption2": "{UMGSPellMinigameOption2}",
  "InputAction_UMGSpellMinigameOption3": "{UMGSPellMinigameOption3}",
  "InputAction_UMGSpellMinigameOption4": "{UMGSPellMinigameOption4}",
  "InputAction_UMGStartSpellMiniGame": "{UMGStartSpellMiniGame}",
  "InputAction_UMGViewSpellVideo": "{UMGViewSpellVideo}",
  "INT_01_CP2_Intro_CastRevelio_TaskObj02d": "Thi triển \"Bùa Hiện Hình (Revelio)\"",
  "INT_01_ProtegoCast_TaskObj": "Dùng \"Bùa Khiên Che Chắn (Protego)\" {Protego} chống đỡ các đòn tấn công đang ập tới ({0}/{1})",
  "INT_01_StupefyCast_TaskObj": "Giữ \"Bùa Khiên Che Chắn (Protego)\" {Protego} để phát động \"Bùa Choáng Váng (Stupefy)\" phản công kẻ địch ({0}/{1})",
  "INT_CentralTower_PotionsCupboard": "Đã mở khóa Tủ Chứa của Bậc Thầy Độc Dược",
  "INT_Pippins_PotionBook": "Đã mở khóa Sách Độc Dược",
  "InvisibilityPotion": "Thuốc Tàng Hình",
  "InvisibilityPotion_Buff": "Cường Hóa Thuốc Tàng Hình",
  "InvisibilityPotion_Buff_desc": "Bạn đang tàng hình",
  "InvisibilityPotion_Desc": "Sau khi uống sẽ tàng hình và ngay lập tức khiến kẻ địch không thể nhìn thấy bạn, sau đó người uống sẽ duy trì trạng thái không bị phát hiện trong suốt thời gian thuốc phát huy tác dụng.",
  "Legend_AssignSpellNB": "Gán Bùa Chú",
  "Legend_BrewPotion": "Pha Chế Độc Dược",
  "Legend_DestroyPotion": "Hủy Bỏ Độc Dược",
  "Legend_DragSlotSpell": "Kéo và đặt bùa chú vào ô",
  "Legend_ViewSpellNB": "Xem Bùa Chú",
  "Levioso": "Bùa Bay Lơ Lửng (Levioso)",
  "Levioso_desc": "Khiến đồ vật và kẻ địch bay lơ lửng. Thích hợp dùng để giải đố hoặc bất ngờ lật ngược tình thế trong chiến đấu.",
  "Levioso_gameplay_desc": "Khiến đồ vật và kẻ địch bay lơ lửng. Thích hợp dùng để giải đố hoặc bất ngờ lật ngược tình thế trong chiến đấu.",
  "LoadingScreen_Spells1": "Rất nhiều đồ vật trong môi trường có thể bị điều khiển bằng bùa chú. Khi đối mặt với thử thách hay câu đố hóc búa, hãy vận dụng sâu sắc tất cả những gì bạn đã học để tìm ra cách giải quyết.",
  "LoadingScreen_Spells2": "{RevelioButton} \"Bùa Hiện Hình (Revelio)\" sẽ làm nổi bật rõ ràng kẻ địch, các yếu tố tương tác, rương báu ở gần đó và thậm chí cả xuyên qua các bức tường. \"Bùa Hiện Hình (Revelio)\" còn có thể báo hiệu vị trí của các trang Cẩm Nang Phù Thủy ở xung quanh.",
  "LoadingScreen_Spells3": "Có thể gán bốn bùa chú vào một bộ bùa chú của bạn, và có thể dùng điểm tài năng để mua thêm ba bộ bùa chú bổ sung.",
  "Lumos": "Bùa Phát Sáng (Lumos)",
  "Lumos_Desc": "Giúp chiếu sáng các khu vực tăm tối, hoặc cung cấp thêm ánh sáng cho các câu đố đặc thù.",
  "Lumos_gameplay_desc": "Giúp chiếu sáng các khu vực tăm tối, hoặc cung cấp thêm ánh sáng cho các câu đố đặc thù.",
  "Map_HW_SUB_PotionsClassroom_F1": "Tầng 1",
  "Map_HW_SUB_PotionsClassroom_F2": "Tầng 2",
  "Map_HW_SUB_PotionsClassroom_F3": "Tầng 3",
  "Menu_AccessibilityCastSpell": "Thi Triển Bùa Chú",
  "Menu_AccessibilityRevelioBell": "Có đồ vật ẩn giấu gần đây",
  "Menu_CancelPotion": "Dừng Độc Dược",
  "Menu_CancelPotion_desc": "Bỏ độc dược hiện tại để làm trống bàn chế",
  "Menu_DarkArtsSpells": "Bùa Chú Nghệ Thuật Hắc Ám",
  "Menu_Error_NoPotions": "Không có độc dược khả dụng trong kho",
  "Menu_Error_PotionAlreadyApplied": "Đã sử dụng độc dược rồi",
  "Menu_Error_PotionNoEffect": "Độc dược này không có hiệu lực.",
  "Menu_MagicSpells": "Danh Sách Bùa Chú",
  "Menu_NewSpellUnlocked": "Bùa Chú Mới Đã Mở Khóa",
  "Menu_NoSpellRequirements": "Không Cần Bùa Chú",
  "Menu_Nurturing_SecretIngredient_ChangePotion": "Đổi độc dược thành {potion}",
  "Menu_PassiveSpells": "Cơ Bản",
  "Menu_Potion_Station": "Bàn Chế Độc Dược",
  "Menu_Potions": "Độc Dược",
  "Menu_Potions_AddSecretIngredient": "Thêm Vào Độc Dược",
  "Menu_Potions_desc": "Học nghệ thuật tinh tế về pha chế độc dược, phối trộn dược liệu và nâng cao kỹ năng điều chế của bạn. Lớp học Độc Dược sẽ giúp bất kỳ học sinh nào hiện thực hóa hoài bão trở thành Bậc Thầy Độc Dược.",
  "Menu_Potions_Effect_FailedCombination": "Hiệu Ứng: Pha chế thất bại",
  "Menu_Potions_Effect_FasterBrewing": "Hiệu Ứng: Tăng tốc pha chế",
  "Menu_Potions_Effect_IncreasedYield": "Hiệu Ứng: Tăng sản lượng",
  "Menu_Potions_RequiredFuel": "Chất Đốt Cần Thiết",
  "Menu_PotionSteps": "Các Bước Pha Chế",
  "Menu_PotionSteps_desc": "Các bước và hướng dẫn pha chế độc dược",
  "Menu_RequiredSpells": "Bùa Chú Yêu Cầu",
  "Menu_SelectPotion": "Chọn Độc Dược",
  "Menu_ShowSpellElements": "Hiển Thị Giao Diện Bùa Chú",
  "Menu_ShowSpellElements_desc": "Bật hoặc ẩn giao diện thi triển bùa chú",
  "Menu_SpellsTalents": "Bùa Chú",
  "Menu_SpellsTalents_desc": "Những tài năng này giúp tăng cường khả năng thi triển bùa chú của bạn",
  "Menu_StartPotion": "Bắt Đầu Pha Chế Độc Dược",
  "Menu_StartPotion_desc": "Thêm nguyên liệu và bắt đầu quá trình pha chế độc dược",
  "Menu_ToggleSpellCastMode": "Chuyển Đổi Chế Độ Thi Triển Bùa Chú",
  "Menu_ToggleSpellCastMode_desc": "Một số bùa chú có thể sử dụng cơ chế điều khiển chuyển đổi. Bật cài đặt này để kích hoạt hoặc tắt để vô hiệu hóa.",
  "MRT_01_01_Learn_Incendio_Task": "Học \"Bùa Lửa (Incendio)\"",
  "NTR_03_ABirdInTheHand_QuestAvailable_LearnGlacius_Task1": "Học \"Bùa Đóng Băng (Glacius)\" từ Giáo sư Kogawa",
  "PIM_CastAccio": "Thi triển \"Bùa Triệu Tập (Accio)\"",
  "PIM_CastLevioso": "Thi triển \"Bùa Bay Lơ Lửng (Levioso)\"",
  "Potion": "Độc Dược",
  "Potion_CreatureBreedingHexed": "Hương Liệu Thú Nuôi Bị Nguyền Rủa",
  "Potion_CreatureBreedingHexed_desc": "Chất bốc mùi hôi thối có thể kích thích thú nuôi sinh sản, mang lại hậu duệ bị ếm bùa",
  "Potion_CreatureBreedingNormal": "Xạ Hương Thú Nuôi"
}

if __name__ == '__main__':
    print(f"Loaded {len(translations_200_300)} keys.")
