"""Translate all 248 strings of Hestia in Hades II."""
from pathlib import Path
import sys

ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(ROOT / "tools"))
from hades2_sjson_helper import apply_translation_to_sjson

SRC = ROOT / "games/0100A00019DE0000_Hades2/source/raw_text/en/_LootData_Hestia.en.sjson"
OUT = ROOT / "games/0100A00019DE0000_Hades2/translations/Game/Text/en/_LootData_Hestia.en.sjson"

translations = {
    # Intro / Cues
    "Melinoe_0644": "Ấn ký ngọn lửa...",
    "Melinoe_1478": "Là Bà cô...",
    "Melinoe_1479": "Hestia...",
    "Melinoe_0645": "Con cứ ngỡ nữ thần lửa không bao giờ nhúng tay vào thế sự chứ? {#Emph}Nhân danh Hades! Hỡi Olympus, con xin tiếp nhận thông điệp này!",
    "Hestia_0002": "Chà, nhìn cháu kìa, nhóc con bốc lửa! Lặn lội tới đây giúp đỡ người già neo đơn, {#Emph}chao ôi {#Prev}cháu quả là một cô bé ngoan. Ấy thế mà ban nãy ta suýt chút nữa tự tay thiêu rụi cả cái chốn chết tiệt này ra tro đấy! Nào, đây là chút {#Emph}khởi động nhẹ {#Prev}cho cháu...",

    # Duos / Banters
    "Hestia_0145": "Thuở xưa ta chưa từng nghĩ chàng trai trẻ vạm vỡ Zeus ở đây lại thuộc tuýp người thích lập gia đình, và ta chẳng mấy vui vẻ khi cậu ta chọn trúng đứa em gái Hera tội nghiệp của ta! Nhưng cậu đã luôn là một người chồng mẫu mực với con bé, đúng không hả Zeus?",
    "Zeus_0164": "...Đôi khi ta thấy tiếc cho nàng đấy, Hestia, vì chưa từng được tự mình nếm trải niềm hạnh phúc của đời sống hôn nhân. Thử thách luôn nảy sinh trong bất kỳ mối quan hệ nào như thế, nhưng cùng với người bạn đời yêu dấu, chúng ta luôn tìm ra lối đi! Tất cả những gì cần làm chỉ là thỏa hiệp và đồng lòng cộng tác.",
    "Hestia_0147": "Ta vốn chẳng mấy mặn mà với việc nhà, dẫu ta luôn có ngoại lệ dành riêng cho cô em gái út. Con bé là người phải chịu đựng nhiều ấm ức nhất trên đỉnh núi này, chưa thèm tính đến cái mớ rắc rối của Chronos đâu nhé. Em xoay xở thế nào được vậy, {#Emph}hỡi Nữ hoàng?",
    "Hera_0106": "Chị hỏi ta xoay xở thế nào ư, cứ cắn răng chịu đựng từng đêm một thôi, chị gái! Biết đâu chúng ta sẽ phải thiêu rụi cái thế giới cũ kỹ này thành tro tàn để bắt đầu lại từ đầu, cơ mà... ta không nghĩ ra ai {#Emph}phù hợp hơn {#Prev}chị nếu chuyện đó xảy ra.",
    "Hestia_0149": "Cứ nhận lấy ân huệ nhưng {#Emph}chớ có {#Prev}học theo tấm gương của bọn ta làm gì, nhóc con à. Một ví dụ điển hình chính là gã Poseidon mặt cá ở đằng kia! Lúc nào cũng thích làm trò gây náo loạn, {#Emph}chẳng bao giờ {#Prev}thèm bận tâm xem ai sẽ bị vấy bẩn ướt sũng. Đúng thế không hả, cái gã đần thô lỗ kia?",
    "Poseidon_0274": "Hoàn toàn ngược lại là đằng khác, Hestia thân mến! Ta nghĩ nàng đã lầm to ở ít nhất hai điểm: Thứ nhất, ta chẳng bao giờ phải {#Emph}cố sức {#Prev}để tạo nên làn sóng lớn cả! Ta làm điều đó nhẹ tênh như không mỗi lần ra tay. Và thứ hai, đừng có gọi ta là {#Emph}mặt cá{#Prev}, đồ mụ già nhăn nheo héo úa, {#Emph}ha-ha!",
    "Hestia_0151": "Được rồi, nhóc con, thổi bùng lên một ngọn lửa thực thụ nào! Không hơi đâu mà loanh quanh nghịch mấy tia lửa cỏn con nữa. Này, {#Emph}Apollo? {#Prev}Nhấc cái mông tròn trịa của cậu lại đây ngay, ta đang cần mồi thêm chút lửa sáng này!",
    "Apollo_0096": "{#Emph}Dạ{#Prev}, có mặt ngay thưa Phu nhân Hestia đáng kính! Cơ mà, xin người làm ơn cẩn thận kẻo lại thiêu rụi nửa đỉnh núi thêm lần nữa...",
    "Hestia_0153": "Cháu có tin nổi không, nhóc con bốc lửa? Ta nghe ngóng từ nguồn tin cực kỳ uy tín rằng có {#Emph}kẻ nào đó {#Prev}trên này dám tự xưng là {#Emph}Bậc Trưởng Bối của Olympus. {#Prev}Này, Demeter? Có muốn giải thích một chút về chuyện {#Emph}đó {#Prev}không hả?",
    "Demeter_0110": "Hestia, chính chị đã {#Emph}ruồng bỏ {#Prev}chúng ta! Trở thành một vị thần Olympus không chỉ là đặc quyền huyết thống, mà còn là một {#Emph}lời thề; {#Prev}với cả gia tộc này lẫn đỉnh núi linh thiêng. Hãy khôi phục lại vị thế chính đáng của chị, và cùng ta tương trợ cho đứa cháu gái ngoan!",
    "Hestia_0155": "Nhanh cái chân lên nào, nhóc con bốc lửa! Tranh thủ lúc cháu vẫn còn giữ được nhan sắc mơn mởn! Chứ không như ả Aphrodite ở đây sẽ chẳng để cháu giữ được nó mãi đâu. Ả ta cực kỳ ghét bị cạnh tranh nhan sắc đấy, cứ tin lời ta đi.",
    "Aphrodite_0147": "Hestia ngọt ngào ơi, người nói {#Emph}vậy {#Prev}nghĩa là sao chứ? Con sẽ là người đầu tiên công nhận nhan sắc đâu phải là {#Emph}tất cả. {#Prev}Ai thèm cần tới nó cơ chứ? Nhưng mặt khác, chúng ta thật có phúc khi có được một người dồi dào trí tuệ và kinh nghiệm từng trải như {#Emph}người {#Prev}đứng về phía mình!",
    "Hestia_0157": "Nếu có một điều ta đúc kết được từ đứa cháu trai lực lưỡng ở đây, nhóc con ạ, thì đó là người ta luôn phải rèn sắt khi còn đang nóng đỏ. Giờ thì {#Emph}nhanh {#Prev}cái tay lên, {#Emph}bắt tay {#Prev}vào việc đi nào, Hephaestus chàng trai trẻ!",
    "Hephaestus_0134": "Con đang làm đây, con đang làm đây, Phu nhân, {#Emph}trời ạ! {#Prev}Cơ mà nếu người cứ tiếp tục tăng nhiệt độ lên thế này, thì toàn bộ cái {#Emph}lò rèn {#Prev}này sẽ nổ tung mất, và hốt trọn cả phần còn lại của ngọn núi đi tong theo {#Emph}luôn đấy! {#Prev}Thế rồi phù thủy nhỏ sẽ còn gì để mà chiến đấu nữa?",
    "Hestia_0204": "Chúng ta bắt lũ phàm nhân tội nghiệp phải nếm trải quá nhiều cay đắng, phần lớn là nhờ ơn Ares ở đây. Ít nhất dạo này hắn bận rộn với mớ rắc rối của chính chúng ta để đổi gió, đúng không nhóc con? Nhờ thế mà hầu hết mọi người dưới trần mới có dịp thở phào nhẹ nhõm.",
    "Ares_0161": "Nhưng thưa Phu nhân Hestia yêu dấu, những tai ương của chúng ta là mối bận tâm sống còn vượt xa khỏi cõi phàm trần! Cuộc chiến của chúng ta thuộc về tầng thứ tối cao, và nó lôi cuốn mỗi chúng ta dấn thân góp phần không thể cưỡng lại.",

    # Low health / Hurt
    "Hestia_0071": "Ôi chao, nhóc con, trông cháu {#Emph}thê thảm {#Prev}quá, chuyện gì đã xảy ra với cháu thế kia? Thôi thì để ta xông hơi cho cháu toát mồ hôi giải tỏa bớt. Giá như ta có thể dùng lửa hàn gắn lại vết thương cho cháu!",
    "Hestia_0072": "{#Emph}Chậc chậc, ái chà{#Prev}, cháu bị nhiều hơn một hai vết xước rồi đấy đúng không? {#Emph}Trời ạ{#Prev}, cuộc đời là thế! Cắn răng chịu đựng rồi xông pha tiếp, đó là cách duy nhất để ta vươn tới chốn tốt đẹp hơn.",
    "Hestia_0166": "{#Emph}Ồ{#Prev}, nhìn qua là ta biết cháu đã trải qua {#Emph}biết bao gian truân! {#Prev}Nếu cháu thấy mình đang rơi vào tình cảnh khốn cùng, cứ việc đạp bằng nó mà tiến bước! Hoặc thiêu rụi thành bình địa mọi thứ xung quanh nếu bắt buộc phải thế.",
    "Hestia_0167": "Ôi nhóc con, nếu cháu cứ bầm dập từ đầu tới chân như thế này, thì làm sao cháu đủ sức bước vào giai đoạn tiếp theo của trận đọ lửa nhỏ này chứ! Mau trấn tĩnh lấy lại phong độ xem nào, {#Emph}hả?",

    # Run start / early greetings
    "Hestia_0077": "Úi chà chào cháu, nhóc con, đang chuẩn bị cho chuyến viễn chinh tiếp theo đấy à? Hiện tại cháu chỉ như một đốm than hồng le lói thôi, vậy sao chúng ta không thổi bùng ngọn lửa rực cháy bên trong cháu lên nhỉ?",
    "Hestia_0117": "Này đừng có dại dột lang thang vào bóng tối mà không mang theo nguồn sáng tử tế nhé! Và ta không có ý nói thứ ánh sáng màu mè Apollo ban phát đâu, dẫu có khi ta tạm chấp nhận Ánh Trăng cũng được. Cơ mà thôi kệ, cầm lấy {#Emph}này!",
    "Hestia_0118": "Tưởng có thể lén lút chuồn ra khỏi đó lúc đêm muộn mà qua mắt được ta sao? Bình thường thì được đấy, nhưng lần này thì đừng hòng! Và hình phạt dành cho cháu là một tuyển tập Ân huệ sưởi ấm tâm can hảo hạng!",
    "Hestia_0119": "Chắc cháu sống ở xó xỉnh nào đó quanh vùng này đúng không, nhóc con? Chà, vì xem chừng đêm nay ngoài trời hơi bị buốt giá, sao chúng ta không làm vài {#Emph}điều chỉnh nhiệt độ {#Prev}ở đây nhỉ...",
    "Hestia_0120": "Sao, lại hướng thẳng lên phía này nữa đấy à? Ta chẳng phản đối câu nào đâu! Cơ mà nghĩ lại thì ta cũng không chắc cháu có nghe thấy tiếng ta nói dưới đó không nữa. Dù sao thì, hãy cùng nhau {#Emph}làm nóng người lên nào!",

    # Core lore & philosophy
    "Hestia_0033": "Cứ mỗi ngọn nến cháu thắp lên, mỗi chiếc vạc cháu đun sôi, đó chính là ngọn lửa của {#Emph}ta {#Prev}đang làm phép thuật của riêng nó vì cháu đấy, nhóc con! Thế nên cứ mỗi lần tia lửa bùng lên là nhớ tới ta đấy nhé.",
    "Hestia_0034": "Điểm thú vị về ngọn lửa, nhóc con ạ, là nó vừa ấm áp lại vừa rực rỡ tuyệt mỹ, đúng không? Nhưng nó có thể liếm sạch mạng sống của cháu chỉ trong tích tắc. Thực sự khiến người ta phải suy ngẫm! Và thực sự biến cháu thành tro than giòn rụm nếu lơ là bất cẩn...",
    "Hestia_0103": "Đoán xem nào, nhóc con bốc lửa, Bà cô của cháu lại quay trở lại để biến quân thù thành muội than đây! Cách tốt nhất để bọn chúng không bao giờ dám bén mảng quấy rầy cháu nữa, dẫu công đoạn dọn dẹp đống tro tàn hơi bị phiền toái đôi chút...",
    "Hestia_0035": "{#Emph}Hừ{#Prev}, cái đỉnh núi này. Ta từng từ bỏ ngai vàng ở đây rồi đấy, cháu biết không. Ta muốn chu du ngắm nhìn thế gian, chứ không phải ngày nào cũng giáp mặt mấy đứa chị em chết tiệt! Thế mà giờ ta lại kẹt cứng ở đây với cả lũ bọn họ. Nghĩ tới thôi là đã sôi cả máu!",
    "Hestia_0052": "Cháu quen sống trong bóng tối rồi đúng không? Trên này, bóng tối là thứ ai nấy đều khiếp sợ. Ngay cả trong ánh lửa ấm áp của ta, họ vẫn giật mình thon thót trước những bóng đen, phàm nhân lẫn thần thánh đôi khi cũng thế! Ta nghĩ họ quá tin vào đôi mắt phàm trần yếu ớt của mình.",
    "Hestia_0044": "Cứ lủi thủi một mình suốt ngần ấy thời gian đúng không? Chà, có khi thế lại hay hơn. Ước gì ta chưa từng biết mặt cha mẹ {#Emph}chết tiệt {#Prev}của ta! Họ chẳng dạy cho ta được điều gì mà ta không thể tự mình học hỏi tốt hơn.",
    "Hestia_0259": "Ngọn lửa nơi bếp sưởi của ngọn núi này bắt đầu chập chờn le lói sau khi Typhon quyết định trồi lên. Kể từ đó nó đã lại bùng cháy rực rỡ và nóng bỏng, nhưng ta vẫn luôn chăm chút cẩn thận, phòng hờ thôi.",
    "Hestia_0253": "Có thấy họ dựng tượng ta trên này rồi không, nhóc con? Trước đây đâu có, cơ mà đám còn lại, họ cứ cố lôi kéo ta quay về chốn này, tỏ vẻ tôn kính ta, ôi ý tưởng hay ho gớm! Cơ mà ta chẳng ham nhìn thấy cái bản mặt già nua của mình suốt ngày đâu!",
    "Hestia_0261": "Sao cháu không sống trong Gia môn Hades cùng với cha mẹ mình? Ắt hẳn sâu dưới lòng đất phải ấm cúng và dễ chịu lắm. Cơ mà, một Ngôi nhà chưa chắc đã là một Tổ ấm. Biết đâu cháu lại thích những cánh rừng của mình hơn...",
    "Hestia_0045": "Biết vấn đề lớn nhất của gia đình này là gì không, nhóc con? Quá đông đúc! Mấy kẻ khác cứ làm như thể thương hại ta lắm, {#Emph}Hestia tội nghiệp không chồng không con{#Prev}, bọn họ bảo thế! Nhưng chính bọn họ mới là những kẻ khao khát những ngày tháng son rỗi, ta nhìn thấu trong mắt họ hết.",
    "Hestia_0046": "Ta thấy tội nghiệp cho cháu đấy, nhóc con, bị cuốn phăng vào mớ bòng bong của chúng ta! Cháu không biết ta đã phải trầy trật né tránh nó thế nào đâu. Cớ sao lúc nào chúng ta cũng bị ép phải chọn một phe chết tiệt nào đó chứ? Nhưng thần thánh bọn ta, ai nấy đều khoái đánh nhau...",
    "Hestia_0248": "Ta đoán bọn ta có thể nhờ cậy tới cháu, nhóc con, chẳng có gì bất ngờ. Nhưng, ta không ngờ bọn ta lại {#Emph}quý mến {#Prev}cháu đến thế, ý ta là cháu còn trẻ, lại mang phong tục tập quán khác biệt này nọ. Bọn ta vốn cực kỳ khó chung sống! Thế mà cháu lại {#Emph}làm được {#Prev}điều đó!",
    "Hestia_0164": "Titan với thần thánh, ta vẫn chịu không phân biệt nổi rốt cuộc có cái quái gì khác nhau giữa hai bên! Nhìn chẳng khác mấy, nói năng cũng y chang. Chẳng phải chuyện tuổi tác, điều {#Emph}đó {#Prev}ta xin lấy uy tín ra bảo đảm! Chẳng qua chỉ là một cái nhãn dán tiện lợi để chỉ mặt kẻ thù thôi.",
    "Hestia_0038": "{#Emph}Ồ{#Prev}, thời hoàng kim ta cũng là một nhân vật lẫy lừng đấy chứ. Bao nhiêu kẻ theo đuổi tán tỉnh. {#Emph}Xời! {#Prev}Ta từng là tay thiện xạ bách phát bách trúng với Khẩu Pháo Kim Cương. Cháu nghe về nó chưa? Thứ vũ khí quái vật, ta vứt bỏ nó rồi. Từ bỏ luôn cả chiến tranh! Cho đến tận bây giờ, xem ra là thế!",
    "Hestia_0042": "{#Emph}Aha{#Prev}, nhiệt huyết thanh xuân! Ta đã cháy rụi chỉ còn than hồng âm ỉ, chẳng còn là bữa tiệc no mắt cho ai ngắm nhìn nữa. Không sao cả. Còn {#Emph}cháu? {#Prev}Vẫn chỉ là một cành củi bén. Nhưng bọn ta sẽ biến cháu thành một trận cuồng phong hỏa hoạn cho xem!",
    "Hestia_0041": "Vậy ra cháu là một phù thủy nhỏ hả? Ta thì chịu! Kẹt cứng với cái gia đình {#Emph}này {#Prev}đã đủ mệt rồi, ta chẳng hiểu sao mình lại muốn có thêm một hội đồng phù thủy nữa. Nhưng ta hiểu sức hút của nó. Rất nhiều nến và lửa bập bùng trong đó, đúng không?",
    "Hestia_0053": "Đáng lẽ chúng ta phải đối xử tử tế hơn với lũ người phàm, thật lòng là thế. Khi đó Chronos sẽ khó lòng ép buộc linh hồn người chết trỗi dậy chống lại chúng ta hơn! Ta luôn cố gắng chăm lo cho người sống. Cơ mà gia đình chúng ta vốn nổi tiếng nhất về khoản chỉ biết lo cho bản thân mình.",
    "Hestia_0054": "Người phàm từng dâng lên bọn ta biết bao lễ vật, thậm chí nhịn cả phần ăn của họ. Họ luôn tán dương ta đầu tiên trong số các vị thần, bởi chính ngọn lửa của ta là thứ họ dùng khi làm lễ tế. Dễ thương làm sao!",
    "Hestia_0238": "Mấy kẻ khác không đồng tình với ta về chuyện này đâu, nhóc con, cơ mà cháu còn trẻ, có lẽ dễ tiếp thu hơn, nên là... {#Emph}ta {#Prev}nghĩ người phàm xứng đáng nhận được từ chúng ta nhiều hơn những gì chúng ta ban phát. Nếu Số Mệnh bảo điều đó sẽ xảy ra trong tương lai, thì tốt quá!",
    "Hestia_0105": "Mụ Hecate già là sư phụ của cháu đấy hả? Ta biết bà ta từ hồi chắc cũng trạc tuổi {#Emph}cháu {#Prev}bây giờ, một quý bà đàng hoàng chuẩn mực! Nghĩ lại thì đã quá lâu rồi bọn ta chưa giáp mặt nhau. {#Emph}Haizz{#Prev}, biết sao được? Bà ta ghét tất cả mọi người, ta cũng ghét tất cả mọi người.",

    # Underworld & Surface
    "Hestia_0047": "Chà, nhìn cháu kìa, nhóc con bốc lửa, rốt cuộc cháu cũng mò lên được mặt đất rồi đấy hả! Ta đoán thể nào cháu cũng lên được mà. Trên này có khi còn rét buốt hơn cả dưới kia, nhưng chuyện {#Emph}đó{#Prev}, ít nhất chúng ta có thể khắc phục ngay tức khắc!",
    "Hestia_0048": "Người phàm chuyển từ tôn thờ ngọn lửa sang sợ hãi nó. Cũng phải thôi! Ngọn lửa nơi bếp sưởi của mọi mái nhà trong cái thành phố tàn tạ cháu đang trú ngụ, tất cả đều đã tắt ngấm. Không phải ta giận dỗi gì đâu nhé, ồ không hề.",
    "Hestia_0036": "Tội nghiệp con bé, bị giam hãm suốt bao lâu trong cõi Âm ti u tối đó đúng không? Có cả một thế giới bao la rộng lớn ngoài kia để ngắm nhìn một khi cháu xong việc. Cứ bảo ta nhé, ta có thể gợi ý vài địa điểm tuyệt mỹ không xa nơi này đâu!",
    "Hestia_0196": "Thành phố Ephyra chìm trong biển lửa, nhưng không hoàn toàn là lỗi của ta đâu nhé! Lửa cũng như một công cụ vậy... một trong những thứ đòi hỏi sự cẩn trọng từ phía người dùng. Lỡ làm mất thứ gì trong đám cháy á, xin lỗi nhé! Ta chịu không giúp được!",
    "Hestia_0107": "Lẽ ra cháu không được phép lên đây đúng không? Ít nhất là cha cháu chẳng bao giờ được phép quay lại mặt đất. Nhưng cháu là phù thủy mà, chắc hẳn cháu có thuốc chữa cho mọi thứ trên đời này rồi!",
    "Hestia_0108": "Đừng để bọn ta cứ liên tục xoay cháu như chong chóng thế chứ, được không? Mới đầu thì sai cháu đi săn lùng Chronos, giờ lại bắt cháu chạy lên đây phòng thủ, {#Emph}chết tiệt! {#Prev}Dù lỡ như chưa ai nói ra, thì bọn ta {#Emph}thực sự {#Prev}vô cùng biết ơn sự giúp đỡ của cháu.",
    "Hestia_0049": "Cháu đang ở cái xó xỉnh chết tiệt nào {#Emph}dưới {#Prev}đáy sâu thế hả, nhóc con, dưới đáy biển đấy ư?! Khó mà nhóm được ngọn lửa bùng cháy khi tứ bề toàn là nước, nhưng nếu cháu chịu được áp lực dưới đó, ta có thể mang lại nhiệt lượng hừng hực!",
    "Hestia_0111": "Cháu từng xuống sâu tới tận Cánh đồng Bi ai rồi cơ à? Một nơi kinh tởm tồi tàn, nghe đồn là thế, phủ đầy cỏ khô rơm rạ ngút tầm mắt. Lần tới có tới đó, nhớ dùng lửa mở đường mà đi nhé! Nghe rõ chưa, nhóc con bốc lửa?",
    "Hestia_0195": "Bữa nào ta rất muốn được chiêm ngưỡng Sông Phlegethon nơi Âm giới của các người! Một dòng sông cuộn trào toàn là {#Emph}lửa... {#Prev}ta từng thử làm thứ gì đó tương tự bên phía chúng ta, nhưng nó làm lũ người phàm hoảng loạn phát khiếp, và thần thánh cũng chẳng mấy ai ưa...",
    "Hestia_0223": "Cháu thậm chí còn chưa được dẫn đi tham quan Cung điện một vòng nữa, Hera bảo thế. {#Emph}Chao ôi{#Prev}, nhóc con, giá mà ta có thể ở đó dẫn cháu đi chơi thay vì cứ phải trông coi mấy ngọn lửa này. Cơ mà nghĩ lại thì, ngắm một cây cột đá hoa lệ là coi như biết hết toàn bộ rồi.",

    # Bosses & Events
    "Hestia_0221": "Ta vẫn nhớ như in cảm giác khi thế hệ trẻ chúng ta cho Chronos biết tay ngày xưa! Giờ đây {#Emph}cháu {#Prev}lại là thế hệ trẻ, nhóc con ạ, đang phải đối mặt với đúng những rắc rối cũ rích và tồi tệ hơn. Vài điều chẳng bao giờ chịu đổi thay!",
    "Hestia_0222": "Cháu với mụ Hecate già ắt hẳn đang tìm cách ngăn không cho tên Chronos hồi phục lại, nếu không thì cháu đâu có rảnh rỗi đuổi theo lão mãi thế này! Đã tìm ra chút manh mối nào ấm dần lên chưa?",
    "Hestia_0113": "Họ đồn rằng cháu vừa tặng cho lão một món quà thay mặt tất cả chúng ta! Chronos ấy mà. Một trận đòn nhừ tử {#Emph}ra trò {#Prev}theo kiểu truyền thống! Cảm giác ấm áp và hả hê lắm đúng không? Khiến người ta cứ muốn làm lại điều đó {#Emph}hết lần này đến lần khác!",
    "Hestia_0114": "Cháu tóm được tên Titan chết tiệt đó rồi hả? Đừng buồn vì chưa thể tiễn lão đi đời vĩnh viễn, đám còn lại của bọn ta cũng có làm nổi đâu như cháu thấy đấy. Thay vào đó, sao không thừa thắng xông lên đạp cho lão vài phát khi lão đang {#Emph}ngã ngựa! {#Prev}Ta rất sẵn lòng trợ lực khoản {#Emph}đó!",
    "Hestia_0229": "Bọn ta đã đày Chronos tới một công việc nhàn hạ nơi Quần đảo Phước Lành, tốt cho lão quá còn gì. Nhưng cháu vẫn đang hợp tác với lão để chiến đấu ngăn không cho lão trỗi dậy nắm quyền, {#Emph}hả? {#Prev}Thôi thì ta nghĩ ta cũng hiểu được phần nào!",
    "Hestia_0194": "Cháu đã giúp bọn ta {#Emph}nện {#Prev}cho con quái vật chết tiệt đó {#Emph}một trận ra trò! Chao ôi{#Prev}, giá mà ta được tận mắt chứng kiến! Cháu quả thực phi thường lắm, nhóc con bốc lửa! Dĩ nhiên bạn hiền Typhon của chúng ta đã lại bắt đầu lồm cồm bò lên rồi. Chúng ta sẽ phải làm cho chặng đường của hắn thêm muôn phần trắc trở...",
    "Hestia_0115": "Cảm ơn cháu đã giúp thanh lọc bầu không khí trên này nhé! Mua cho bọn ta một chút thời gian quý giá để hồi phục và tập hợp lại lực lượng. Giờ thì ai nấy đều bừng bừng khí thế phá tan vòng vây! {#Emph}Trời ạ{#Prev}, nghe ta nói này! Toàn mùi chiến tranh chém giết hệt như cái lũ còn lại...",
    "Hestia_0227": "Để xem ta có hiểu đúng không nhé: Dẫu cháu đã giúp bọn ta tống khứ Typhon đi, giờ cháu lại phải đi săn lùng phần tàn dư còn sót lại của hắn, ở một nơi nào đó ngoài cái thế giới chết tiệt này? {#Emph}Ôi {#Prev}cháu chẳng bao giờ có lấy một phút {#Emph}thảnh thơi{#Prev}, nhóc con bốc lửa à! Nhưng ta luôn đứng sau lưng cháu.",
    "Hestia_0255": "Tuyệt vời lắm, nhóc con, cho cả Chronos xấu xa lẫn Typhon ăn trọn đòn đúp ngoạn mục! Giờ cháu làm mấy trò này trông nhẹ tênh như không. Hay là bữa nào ta cũng nên tự mình thử một phen nhỉ?",
    "Hestia_0055": "Cháu kiếm được chút Tro Tàn Cinder rồi đúng không? Không phải thứ vật chất hào nhoáng lấp lánh, nhưng nó cứng cáp, nguồn mồi lửa tuyệt hảo! Hầu hết thần thánh và người phàm chỉ ham hố mấy món đồ trang sức lấp lánh thôi. Nhưng vài phù thủy các cháu quả thực rất am tường đấy!",
    "Hestia_0199": "Cháu tích trữ cả đống Tro Tàn Cinder trên người đúng không? Nhiều đến mức ta ngửi thấy mùi từ tận nơi đây... loại đặc biệt từ những ngọn đuốc mà ta quá quen thuộc. Tàn tích sau những trận tỉ thí với Hecate đấy à? Chắc hai người không đánh nhau thật đâu nhỉ. Hẳn chỉ là bài tập thể dục ban đêm thôi!",
    "Hestia_0112": "Mấy kẻ khác, mỗi người một phách, họ khoái được người phàm biến thành nhân vật chính trong thơ ca nhạc họa lắm. Ta thì {#Emph}không! {#Prev}Về khoản này ta thấy các vị thần Âm giới các người xử sự đúng đắn nhất. Tốt nhất là chuyện nhà ai người nấy biết, đóng cửa bảo nhau!",
    "Hestia_0109": "Thứ cháu đang cầm là gì thế kia, Ygnium phải không? Làm ta nhớ tới đôi đuốc mà mụ Hecate già lúc nào cũng lăm lăm bên mình. Nếu chúng giống với đôi đuốc ấy, thì chúng sẽ chẳng bao giờ lụi tàn đâu. Nhưng để chắc ăn, chúng ta sẽ giữ cho chúng luôn đỏ lửa hừng hực!",
    "Hestia_0165": "Có chuyện gì xảy ra với Ngọn Lửa của cháu thế? Giờ tỏa sáng rạng ngời gần như ánh rạng đông. Biết đâu nàng Eos ngón tay hồng hào đã quyết định góp một tay! Dẫu bọn ta cực kỳ ngại ngần làm phiền lịch trình duy nhất trong ngày của nàng ấy...",
    "Hestia_0250": "Chà nhìn những ngọn lửa tinh xảo cháu đang có kìa, tóe tia lửa ra khắp nơi không tài nào kiểm soát nổi! Mối nguy hỏa hoạn đấy nhé, nhóc con. Hồi xưa khi ta bắn lửa vào quân thù, đâu có tự động hóa như thế này. Lũ trẻ các cháu bây giờ sướng {#Emph}thật đấy {#Prev}nhé!",
    "Hestia_0254": "Thứ vũ khí kỳ quặc cháu đang dùng để làm mọi thứ nổ tung lên kìa! Ngày xưa khi ta còn cầm Khẩu Pháo Kim Cương người ta cũng nhìn ta bằng ánh mắt kỳ dị y như thế, cơ mà nó khiến chúng phải ngoảnh mặt đi trong tích tắc.",
    "Hestia_0076": "Bọn ta vẫn đang tự lực cánh sinh trên này chống lại Chronos và quân đoàn của lão, nhưng có điều gì đó bất thường đang diễn ra, ta ngửi thấy mùi rồi. Dù tên Titan toan tính trò gì đi nữa, ta ngờ rằng thứ đó đều có thể {#Emph}bị thiêu rụi...",
    "Hestia_0190": "Bọn ta chưa rõ Chronos đang toan tính nấu nướng món gì cho bọn ta, nhưng ai nấy đều nghĩ mấy trận xô xát nhỏ lẻ gần sườn núi vừa qua chưa phải đòn đánh chủ lực của lão. Ta chẳng hào hứng gì việc tìm hiểu đâu.",
    "Hestia_0102": "Ban nãy ta bỗng cảm thấy một thôi thúc kỳ lạ muốn đi tìm cháu, nhóc con ạ! Cứ như thể không phải do chính ta quyết định vậy! Cháu đang nghịch ngợm với mấy thế lực hắc ám cổ xưa hay gì đấy à? Thôi thì nếu cháu muốn nhìn sâu vào vực thẳm lạnh lẽo, ta sẽ giữ cho cháu luôn ấm áp dễ chịu.",
    "Hestia_0188": "Chẳng biết làm sao đêm nay cháu đi được xa và nhanh đến thế, nhóc con bốc lửa, nhưng cháu sẽ chẳng đi thêm được bước nào nữa đâu nếu chưa chuẩn bị kỹ càng. Cháu phải mang theo thật nhiều {#Emph}hơi ấm hừng hực {#Prev}tới nơi cháu sắp đến đấy!",
    "Hestia_0039": "{#Emph}Aha{#Prev}, ta thích một cô bé biết thắt lưng buộc bụng, sẵn sàng xắn tay áo vấy bẩn làm việc. Quá nhiều kẻ chỉ ngồi chờ người khác dọn dẹp đống rác rưởi của mình, bực cả mình. Nhân tiện nhắc tới, sao cháu không đi {#Emph}thổi bay {#Prev}vài tên giùm ta nhỉ, hả?",
    "Hestia_0074": "Bọn ta đã tỏa sáng rực rỡ trên đỉnh Olympus suốt không biết bao nhiêu kỷ nguyên rồi, nhóc con. Phải chăng thời đại của chúng ta đã đến lúc tàn lụi? Biết đâu chúng ta cũng giống lũ người phàm hơn là chúng ta dám thừa nhận. Thôi thì, bất kể kiếp nạn nào đang chờ phía trước, ta xin đón nhận hết!",
    "Hestia_0075": "Cháu đúng là một đứa kỳ lạ thật đấy, nhóc con bốc lửa. Lúc đầu ta cứ ngỡ cháu hơi bị kênh kiệu, giống y như vài kẻ khác mà ta biết quá rõ mặt. Nhưng cháu thực sự dốc lòng sửa chữa những sai lầm từ trước thời đại của mình đúng không?",
    "Hestia_0239": "Ta biết cháu đang ngập đầu giải quyết chuyện của Chronos nhưng ta muốn nói rằng, ta rất trân trọng nỗ lực của cháu khi cố gắng biến ngôi nhà dưới kia trở nên ấm cúng hơn. Cứ làm cho mọi thứ ấm áp lên là lão bà Hestia này nhận ra ngay!",
    "Hestia_0240": "Ta chưa từng xuống nơi cháu sống nhưng ta có thể cảm nhận được khi một ai đó tạo dựng được một mái ấm hạnh phúc, theo cách họ có thể. Trang hoàng, thêm thắt chút điểm nhấn tạo cảm giác chào đón, thế mới là nhà chứ! Không phải ai cũng hiểu được điều đó đâu nhưng {#Emph}cháu {#Prev}thì hiểu.",
    "Hestia_0057": "Ngay cả ta cũng phải thừa nhận tiếng nổ lách tách êm dịu của bếp sưởi không phải lúc nào cũng giải quyết được vấn đề. Đôi khi, thứ chúng ta cần là một trận đại hỏa hoạn kinh thiên động địa, một biển lửa ở đẳng cấp tối cao! Làm một trận nhé?",
    "Hestia_0058": "Bếp lửa nằm ở vị trí trung tâm trong mái nhà của phàm nhân, nhóc con ạ, giữ cho ngọn lửa của ta luôn an phận êm đềm. Nhưng ta có thể tạo ra một trận cháy rừng hung bạo chỉ trong một {#Emph}cái búng tay! {#Prev}Và mỗi khi nổi giận, đó {#Emph}chính xác {#Prev}là những gì ta làm.",
    "Hestia_0037": "Cha cháu và ta hòa hợp với nhau khá tốt, xét một cách tương đối, ta nghĩ thế. Dẫu vậy sau khi bọn ta dạy cho lũ Titan một bài học thích đáng, ngài ấy lui về Âm giới, còn ta thì trôi dạt khắp chốn, như tàn lửa bay ra từ đám cháy...",
    "Hestia_0110": "Cha cháu và ta có nhiều điểm tương đồng lắm, ta đoán thế. Hai kẻ {#Emph}về mặt danh nghĩa không phải thần Olympus! {#Prev}Ít nhất ta còn được ghé thăm bất cứ khi nào ta muốn, trong khi Hades tội nghiệp, ngay khi phải gánh vác cõi Âm ti, bọn họ chẳng bao giờ thèm xem ngài ấy là người cùng hội cùng thuyền nữa!",
    "Hestia_0234": "Ta thực sự nhẹ cả người khi biết cha cháu vẫn bình an vô sự. Ngài ấy cùng mẹ cháu, anh trai cháu, và tất cả mọi người trong Gia môn ấy. Cầu cho tất cả bọn họ luôn được ấm áp và quây quần bên nhau.",
    "Hestia_0236": "Mọi chuyện chẳng mấy suôn sẻ theo ý chúng ta, nhóc con à. Nhất là nếu những gì ta nghe ngóng về Tam Nữ Thần Số Mệnh là thật. Dù bọn ta có nên nắm quyền hay không, thì chính họ là người đã đặt bọn ta vào vị trí này... thế mà giờ họ bốc hơi như một làn khói mỏng ư?",
    "Hestia_0043": "Cháu nên được chứng kiến cảnh tượng đó, nhóc con, cái ngày bọn ta quật ngã lão già Chronos! Phải tốn ít nhất sáu người bọn ta, nhưng bọn ta đã tóm được lão! Hèn chi đến tận bây giờ lão vẫn còn hậm hực căm hờn. Lần này chúng ta sẽ phải thanh trừng lão triệt để hơn nữa! {#Emph}Hỏa táng {#Prev}chẳng hạn?",
    "Hestia_0192": "Nhân dịp Typhon quay trở lại, ta muốn nói rằng {#Emph}rất hân hạnh được biết cháu, nhóc con à! {#Prev}Không phải bọn ta chịu đầu hàng mà không đánh trả đâu, chỉ là phòng hờ thôi. Hồi xưa bọn ta đã phải trầy vi tróc vảy mới thắng được hắn khi thanh trừng Chronos thuở nào! Thế mà giờ hắn còn lớn hơn trước, rất {#Emph}nhiều!",
    "Hestia_0193": "Ta chẳng hiểu nổi làm sao bọn ta có thể kìm hãm Typhon không biến toàn bộ đỉnh núi này thành tro bụi nữa. Chắc là nhờ sấm sét, ngọn lửa, lũ lụt cùng động đất này nọ gộp lại! Nếu cháu có cao kiến gì sáng láng, cứ việc phi thẳng lên đây!",
    "Hestia_0224": "Con quái vật chết tiệt đó bị hạ đo ván rồi ư? Ý ta là đo ván vĩnh viễn luôn ấy, tới mức bọn ta chẳng tìm thấy một mẩu vụn nào của hắn {#Emph}nữa! {#Prev}Người ta bảo chính cháu đã biến Typhon thành {#Emph}tro bụi{#Prev}, nhóc con ạ! Đáng sợ thật sự đấy...",
    "Hestia_0187": "Hóa ra chính Artemis đã đánh hơi thấy cháu đấy hả? Nghe có vẻ như một sự trùng hợp quá đỗi vĩ đại, cơ mà bọn ta là thần thánh mà, mấy chuyện này xảy ra như cơm bữa! Phải công nhận ta mừng vì con bé đã tìm thấy cháu kịp lúc.",
    "Hestia_0197": "À khi ở trên này nhớ để mắt tới Heracles nhé, một gã đàn ông to con vạm vỡ? Một trong những chiến binh cừ khôi nhất chúng ta có nhưng thỉnh thoảng cứ tạo cảm giác như hắn đang chán ghét công việc của mình. Làm sao có thể như thế được chứ, ta chịu không hiểu nổi!",
    "Hestia_0258": "Ta vừa trò chuyện với Hera, phải gọi là {#Emph}Nữ hoàng Hera {#Prev}mới đúng, về chuyện có lẽ tất cả chúng ta nên nới lỏng bớt cho Heracles sau toàn bộ biến cố này. Hắn nên đặt cây gậy to xác đó xuống và ngồi nghỉ ngơi thật lâu!",
    "Hestia_0198": "Nghe đồn cháu vừa đụng độ Polyphemus hả! Ta vẫn nhớ như in cách hắn bị mất con mắt. Cứ cho là {#Emph}ngọn lửa {#Prev}đã đóng một vai trò tối quan trọng đi và dừng lại ở đó nhé. Suýt chút nữa thì ta thương hại thằng nhóc, cơ mà hắn vẫn sống khỏe chán. Và đang cản đường cháu nữa...",
    "Hestia_0073": "Cháu có một cuộc chạm trán tồi tệ với ả Eris đáng ghét trên đường tới đây đúng không, hả? Thật là {#Emph}tuyệt cú mèo{#Prev}, khi biết rằng chính Nữ thần Bất Hòa đang chống lại chúng ta lúc này! Lại còn thò móng vuốt bẩn thỉu vào Khẩu Pháo Kim Cương của ta nữa chứ... Đáng lẽ ta nên giữ nó lại.",
    "Hestia_0116": "Nghe nói cháu vừa vặt lông ả Eris đê tiện rơi khỏi bầu trời hả! Đáng đời ả lắm! Dẫu bọn ta chưa bao giờ đuổi ả đi được mãi mãi. Thật không ngờ ả lại là một trong số những đứa con của {#Emph}Nyx! {#Prev}Đẻ sòn sòn cả bầy con như thế, thể nào cũng lòi ra một đứa dị tật tật nguyền.",
    "Hestia_0247": "Ả Eris đó cứ liên tục ngáng đường cháu, ngay cả khi chính Chronos đã chịu rút lui và Typhon đã chết này nọ ư? Chà, ả ta cũng ngoan cố lì lợm ngang ngửa {#Emph}chúng ta{#Prev}, ta bắt đầu thấy ấn tượng rồi đấy!",
    "Hestia_0162": "Vậy là tên Titan Tiên Tri đã bẻ gãy xiềng xích và đang chống lại chúng ta lúc này! Thật đáng tiếc. Bất hòa với bọn ta kể từ ngày bị bắt quả tang tay nhúng chàm trộm lửa của ta. Trộm lửa vì nhân loại cơ đấy! Đàng hoàng mở lời xin ta một câu tử tế thì đã chết ai!",
    "Hestia_0163": "Prometheus, theo trí nhớ của ta thì hắn chưa từng thiếu thốn đầu óc. Từng là một người cực kỳ điềm tĩnh sáng suốt, thế mà giờ đây? Hắn lại đi phục vụ Chronos, gây náo loạn cho bọn ta ở đây! Người ta bảo hắn nhìn thấy trước tương lai, vậy hắn phải biết mình sẽ không thoát tội chứ...",
    "Hestia_0232": "Ta đoán một khi chúng ta chạm tới Chronos, thì Prometheus thể nào cũng bám gót theo sau, khao khát những ngày tháng buồng gan của mình làm mồi ngon cho đại bàng. Ta biết hắn là một hiểm họa, nhưng... ta không muốn thấy hắn phải trải qua cảnh ngộ đó thêm lần nào nữa. Chẳng hiểu vì sao...",
    "Hestia_0233": "Ta biết Prometheus được cho là có thể nhìn thấy những gì sắp diễn ra, nhưng ta không thể tin nổi hắn lại nhìn thấy toàn bộ chuyện {#Emph}này! {#Prev}Có lẽ ta nên giận hắn nhiều hơn, cơ mà... ít nhất xem ra hắn vẫn luôn để mắt bảo bọc cho lũ người phàm.",
    "Hestia_0256": "Nghe đồn cháu bị Prometheus tiễn về nhà hả. Nếu hắn có làm cháu bị bỏng thì chớ dại mà chườm đá lên nhé, bất kể Demeter có nói gì đi nữa. Lũ phù thủy các cháu ắt hẳn phải có thuốc mỡ hay thứ gì tương tự chứ...",
    "Hestia_0059": "Cháu đang mang ánh trăng của Selene soi rọi trên người đấy hả? Ta không phủ nhận nó có sức mạnh và nét quyến rũ riêng... nhưng thứ ánh sáng lạnh lẽo xa xăm đó, làm sao sánh được với ngọn lửa thiêu đốt hừng hực? Không có cửa so sánh đâu!",
    "Hestia_0060": "Đã chạm trán với em gái Hera của ta rồi đúng không? Con bé quen giao tiếp với lớp trẻ như cháu hơn, cơ mà nghĩ lại thì, con bé cũng có cả đống con cái phải lo liệu rồi. Thế nên sao không gắn bó với ta này?",
    "Hestia_0050": "Nữ hoàng Hera trẻ tuổi của chúng ta, con bé lúc nào cũng bảo người ta phải kìm nén cảm xúc và giữ kẽ thật cẩn thận. Nhìn xem thái độ đó dẫn con bé tới đâu! Ta thì bảo cứ xả hết cơn thịnh nộ và giận dữ ra ngoài đi. Trút sạch ra {#Emph}toàn bộ {#Prev}chớ giữ lại!",
    "Hestia_0061": "{#Emph}Ồ{#Prev}, vị thống lãnh tối cao của Olympus đã ban phát cho cháu chút {#Emph}uy lực sấm sét{#Prev}, đúng không nào? Chừng đó chẳng giúp cháu đi được bao xa đâu, nên để ta trang bị cho cháu thêm {#Emph}chút hỏa lực bổ sung {#Prev}ở đây nhé.",
    "Hestia_0062": "Được vị thần hùng mạnh của đất mẹ và đại dương ban phước rồi đấy hả? Sức mạnh của Poseidon và ta chẳng mấy khi hòa trộn được với nhau, nhưng nghĩ lại thì, chính chú ấy và ta cũng đâu có đội trời chung, điều đó cháu có thể tin chắc đấy, nhóc con à.",
    "Hestia_0063": "Chà, vị thần ánh sáng hoa mỹ đã điểm xuyết cho cháu chút {#Emph}lấp lánh {#Prev}rồi đúng không? Tỏa sáng rực rỡ như vầng thái dương, Apollo đúng là thế, {#Emph}dĩ nhiên rồi! {#Prev}Nhưng có nhiều cách để thắp sáng một căn phòng lắm, cháu biết mà.",
    "Hestia_0064": "Cháu đang mang món quà của Aphrodite đúng không? Cháu biết đấy, nàng ta già hơn vẻ ngoài {#Emph}rất, rất nhiều {#Prev}lần. Diện mạo là tất cả đối với nàng ta, còn đối với ta, ta chuộng vẻ nóng bỏng theo một phong cách hoàn toàn khác...",
    "Hestia_0104": "Cô em gái băng giá Demeter của ta đã liên lạc rồi, ta nhận ra ngay! Bà ngoại cháu cứ thích tự xưng là {#Emph}bậc trưởng bối của Olympus{#Prev}, gớm thật! Điều đó chỉ đúng vì ta thường không có mặt ở đây thôi. Có thể bà ta làm cháu lạnh sống lưng, nhưng đừng lo, ta có {#Emph}đúng {#Prev}phương thuốc giải đây!",
    "Hestia_0051": "Cô em gái Demeter tội nghiệp của ta. Con bé chỉ sinh được duy nhất một mụn con, một bé gái, nhóc con à. Persephone, mẹ của cháu đấy! Ấy thế mà, đứa con đó mang lại cho con bé nỗi đau ít nhất cũng ngang ngửa niềm vui. Không phải lỗi của mẹ cháu đâu nhé. Con bé từng là một cô gái đáng yêu vô cùng, với mái tóc óng ả hệt như cháu.",
    "Hestia_0067": "Ta rất vui khi biết cháu và Hephaestus hòa thuận với nhau. Thằng nhóc đó hay thui thủi một mình, cứ như thể ngọn lửa của ta là người bạn đồng hành duy nhất nó cần. Thằng bé không phải dạng tồi tệ nhất trong số thần thánh bọn ta đâu.",
    "Hestia_0203": "Cháu biết mặt Ares rồi đúng không, nhóc con? Hắn ta điềm tĩnh hơn vài người trong chúng ta, chắc chắn thế, nhưng ta nghĩ đầu óc hắn có vấn đề. Thứ hơi ấm duy nhất mà {#Emph}hắn {#Prev}quan tâm chỉ bắt nguồn từ máu tươi vừa đổ và ngọn lửa chiến trận khốc liệt thôi.",
    "Hestia_0066": "Bước chân của cháu thoăn thoắt hẳn lên nếu ta không nhìn nhầm, nhóc con ạ! Tuyệt tác của Hermes lanh lẹ nhất trần đời, ta đoán thế. Cháu có biết thứ gì khác cũng di chuyển nhanh kinh hoàng không? Nào, để ta gợi ý cho một chút nhé!",
    "Hestia_0191": "Ta cảm nhận được điều gì đó khác lạ bên trong cháu, nhóc con à. Giống như một dấu ấn thần thánh của chúng ta nhưng chắc chắn không thuộc về bất kỳ ai ở đây. Nó cổ xưa thực sự, ngay cả khi so với ta! Cháu có vài người bạn cũ mà bọn ta chưa từng hay biết đúng không?",
    "Hestia_0200": "Bọn ta trên này không quá lo lắng lúc này khi có Athena trấn giữ tiền tuyến. Nàng ta có thể hơi nguyên tắc cứng nhắc nếu hai đứa gặp nhau, nhưng trong số tất cả mọi người ở đây, nàng sẽ là người đầu tiên ta chọn để bọc hậu cho mình.",
    "Hestia_0202": "Ta thậm chí còn chẳng muốn biết chuyện gì đang xảy ra với Dionysus nữa rồi. Tình hình càng tồi tệ bao nhiêu, hắn lại càng muốn quẩy bung nóc bấy nhiêu! Cả cái thế giới chết tiệt này có bốc cháy thì hắn cũng mặc kệ cho nó cháy! Cơ mà lúc này có chút rượu vang của hắn thì tốt biết mấy...",
    "Hestia_0106": "Cháu đang giữ Than Hồng Bất Tử của ta đúng không? Từ tận nơi đây ta vẫn thấy ánh lửa bập bùng le lói của nó. Đó là tín hiệu cháu báo cho Bà cô Hestia và những người khác biết rằng cháu đang thèm muốn những Ân huệ có thêm {#Emph}chút xíu {#Prev}vị cay nồng!",
    "Hestia_0189": "Có điều gì đó trong đêm nay làm ta thấy rùng mình thực sự, nhóc con bốc lửa. Cứ như thể bóng tối dày đặc đến mức bóp nghẹt tất cả! Mà ngặt nỗi, không có dưỡng khí thì làm sao có lửa cháy. Cẩn thận đấy, nghe chưa?",
    "Hestia_0225": "Cái gì đã nhập vào Chronos thế không biết, {#Emph}hả? {#Prev}Vừa mới trước đó còn là cuộc chiến dai dẳng cũ rích, thế rồi chớp mắt một cái, lão xuất hiện trên đỉnh núi của chúng ta với vẻ hối lỗi ăn năn! Ta biết lũ phù thủy các cháu có thể làm nên chuyện lớn nhưng chuyện này vượt xa những gì ta tưởng tượng cháu làm được!",
    "Hestia_0226": "Lần trước ta xúc động quá nên chưa kịp chúc mừng cháu đàng hoàng, nhóc con à! Cầu trời ban phước lành cho cháu vì tất cả! Cháu tìm thấy bọn ta giữa một đống hỗn độn tột cùng và kéo bọn ta ra khỏi đó. Dĩ nhiên bọn ta có hỗ trợ này nọ, nhưng cháu mới là đầu bếp chính, và cháu nấu nướng xuất sắc lắm.",
    "Hestia_0237": "Cháu đã tìm thấy mấy đứa em gái dệt chỉ số mệnh rồi đấy hả? Đúng lúc ta cứ ngỡ họ đã bỏ rơi tất cả chúng ta mãi mãi! Ta chưa rõ nên nghĩ gì về lời tiên tri mới của họ, nhưng với mấy lời sấm truyền đó thì thời gian rồi sẽ trả lời tất cả.",
    "Hestia_0252": "Khi toàn bộ biến cố này qua đi, ta đoán mình sẽ lại tiếp tục chu du khắp chốn. Đi xem lũ người phàm và thế gian đang sống ra sao, đứng từ trên đỉnh núi cao này nhìn xuống đâu có dễ. Olympus có thể là một nơi tuyệt vời để ghé thăm nhưng bản thân ta chưa từng muốn định cư ở đây.",
    "Hestia_0262": "{#Emph}Trời ạ{#Prev}, giờ ta mệt nhoài thực sự rồi đấy, cháu biết không? Thiêu rụi hết thứ này tới thứ khác, liên tục không ngừng nghỉ, sau một thời gian nó bào mòn sức lực kinh khủng! Ta vẫn sẽ tiếp tục chống lưng cho cháu, nhóc con ạ, nhưng có thể ta sẽ bớt tán gẫu đôi chút một thời gian.",

    # Standard / Shouts / Combat
    "Hestia_0003": "{#Emph}Aha{#Prev}, hãy {#Emph}thiêu rụi {#Prev}tất cả nào, cháu thấy sao hả nhóc con?",
    "Hestia_0004": "Chúng ta sẽ biến đốm lửa le lói dưới bước chân cháu thành một ngọn lửa bùng cháy dữ dội!",
    "Hestia_0005": "Sao chúng ta không nhóm lên một ngọn lửa ấm cúng, rồi ném toàn bộ kẻ thù vào trong đó nhỉ?",
    "Hestia_0006": "Xem ra chúng ta sắp có một đêm nóng bỏng thực sự phía trước rồi!",
    "Hestia_0007": "Mọi thứ sẽ bị phủ kín trong muội than sau khi chúng ta xong việc!",
    "Hestia_0008": "Đừng để ngọn lửa trong tim cháu lụi tàn nhé, nghe chưa?",
    "Hestia_0009": "{#Emph}Hô hô{#Prev}, để ta xem nào và giúp cháu bừng sáng hừng hực trở lại nhé, nhóc con!",
    "Hestia_0010": "Được rồi, nhóc con bốc lửa! Chúng ta sẽ tăng nhiệt độ lên hết cỡ để thổi bùng mọi thứ!",
    "Hestia_0011": "Đã quá lâu rồi chúng ta chưa cùng nhau thiêu rụi thứ gì đó, đúng không nào?",
    "Hestia_0012": "Đôi khi, cháu chỉ việc {#Emph}thiêu rụi {#Prev}mọi thứ thành bình địa rồi bắt đầu lại từ đó, nhóc con bốc lửa ạ.",
    "Hestia_0013": "Dĩ nhiên mọi thứ đều thối nát tồi tệ, cơ mà nói riêng giữa chị em chúng mình thôi nhé, lâu lắm rồi ta mới thấy mình tràn trề sức sống thế này!",
    "Hestia_0014": "Người ta bảo đừng bao giờ đùa với lửa, nhóc con ạ. Nhưng cháu có toàn quyền cho phép của ta để cứ việc {#Emph}làm tới {#Prev}bến!",
    "Hestia_0015": "Đến lúc tăng hỏa lực lên mức tối đa rồi, đúng thế không hả nhóc con?",
    "Hestia_0016": "Lại có thêm một bài khởi động nhẹ dành cho cháu ở đây này, nhóc con bốc lửa!",
    "Hestia_0017": "Chắc dưới nơi cháu ở lạnh lẽo lắm nhỉ... cơ mà sẽ không kéo dài lâu đâu!",
    "Hestia_0018": "Ta lại tới đây rồi, nhóc con, chuẩn bị ấm cúng đi vì chúng ta sắp có một cú nổ {#Emph}vang trời đấy!",
    "Hestia_0019": "Ngọn lửa cổ xưa này sẽ không bao giờ bị dập tắt, chớ có quên điều đó đấy nhé, nhóc con!",
    "Hestia_0020": "{#Emph}Chao ôi{#Prev}, giá mà đích thân ta có thể nướng thêm nhiều tên kẻ thù chết tiệt hơn nữa!",
    "Hestia_0021": "Gửi tới cháu những lời chúc ấm áp nhất, nhóc con, cùng một chút quà bổ sung đính kèm!",
    "Hestia_0022": "Một đêm nào đó, biết đâu cháu sẽ an cư lạc nghiệp hưởng thụ cuộc sống êm đềm, nhưng {#Emph}chao ôi{#Prev}, không phải đêm nay đâu!",
    "Hestia_0023": "Đôi khi sự hy sinh là điều bắt buộc, nhóc con ạ. Gom hết bọn chúng lại rồi ném vào ngọn lửa đi!",
    "Hestia_0024": "Đêm nay chúng ta sắp được nếm trải một đêm {#Emph}nóng bỏng rực lửa{#Prev}, ta ngửi thấy mùi rồi!",
    "Hestia_0025": "Bản thân cháu đã cháy bỏng hừng hực ngay cả khi không có ta giúp rồi, cơ mà có {#Emph}thêm {#Prev}ta trợ lực thì, {#Emph}ô hô hô hô!",
    "Hestia_0026": "Tối nay chúng ta nấu món gì đây hả, nhóc con? Bất cứ món gì chúng ta thích, thế thôi!",
    "Hestia_0027": "Chà giờ ta nghĩ đã đến lúc tiếp thêm chút gió cho ngọn lửa bùng lên rồi đúng không nào?",
    "Hestia_0028": "Ta vừa mới nấu nướng một món đặc biệt dành riêng cho {#Emph}cháu {#Prev}đây, nhóc con bốc lửa!",
    "Hestia_0029": "Có cái gì đang cháy khét lẹt đằng kia thế hả, nhóc con? Nó sắp sửa cháy bùng lên rồi đấy!",
    "Hestia_0030": "Hãy cùng nhau giữ cho ngọn lửa vĩnh cửu luôn rực sáng và ấm áp, cháu thấy sao hả nhóc con bốc lửa?",
    "Hestia_0031": "Thôi thì ít nhất chúng ta cũng đang được sống trong những thời khắc hào hứng thú vị, phải công nhận điều đó!",
    "Hestia_0032": "Sao chúng ta không thêm chút dầu vào ngọn lửa đang cháy này nhỉ, sao lại không chứ?",
    "Hestia_0208": "Nếu lũ người phàm không được hưởng thụ giây phút ấm cúng, thì ta cũng tuyên bố luôn, {#Emph}chẳng kẻ nào {#Prev}được hưởng hết!",
    "Hestia_0209": "Lẽ ra giờ này chúng ta có thể đang ngồi thoải mái bên bếp lửa nhâm nhi Tiên tửu Nectar này nọ, thế mà {#Emph}không!",
    "Hestia_0210": "Cháu lúc nào cũng ăn mặc mát mẻ chuẩn bị cho thời tiết nóng bức vì thừa biết Bà cô sẽ không ở quá xa đúng không!",
    "Hestia_0211": "Đến giờ nhóm bếp nấu nướng lại rồi, nhóc con bốc lửa, khi màn đêm vẫn còn dài!",
    "Hestia_0212": "Sao chúng ta không thắp sáng màn đêm nhỉ, nhóc con, dùng bất kỳ que củi nào sẵn có trong tay?",
    "Hestia_0214": "Ta đã chứng kiến quá nhiều điều trong suốt cuộc đời mình, cơ mà mấy chuyện gần đây, phải công nhận là hơi bị mới mẻ đấy!",
    "Hestia_0215": "Đừng bao giờ để ngọn lửa trong lòng cháu tắt ngấm, nhóc con ạ, nhưng cũng đừng để nó cháy quá bùng phát thiêu rụi chính mình!",
    "Hestia_0216": "Đừng để mấy chuyện này làm cháu phiền lòng vì mọi thứ rồi sẽ sớm qua đi thôi, lúc nào chả thế.",
    "Hestia_0219": "Lại đến lúc để những tia lửa bay mù mịt rồi đúng không, {#Emph}hả? Ồ {#Prev}ta sẵn sàng bất cứ khi nào cháu muốn!",
    "Hestia_0218": "Lại đang nhắm thẳng lên đỉnh ngọn núi của chúng ta đấy hả? Vậy thì hãy chắc chắn rằng cháu không bị cảm lạnh nhé.",

    # Shop / Exchange
    "Hestia_0169": "Nhét Ân huệ của ta vào một cái bao tải vô danh rách rưới thế này, ta {#Emph}thề đấy! {#Prev}Hơi bị ngạc nhiên là nó không thiêu rụi cái bao luôn. Cháu biết đấy đôi khi tìm gặp cháu chẳng dễ dàng gì!",
    "Hestia_0244": "Chắc cháu nhận ra ngay đây là Ân huệ của ta nhờ luồng nhiệt lượng phả ra hừng hực từ bưu kiện đằng kia đúng không! Ngạc nhiên là nó chưa bốc cháy ngùn ngụt đấy!",
    "Hestia_0121": "Chắc cháu đang có thừa mứa mấy cái đồng tiền vàng mà Chronos vung vãi khắp nơi rồi đúng không. Để cám dỗ lũ người phàm tham lam nhất, ta đoán thế! Hoặc những kẻ bần cùng nhất. Ta chẳng hơi đâu phán xét!",
    "Hestia_0122": "Gã Người Lái Đò đó chuyển tin nhắn giỏi phết đấy nhỉ? Gần giống như việc chở xác chết xuống Âm phủ như gã từng làm vậy. {#Emph}Haizz{#Prev}, dạo này chẳng còn việc gì cho đám xác chết đó làm nữa... ngoại trừ bị {#Emph}thiêu rụi!",
    "Hestia_0123": "Cháu thực sự phải trả tiền cho cái gã Charon đó trong những tình huống này đấy à! Cái hệ thống ngớ ngẩn quái đản {#Emph}gì thế không biết? {#Prev}Sao, người nghèo thì không được nhận ân huệ à? Chẳng công bằng chút nào.",
    "Hestia_0124": "Ân huệ của ta đã vượt qua cả quãng đường dài dằng dặc ấy trên một chiếc phà gỗ ọp ẹp cũ kỹ đấy ư? Hẳn phải tiềm ẩn cả đống nguy cơ hỏa hoạn, dẫu xung quanh có đầy nước để dập lửa.",
    "Hestia_0168": "Sao, gã lái phà đó đang mở đợt xả hàng giảm giá đấy hả? Ta không muốn cháu phải trả một cái giá cắt cổ đâu! Dẫu lẽ ra ân huệ không bao giờ nên có giá tiền gắn kèm.",

    # Wrath & Revenge
    "Hestia_0125": "Mụ Hecate già chưa dạy cho cháu biết kính trọng người già nhiều hơn {#Emph}thế này sao? {#Prev}Thôi được rồi, đây là một bài học cấp tốc dành cho cháu!",
    "Hestia_0126": "Chẳng hay ho gì nếu để đám còn lại tưởng bà già Hestia này là kẻ dễ bị bắt nạt trong mấy chuyện thế này. Thế nên ta phải nướng chín cháu một tí mới được!",
    "Hestia_0127": "Không thèm nhận ân huệ của ta khi chúng còn đang nóng hổi đỏ rực đúng không hả? Vậy thì {#Emph}thứ này {#Prev}sẽ giúp sưởi ấm cho cháu trong lúc chờ đợi nhé.",
    "Hestia_0128": "Ta đâu có thực sự giận dỗi gì cháu đâu, nhóc con! Cơ mà lúc này ta chẳng đủ sức lực để đi ngược lại mấy cái truyền thống ngớ ngẩn cổ hủ của chúng ta.",
    "Hestia_0129": "{#Emph}Hừ{#Prev}, một cú bỏng rát đau đớn như thế đáng phải nhận lại một cú tương tự. Rất công bằng, cháu có đồng ý không hả nhóc con bốc lửa?",
    "Hestia_0130": "Cứ nhìn cái cảnh {#Emph}cãi vã bới móc{#Prev}, đống hỗn độn thảm hại mà chúng ta biến thành xem! Cơ mà ai nấy đều phải gánh vác phần việc của mình, đúng không?",
    "Hestia_0131": "Ta đã có lòng tốt chìa tay ra giúp đỡ, thế mà {#Emph}không! {#Prev}Lúc nào cũng có kẻ cản mũi ta. Ta {#Emph}không {#Prev}để yên đâu nhé!",
    "Hestia_0132": "Thôi nào, ngay cả lũ người phàm cũng biết điều nhất là nên kính trọng bà già Hestia này đầu tiên khi đụng tới mấy chuyện này!",
    "Hestia_0133": "Chối bỏ Ân huệ của Hestia đấy hả? Vậy thì để ta nhắc nhở nhanh cho cháu nhớ về cách thức dâng lễ tế đúng chuẩn mực nhé!",
    "Hestia_0134": "Dù ta có cố gắng thế nào đi nữa, ta vẫn không khỏi cảm thấy hơi phật ý đấy! Và ta không phải là kẻ dễ dàng bỏ qua chuyện đó đâu...",
    "Hestia_0264": "Này cớ sao cháu lại dám chọn một trong những đứa em gái của ta thay vì chọn ta thế, {#Emph}hả?",
    "Hestia_0135": "Đó chính là thứ ta gọi là bỏng độ {#Emph}một{#Prev}. Coi như tha cho cháu với một lời cảnh cáo {#Emph}nhỏ {#Prev}thôi đấy!",
    "Hestia_0136": "Ta quý cháu đấy, nhóc con. Thế nên ta sẽ không biến cháu thành tro bụi trong lần {#Emph}này {#Prev}đâu. Nhưng sau này thì ta chẳng dám hứa trước điều gì đâu nhé.",
    "Hestia_0267": "Vậy là cháu vừa nhận một cái tát cảnh cáo vào cổ tay rồi đấy! Mau dội chút nước mát lạnh lên chỗ đó đi.",

    # Reconciliation
    "Hestia_0138": "{#Emph}Thôi{#Prev}, cháu bình an vô sự, và {#Emph}ta {#Prev}bây giờ cũng nguôi ngoai rồi, nên ta đoán là {#Emph}mọi chuyện {#Prev}đều ổn thỏa cả.",
    "Hestia_0139": "Được rồi, không việc gì phải sôi máu bực dọc quá lâu vì mấy chuyện cỏn con này. Tiếp tục thôi nào!",
    "Hestia_0140": "Ban nãy ta hơi bị bốc hỏa một tí, nhưng ta đã quay trở lại với bản chất hay cáu kỉnh thường ngày rồi đây, cảm ơn nhé!",
    "Hestia_0141": "Chà, chúng ta lại thế nữa rồi! Cháu biết là người ta luôn coi ta là kẻ điềm tĩnh và hiền hòa nhất trên đỉnh núi này không?",
    "Hestia_0142": "Đùa với lửa thì thể nào cũng bị bỏng tay! Quy luật đơn giản thế thôi trừ khi ta tuyên bố ngược lại.",
    "Hestia_0143": "Được rồi, được rồi, hạ hỏa bớt đi trước khi mấy ngọn lửa này của ta vượt {#Emph}quá {#Prev}tầm kiểm soát...",
    "Hestia_0144": "Ta thích một cô bé biết bật lại đấy! Đừng bao giờ để bất kỳ ai trên này ức hiếp cháu.",

    # Gift / Affinity dialogues
    "Melinoe_0951": "Kính thưa Nữ thần Hestia, con hy vọng người sẽ nhận lễ vật này. Thật là một vinh hạnh lớn khi được gặp một người có đầy đủ sự ấm áp, trí tuệ và sức mạnh như người.",
    "Hestia_0068": "Chà nhìn cháu kìa, lại còn dâng lễ vật cho ta nữa chứ! Thật hiếu khách làm sao, và dẫu ta sẵn sàng ném hầu hết mọi hủ tục vào đống lửa, truyền thống trao đổi quà tặng này là thứ ta không hề phản đối. Cầm lấy này, chút quà từ ta.",
    "Melinoe_0952": "Xin hãy nhận lấy món này, thưa Bà cô Hestia! Sự ủng hộ hào phóng của người có ý nghĩa vô cùng lớn lao đối với con. Con biết mình còn quá nhiều điều có thể học hỏi từ người.",
    "Hestia_0069": "Thôi nào, ta có cái gì đáng để dạy dỗ đâu. Xem ra cháu cũng là kẻ thích sống ẩn dật y chang như ta thôi, ngoài ra, cháu vẫn còn là một cô bé xinh xắn. Cơ mà thật vui khi được làm quen với cháu.",
    "Melinoe_0953": "Hestia vĩ đại, nữ thần của bếp sưởi và ngọn lửa thiêng! Cầu cho tia lửa của người luôn bùng cháy rực rỡ như thế. Người đã giúp đỡ con rất nhiều trên hành trình này!",
    "Hestia_0070": "Chao ôi, cảm ơn cháu vì điều đó nhé, nhóc con, cháu tốt bụng quá. Lũ phàm nhân cứ đinh ninh ta chỉ thích mấy món đồ tế {#Emph}cháy khét lẹt{#Prev}, bọn chúng chưa từng dâng tặng ta thứ hảo hạng thế này bao giờ.",
    "MelinoeField_2244": "Một cống phẩm kính dâng lên Phu nhân Hestia yêu quý! Những ngọn lửa rực sáng của người là ánh hải đăng dẫn lối, và là nỗi khiếp sợ của muôn vàn kẻ thù. Dẫu vậy trí tuệ sắc sảo cùng tinh thần rực lửa của người mới là thứ thúc giục con tiến bước nhiều hơn cả!",
    "Hestia_0159": "Chẳng việc gì phải nịnh nọt vuốt ve ta đâu nhé, cháu biết mà. Sao, tưởng ta sẽ ỉm đi những thứ xịn sò nhất trừ phi cháu ban phát vài lời khen có cánh sao? Ta có thể nhỏ nhen thật đấy, cơ mà không đến mức {#Emph}nhỏ nhen {#Prev}như thế đâu!",
    "MelinoeField_2245": "Nếu con nhận thêm một Ân huệ nữa của người, thưa Bà cô, con xin người hãy nhận thêm một vò Tiên tửu Nectar này từ con! Cách người mang phong thái ung dung tự tại luôn truyền cảm hứng cho con. Nếu nhiều kỷ nguyên sau con có thể trở nên giống người đôi phần, con sẽ thấy mình vô cùng may mắn.",
    "Hestia_0160": "Cháu muốn trở nên giống {#Emph}ta ư? {#Prev}Đó mới đúng là {#Emph}chuyện lạ {#Prev}đầu tiên ta nghe thấy đấy! Ta sẵn sàng đánh đổi mọi thứ để quay ngược thời gian và làm lại từ đầu với những hiểu biết ta có lúc này. Cơ mà nghĩ lại thì, chúng ta đang lên kế hoạch quay ngược Thời Gian còn gì, đúng không?",
    "MelinoeField_2246": "Thưa Bà cô Hestia! Càng ngày con càng tự hỏi mọi chuyện sẽ ra sao nếu người luôn hiện diện trong cuộc đời con từ trước đến nay. Có lẽ con đã lớn lên nhanh trí sắc sảo hơn chăng? Hoặc hạnh phúc hơn! Cầu mong đôi ta rồi sẽ thấu hiểu nhau như thể chúng ta đã gắn bó suốt bấy lâu nay!",
    "Hestia_0161": "Cháu biết đấy, ta chưa từng muốn có con cái, nhóc con à. Và cháu đừng hòng làm ta phải hoài nghi quyết định có lẽ là sáng suốt nhất cuộc đời mình, bằng cách ăn nói ngọt ngào dẻo quẹo như cháu vừa làm ban nãy! Giờ thì {#Emph}cầm lấy {#Prev}Ân huệ chết tiệt của cháu rồi biến đi mau!",
    "MelinoeField_4346": "Chắc hẳn chính người là nguồn cảm hứng giúp con tạo dựng một mái ấm ấm áp và hạnh phúc, thưa Bà cô! Vò Tiên tửu Ambrosia này, đổi lại, là để chia sẻ với tất cả những ai làm cho chính ngôi nhà của người cảm thấy an toàn và ấm cúng, hệt như cảm giác con có được mỗi khi người liên lạc.",
    "Hestia_0241": "{#Emph}Ôi {#Prev}cháu thật ngọt ngào quá đi mất, nhóc con à, và cháu đã chạm đúng vào chân lý rồi đấy! Biết bao kẻ khao khát được nổi tiếng hay thành công rực rỡ này nọ, nhưng để được bình an và thoải mái ấm cúng ư? Chẳng có gì sánh bằng điều đó cả, và ta biết cháu hiểu rõ điều đó. {#Emph}Cầu cho cháu sẽ luôn được như vậy.",
    "Melinoe_1737": "Một món quà từ Bà cô Hestia...",

    # Combat Calls / Shouts
    "Hestia_0078": "Sao chúng ta không tăng nhiệt độ lên nhỉ?!",
    "Hestia_0079": "Bọn chúng sẽ bị thiêu rụi!",
    "Hestia_0080": "Ngọn lửa hãy nuốt chửng lấy toàn bộ bọn chúng!",
    "Hestia_0268": "Ấm áp và dễ chịu nào, tất cả mọi người!",
    "Hestia_0269": "Một bài khởi động nhẹ cho các ngươi đây!",
    "Hestia_0270": "Ồ, {#Emph}giờ thì {#Prev}chúng ta bắt đầu nổi lửa nấu nướng rồi đây!",
    "Hestia_0271": "Ồ {#Emph}giờ thì {#Prev}cháu chịu sưởi ấm rồi đấy à?",
    "Hestia_0272": "Cháu đang đùa với lửa đấy, nhóc con!",
    "Hestia_0273": "Thiêu cháy cừ lắm, nhóc con bốc lửa!",
    "Chronos_1267": "Ngươi lại lôi cả bà già {#Emph}Hestia ra nữa đấy à!",
    "Chronos_1268": "Trong này có vẻ hơi bị nóng bức ngột ngạt đấy...!",
    "Zagreus_0366": "Phu nhân Hestia?!",
    "Zagreus_0367": "Hestia, đừng...!",

    # Warnings / Revenge
    "Hestia_0100": "Ta không thích những hành vi như thế đâu nhé.",
    "Hestia_0101": "Dám đùa cợt với ta, cháu sẽ bị bỏng tay đấy.",
    "Hestia_0099": "Cháu coi ta là ai hả?",
    "Hestia_0170": "Đừng đùa với lửa nếu còn biết điều gì tốt cho mình.",
    "Hestia_0171": "Ta đã thôi làm kẻ dễ bị bắt nạt từ lâu lắm rồi, nhóc con ạ!",
    "Hestia_0172": "Xem ra ta lỡ tay nướng cháu hơi bị kỹ quá rồi, nhóc con bốc lửa...",

    # Quick accepts
    "Hestia_0084": "{#Emph}Ha! {#Prev}Được thôi.",
    "Hestia_0085": "{#Emph}Ờ{#Prev}, duyệt luôn!",
    "Hestia_0173": "Chắc chắn rồi!",
    "Hestia_0174": "Đấy!",
    "Hestia_0175": "Nóng hổi vừa thổi vừa ăn!",
    "Hestia_0176": "Được!",
    "Hestia_0177": "Dễ ợt.",
    "Hestia_0178": "Sẵn sàng!",
    "Hestia_0081": "{#Emph}Ồ{#Prev}, cô bé đây rồi!",
    "Hestia_0082": "Bà cô Hestia tới rồi đây!",
    "Hestia_0083": "Đang nấu món gì thế?",
    "Hestia_0096": "Từ ta gửi tới cháu!",
    "Hestia_0097": "Chút quà mọn ở đây này!",
    "Hestia_0183": "Hàng nóng hổi tới đây!",
    "Hestia_0184": "Bất ngờ chưa!",
    "Hestia_0185": "Xin chào, nhóc con bốc lửa!",
    "Hestia_0186": "{#Emph}Nhóc con!",
}

def main():
    source_raw = SRC.read_text(encoding="utf-8-sig")
    OUT.parent.mkdir(parents=True, exist_ok=True)
    
    entries_dict = {
        k: v if isinstance(v, dict) else {"DisplayName": v}
        for k, v in translations.items()
    }
    
    updated_raw = apply_translation_to_sjson(source_raw, entries_dict)
    OUT.write_text(updated_raw, encoding="utf-8")
    sys.stdout.reconfigure(encoding="utf-8")
    print(f"Đã dịch và lưu thành công {len(entries_dict)} chuỗi của Hestia vào: {OUT}")

if __name__ == "__main__":
    main()
