# -*- coding: utf-8 -*-

translations_500_600 = {
  "Talent_Spell_Diffindo_desc": "\"Bùa Cắt Sâu (Diffindo)\" có thể xuyên qua kẻ địch và tiếp tục tấn công nhiều mục tiêu.",
  "Talent_Spell_Diffindo_Requirements": "Điều kiện mở khóa tài năng: Học cách sử dụng \"Bùa Cắt Sâu (Diffindo)\".",
  "Talent_Spell_Expelliarmus": "Lời Nguyền Tước Khí",
  "Talent_Spell_Expelliarmus_desc": "Bùa Giải Giới (Expelliarmus) sẽ giáng lên kẻ địch hiệu ứng tương đương một lời nguyền. Kẻ địch bị nguyền rủa sẽ chịu thêm sát thương.",
  "Talent_Spell_Expelliarmus_Requirements": "Điều kiện mở khóa tài năng: Học cách sử dụng Bùa Giải Giới (Expelliarmus).",
  "Talent_Spell_Fiendfyre": "Thông Thạo Lửa Quỷ Fiendfyre",
  "Talent_Spell_Fiendfyre_desc": "Mở rộng quy mô tác dụng của Lửa Quỷ Fiendfyre, đồng thời phóng ra một luồng lửa có thể sát thương kẻ địch trong phạm vi rộng lớn.",
  "Talent_Spell_Fiendfyre_Requirements": "Điều kiện mở khóa tài năng: Học cách sử dụng Lửa Quỷ Fiendfyre.",
  "Talent_Spell_Flippendo": "Lời Nguyền Đẩy Lùi",
  "Talent_Spell_Flippendo_desc": "\"Bùa Lộn Nhào (Flipendo)\" sẽ giáng lên kẻ địch hiệu ứng tương đương một lời nguyền. Kẻ địch bị nguyền rủa sẽ chịu thêm sát thương.",
  "Talent_Spell_Flippendo_Requirements": "Điều kiện mở khóa tài năng: Học cách sử dụng Bùa Lộn Nhào (Flipendo).",
  "Talent_Spell_Glacius": "Thông Thạo \"Bùa Đóng Băng (Glacius)\"",
  "Talent_Spell_Glacius_desc": "Tấn công kẻ địch đang bị đóng băng dưới tác dụng của \"Bùa Đóng Băng (Glacius)\" sẽ khiến mục tiêu bắn ra các mảnh băng sắc nhọn gây sát thương xung quanh.",
  "Talent_Spell_Glacius_Requirements": "Điều kiện mở khóa tài năng: Học cách sử dụng \"Bùa Đóng Băng (Glacius)\".",
  "Talent_Spell_Incendio": "Thông Thạo \"Bùa Lửa (Incendio)\"",
  "Talent_Spell_Incendio_desc": "Khi thi triển \"Bùa Lửa (Incendio)\", một vòng tròn lửa sẽ đồng thời bùng cháy xung quanh bạn.",
  "Talent_Spell_Incendio_Requirements": "Điều kiện mở khóa tài năng: Học cách sử dụng \"Bùa Lửa (Incendio)\".",
  "Talent_Spell_Levioso": "Thông Thạo \"Bùa Bay Lơ Lửng (Levioso)\"",
  "Talent_Spell_Levioso_desc": "\"Bùa Bay Lơ Lửng (Levioso)\" sẽ tạo hiệu ứng bay lơ lửng lên cả những kẻ địch xung quanh mục tiêu.",
  "Talent_Spell_Levioso_Requirements": "Điều kiện mở khóa tài năng: Học cách sử dụng \"Bùa Bay Lơ Lửng (Levioso)\".",
  "Talent_Spell_Transformation": "Thông Thạo \"Bùa Biến Hình\"",
  "Talent_Spell_Transformation_desc": "Kẻ địch bị đánh trúng bởi \"Bùa Biến Hình\" sẽ bị biến đổi thành các vật thể có khả năng phát nổ.",
  "Talent_Spell_Transformation_Requirements": "Điều kiện mở khóa tài năng: Học cách sử dụng \"Bùa Biến Hình\".",
  "TUT_Acciopuzzles": "Bùa Triệu Tập (Accio)",
  "TUT_Acciopuzzles2": "Bùa Triệu Tập (Accio)",
  "TUT_Descendo": "Bùa Đập Xuống (Descendo)",
  "TUT_Descendo_desc": "\"Bùa Đập Xuống (Descendo)\" là một bùa chú lực đẩy, có thể di chuyển vật thể hướng xuống và đập mạnh kẻ địch xuống mặt đất, từ đó tạo ra sóng xung kích.",
  "TUT_Diffindo": "Bùa Cắt Sâu (Diffindo)",
  "TUT_Diffindo_desc": "\"Bùa Cắt Sâu (Diffindo)\" sẽ cắt chém kẻ địch và đồ vật trong phạm vi cự ly gần trước mặt người thi triển.",
  "TUT_Display_AccioBlue_desc": "Sử dụng bùa chú lực đẩy <img src=\"SpellTypeDiamond_Forceful\" color=\"UI.SpellCategory.Force\"/> để phá vỡ khiên màu tím nhạt, chẳng hạn như Bùa Triệu Tập (Accio) <img src=\"Accio\"/>\n\nKhóa mục tiêu {LockOn} cho phép bạn theo dấu kẻ địch mà không cần ngắm. Sử dụng {UMGMapScreenMove_X} để chuyển đổi mục tiêu khi đang khóa.",
  "TUT_Display_AccioBlue_desc2": "Giữ {SpellModifierButton} để mở bộ bùa chú và thi triển Bùa Triệu Tập (Accio) <img src=\"Accio\"/>.",
  "TUT_Display_AccioBluePC_desc": "Sử dụng bùa chú lực đẩy <img src=\"SpellTypeDiamond_Forceful\" color=\"UI.SpellCategory.Force\"/> để phá vỡ khiên màu tím nhạt, chẳng hạn như Bùa Triệu Tập (Accio) <img src=\"Accio\"/>\n\nKhóa mục tiêu {LockOn} cho phép bạn theo dấu kẻ địch mà không cần ngắm. Sử dụng {CameraMove_X} để chuyển đổi mục tiêu khi đang khóa.",
  "TUT_Display_AccioBluePC_desc2": "Nhấn phím được gán để thi triển \"Bùa Triệu Tập (Accio)\" <img src=\"Accio\"/>.",
  "TUT_display_AccioCombat": "Bùa Triệu Tập (Accio) Trong Chiến Đấu",
  "TUT_display_AMSpells": "Phép Thuật Cổ Xưa",
  "TUT_display_AMSpells_desc1": "Khi thước đo Phép Thuật Cổ Xưa được nạp đầy, một biểu tượng sẽ xuất hiện phía trên mục tiêu đang được làm nổi bật. Nhấn {UMGFaceButtonLeft} để triệu tập Phép Thuật Cổ Xưa hùng mạnh giáng đòn lên kẻ địch.",
  "TUT_Display_AMSpellTriggering": "Phép Thuật Cổ Xưa",
  "TUT_Display_AMSpellTriggering_desc": "Nhấn {UMGFaceButtonLeft} Phép Thuật Cổ Xưa <img src=\"AncientMagicFinisher\"/>",
  "TUT_Display_Bombarda": "Bùa Nổ Công Phá (Bombarda)",
  "TUT_Display_Bombarda_desc": "Bùa nổ \"Bùa Nổ Công Phá (Bombarda)\" <img src=\"Skill_Bombarda1\"/> là một bùa chú sát thương cực mạnh, có thể tạo ra vụ nổ trên một diện rộng.",
  "TUT_Display_Confringo": "Bùa Nổ Súng (Confringo)",
  "TUT_Display_Confringo_desc": "Bùa nổ \"Bùa Nổ Súng (Confringo)\" có thể phóng ra xung kích bùng nổ. Một số tài năng nhất định có thể thay đổi hiệu ứng của bùa chú này lên kẻ địch.",
  "TUT_display_CustomSpellLoadouts_desc1": "Sử dụng các bùa chú phù hợp nhất với phong cách chiến đấu cụ thể của bạn để tùy biến bộ bùa chú. Nhấn {UMGActionScreenToggle} để mở menu chọn bùa chú.",
  "TUT_Display_DepulsoUnlocked": "Bùa Đẩy Lùi (Depulso)",
  "TUT_Display_DepulsoUnlocked_desc": "Bùa xua đuổi \"Bùa Đẩy Lùi (Depulso)\" <img src=\"Depulso\"/> là một bùa chú lực đẩy, có thể đẩy kẻ địch và đồ vật ra xa khỏi người thi triển.",
  "TUT_display_Descendo": "Bùa Đập Xuống (Descendo)",
  "TUT_Display_EquippingSpells": "Trang Bị Bùa Chú",
  "TUT_Display_EquippingSpells_desc1": "Bạn đã học đủ số lượng bùa chú, và giờ cần trang bị \"Bùa Lửa (Incendio)\" vào bộ bùa chú của mình. Để làm điều này, bạn cần hoán đổi nó với một bùa chú khác.",
  "TUT_Display_EquippingSpells_desc2": "Bạn đã học đủ số lượng bùa chú, và giờ cần trang bị \"Bùa Lửa (Incendio)\" vào bộ bùa chú của mình. Để làm điều này, bạn cần hoán đổi nó với một bùa chú khác. Di chuột lên \"Bùa Lửa (Incendio)\" và giữ {Stupefy}.",
  "TUT_Display_EquippingSpellsGamepad_desc": "Để sử dụng một bùa chú hoặc vật phẩm, trước tiên bạn phải thêm nó vào bộ bùa chú của mình. Giờ hãy cùng thêm \"Bùa Lửa (Incendio)\". Di chuyển đến \"Bùa Lửa (Incendio)\", giữ {Stupefy} và nhấn nút bạn muốn gán vào.",
  "TUT_Display_EquippingSpellsPC_desc": "Để sử dụng một bùa chú hoặc vật phẩm, trước tiên bạn phải thêm nó vào bộ bùa chú của mình. Giờ hãy cùng thêm \"Bùa Lửa (Incendio)\". Di chuột lên \"Bùa Lửa (Incendio)\", giữ {Stupefy} và kéo nó vào bộ bùa chú của bạn.",
  "TUT_display_ForcefulSpells_desc1": "Các bùa chú lực đẩy như \"Bùa Triệu Tập (Accio)\", \"Bùa Đẩy Lùi (Depulso)\" và \"Bùa Đập Xuống (Descendo)\" có thể sử dụng ma thuật uy lực để di chuyển nhanh chóng đồ vật hoặc kẻ địch. Bùa chú lực đẩy còn có thể phá vỡ \"Bùa Khiên Màu Tím Nhạt\", ví dụ như loại mà các Pháp Sư Hắc Ám thường sử dụng.",
  "TUT_Display_Glacius": "Bùa Đóng Băng (Glacius)",
  "TUT_Display_Glacius_desc": "\"Bùa Đóng Băng (Glacius)\" là một bùa chú khống chế, có thể đóng băng kẻ địch ngay trên đường di chuyển của chúng.",
  "TUT_display_HeavySpells": "Bùa Chú Sát Thương Cao",
  "TUT_display_Incendio": "Bùa Lửa (Incendio)",
  "TUT_display_Incendio_desc1": "\"Bùa Lửa (Incendio)\" <img src=\"Incendio\"/> là một bùa chú sát thương cao, có thể giải phóng ngọn lửa hủy diệt trong cự ly ngắn.",
  "TUT_Display_IncendioRed_desc1": "Sử dụng bùa chú sát thương <img src=\"SpellDiamond_Red\"/> để phá vỡ khiên màu đỏ, ví dụ như bùa tạo lửa \"Bùa Lửa (Incendio)\" <img src=\"Incendio\"/>\n\nKhóa mục tiêu {LockOn} cho phép bạn theo dấu kẻ địch mà không cần ngắm. Sử dụng {UMGMapScreenMove_X} để chuyển đổi mục tiêu khi đang khóa.",
  "TUT_Display_IncendioRed_desc2": "Giữ {SpellModifierButton} để mở bộ bùa chú và thi triển \"Bùa Lửa (Incendio)\" <img src=\"Incendio\"/>.",
  "TUT_Display_IncendioRedPC_desc1": "Sử dụng bùa chú sát thương <img src=\"SpellDiamond_Red\"/> để phá vỡ khiên màu đỏ, ví dụ như bùa tạo lửa \"Bùa Lửa (Incendio)\" <img src=\"Incendio\"/>\n\nKhóa mục tiêu {LockOn} cho phép bạn theo dấu kẻ địch mà không cần ngắm. Sử dụng {CameraMove_X} để chuyển đổi mục tiêu khi đang khóa.",
  "TUT_Display_IncendioRedPC_desc2": "Nhấn phím được gán để thi triển \"Bùa Lửa (Incendio)\" <img src=\"Incendio\"/>.",
  "TUT_Display_IncendioVines": "Dây Leo Bốc Cháy",
  "TUT_Display_LeviosoCombat": "\"Bùa Bay Lơ Lửng (Levioso)\" Trong Chiến Đấu",
  "TUT_Display_Lumos": "Bùa Phát Sáng (Lumos) & Bộ Bùa Chú",
  "TUT_Display_Lumos_desc1": "Bạn đã nhận được bùa chú thắp sáng đầu đũa \"Bùa Phát Sáng (Lumos)\" <img src=\"Lumos\"/>, bùa chú này đã tự động được đặt vào bộ bùa chú của bạn. \"Bùa Phát Sáng (Lumos)\" tạo ra một luồng sáng nơi đầu đũa phép, giúp bạn có tầm nhìn rõ ràng trong bóng tối.",
  "TUT_Display_Lumos_desc2": "Giữ {SpellModifierButton} và nhấn {AM_SpellButton1} để thi triển \"Bùa Phát Sáng (Lumos)\" <img src=\"Lumos\"/>.",
  "TUT_Display_LumosPC_desc1": "Bạn đã nhận được bùa chú thắp sáng đầu đũa \"Bùa Phát Sáng (Lumos)\" <img src=\"Lumos\"/>, bùa chú này đã tự động được đặt vào bộ bùa chú của bạn. \"Bùa Phát Sáng (Lumos)\" tạo ra một luồng sáng nơi đầu đũa phép, giúp bạn có tầm nhìn rõ ràng trong bóng tối.",
  "TUT_Display_LumosPC_desc2": "Nhấn {AM_SpellButton1} để thi triển hoặc dập tắt \"Bùa Phát Sáng (Lumos)\" <img src=\"Lumos\"/>.",
  "TUT_display_PotionBrewing": "Pha Chế Độc Dược",
  "TUT_display_PotionBrewing_desc1": "Pha chế độc dược tại Bàn Chế Độc Dược bằng các công thức đã mở khóa. Công thức và nguyên liệu có thể mua từ các cửa hàng tương ứng. Nguyên liệu cũng có thể được gieo trồng và tìm thấy ngoài thiên nhiên hoang dã.",
  "TUT_display_PotionBrewing_desc2": "Sau khi pha chế hoàn tất, bạn có thể quay lại để nhận độc dược.",
  "TUT_display_PotionStations": "Bàn Chế Độc Dược",
  "TUT_display_PotionStations_desc1": "Bằng cách sử dụng các nguyên liệu thích hợp, bạn có thể pha chế độc dược tại Bàn Chế Độc Dược.",
  "TUT_Display_Reparo": "Bùa Sửa Chữa (Reparo)",
  "TUT_Display_Reparo_desc1": "Bùa hồi phục \"Bùa Sửa Chữa (Reparo)\" <img src=\"Reparo\"/> có thể dùng để sửa chữa các đồ vật và mảnh vỡ môi trường bị gãy đổ.",
  "TUT_Display_Revelio": "Bùa Hiện Hình (Revelio)",
  "TUT_Display_Revelio_desc": "{RevelioButton} Thi triển \"Bùa Hiện Hình (Revelio)\" <img src=\"Revelio\"/>.",
  "TUT_Display_Revelio_desc1": "Thi triển \"Bùa Hiện Hình (Revelio)\" <img src=\"Revelio\"/> sẽ làm hiển thị vị trí của nhân sự cấp cao hoặc kẻ địch, cho phép bạn trinh sát phía trước và duy trì ẩn nấp không bị phát hiện.",
  "TUT_display_Spell_Protego_desc1": "Nhấn và giữ {AM_Protego} để thi triển \"Bùa Khiên Che Chắn (Protego)\", bảo vệ bản thân khỏi mọi sát thương.",
  "TUT_display_Spell_Stupefy": "Thi Triển Cơ Bản",
  "TUT_display_Spell_Stupefy_desc1": "Nhấn {Stupefy} để thực hiện thi triển cơ bản <img src=\"Stupefy\"/>.",
  "TUT_display_SpellCooldowns": "Thời Gian Hồi Bùa Chú",
  "TUT_Display_SpellMiniGameAdvanced_desc": "Dùng {PIM_LeftStick} giữ vững đũa phép của bạn, và dẫn dắt nó di chuyển dọc theo ký hiệu để học bùa chú. Khi hệ thống nhắc bạn tăng tốc chuyển động của đũa dọc theo quỹ đạo ký hiệu, hãy nhấn nút tương ứng.",
  "TUT_Display_SpellMiniGameBasic_desc": "{PIM_LeftStick} Di chuyển êm dịu đũa phép theo quỹ đạo ký hiệu để học bùa chú.",
  "TUT_display_StunningSpell": "Bùa Choáng Váng (Stupefy)",
  "TUT_display_StunningSpell_desc1": "Trong thời gian \"Bùa Khiên Che Chắn (Protego)\" <img src=\"Protego\"/> có hiệu lực, hãy giữ {Protego} để tung đòn phản công bằng \"Bùa Choáng Váng (Stupefy)\" <img src=\"TUT_Stupefy\"/> làm choáng kẻ địch.\n\nKẻ địch bị choáng sẽ chịu thêm sát thương, biểu thị bằng các con số màu vàng kim.",
  "TUT_display_StunningSpell_desc2": "Trong thời gian \"Bùa Khiên Che Chắn (Protego)\" <img src=\"Protego\"/> có hiệu lực, hãy giữ {Protego} để tung đòn phản công bằng \"Bùa Choáng Váng (Stupefy)\" <img src=\"TUT_Stupefy\"/> làm choáng kẻ địch.",
  "TUT_display_StunningSpellReminder_desc2": "Nhấn {Protego}: Thi triển \"Bùa Khiên Che Chắn (Protego)\" <img src=\"Protego\"/>.\nGiữ {Protego}: Thi triển \"Bùa Khiên Che Chắn (Protego)\" và phản công bằng \"Bùa Choáng Váng (Stupefy)\" <img src=\"TUT_Stupefy\"/>.",
  "TUT_Expelliarmus": "Bùa Giải Giới (Expelliarmus)",
  "TUT_Expelliarmus_desc": "\"Bùa Giải Giới (Expelliarmus)\" có thể tước đũa phép và các vũ khí khác trên tay kẻ địch. Việc bị tước vũ khí sẽ tạo ra các tác động khác nhau tùy theo từng loại kẻ địch.",
  "TUT_Flipendo": "Bùa Lộn Nhào (Flipendo)",
  "TUT_Flipendo_desc": "Cũng giống như Bùa Triệu Tập, bùa ác độc đẩy lùi \"Bùa Lộn Nhào (Flipendo)\" là một bùa chú lực đẩy, có thể khiến mục tiêu lộn nhào lên xuống và nhờ đó phá tan bùa khiên màu tím nhạt của chúng.",
  "TUT_GT01_Depulso": "Bùa Đẩy Lùi (Depulso)",
  "TUT_GT01_Depulso_Title": "Bùa Đẩy Lùi (Depulso)",
  "TUT_Legend_DrinkHealthPotion": "Uống Thuốc Hồi Máu",
  "TUT_Levioso_Part1_desc": "Sử dụng các bùa chú khống chế <img src=\"SpellTypeBack_Yellow\"/> như bùa bay lơ lửng hoặc \"Bùa Bay Lơ Lửng (Levioso)\" <img src=\"Levioso\"/> để đánh tan khiên màu vàng của kẻ địch\n\nKhóa mục tiêu {LockOn} cho phép bạn theo dấu kẻ địch mà không cần ngắm. Sử dụng {UMGMapScreenMove_X} để chuyển đổi mục tiêu khi đang khóa.",
  "TUT_Levioso_Part1_desc2": "Giữ {SpellModifierButton} để mở bộ bùa chú và thi triển \"Bùa Bay Lơ Lửng (Levioso)\" <img src=\"Levioso\"/>.",
  "TUT_Levioso_Part2": "Chuỗi Phối Hợp Bùa Chú",
  "TUT_Levioso_Part2_desc2": "Sử dụng {Stupefy} để thực hiện thi triển cơ bản.",
  "TUT_LeviosoPC_Part1_desc": "Sử dụng các bùa chú khống chế <img src=\"SpellTypeBack_Yellow\"/> như bùa bay lơ lửng hoặc \"Bùa Bay Lơ Lửng (Levioso)\" <img src=\"Levioso\"/> để đánh tan khiên màu vàng của kẻ địch\n\nKhóa mục tiêu {LockOn} cho phép bạn theo dấu kẻ địch mà không cần ngắm. Sử dụng {CameraMove_X} để chuyển đổi mục tiêu khi đang khóa."
}

if __name__ == '__main__':
    print(f"Loaded {len(translations_500_600)} keys.")
