"""Translate a reviewed first batch of Apollo's Hades II dialogue."""
from pathlib import Path
import sys

ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(ROOT / "tools"))
from hades2_sjson_helper import apply_translation_to_sjson  # noqa: E402

SRC = ROOT / "games/0100A00019DE0000_Hades2/source/raw_text/en/_LootData_Apollo.en.sjson"
OUT = ROOT / "games/0100A00019DE0000_Hades2/translations/Game/Text/en/_LootData_Apollo.en.sjson"

translations = {
    "Apollo_0058": "Thôi nào, em đâu cần phải làm thế. Ta bảo đảm lời nịnh nọt hoàn toàn không cần thiết! Nhưng ta rất vui lòng nhận nhé!",
    "Apollo_0059": "Ôi, em tốt bụng quá. Em đâu cần tặng ta {#Emph}món này!{#Prev} Ta không ngờ các vị thần Âm phủ lại lịch thiệp đến thế. Em còn hiểu phong tục của chúng ta hơn cả {#Emph}chúng ta{#Prev} nữa!",
    "Apollo_0165": "Thôi nào, ta mới là người vui chứ! Dạo này Olympus chẳng mấy khi vui vẻ. Nhưng mỗi lần nhận tin từ em, ta lại thấy mọi chuyện rồi sẽ ổn. Chẳng hiểu vì sao, nhưng ta rất biết ơn vì chúng ta đã gặp nhau.",
    "Apollo_0166": "Ta là thần Olympus, quen được người xu nịnh và bợ đỡ rồi. Ai cũng muốn được chúng ta ưu ái, phải không? Ta còn cười gật đầu giỏi hơn bất kỳ ai, kể cả cha. Nhưng với em... giá mà chúng ta có thêm dịp trò chuyện, chứ không chỉ khách sáo với nhau...",
    "Apollo_0168": "Tin tưởng nữ thần Melinoë dễ như trở bàn tay, kể cả khi không có Tiên tửu Ambrosia này lấp lánh ánh trăng từ Ngã ba Địa Giới. Ta thật lòng biết ơn vì đã gặp em, và vì em gái ta tìm thấy em đúng lúc. Em là ân huệ lớn nhất gia đình ta nhận được suốt bao năm qua.",
    "Apollo_0145": "Ta sẽ tỏa sáng đến mức khiến chúng đau mắt!",
    "Apollo_0146": "Không trốn được khỏi {#Emph}ánh sáng này{#Prev} đâu!",
    "Apollo_0148": "Đến lúc trình diễn rực rỡ rồi!",
    "Apollo_0217": "Ánh sáng mặt trời!",
    "Apollo_0218": "Nghe mà vui quá!",
    "Apollo_0219": "Ồ, {#Emph}giờ thì{#Prev} em mới cần ta giúp à?",
    "Apollo_0220": "Được thôi, ta chẳng thấy lý do gì phải từ chối!",
    "Apollo_0221": "Giờ chúng ta còn bày trò tinh quái nữa cơ!",
    "Apollo_0139": "Chọc giận ta là ta cho em tối mắt đấy, nắng nhỏ.",
    "Apollo_0140": "Ta cần nhắc em rằng vẻ ngoài tử tế này không phải lúc nào cũng thật sao?",
    "Apollo_0141": "Đừng thử thách mối quan hệ của chúng ta quá giới hạn.",
    "Apollo_0142": "Em họ à, ta cũng dễ nổi giận chẳng kém ai đâu.",
    "Apollo_0143": "Thần Olympus chúng ta đâu thể ai cũng giỏi nhất; việc đó để ta lo.",
    "Apollo_0144": "Em chẳng chừa cho ta lựa chọn nào ngoài cách phô trương sức mạnh cũ rích này.",
    "Apollo_0131": "Đương nhiên rồi!",
    "Apollo_0132": "Chắc chắn!",
    "Apollo_0133": "Đây!",
    "Apollo_0134": "Được như ý em!",
    "Apollo_0135": "Dành cho em!",
    "Apollo_0136": "Đúng vậy!",
    "Apollo_0137": "Được chứ!",
    "Apollo_0138": "Tuyệt vời!",
    "Apollo_0119": "Chào em, nắng nhỏ!",
    "Apollo_0120": "Chào em họ!",
    "Apollo_0121": "Đoán xem ai đây, nắng nhỏ?",
    "Apollo_0122": "Lời chào từ Olympus!",
    "Apollo_0123": "Ta sẵn lòng phục vụ!",
    "Apollo_0124": "Bất ngờ chưa nào!",
    "Apollo_0103": "Ta không phải lựa chọn đầu tiên của em sao?! Chắc em chưa nghe chuyện này, để ta nói cho rõ: lòng hào phóng của ta cũng có giới hạn.",
    "Apollo_0104": "Ta ít điểm yếu lắm, nhưng lòng kiêu hãnh là một trong số đó. Em đánh trúng chỗ đau rồi, giờ ta phải trả đũa thôi.",
    "Apollo_0105": "Ta đã nói hay làm gì khiến em phật ý à? Hay em không tôn trọng sức mạnh của ta? Kể cả khi nó đang quay lại chống em sao?",
    "Apollo_0106": "Ta đã cố hết sức ban sức mạnh cho em, vậy mà em từ chối à? Thần linh có lòng tự trọng nào chịu nổi chuyện đó chứ.",
    "Apollo_0107": "Thôi nào, nắng nhỏ, sao em hắt hủi ta? Em biết khi ta tổn thương thì chẳng chỉ có cảm xúc bị đau đâu.",
    "Apollo_0108": "Ta còn phải giữ thể diện chứ. Đâu thể để em gạt ta đi như một phàm nhân tầm thường chẳng có gì ngoài lời cầu nguyện!",
    "Apollo_0109": "Biết đâu một ngày nào đó tất cả chúng ta sẽ giải quyết bất đồng sáng suốt hơn. Nhưng chúng ta là thần, lại còn là người một nhà cơ mà!",
    "Apollo_0110": "Dưới vẻ ngoài tươi sáng này, ta cũng có chút máu báo thù đấy, em họ à. Dù ta biết hành động có sức nặng hơn lời nói.",
    "Apollo_0066": "Thôi, đủ rồi. Hãy cùng dốc sức theo một hướng như trước, rồi bước tiếp nào.",
    "Apollo_0067": "Chuyện vừa rồi hơi xấu xí nhỉ? Hay cả hai cùng tập trung vào việc trước mắt đi.",
    "Apollo_0111": "Tha thứ cho cơn nóng nảy vừa rồi của ta nhé? Chỉ là chút bực bội thôi. Nhà này ai cũng thế cả.",
    "Apollo_0112": "Chỉ là cơn giận bộc phát trong chốc lát thôi! Thần linh chúng ta dễ bị tổn thương thật, dù bất tử cả đám.",
    "Apollo_0113": "Lúc nãy em chỉ trêu ta thôi, phải không? Bình thường ta chịu được mấy trò đùa, nhưng dạo này ai cũng căng thẳng.",
    "Apollo_0114": "Đừng giữ cơn giận trong lòng. Chúng ta là thần mà! Chuyện gì cũng kiểm soát được, trừ cảm xúc, phải không?",
    "Apollo_0115": "Quan hệ càng bền chặt sau khi cùng vượt qua gian khó. Vậy là tình cảm của chúng ta cũng sâu đậm thêm một chút rồi!",
    "Apollo_0116": "{#Emph}Ờ{#Prev}, xin lỗi nhé, nắng nhỏ. Khi cơn thịnh nộ của ta bùng lên, tốt nhất đừng đứng gần.",
    "Apollo_0117": "Thôi, mặc kệ đám đó! Mong Ân huệ của ta giúp em tốt hơn chúng. Em xứng đáng nhận nó!",
    "Apollo_0118": "Ta đã để nỗi bực bội lấn át mình, nhưng màn trình diễn thú vị kia khiến ta tỉnh cả người!",
    "Apollo_0056": "Em dâng lễ vật cho ta ư? Bất ngờ thú vị quá, mà dạo này ta hiếm có dịp bất ngờ như thế. Này, ta cũng có món này cho em!",
    "Apollo_0057": "Món quà chu đáo quá! Em vẫn nghĩ đến ta giữa thời buổi này, thật tốt bụng. Nhưng em đâu cần phải cất công làm thế!",
    "Apollo_0260": "Là thần tiên tri, ta chắc chắn chúng ta sẽ thành công.",
    "Apollo_0261": "Tài năng di truyền trong nhà mà! Chỉ là vài người chúng ta được chia phần nhiều hơn thôi.",
    "Apollo_0262": "Nhìn em kìa, nghênh ngang đi khắp Âm phủ như thể nơi đó là của mình vậy!",
    "Apollo_0263": "Không biết em sống dưới đó bao lâu mà chẳng có lấy một tia nắng mặt trời.",
    "Apollo_0264": "Hôm nay ta có thể chiếu cho em loại ánh sáng nào đây?",
    "Apollo_0265": "Không biết em nghĩ sao, chứ ta có linh cảm chuyến này sẽ suôn sẻ!",
    "Apollo_0266": "Cầm đôi Lửa Âm trên tay thì em dễ nhận ra hơn hẳn!",
    "Apollo_0267": "Đêm nay xem chừng tối tăm, ngột ngạt thật...",
    "Apollo_0268": "Trước khi em lại lao vào trận chiến và vinh quang, để ta giúp đã!",
    "Apollo_0269": "Mong Ân huệ này sẽ hữu ích với em suốt hành trình tối nay.",
    "Apollo_0270": "Dù chúng ta ban bao Ân huệ, em đã đáp lại bằng một ân tình lớn lao.",
    "Apollo_0271": "Ta thích làm vị thần cai quản đủ thứ... bao đam mê, mà thời gian thì vô tận!",
    "Apollo_0225": "Có lẽ em đoán được đây là Ân huệ của ta, vì ánh sáng của ta sao có thể bị nhốt kín trong một gói đồ nặng thế? Chắc nó vẫn phát sáng {#Emph}đôi chút{#Prev} chứ nhỉ?",
    "Apollo_0226": "Bình thường ánh sáng của ta giúp dễ tìm ra ai cần được ban Ân huệ hay trừng phạt, nhưng em lúc nào cũng như bị bóng tối che phủ! May mà Charon biết cách liên lạc với em.",
    "Apollo_0062": "May thật, Người lái đò Âm phủ vẫn hành nghề dù thời buổi khó khăn thế này! Ta mong giá của chàng ít nhất đã rẻ hơn? Hay lại đắt hơn...",
    "Apollo_0063": "Bằng cách nào chúng ta cũng phải tìm được em, mà Charon thì rất sẵn lòng giúp. Chàng hơi kỳ quặc, nhưng chúng ta ai chẳng thế?",
    "Apollo_0227": "Người lái đò ấy có vẻ thích sưu tầm tiền xu nhỉ? Khi xử xong lão Chronos, đống Đồng Vàng của chàng sẽ thành đồ sưu tầm cực hiếm!",
    "Apollo_0228": "Chúng ta bắt đầu hợp tác với Charon từ hồi phải nghĩ cách đưa người chết phàm trần xuống cõi của cha em. Chắc đưa tin nhắn cho chúng ta dễ chịu hơn nhiều!",
    "Apollo_0064": "Em làm ta đau lòng đấy, em họ. Sau bao chuyện cùng trải qua, em lại dễ dàng gạt ta sang bên sao?",
    "Apollo_0065": "{#Emph}Ái!{#Prev} Giờ không phải lúc cãi vã vụn vặt, nhưng em chẳng cho ta lựa chọn nào khác...",
    "Apollo_0005": "Ta muốn chúng ta giải quyết mọi chuyện dưới ánh sáng ban ngày hơn, nhưng cách nào hiệu quả là được!",
    "Apollo_0006": "Những ngày tươi sáng hơn đang chờ phía trước; chỉ cần vượt qua quãng thời gian khó khăn này thôi.",
    "Apollo_0007": "Em họ, ngoài cố làm những ngày tăm tối này tươi sáng hơn, chúng ta còn biết làm gì nữa?",
    "Apollo_0008": "Tối nay em sẽ có màn trình diễn rực rỡ cho xem, em họ à.",
    "Apollo_0009": "Rồi hòa bình cũng sẽ trở lại, nhưng trước mắt chúng ta phải giữ thể diện đã.",
    "Apollo_0010": "Thay mặt tất cả chúng ta trên Olympus, ta cảm ơn em vì luôn ủng hộ.",
    "Apollo_0011": "Chắc phải có cách nào đó để buổi tối của em tươi sáng hơn đôi chút chứ?",
    "Apollo_0012": "Lên đường đi, nắng nhỏ. Mong ánh sáng của ta dẫn em đến nơi cần đến.",
    "Apollo_0013": "Nếu không thể tận hưởng ngày đẹp trời ngoài nắng thì đây là lựa chọn tốt thứ nhì!",
    "Apollo_0014": "Không có ánh sáng của ta em vẫn rạng ngời, nhưng cứ cầm chút ánh sáng này phòng khi cần nhé.",
    "Apollo_0015": "Ta muốn tặng em thơ ca và âm nhạc hơn, nhưng lúc này đành đưa em mấy thứ này vậy.",
    "Apollo_0016": "Ở đâu có ánh sáng, ở đó có hy vọng, nắng nhỏ. Chuẩn bị đón cả hai nhé!",
    "Apollo_0017": "Ôi, ta biết ngay đêm nay sẽ tuyệt vời hết sức mà!",
    "Apollo_0018": "Chỉ cần làm chúng lóa mắt một chút là kẻ địch chẳng chạm được vào em đâu.",
    "Apollo_0019": "Ta định giáng dịch bệnh xuống đầu kẻ địch, nhưng chắc em tự lo được rồi.",
    "Apollo_0020": "Xuống đó nhớ cẩn thận nhé. Đừng quên chúng ta sẽ sát cánh cùng em đến cùng.",
    "Apollo_0021": "Nhớ mang theo ánh sáng khi đi xuống chốn tối tăm ấy nhé.",
    "Apollo_0022": "Thú thật, ta khá thích màn ca múa nguy hiểm lần này đấy.",
    "Apollo_0257": "Ánh sáng của ta thường chẳng thể chạm đến những vực sâu của Âm phủ, nhưng em có thể thay đổi điều đó!",
    "Apollo_0258": "Chúng ta sẽ sát cánh đến cùng, nắng nhỏ! Dù chẳng biết {#Emph}đến khi nào{#Prev}, phải không?",
    "Apollo_0259": "Ta không thích bị lôi vào chuyện gia đình, nhưng lần này ta đâu thể {#Emph}đứng ngoài{#Prev} được.",
    "Apollo_0173": "Em đang ở ngay ngoài cổng thành Ephyra phải không? Thành phố ấy hết thuốc chữa rồi. Ta biết nơi đó từng thờ phụng cha mẹ em, nhưng dù vậy... nếu chỉ mình ta quyết định, ta sẽ san phẳng nó rồi xây lại từ đầu.",
    "Apollo_0174": "Tối nay có gì đó kỳ lạ lắm; chẳng phải ta đã trải qua một buổi tối y hệt thế này, đến từng chi tiết sao? Có khi Pháp lực của em đang tác động... miễn là không phải Chronos.",
    "Apollo_0175": "Đêm nay xem chừng tối tăm, ngột ngạt thật... Dù ta có thể soi sáng mọi kẻ địch đang mai phục, ta cũng chẳng chắc em muốn nhìn thấy chúng đâu. Cẩn thận nhé...",
    "Apollo_0167": "Lần đầu ta chủ động liên lạc với em từ nhiều đêm trước, ta đã nghĩ: {#Emph}‘Này, thêm một em họ nữa! Ta thích thế!’{#Prev} Nhưng thật lòng, ta không ngờ em lại tạo nên khác biệt lớn đến vậy. Mong là ta cũng góp phần giúp được em.",
    "Apollo_0223": "Cây trượng cầu kỳ em có là gì thế, đầu trượng còn quấn một con rắn? Lạ thật, nó... gợi ta nhớ đến một khải thị... về một kiệt tác không thể làm hại ai...",
    "Apollo_0176": "Thấy chưa, nắng nhỏ? Mỗi khi em lên đường cùng Kỷ vật Photon Hòa Âm ta tặng, ta sẽ luôn ở gần bên. Cảm giác ấm áp dễ chịu cũng đi kèm nữa!",
    "Apollo_0222": "Photon ta tặng em đã được dùng nhiều lần rồi nhỉ? Ta biết em không phải lúc nào cũng cần ánh sáng trong bóng tối như nhiều người khác, nên mừng vì nó vẫn giúp ích được cho em.",
    "Apollo_0155": "Cầm đôi Lửa Âm trên tay thì dễ nhận ra em hơn... dù lửa của em chẳng tỏa ra thứ ánh sáng thường thấy! Càng biết về em, ta càng có thêm nhiều thắc mắc!",
    "Apollo_0156": "Ta để ý kho vũ khí của em chẳng có cây {#Emph}cung{#Prev} nào! Artemis với ta nghĩ đã có thể giải quyết chuyện xấu từ xa thì cần gì phải nhúng tay vào... dù Pháp lực của em chắc cũng đủ dùng!",
    "Apollo_0069": "Em họ, sao thế gian này lại có nhiều dối trá đến vậy? Tin ta đi, đôi khi nơi này cần một vị thần của chân lý lắm. Ta rất vui lòng nhận việc ấy, mong mọi người cũng làm theo.",
    "Apollo_0070": "À mà mong em không phiền vì ta gọi em là nắng nhỏ nhé! Ta nói thật lòng đấy. Em đến từ dưới lòng đất, nhưng em có ánh sáng rực rỡ riêng. Chắc là thừa hưởng từ mẹ em.",
    "Apollo_0071": "Trong đời em có ai đặc biệt chưa? Công chúa như em hẳn có đủ kiểu người theo đuổi. Ta cũng từng có vài người, nhưng không thuộc kiểu muốn kết hôn; với lại Hera chắc cũng chẳng chấp thuận đâu...",
    "Apollo_0252": "Dù chúng ta ban bao Ân huệ, em đã đáp lại bằng một ân tình lớn lao. Olympus có những đồng minh mạnh mẽ... ít nhất là em và Heracles! Nhưng em còn có ngọn lửa nhiệt huyết mà nhiều người khác thiếu.",
    "Apollo_0247": "Ta chỉ kịp nhìn thoáng qua thôi, nhưng cách em xử lý đám đó đúng là thi ca chuyển động! Tài năng có trong dòng máu gia đình mà. Chỉ là vài người được chia phần nhiều hơn thôi.",
    "Apollo_0040": "Nắng nhỏ, giờ lại chỉ còn hai chúng ta, sau khi em tàn sát hết đám... chúng gọi là gì nhỉ? Thôi kệ, nhận cái này đi!",
    "Apollo_0149": "Tối nọ chúng ta mất liên lạc với em ở tầng sâu nhất của Âm phủ. Ngay sau đó, kẻ địch rối loạn cả lên, ít nhất cũng được một lúc. Là em làm phải không? Giỏi lắm!",
    "Apollo_0213": "Em vừa phát hiện dấu vết nguy hiểm của Chronos, giờ lại có dấu vết của Typhon nữa à? Mừng là ở chỗ {#Emph}chúng ta{#Prev} chẳng có dấu hiệu nào của chúng... ngoài đám quân rải rác và cảnh tàn phá chúng gây ra, nhưng dọn dẹp được thôi!",
    "Apollo_0224": "Trên này quyền sở hữu mọi thứ rắc rối lắm. Em biết Helios, thần Mặt Trời chứ? Chàng lại rong ruổi ngang trời trên cỗ xe như thể chẳng có gì đổi khác, nhưng thiếu {#Emph}ánh sáng của ta{#Prev} thì chàng chẳng biết làm sao! {#Emph}Eo ôi{#Prev}, Titan. Biết làm sao đây?",
    "Apollo_0214": "Mừng vì cuối cùng em cũng gặp lại anh trai nhé! Còn ta thì có {#Emph}thừa{#Prev} anh chị em, nhưng nếu em lớn lên như con một thì chắc em cần có một người. Muộn đến đâu cũng có thể bù đắp quãng thời gian đã mất.",
    "Apollo_0208": "Được cùng em đến Ngã ba Địa Giới trên cỗ xe bạc của Selene thật vui và vinh dự, em họ à. Bản ballad Artemis với ta biểu diễn... là bài đầu tiên hai chị em cùng sáng tác. Chúng ta chẳng phải lúc nào cũng hòa thuận, nhưng em đã truyền cảm hứng cho cả hai.",
    "Apollo_0212": "Dù cha mẹ em đã trở về, em vẫn không thể cứ thế đi xuống đáy Âm phủ phải không? Muốn tìm tàn dư của Chronos thì phải tái tạo hoàn cảnh lúc trước em đối đầu với lão, đại khái vậy...?",
    "Apollo_0215": "Cả ba Nữ Thần Số Mệnh đều trở về rồi, nắng nhỏ! Thật nhẹ nhõm khi lại được nghe lời tiên tri của họ. Giờ họ còn báo trước một thời đại mới, khác hẳn sắp bắt đầu. Còn khối thời gian để chuẩn bị... nhưng trước hết cứ tận hưởng hiện tại nhé?",
    "Apollo_0003": "Nào, cho chúng xem màn trình diễn rực rỡ khiến chúng nhớ mãi!",
    "Apollo_0004": "Chỉ cần đợi một lát thôi, em sẽ rạng ngời cho xem!",
    "Apollo_0083": "Chuyến vượt biển đến đây thế nào rồi, nắng nhỏ? Giá mà chúng ta có thể đưa em đến đây bằng phép thần thông, nhưng bầu trời cũng hiểm trở chẳng kém mặt biển... chắc em nhận ra rồi.",
    "Apollo_0153": "{#Emph}Ờ{#Prev}, tình hình bắt đầu rắc rối rồi. Một khe nứt lớn vừa mở ra dưới chân núi, bên trong có thứ gì đó... thứ gì đó rất to. Và nó đang {#Emph}thở... {#Prev}chắc là thân thiện nhỉ...?",
    "Apollo_0030": "Ta thích làm vị thần cai quản đủ thứ. Ánh sáng, thơ ca, âm nhạc, chữa lành... bao đam mê, mà thời gian thì vô tận. Sao phải chỉ chọn nghề rèn hay gì đó tương tự chứ?",
    "Apollo_0250": "Artemis bảo em khá có năng khiếu âm nhạc! Đúng là tài năng di truyền trong nhà; cha mẹ em cũng biết thưởng thức nhờ Orpheus làm nhạc công trong cung. Cậu ấy là học trò giỏi nhất ta từng dạy!",
    "Apollo_0052": "Được rồi, nắng nhỏ... thôi hát hò múa may, để ta tặng em thứ thật rực rỡ lần này nhé. Nhìn đây!",
    "Apollo_0053": "Trên Olympus chẳng có riêng một thần báo thù nào, vì đôi lúc trách nhiệm ấy thuộc về tất cả chúng ta. Cầm lại thứ vốn thuộc về em đi.",
    "Apollo_0076": "Cha ta, Zeus, đến gặp em rồi à? Ta phải nói là ngài đã ban {#Emph}ân huệ{#Prev} cho em mới đúng! Ngài là thần cai quản đủ thứ. Nhưng khi quyền cai trị của chúng ta bị đe dọa, dù chỉ bị xúc phạm, chẳng ai chiến đấu dữ dội hơn ngài.",
    "Apollo_0077": "Bên dưới vẻ thân thiện của chú Poseidon là sự hung dữ mà ta đã học cách tránh xa. Nếu ngài ấy đã tiếp sức cho em bằng sức mạnh đại dương thì em được lợi rồi. Tận dụng cho tốt nhé!",
    "Apollo_0078": "Ta khuyên em chuyện này về nữ thần Aphrodite tốt bụng nhé: đừng để nàng làm em xao nhãng. Nàng thường nói về tình yêu và sắc đẹp, nhưng xung đột cũng chẳng xa lạ gì với nàng. Có lẽ quyền năng của ta sẽ cân bằng được sức mạnh của nàng.",
    "Apollo_0079": "{#Emph}À{#Prev}, em gặp mẹ kế của ta rồi sao? Ta may mắn được yêu thương, nhưng Hera thì... ta chẳng phải đứa con bà yêu quý nhất. Chỉ cần đừng để ai khiến bà nghĩ em là con của Zeus, em sẽ ổn thôi.",
    "Apollo_0080": "Này, em đã khiến bà Hestia già cả chịu xuất hiện rồi! Bình thường bà chẳng muốn dính dáng đến ai trong chúng ta, nhưng chuyện Chronos làm bà nổi giận thật. Hay lắm!",
    "Apollo_0081": "Khi Artemis mới kể về em, ta không khỏi nghĩ đến Demeter. Bà không thể ở bên mẹ em khi Chronos ra tay, nhưng ta biết bà sẽ làm mọi điều có thể vì em.",
    "Apollo_0229": "Hephaestus đang dốc sức củng cố phòng tuyến, nên ta mừng vì em đã gặp chàng. Đừng hiểu lầm vẻ cộc cằn ấy nhé! Chàng ít khi ra ngoài, nhất là dạo này.",
    "Apollo_0171": "Nói riêng nhé, ta chưa từng thấy Ares vui đến thế như dạo gần đây. Chắc ta đoán được lý do rồi. Cuộc chiến chúng ta đang tiến hành... đúng là một trận ra trò, ngay cả với ngài ấy.",
    "Apollo_0082": "Em đến nơi nhanh hơn ta tưởng, chắc Hermes đã giúp em một tay! Cậu ta nhanh thật, nhưng ta chẳng bao giờ moi được câu trả lời thẳng thắn về bất cứ chuyện gì...",
    "Apollo_0230": "Em có thể trông cậy vào hầu hết chúng ta, nhưng Dionysus thì ta không dám hứa; ta còn chẳng biết chàng đang ở đâu! Ta cũng thích tiệc tùng đúng dịp như mọi người, nhưng với Thần Rượu Vang thì dịp thích hợp là {#Emph}mọi lúc{#Prev}.",
    "Apollo_0034": "Nếu Artemis nói chuyện cộc lốc hay bất lịch sự với em thì đừng để bụng nhé. Cô ấy đối xử với ai cũng vậy. Xưa nay vốn thích ở một mình, đến lúc cần thì chẳng ai biết cô ấy ở đâu.",
    "Apollo_0038": "Chị cùng cha khác mẹ Athena biết rõ anh trai em, nhờ ta gửi lời hỏi thăm. Chị ấy đang bận lo phòng thủ, chỉ huy tiền tuyến và đủ thứ khác! Chị ấy tiếc vì không thể giúp em chuyện đó.",
    "Apollo_0150": "Cyclops mù Polyphemus đang chặn đường em à? Chẳng biết ánh sáng của ta làm gì nổi {#Emph}hắn{#Prev}, nhưng ít nhất ta có thể giúp em đến đó nguyên vẹn.",
    "Apollo_0151": "Chúng ta đã xác nhận Eris {#Emph}lảng vảng{#Prev} quanh đây. Cô ta đến từ cõi của em chứ không phải chúng ta, nên chắc em biết vì sao cô ta tự tiện xuất hiện! Dù xưa nay cô ta vẫn vậy. Ai đó phải đuổi cô ta đi thôi...",
    "Apollo_0152": "Chính Prometheus đang dẫn đầu cuộc tấn công vào chúng ta... Một trong số ít đồng minh của chúng ta giữa các Titan giờ đã thành kẻ thù cay nghiệt. Tất cả chỉ vì cách chúng ta đối xử với hắn! Hoặc vì... hắn biết sau cùng phe nào sẽ thắng...",
    "Apollo_0211": "Ta không ngờ chúng ta lại để Prometheus tiếp tục tấn công như thế này. Đúng là một mối liên minh kỳ quặc: tất cả chỉ để em đi lại con đường từng dẫn đến Typhon, rồi đối đầu với tàn dư của con quái vật trên đỉnh núi như trước...?",
    "Apollo_0216": "Nếu Prometheus thật sự biết trước mọi chuyện sẽ xảy ra như vậy... sao hắn lại chặn đường em, chiến đấu quyết liệt rồi hết lần này đến lần khác bị đánh bại...? Trừ phi một thời đại mới chẳng thể bắt đầu theo cách nào khác...",
    "Apollo_0172": "Ta chẳng biết chính xác vì sao, nhưng đêm nay khiến ta nhớ lại lần đầu em liên lạc với ta trong khu rừng ấy. Chắc có thế lực kỳ lạ nào đang tác động, hoặc chỉ là trí tưởng tượng của ta thôi nhỉ?",
    "Apollo_0177": "Khoan, em đang ở ngay trên Olympus rồi, nắng nhỏ! Gần chúng ta đến thế, vậy mà ta biết đau lòng rằng chặng khó khăn nhất vẫn còn phía trước. May mà ta có thứ tốt nhất dành cho em ngay đây!",
    "Apollo_0251": "Không thể tin nổi chúng ta lại để đám Satyr tràn ngập sườn núi... đúng là chỉ Dionysus mới định kết bạn với chúng. Còn ta thì chẳng may mắn như thế, tin ta đi.",
    "Apollo_0051": "Thế gian từng trải qua chuyện còn tệ hơn {#Emph}thế này,{#Prev} em họ à! Ít nhất người ta kể vậy; ta chưa từng thấy cảnh nào kinh khủng đến thế. Dù sao thì chúng ta vẫn xoay xở được, phải không?",
    "Apollo_0084": "Khi Artemis kể chuyện của em, ta tưởng đó chỉ là một trò đùa của cô ấy. Tự mình đi đối đầu Titan ư, {#Emph}thôi nào.{#Prev} Nhưng chuyện đó {#Emph}đúng là{#Prev} kiểu mà một đứa con của Hades ôm mối thù có thể làm...",
    "Apollo_0085": "Vậy là em được chọn giữa việc xuống Âm phủ truy đuổi Chronos hoặc đến đây cứu chúng ta! Nói thật, mọi người còn tranh luận xem lựa chọn nào sáng suốt hơn. Nhưng chắc em hiểu việc mình làm hơn chúng ta.",
    "Apollo_0047": "Vậy em là phù thủy à? Nghề này thú vị đấy. Những câu thần chú tạo Pháp lực của em có nhịp điệu và sức mạnh riêng. Thơ ca cũng vậy! Chỉ khác là phép màu của thơ chỉ lay động trái tim.",
    "Apollo_0255": "Người ta thường nói chẳng có gì mới dưới mặt trời, nhưng ta chưa từng thấy vũ khí nào giống thứ em đang cầm! Hephaestus bảo đó là Vũ Khí Màn Đêm huyền thoại. Ấn tượng đấy!",
    "Apollo_0044": "Phàm nhân trông cậy vào chúng ta để được dẫn đường và truyền cảm hứng. Gần đây hẳn họ phải {#Emph}kinh hãi{#Prev} trước những gì chứng kiến! Có vẻ một nửa đã quay lưng với chúng ta. Mong khi chuyện này kết thúc, {#Emph}nửa còn lại{#Prev} vẫn đứng về phía ta.",
    "Apollo_0240": "Phàm nhân đúng là giống loài nhát gan mà lại thích giết hại lẫn nhau! Có cuộc chiến nọ cách đây không lâu khiến cả các thần chúng ta quay sang đối đầu. Ta thử dẹp yên bằng dịch bệnh, cung tên các kiểu, nhưng {#Emph}không được!{#Prev} Cha muốn để nó diễn ra.",
    "Apollo_0241": "Ta vẫn luôn muốn thăm Nhà Hades, dù cha mẹ em có đội cận vệ hoàng gia mà ta {#Emph}có thể{#Prev} đã lỡ tay đưa về cõi của họ hơi sớm. Nếu chúng ta tình cờ gặp nhau ở đó thì sẽ ngượng lắm...",
    "Apollo_0246": "Ta không thích bị kéo vào những mối hiềm khích vụn vặt trong gia đình, nhất là khi thế hệ lớn tuổi dường như chẳng có việc gì hay hơn để làm. Nhưng em với ta đâu thể đứng ngoài lần này, phải không?",
    "Apollo_0028": "Bảo sao Chronos ghét chúng ta. Đúng là nhà này ai cũng có tính khí khó chiều, nhưng dù kỳ quặc đến đâu thì chúng ta vẫn là gia đình và luôn sát cánh bên nhau. Titan chẳng thể hiểu được điều đó.",
    "Apollo_0031": "Ta hơi xấu hổ khi phải nhận mình là thần tiên tri, trong số bao việc khác. Đáng lẽ ta phải thấy trước chuyện Titan này chứ! Nhưng ta đã không thấy... và lão Chronos khiến chúng ta trở tay không kịp.",
    "Apollo_0032": "Là thần tiên tri, ta chắc chắn chúng ta sẽ thành công. Chỉ là thành công bằng cách nào thì ta chưa thể nói chắc. Lời tiên tri là thế đấy! Phần lớn thời gian chỉ khiến người ta bực mình.",
    "Apollo_0049": "Hôm nay ta có thể chiếu loại ánh sáng nào cho em đây? Ánh sáng cứng, ánh sáng dịu, ánh sáng chói lòa, hay thứ cuối cùng một phàm nhân nhìn thấy... em muốn loại nào cũng có!",
    "Apollo_0050": "Em có bao giờ tự hỏi ánh sáng thật sự là gì không, em họ? Chẳng thể nắm trong tay, cũng chẳng nặng chút nào, vậy mà ở quanh ta khắp nơi! Bí ẩn thật... ta đang chờ phàm nhân tìm ra đấy!",
    "Apollo_0042": "Em hợp với ban đêm hơn nhỉ, nắng nhỏ? Quen bóng tối rồi. Còn ta thuộc kiểu người của ban ngày, nhưng mỗi người một sở thích mà.",
    "Apollo_0043": "Không biết em sống dưới đó bao lâu mà chẳng có lấy một tia sáng thế nào. Hai thế giới khác nhau thật, nhưng đôi khi những điều tốt đẹp xuất hiện khi chúng giao nhau.",
    "Apollo_0029": "Vậy là em sinh ra và lớn lên trong một khu rừng hẻo lánh dưới đó à? Chẳng có tiện nghi hay phàm nhân thờ phụng... khi giải quyết xong chuyện xấu xí này, em còn nhiều điều phải trải nghiệm lắm.",
    "Apollo_0048": "Không biết ở Vực Erebus có gì vui để làm lúc rảnh rỗi, khi em không phải miệt mài luyện tập để tiêu diệt đám Titan đáng ghét nhỉ. Hẳn phải có gì đó chứ...",
    "Apollo_0072": "Em đang ở xó xỉnh nào thế, nắng nhỏ? Cứ như đang dưới đáy biển vậy. Chỗ nào cũng tối om, mà em biết rồi đấy, ta luôn có cách chữa trị chuyện đó.",
    "Apollo_0244": "Em đang ở Cánh đồng U Buồn. Không biết hoa dạ lan hương có mọc ở đó không... loài hoa của vị hoàng tử hiền hòa đã khuất từ lâu. Khi Âm phủ mở cửa trở lại, có lẽ ta sẽ đi tìm chàng.",
    "Apollo_0073": "Trời đất, em đã lên {#Emph}Mặt đất{#Prev} rồi sao, nắng nhỏ? Ta tưởng thân phận của em không cho phép em sống ở trên này chứ!",
    "Apollo_0074": "Ngày trước, mặt đất dễ chịu hơn nhiều. Nhưng từ sau cuộc vây hãm, chú Poseidon dốc toàn lực gây động đất với thiên tai để đáp trả. Khuấy đảo cả vùng đất như thể nó là tô trộn của ngài vậy.",
    "Apollo_0157": "Em họ, lần trước ta kiểm tra thì em đang trên đường đến Olympus mà? Chắc bị đám tay sai Titan chặn lại rồi. Đừng bỏ cuộc nhé! Mà nếu bỏ cuộc thật thì em đã chẳng ở đó rồi nhỉ.",
    "Apollo_0088": "Lời chào từ Olympus, lại gặp em rồi, nắng nhỏ! Chúng ta chưa thể đến chỗ Titan, nhưng nếu em thật sự định ngăn hắn, ít nhất ta cũng có thể soi đường cho em xuống đó.",
    "Apollo_0060": "Trông em hơi mệt mỏi, nắng nhỏ. Ta là thần chữa lành mà ngay cả ta cũng khó giúp em nhiều trong tình trạng này. Nhưng cứ để ta xem có thể làm gì nhé.",
    "Apollo_0061": "{#Emph}Eo ôi{#Prev}, em họ trông chẳng khỏe chút nào. Hoặc em cố quá sức, hoặc kẻ địch đánh trúng em quá nhiều. Có khi cả hai. Nhớ giữ gìn nhé?",
    "Apollo_0234": "Ta cũng biết chút ít về y thuật, nắng nhỏ, và theo đánh giá chuyên môn thì các chỉ số sinh tồn của em đang không ổn lắm. Nhưng có lẽ ta vẫn giúp em khỏe lại được...",
    "Apollo_0054": "Tối nay em mới bắt đầu cuộc hành trình thôi à, nắng nhỏ? Không biết em nghĩ sao, chứ ta có linh cảm chuyến này sẽ suôn sẻ!",
    "Apollo_0055": "Đêm còn dài mà ta đã tìm thấy em rồi. Chẳng lẽ ta đang học được chút tài lần dấu của em gái mình sao?",
    "Apollo_0231": "Trước khi em lại lao vào trận chiến và vinh quang, để ta giúp đã! Mong Ân huệ này sẽ hữu ích với em suốt hành trình tối nay.",
    "Apollo_0023": "Cứ kiên nhẫn, nắng nhỏ. Titan tưởng đã dồn chúng ta vào đường cùng, nhưng tình hình ở đây vẫn trong tầm kiểm soát! Chỉ là đôi bên đang giằng co chút thôi.",
    "Apollo_0046": "{#Emph}Ôi trời{#Prev}, cuộc chiến khốn kiếp này chẳng chừa thời gian cho âm nhạc, thơ ca hay niềm vui nào trong đời. Dù sao thì nó cũng khiến gia đình gần gũi hơn, ta nghĩ vậy!",
    "Apollo_0026": "Chronos đang âm mưu gì đó, nhưng ngay cả Athena cũng chẳng biết là gì. Các đợt tấn công Olympus của lão đều thất bại, dù vẫn khiến chúng ta bận tối mắt. Tiếp theo lão định làm gì...?",
    "Apollo_0024": "Ai mà ngờ chúng ta lại gây chiến với chính ông nội mình. Nhưng đừng đề cao Chronos như thế. Lão làm ô danh dòng dõi chúng ta; là một Titan đáng ghét, chẳng phải thần linh. Chẳng phải người nhà.",
    "Apollo_0025": "Ta cứ mong lão Chronos và đồng bọn cuối cùng cũng hiểu lẽ phải, nhưng than ôi. Có lẽ chúng ta phải tiếp tục chiếu sáng vào mặt họ thêm một thời gian nữa.",
    "Apollo_0158": "Em vừa giáng một đòn mạnh vào quân Titan, nhưng chúng đã bắt đầu tập hợp lại. Dù vậy, những chiến thắng như thế hẳn khiến chúng run sợ. Đẩy lùi chúng thôi!",
    "Apollo_0159": "Nghe nói em hạ được Chronos rồi, phải không nắng nhỏ? Ít nhất là tối qua. Titan bất tử là thế đấy! Chẳng chịu nằm yên lâu đâu. Nhưng chị gái ta bảo em đã có cách đối phó...",
    "Apollo_0154": "Em có bao giờ tự hỏi Typhon, Cha của Muôn Loài Quái Vật, thật sự to lớn đến mức nào chưa? Chỉ cần ghé qua đây là em sẽ biết ngay! Còn trước lúc đó, {#Emph}ờ{#Prev}, chúng ta... đành cố chống đỡ hắn vậy!",
    "Apollo_0160": "Nghe tiếng gầm đầy thù hận của hắn, hẳn Typhon căm ghét cha ta chẳng kém Chronos. Nhưng chúng thật sự đang hợp tác sao? Quái vật như thế làm sao chịu nghe lệnh một Titan hay bất kỳ ai được.",
    "Apollo_0162": "Ta vẫn khó tin em đã {#Emph}hạ được{#Prev} hắn, nắng nhỏ! Typhon đáng lẽ phải cần cả nhà ta hợp sức mới đánh bại được. Mà đúng là vậy, chỉ có điều những người còn lại phải bận tay chống đàn quái vật của hắn. Hắn khiến chúng ta xoay như chong chóng.",
    "Apollo_0161": "Nếu Typhon cứ quay lại, chẳng mấy chốc ngọn núi này sẽ chẳng còn gì để trèo lên. Cha ta và Nữ hoàng Hera có kế hoạch phòng khi tình hình tệ hơn nữa, nhưng ta lạc quan hơn về kế hoạch của em...",
    "Apollo_0163": "Chúng ta còn cầm chân được Typhon một thời gian, nhất là giờ em đã cho chúng ta thấy phải làm thế nào, {#Emph}nắng nhỏ{#Prev}. Em định đi tìm Chronos tiếp, phải không? Tống khứ {#Emph}lão ta{#Prev} đi chắc chắn chẳng hại gì.",
    "Apollo_0206": "Ta biết em chẳng hay than vãn, nhưng chắc hẳn khó khăn lắm khi em đến cung điện này lúc bình minh vừa ló... Ánh sáng hẳn chói hơn nhiều so với những gì em quen. Giờ chính chúng ta cũng chẳng quen với nó, do bão tố của Typhon.",
    "Apollo_0207": "Chronos hẳn nghĩ chẳng gì ngăn nổi lão nếu thả Typhon ra, nhưng lão đã lầm. Dốc hết sức tấn công lão rồi kết thúc chuyện này thôi, nắng nhỏ.",
    "Apollo_0209": "Vậy giờ chúng ta đang tìm cách ngăn cả {#Emph}khả năng{#Prev} Typhon có thể áp đảo nơi này sao? Quân Titan bằng cách nào đó cũng nằm trong kế hoạch mới. Nếu em tham gia thì {#Emph}ta cũng{#Prev} tham gia. Chắc vài buổi tối tới sẽ thú vị hơn đấy!",
    "Apollo_0035": "Em từng theo học Hecate, Phù thủy Ngã ba Địa giới à? Ở đây ai cũng kính trọng bà, dù dạo này chúng ta chẳng gặp bà. Gần đây ta thường nói xấu các Titan, nhưng chợt nhớ ra đâu phải ai trong số họ cũng xấu.",
    "Apollo_0036": "Em biết không, em gái Artemis của ta cũng từng học với Hecate! Nhưng học {#Emph}môn gì{#Prev} thì ta chịu. Ta vẫn nhớ hai người họ tru lên mỗi đêm như bầy sói, {#Emph}hề hề{#Prev}. Nghĩ lại cũng hơi rợn người!",
    "Apollo_0037": "Ta chưa bao giờ thân thiết với cha em, nhưng có lẽ em cũng vậy. Ông ấy lúc nào cũng có vẻ u sầu, dù rất quan tâm đến người nhà. Rồi công lý sẽ được thực thi cho ông ấy thôi.",
    "Apollo_0164": "Ta không nghĩ tình hình có thể nguy ngập hơn, nhưng nếu các Nữ Thần Số Mệnh thật sự biến mất thì... lời tiên tri của họ về tương lai có thể không thành hiện thực. Họ từng phán gia đình ta sẽ cai trị thế gian mãi mãi... lỡ họ sai thì sao?",
    "Apollo_0210": "Dù em khiến Chronos hiểu lẽ phải, các Nữ Thần Số Mệnh vẫn mất tích. Chẳng lẽ ta phải tin lão không biết họ ở đâu sao? Chuyện này không thể nào là điều họ mong muốn hay tiên báo...",
    "Apollo_0045": "Chúng ta sẽ tiếp tục chống đỡ trên đỉnh núi này, miễn là em vẫn vững vàng... dù em đang ở bất cứ nơi nào! Nhớ giữ gìn nhé?",
    "Apollo_0089": {"DisplayName": "{#Emph}Ờm{#Prev}, xin chào cô em họ đáng kính! Ta đến đây cùng chính vị thần sấm chớp, Đức Vua Olympus vĩ đại, người chú đáng kính của em và cũng là người cha lừng danh của ta: Zeus!"},
    "Zeus_0100": {"DisplayName": "Ồ, {#Emph}ha ha{#Prev}, cha con ta với cháu gái đã thân thiết đến mức chẳng cần khách sáo vậy đâu! Nhưng nhân lúc cháu ở đây, sao ta không cho cháu thấy chúng ta khiến {#Emph}ánh sáng {#Prev}lóe lên trong {#Emph}sấm chớp thế nào nhỉ?"},
    "Apollo_0093": {"DisplayName": "Ta biết em đang mong ta, nắng nhỏ à, nhưng {#Emph}mẹ kế vinh quang{#Prev} của ta, Đức Nữ hoàng, muốn nói chuyện! Ngay bây giờ... nên ta phải nhường chỗ thôi nhé?"},
    "Hera_0104": {"DisplayName": "Thấy chưa, cháu yêu? Trên Olympus vẫn có người biết kính trọng Nữ hoàng cho phải phép. Đừng tìm cách khiến thần dân yêu quý mình; cứ khiến chúng hơi khiếp sợ là được."},
    "Apollo_0091": {"DisplayName": "Em họ à, chú của chúng ta với ta đang bàn xem nên xử trí đám phàm nhân quay lưng với thần linh thế nào... Ta nghĩ để dịch bệnh hoành hành một năm là đủ trả món nợ ấy! Nhưng ngài Poseidon đây cho rằng phải {#Emph}làm cho ra trò..."},
    "Poseidon_0042": {"DisplayName": "Đã có cơ hội thì sao lại {#Emph}không {#Prev}làm cho ra trò, cháu trai mảnh khảnh của ta? Ta sẽ rung chuyển mặt đất đến mức nó nuốt chửng lũ phàm nhân đáng ghét, rồi đưa thẳng chúng vào vòng tay cô em họ xinh đẹp của cháu!"},
    "Apollo_0097": {"DisplayName": "Tất cả chúng ta đều mong em thành công, em họ à, nhưng chẳng ai mong điều đó hơn quý cô Demeter... Nghĩ lại mới thấy em là cháu ngoại của bà ấy. {#Emph}Ờm{#Prev}, khoan đã, bà muốn tự mình nói chuyện với em kìa!"},
    "Demeter_0104": {"DisplayName": "Cảm ơn con đã giúp bà lên tiếng, Apollo. Khi nào cần, bà sẽ gọi con. Còn giờ, cháu gái ta cần sức mạnh của chúng ta, chứ không cần lời đường mật."},
    "Apollo_0099": {"DisplayName": "Ta, {#Emph}ờm{#Prev}, đang nói đến đâu rồi nhỉ, em họ? Aphrodite đây dường như chẳng hiểu thế nào là {#Emph}trò chuyện riêng tư. {#Prev}Thưa quý cô, hay là nàng cùng tham gia nhé?"},
    "Aphrodite_0095": {"DisplayName": "Ôi Apollo yêu dấu, {#Emph}tất nhiên{#Prev} ta {#Emph}luôn luôn {#Prev}muốn tham gia chuyện trò với chàng, {#Emph}nhất là {#Prev}những cuộc trò chuyện riêng tư! Ai mà trách ta được chứ? Tình yêu và ánh dương vốn đi đôi với nhau mà!"},
    "Apollo_0101": {"DisplayName": "Em họ à, em với Hephaestus có một điểm chung: cả hai dường như chẳng được thấy ánh mặt trời mấy! Ta vẫn thường dụ anh ấy ra khỏi hang, nhưng thường chẳng thành công. Lần này thì {#Emph}khác{#Prev}!"},
    "Hephaestus_0126": {"DisplayName": "Thôi đi ông bạn, trước khi cô phù thủy nhận ra trò của cậu! Giờ thì qua đây làm việc có ích đi, không là tôi nhét cái búa này vào đúng chỗ {#Emph}cậu chẳng mấy khi thấy nắng{#Prev} đấy!"},
    "Apollo_0095": {"DisplayName": "Cô Hestia vĩ đại cũng đến đây rồi, em họ! Sau bao chuyến đi khắp thế gian, cô trở về để trao trí tuệ cho chúng ta lúc nguy nan. Nơi nào lửa bếp của cô rực cháy, nơi đó cũng có ánh sáng của ta. Và cùng nhau, chúng ta có thể... {#Emph}ồ—!"},
    "Hestia_0152": {"DisplayName": "{#Emph}Thôi {#Prev}đi, Cậu Bé Vàng, không có thời gian diễn tuồng đâu! Chi bằng cho cô em họ bé bỏng của cậu thấy chúng ta thắp sáng màn đêm thế nào? Không thể để con bé mò mẫm trong bóng tối được!"},
    "Apollo_0169": {"DisplayName": "Ares với ta vừa nói chuyện về việc hai anh em hợp sức nhất khi đứng cùng một phe trong chiến tranh. Này em trai, đây là kế hoạch công phu để khiến chúng ta thân thiết hơn đấy à?"},
    "Ares_0159": {"DisplayName": "Ta nghĩ chiến tranh đúng nghĩa khiến tất cả chúng ta bộc lộ mặt tốt nhất, cả em nữa, Apollo, và cả ta. Gian khổ nơi chiến trường rèn nên tình thân bền chặt! Và tạo ra những phước lành hùng mạnh."},
}

translations.update({
    "Melinoe_0168": {"DisplayName": "Là anh ấy..."},
    "Melinoe_0229": {"DisplayName": "Anh ấy đến rồi..."},
    "Melinoe_1470": {"DisplayName": "Anh họ..."},
    "Melinoe_1471": {"DisplayName": "Apollo..."},
    "MelinoeField_3124": {"DisplayName": "Apollo...!"},
    "Melinoe_0630": {"DisplayName": "Chỉ là một câu thần chú thôi, thêm một câu nữa thôi. Mười từ... {#Emph}Nhân danh Hades! Olympus, con xin nhận thông điệp này!"},
    "Melinoe_0502": {"DisplayName": "Anh họ Apollo! Em biết ơn anh vì sự ấm áp, lòng tốt và bao lần giúp đỡ! Xin anh nhận món quà này!"},
    "Melinoe_0503": {"DisplayName": "Không biết vẻ lấp lánh của chai này có phải do chính thần ánh sáng ban cho không nhỉ? Hay là nên gửi nó về cho anh ấy ngay bây giờ!"},
    "MelinoeField_1759": {"DisplayName": "Apollo rực rỡ, tài năng của anh hẳn khiến người đời ngưỡng mộ. Em thật vinh dự khi được anh chia sẻ chúng. Đây, tặng anh!"},
    "MelinoeField_1760": {"DisplayName": "Người ta bảo Tiên tửu Nectar này sáng như mặt trời, anh họ à. Mong là nó xứng với lời đồn, nhất là giờ đã thuộc về anh! Em thật may mắn khi có anh làm bạn."},
    "MelinoeField_1761": {"DisplayName": "Anh họ yêu quý! Anh là người đầu tiên trong số các vị thần Olympus chủ động tìm đến em. Em đi được đến hôm nay là nhờ anh, và dù có chuyện gì, em cũng không quên lòng tốt của anh."},
    "MelinoeField_1762": {"DisplayName": "Anh họ thân mến, chắc anh có thừa Tiên tửu Nectar. Nhưng giá trị của mỗi chai nằm ở tấm lòng người tặng. Xin anh nhận chai này; em nghĩ nó sẽ có ích."},
    "MelinoeField_3827": {"DisplayName": "Apollo, anh họ, bạn của em! Chai Tiên tửu Ambrosia này khiến em nhớ ngày đầu tiên được thấy cung điện của cha anh và nghe khúc ca tuyệt diệu. Cảm ơn anh đã cho em nhìn thế giới bằng ánh mắt mới và luôn tin tưởng em."},
    "Melinoe_1734": {"DisplayName": "Cảm ơn anh nhé, anh họ!"},
    "Artemis_0464": {"DisplayName": "Chào cậu em trai!"},
    "Artemis_0465": {"DisplayName": "Apollo?!"},
    "Chronos_1261": {"DisplayName": "Thứ ánh sáng chết tiệt này chói quá..."},
    "Chronos_1262": {"DisplayName": "Ánh sáng của {#Emph}Mặt Trời ư?!"},
    "Zagreus_0360": {"DisplayName": "Apollo...!"},
    "Zagreus_0361": {"DisplayName": "Chào Apollo...!"},
})

source = SRC.read_text(encoding="utf-8-sig")
OUT.parent.mkdir(parents=True, exist_ok=True)
translations = {
    key: value if isinstance(value, dict) else {"DisplayName": value}
    for key, value in translations.items()
}
OUT.write_text(apply_translation_to_sjson(source, translations), encoding="utf-8")
sys.stdout.reconfigure(encoding="utf-8")
print(f"Đã dịch {len(translations)} câu thoại Apollo: {OUT.relative_to(ROOT)}")
