# -*- coding: utf-8 -*-

translations_0_100 = {
  "Accio": "Bùa Triệu Tập (Accio)",
  "Accio_desc": "Có thể kéo nhiều loại đồ vật và kẻ địch về phía người thi triển. Một số vật thể đặc biệt nặng hoặc có chứa ma thuật sẽ đòi hỏi phải duy trì niệm chú liên tục mới có thể kéo lại gần. Khi mục tiêu bị ảnh hưởng được kéo đến vị trí của bản thân, bạn sẽ tự động thi triển Wingardium Leviosa, nhờ đó không cần thao tác thêm mà vẫn có thể tiếp tục khống chế mục tiêu đang bay lơ lửng.",
  "Accio_gameplay_desc": "Có thể kéo nhiều loại đồ vật và kẻ địch về phía người thi triển. Một số vật thể đặc biệt nặng hoặc có chứa ma thuật sẽ đòi hỏi phải duy trì niệm chú liên tục mới có thể kéo lại gần. Khi mục tiêu bị ảnh hưởng được kéo đến vị trí của bản thân, bạn sẽ tự động thi triển Wingardium Leviosa, nhờ đó không cần thao tác thêm mà vẫn có thể tiếp tục khống chế mục tiêu đang bay lơ lửng.",
  "AccioActivity_Desc": "Sử dụng \"Bùa Triệu Tập (Accio)\", kéo quả cầu về vị trí càng gần càng tốt mà không làm rơi khỏi sân để ghi điểm.",
  "AccioActivity_Title": "Triệu Tập Tỉ Thí (Accio)",
  "AccioBall_CourtRules": "Luật Sân Đấu",
  "AccioBall_PlayersTurn": "Đến lượt của {0}",
  "AccioBall_Tie": "Hòa Trận Triệu Tập Tỉ Thí",
  "AccioBall_Winner": "Người chiến thắng: {0}",
  "AMFillPotion": "Thuốc Tập Trung",
  "AMFillPotion_desc": "Giảm thời gian hồi chiêu của các bùa chú cho người uống.",
  "AutoDamagePotion": "Thuốc Sấm Sét Thunderbrew",
  "AutoDamagePotion_desc": "Sau khi uống sẽ tạo ra một cơn bão sấm sét xung quanh bản thân, làm choáng váng và sát thương kẻ địch xung quanh.",
  "Avadakedavra": "Lời Nguyền Chết Chóc (Avada Kedavra)",
  "Avadakedavra_Desc": "Lập tức tiêu diệt kẻ địch.",
  "AvadaKedavra_gameplay_desc": "Lập tức tiêu diệt kẻ địch.",
  "Bombarda_gameplay_desc": "Gây sát thương lớn khi đánh trúng, vụ nổ tiếp sau đó có thể phá hủy các chướng ngại vật cỡ lớn và sát thương kẻ địch xung quanh.",
  "CastBottomSpell": "Dùng Thao Tác Dưới",
  "CastLeftSpell": "Dùng Thao Tác Trái",
  "CastRightSpell": "Dùng Thao Tác Phải",
  "CastTopSpell": "Dùng Thao Tác Trên",
  "Category_Potion": "Công Cụ",
  "Category_Potion_desc": "Có thể gán độc dược và thực vật ma thuật vào Vòng Xoay Công Cụ {ItemMenuButton}. Sau khi mua công thức độc dược và gói hạt giống tại Làng Hogsmeade, có thể chế tạo công cụ tại Bàn Chế Độc Dược và Bàn Trồng Trọt. Cũng có thể mua trực tiếp từ các thương nhân.",
  "Category_Potions": "Công Cụ",
  "Category_Potions_desc": "Độc dược và thực vật ma thuật bạn đã thu thập.",
  "Category_Spell": "Bùa Chú",
  "COM_05_LeviosoPuzzles_Journal01": "Zenobia Noke đang vô cùng lo lắng vì những viên đá Gobstone của mình bị mất tích.",
  "COM_05_LeviosoPuzzles_Journal02": "Nói chuyện với Zenobia Noke.",
  "COM_05_LeviosoPuzzles_QuestAvailable_Journal": "Zenobia Noke đang vô cùng lo lắng vì những viên đá Gobstone của mình bị mất tích.",
  "COM_05_LeviosoPuzzles_QuestComplete_Journal01": "Tôi đã gặp cô bé già dặn trước tuổi Zenobia Noke cạnh cầu thang dẫn đến lớp học Phòng Chống Nghệ Thuật Hắc Ám. Theo lời Zenobia, cô bé từng mang bộ sưu tập đá Gobstone quý giá của mình đến trường, nhưng chất dịch hôi hám phun ra từ đá Gobstone đã khiến các bạn học khác bức bối khôn cùng, cuối cùng họ thậm chí đã cướp lấy đá Gobstone của Zenobia và giấu trên những nơi cao trong lâu đài mà cô bé không với tới được. Zenobia hỏi tôi có sẵn lòng giúp tìm lại những viên đá ấy không. Tôi bảo rằng mình sẽ cân nhắc. Dù sao đi nữa, ít nhất tôi cũng có thể nhân cơ hội này để khám phá những khu vực khác của Lâu đài Hogwarts.",
  "COM_05_LeviosoPuzzles_QuestComplete_Journal02": "Dù ban đầu định trả lại đá Gobstone cho Zenobia Noke, nhưng vào phút chót tôi đã đổi ý: nếu làm vậy, có thể tôi cũng sẽ bị những \"người bạn mới tiềm năng\" ở Hogwarts ghét bỏ giống như Zenobia. Xét đến công sức mà các bạn cùng nhà của cô bé bỏ ra để giấu những viên đá Gobstone này, họ hẳn phải có hiềm khích rất lớn với Zenobia. Nếu trả đá lại rồi lại gây thêm rắc rối mới, chắc chắn họ sẽ trút cơn giận lên đầu tôi.",
  "Confringo": "Bùa Nổ Súng (Confringo)",
  "Confringo_Desc": "Bắn ra một quả cầu lửa tầm xa gây sát thương khi trúng đích. Kẻ địch bị đòn tấn công hệ lửa đánh trúng sẽ liên tục nhận sát thương trong vài giây, nếu chịu va đập mạnh trong khoảng thời gian này sẽ kích hoạt ngọn lửa bùng nổ.",
  "Confringo_gameplay_desc": "Bắn ra một quả cầu lửa tầm xa gây sát thương khi trúng đích. Kẻ địch bị đòn tấn công hệ lửa đánh trúng sẽ liên tục nhận sát thương trong vài giây, nếu chịu va đập mạnh trong khoảng thời gian này sẽ kích hoạt ngọn lửa bùng nổ.",
  "Control_PerformBottomAncientMagicSpell": "<Body_Text>Thi triển Phép Thuật Cổ Xưa Dưới</>",
  "Control_PerformLeftAncientMagicSpell": "<Body_Text>Thi triển Phép Thuật Cổ Xưa Trái</>",
  "Control_PerformRightAncientMagicSpell": "<Body_Text>Thi triển Phép Thuật Cổ Xưa Phải</>",
  "Control_PerformTopAncientMagicSpell": "<Body_Text>Thi triển Phép Thuật Cổ Xưa Trên</>",
  "Control_Protego": "(Nhấn) <Body_Text>Bùa Khiên Che Chắn (Protego)</>",
  "Control_ProtegoRetaliation": "(Giữ) <Body_Text>Đỡ Đòn & \"Bùa Choáng Váng (Stupefy)\"</>",
  "Control_Revelio": "<Body_Text>Bùa Hiện Hình (Revelio)</>",
  "Control_SpellMenu": "<Body_Text>Menu Bùa Chú</>",
  "Crucio": "Lời Nguyền Tra Tấn (Crucio)",
  "Crucio_desc": "Hiệu ứng sát thương duy trì sẽ khiến hầu hết kẻ địch phải quằn quại trong đau đớn cùng cực. Ngoài ra còn khiến nạn nhân bị nguyền rủa và chịu thêm sát thương.",
  "Crucio_gameplay_desc": "Hiệu ứng sát thương duy trì sẽ khiến hầu hết kẻ địch phải quằn quại trong đau đớn cùng cực. Ngoài ra còn khiến nạn nhân bị nguyền rủa và chịu thêm sát thương.",
  "Depulso": "Bùa Đẩy Lùi (Depulso)",
  "Depulso_desc": "Có thể dùng một lực cực lớn để đẩy lùi các loại đồ vật và kẻ địch. Tuy không trực tiếp gây sát thương, nhưng khi kẻ địch và đồ vật va chạm vào nhau sẽ tạo ra hậu quả mang tính hủy diệt. Ngoài ra, bùa chú này còn có thể dùng để đẩy hoặc xoay chuyển đồ vật tùy ý.",
  "Depulso_gameplay_desc": "Có thể dùng một lực cực lớn để đẩy lùi các loại đồ vật và kẻ địch. Tuy không trực tiếp gây sát thương, nhưng khi kẻ địch và đồ vật va chạm vào nhau sẽ tạo ra hậu quả mang tính hủy diệt. Ngoài ra, bùa chú này còn có thể dùng để đẩy hoặc xoay chuyển đồ vật tùy ý.",
  "Descendo": "Bùa Đập Xuống (Descendo)",
  "Descendo_desc": "Tuy không trực tiếp gây sát thương, nhưng đồ vật và kẻ địch bị đập mạnh xuống mặt đất sẽ chịu lượng sát thương va chạm cực lớn. Cũng chính vì lý do này, kẻ địch đang ở trên không khi rơi xuống sẽ phải chịu sát thương nặng nề hơn.",
  "Descendo_gameplay_desc": "Tuy không trực tiếp gây sát thương, nhưng đồ vật và kẻ địch bị đập mạnh xuống mặt đất sẽ chịu lượng sát thương va chạm cực lớn. Cũng chính vì lý do này, kẻ địch đang ở trên không khi rơi xuống sẽ phải chịu sát thương nặng nề hơn.",
  "Diffindo_gameplay_desc": "Cắt chém đồ vật và kẻ địch từ xa, có thể gây ra lượng sát thương đáng kể.",
  "DT_AvadaKedavra": "Sử dụng \"Lời Nguyền Chết Chóc (Avada Kedavra)\" đánh bại 3 kẻ địch cùng một lúc",
  "DT_DescendoShockwave": "Dùng sóng xung kích của \"Bùa Đập Xuống (Descendo)\" đánh trúng một kẻ địch",
  "DT_DiffindoDugbog": "Cắt toạc một con Cóc Đầm Lầy Dugbog đang lơ lửng trên không",
  "DT_GoblinCasterBombarda": "Sử dụng \"Bùa Nổ Công Phá (Bombarda)\" đánh bay một Vọng Lâu Binh Thuộc Hạ Ranrok đang chuẩn bị niệm chú",
  "DT_InAirDescendo": "Sử dụng \"Bùa Đập Xuống (Descendo)\" đập mạnh kẻ địch đang lơ lửng",
  "DT_InferiusBombarda": "Sử dụng \"Bùa Nổ Công Phá (Bombarda)\" ngăn chặn cú nhảy bổ đầu của một Âm Binh (Inferi) đang bốc cháy",
  "DT_LaunchTwoDepulso": "Sử dụng \"Bùa Đẩy Lùi (Depulso)\" đánh bay 2 kẻ địch cùng một lúc",
  "DT_Protego": "Thi triển thành công Bùa Khiên Che Chắn (Protego)",
  "DT_SpellbinderStupefy": "Dùng Bùa Choáng Váng (Stupefy) đánh trúng một Du Hiệp Rắn Tro (Ashwinder Ranger)",
  "DT_Stupefy": "Thi triển Bùa Choáng Váng (Stupefy) lên một kẻ địch",
  "DT_StupefyShield": "Sử dụng \"Bùa Choáng Váng (Stupefy)\" phá vỡ bùa khiên chắn",
  "DT_TransformBombarda": "Kích nổ một thùng gỗ đỏ biến hình từ kẻ địch",
  "DT_TwoEnemyPullAccio": "Đồng thời triệu tập và kéo lê 2 kẻ địch",
  "DT_WolfDepulso": "Sử dụng \"Bùa Đẩy Lùi (Depulso)\" bẻ gãy đòn lao tới của một con Chó Sói Hung Dữ",
  "EdurusPotion": "Thuốc Cường Hóa Edurus",
  "EdurusPotion_desc": "Khiến lớp da của người uống phủ một lớp cứng như bàn thạch, qua đó tăng cường khả năng phòng thủ.",
  "EVL_01_DepthofStudy_QuestComplete_Journal_CrucioSeb": "Tôi đã thuyết phục Ominis giúp tôi và Sebastian tiến vào Thư Phòng Bí Mật của Slytherin. Chúng tôi phải quanh co bước qua những dãy hành lang đầy điềm gở và vượt qua nhiều chướng ngại vật. Cuối cùng, chúng tôi đến trước một cánh cửa chỉ mở ra khi một người thi triển Lời Nguyền Tra Tấn (Crucio) lên một người khác. Giờ đây chúng tôi đã hiểu vì sao Noctua Gaunt lại thất bại: bà đã dấn thân vào hành trình này một mình. Ominis kiên quyết từ chối niệm chú. Dẫu vậy, Sebastian đã dạy tôi lời nguyền và đồng ý để tôi thi triển lên cậu ấy. Tôi không chắc cảm xúc của mình thế nào khi thi triển Nghệ Thuật Hắc Ám này. Cuối cùng chúng tôi đã vào được thư phòng, tại đó tôi tìm thấy một cuốn sách thần chú cổ của Salazar Slytherin. Tôi đã đưa nó cho Sebastian, hy vọng điều này sẽ mang lại cho cậu ấy vài lời giải đáp. Chỉ có thời gian mới chứng minh được tất cả.",
  "EVL_01_DepthofStudy_QuestComplete_Journal_CrucioYou": "Tôi đã thuyết phục Ominis giúp tôi và Sebastian tiến vào Thư Phòng Bí Mật của Slytherin. Chúng tôi phải quanh co bước qua những dãy hành lang đầy điềm gở và vượt qua nhiều chướng ngại vật. Cuối cùng, chúng tôi đến trước một cánh cửa chỉ mở ra khi một người thi triển Lời Nguyền Tra Tấn (Crucio) lên một người khác. Giờ đây chúng tôi đã hiểu vì sao Noctua Gaunt lại thất bại: bà đã dấn thân vào hành trình này một mình. Ominis kiên quyết từ chối niệm chú. Nhưng tôi đã đồng ý để Sebastian thi triển Lời Nguyền Tra Tấn (Crucio) lên người mình. Tôi hy vọng bản thân sẽ không bao giờ phải nếm trải nỗi đau đớn cùng cực như thế này thêm lần nào nữa. Cuối cùng chúng tôi đã vào được thư phòng, tại đó tôi tìm thấy một cuốn sách thần chú cổ của Salazar Slytherin. Tôi đã đưa nó cho Sebastian, hy vọng điều này sẽ mang lại cho cậu ấy vài lời giải đáp. Chỉ có thời gian mới chứng minh được tất cả.",
  "Expelliarmus": "Bùa Giải Giới (Expelliarmus)",
  "Expelliarmus_desc": "Có thể tước đoạt đũa phép và vũ khí mà hầu hết kẻ địch đang sử dụng. Cho dù đối phương không mang bất kỳ loại vũ khí nào, bùa chú này vẫn gây sát thương lên tất cả kẻ địch.",
  "Expelliarmus_gameplay_desc": "Có thể tước đoạt đũa phép và vũ khí mà hầu hết kẻ địch đang sử dụng. Cho dù đối phương không mang bất kỳ loại vũ khí nào, bùa chú này vẫn gây sát thương lên tất cả kẻ địch.",
  "Expelliarmus_Vul": "Yếu thế trước \"Bùa Giải Giới (Expelliarmus)\"",
  "Expelliarmus_Vul_desc": "Sử dụng \"Bùa Giải Giới (Expelliarmus)\" có thể dễ dàng tước vũ khí của những Yêu Tinh mang theo vật phẩm.",
  "FGC_Brew_AMFillPotion": "Pha chế {0} Thuốc Tập Trung",
  "FGC_Brew_AutoDamagePotion": "Pha chế {0} Thuốc Sấm Sét Thunderbrew",
  "FGC_Brew_HealingPotion1": "Pha chế {0}",
  "FGC_Brew_HealingPotion2": "Pha chế {0} Thuốc Tàng Hình",
  "FGC_Brew_HealingPotion3": "Pha chế {0}",
  "FGC_Brew_NeathYourNosePotion": "Pha chế {0} độc dược",
  "FGC_Brew_Potions": "Pha chế độc dược",
  "FGC_Brew_TalentPointPotion": "Pha chế {0} độc dược",
  "FGC_Brew_TalentResetPotion": "Pha chế {0} độc dược",
  "FGC_Collect_JPippinsPotions": "Khám phá tất cả các trang cẩm nang đã tìm thấy trong khu vực này",
  "FGC_Conjure_MediumPotionStation": "Biến hình vật thể này một lần",
  "FGC_Conjure_SmallPotionStation": "Biến hình vật thể này một lần",
  "FGC_Conjure_TShapePotionStation": "Biến hình vật thể này một lần",
  "FGC_Craft_Gear_Dark_SpellDamage_1": "Chế tạo vật phẩm này một lần",
  "FGC_Craft_Gear_Dark_SpellDamage_2": "Chế tạo vật phẩm này một lần",
  "FGC_Craft_Gear_Dark_SpellDamage_3": "Chế tạo vật phẩm này một lần",
  "FGC_Craft_Gear_Sneak_RevelioDamage_1": "Chế tạo vật phẩm này một lần",
  "FGC_Craft_Gear_Sneak_RevelioDamage_2": "Chế tạo vật phẩm này một lần",
  "FGC_Craft_Gear_Sneak_RevelioDamage_3": "Chế tạo vật phẩm này một lần",
  "FGC_Craft_Gear_Sneak_StupefyDamage_1": "Chế tạo vật phẩm này một lần",
  "FGC_Craft_Gear_Sneak_StupefyDamage_2": "Chế tạo vật phẩm này một lần",
  "FGC_Craft_Gear_Sneak_StupefyDamage_3": "Chế tạo vật phẩm này một lần",
  "FIG_01_MissionAvailable_LearnIncendio_Task1": "Phải học được Bùa Lửa (Incendio) mới có thể tiếp tục câu chuyện này",
  "Flipendo": "Bùa Lộn Nhào (Flipendo)",
  "Flipendo_desc": "Có thể khiến đồ vật và kẻ địch lộn nhào lên xuống. Nhờ thời gian hồi chiêu ngắn, bùa chú này rất thích hợp để thực hiện các đòn tung hứng đầy sáng tạo. Khả năng lập tức lật ngược vật thể cực kỳ thích hợp để giải đố hoặc khai thác điểm yếu của một số kẻ địch nhất định."
}

if __name__ == '__main__':
    print(f"Loaded {len(translations_0_100)} keys.")
