"""Translate a reviewed first batch of Selene dialogue."""
from pathlib import Path
import sys

ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(ROOT / "tools"))
from hades2_sjson_helper import apply_translation_to_sjson  # noqa: E402

SRC = ROOT / "working/0100A00019DE0000_Hades2/raw_text/en"
TR = ROOT / "translations/0100A00019DE0000_Hades2/Game/Text/en"

translations = {
    "Melinoe_1881": "Mong ánh sáng của chị chẳng bao giờ tắt.",
    "Melinoe_1711": "Chị em mình cùng tỏa sáng nhé.",
    "Melinoe_1882": "Ánh trăng dẫn lối— {#Emph}ư... {#Prev}Xin lỗi. Thành thói quen rồi.",
    "Selene_0233": "Sẽ không bao giờ.", "Selene_0234": "{#Emph}Ừm.", "Selene_0235": "Mãi mãi.",
    "Selene_0236": "Chào em.", "Selene_0237": "Bóng đêm soi đường cho em.", "Selene_0238": "Đến muôn đời.",
    "Selene_0136": "Ta rất cảm kích.", "Selene_0486": "Chronos phải chết.", "Selene_0487": "Hãy cứ tỏa sáng.",
    "Selene_0488": "Vì Chị Em Ánh Bạc.", "Selene_0489": "Ta cũng xin ban phúc cho em.",
    "Melinoe_0024": "{#Emph}Hỡi Mặt Trăng, hãy xuống đây. Ban cho con ánh sáng của Người!",
    "MelinoeField_1936": "{#Emph}Hỡi Mặt Trăng, hãy xuống đây. Ban cho con ánh sáng của Người!",
    "MelinoeField_1935": "{#Emph}Con khẩn cầu Mặt Trăng, xin Người giáng xuống!",
    "MelinoeField_1937": "{#Emph}Hỡi Mặt Trăng, đêm nay ta cùng tỏa sáng!",
    "MelinoeField_1938": "{#Emph}Đêm nay, xin Người lại soi sáng cho ta!",
    "Melinoe_0026": "Ánh trăng...", "Melinoe_0027": "Chị Selene...", "Melinoe_0189": "Giọt Trăng...",
    "Selene_0116": "Chào buổi tối.", "Selene_0117": "Mừng em đến.", "Selene_0118": "Ta đã trở lại.",
    "Selene_0119": "Chị em ta lại đoàn tụ.", "Selene_0131": "Ta có thứ này cho em.", "Selene_0132": "Cái này tặng em.",
    "Selene_0149": "Cái này tặng em.", "Selene_0133": "Hãy đánh thức sức mạnh thật sự của em.",
    "MelinoeField_3529": "{#Emph}Ta thấy trong vòng tay dang rộng của chị là niềm hoan lạc và sự hủy diệt...",
    "Selene_0438": "Một vị thần có thể xuất hiện trên Đường em đi...", "Selene_0439": "Một nữ thần có thể xuất hiện trên Đường em đi...",
    "Selene_0123": "Hãy nhìn xem.", "Selene_0130": "Xin hãy chọn đi.", "Selene_0178": "Nhìn về phía trước.",
    "Selene_0179": "Em có quyền lựa chọn.", "Selene_0180": "Cái nào hợp với em?", "Selene_0181": "Giờ thì...",
    "Selene_0182": "Em chọn gì?", "Selene_0183": "Hãy nhìn ánh sáng của ta.",
    "Selene_0158": "Chào buổi tối, vì sao nhỏ. Từ nay, vận mệnh đôi ta đã đan vào nhau; ta không thể chỉ đứng nhìn nữa. Dù phải đối mặt với hiểm họa nào, ta thề sẽ luôn soi đường cho em.",
    "Selene_0053": "Ta tiếc vì mỗi lần gặp nhau đều vội vã, chẳng thể chuyện trò lâu. Ta phải hiện diện trên cao để mọi người nhìn thấy. Mối liên kết của chúng ta phải được giấu kín như Ngã ba Địa Giới. Ta và em phải bước đi trong bóng tối.",
    "Selene_0062": "Sư phụ của em và ta đã sát cánh từ khi Mẹ Nyx giao cho chúng ta trông coi cõi giới của mình, còn Người canh giữ Âm phủ. Hai Titan nữ, gắn kết bởi màn đêm.",
    "Selene_0063": "Vì sao nhỏ, em tiến bộ cả về sức mạnh lẫn hiểu biết nhanh thật. Hẳn Sư phụ tự hào khi cuối cùng em đã vượt qua bà ấy. Nhưng chúng ta đều biết gánh nặng em đang mang.",
    "Selene_0064": "Gần đây, Sư phụ hỏi ta liệu những chuyến rong ruổi trên bầu trời có trở nên nhàm chán không. Ta bật cười trước câu đùa ấy. Đêm nào cũng khác với mọi đêm ta từng biết.",
    "Selene_0215": "Ta đã là Con Mắt Đêm từ lâu, âm thầm dõi theo em lớn lên và rèn luyện; biết rằng rồi sẽ có một đêm như thế này, khi Chị Em Ánh Bạc chúng ta đứng lên chiến đấu. Đi thôi chứ?",
    "Selene_0221": "Mọi sinh linh đều chật vật tìm cách thấu hiểu nhau. Nyx dạy ta cách bày tỏ lòng mình, cũng như Sư phụ dạy em. Lời nói bắt nguồn từ quá khứ; còn những mối liên kết thì mong manh.",
    "Selene_0056": "Em không nhớ Nyx sao? Chính màn đêm đã tìm thấy ta, khi ta bị bỏ rơi và chẳng ai cần đến, rồi nuôi nấng ta từ thuở nhỏ. Khi Titan Chronos chiếm lấy Nhà Hades, Người vẫn ở đó. Ta vẫn nhớ Người.",
    "Selene_0057": "Những đêm tối như thế này, ta chỉ nghĩ đến Nyx. Người cai quản Âm phủ trong Nhà của cha em và chăm lo cho biết bao người, trong đó có ta. Người biết ta luôn hướng về bầu trời. {#Emph}Cứ đi đi{#Prev}, Người bảo thế. {#Emph}Và nhớ trông nom nơi đó giúp ta.",
    "Selene_0058": "Với vẻ uy nghiêm, Mẹ Nyx gọi ta là Con Mắt Đêm, vì ta nhìn thấy cả những điều Người không thể thấy. Danh xưng ấy vẫn tiếp thêm sức mạnh cho ta, cũng như ta thúc ngựa tiến lên. Chị Em Ánh Bạc chúng ta sẽ báo thù cho Người, vì sao nhỏ.",
    "Selene_0058_B": "Với vẻ uy nghiêm, Mẹ Nyx gọi ta là Con Mắt Đêm, vì ta nhìn thấy cả những điều Người không thể thấy. Danh xưng ấy vẫn tiếp thêm sức mạnh cho ta, cũng như ta thúc ngựa tiến lên.",
    "Selene_0368": "Cuối cùng Nyx cũng trở về bên chúng ta. Có lẽ rồi em sẽ hiểu Người như ta. Dù ảnh hưởng của Người chưa từng phai nhạt, ta vẫn nhớ khôn nguôi trí tuệ và sự hiện diện của Người. Tất cả là nhờ em đã đưa chúng ta đoàn tụ.",
    "Selene_0156": "Titan Chronos chính là Thời Gian. Bởi bản chất ấy, chúng ta chẳng bao giờ có thể chuẩn bị đủ để đối phó hắn. Hắn muốn hủy diệt Olympus, nhưng cụ thể bằng cách nào thì đến giờ ta vẫn chưa rõ.",
    "Selene_0175": "Em đã xuống Vực Tartarus, hẳn đã thấy Chronos biến nơi linh thiêng ấy thành ra sao. Ta biết cuộc đối đầu không diễn ra như em mong muốn, nhưng đêm nay là một đêm mới. Em cũng đã sẵn sàng hơn trước nhiều.",
    "Selene_0366": "Ta từng căm ghét Titan Chronos vì mọi chuyện hắn gây ra, vì tất cả những gì hắn bắt em phải chịu đựng. Vậy mà giờ chính hắn lại tìm cách khắc phục tổn hại mình gây nên? Em có sức mạnh lớn đến mức khiến hắn thay đổi được như vậy.",
    "Selene_0322": "Tên Titan ngu xuẩn ấy đã đánh thức Typhon, quái vật khủng khiếp nhất từng tồn tại. Ta vẫn mang sẹo từ lần đầu giao chiến với hắn thuở xa xưa. Khi đó chúng ta đã đánh bại được hắn; lần này cũng sẽ làm được.",
    "Selene_0341": "Typhon từng nếm mùi thất bại. Hắn nay đã to lớn, mạnh mẽ và hung tợn hơn, nhưng ta vẫn tin chắc em sẽ chiến thắng, vì sao nhỏ.",
    "Selene_0342": "Ngay cả quái vật như Typhon cũng không thể chống lại em, vì sao nhỏ. Sư phụ và ta luôn biết em có tiềm năng. Giờ ta đã tận mắt thấy em phát huy nó, còn vượt xa mong đợi.",
    "Selene_0343": "Đến giờ hẳn Typhon vẫn nhớ vị đắng của thất bại, vậy mà hắn chưa chịu dừng lại. Chúng ta không còn lựa chọn nào khác ngoài tìm cách tiêu diệt hắn, vì sao nhỏ.",
    "Selene_0172": "Qua lời Sư phụ, ta biết em đã thấy viễn cảnh Chronos tìm ra và bắt giữ Tam Nữ Thần Số Mệnh. Hẳn đó là mắt xích quan trọng trong kế hoạch của hắn... nhưng chuyện ấy {#Emph}không {#Prev}làm thay đổi kế hoạch của chúng ta. Chị Em Ánh Bạc không bao giờ nhường quyền kiểm soát.",
    "Selene_0077": "Ta hít thở, đổ máu, nghỉ ngơi rồi lại bắt đầu. Chính chúng ta tạo nên vòng tuần hoàn này, hay chỉ là một phần trong đó? Đôi khi, lúc rong ruổi trên trời, ta vẫn tự hỏi như vậy.",
    "Selene_0078": "Bắt đầu một vòng tuần hoàn mới thôi, vì sao nhỏ. Mỗi vòng đều có điều bất ngờ, nhưng hẳn em cũng thấy niềm vui ẩn trong quy luật lớn hơn ấy chứ?",
    "Selene_0080": "Bao người phàm sợ màn đêm buông xuống, còn chúng ta thì sao? Bóng tối chỉ là nơi ta hành sự. Nào, vì sao nhỏ, hãy cùng nhau tỏa sáng giữa đêm đen.",
    "Selene_0081": "Ta thường đơn độc rong ruổi trên bầu trời. Đúng là ta còn có lũ ngựa để trò chuyện, nhưng vẫn chẳng thể sánh với những lúc được nói chuyện cùng em.",
    "Selene_0086": "Lâu lắm rồi ta mới gặp lại em. Lũ ngựa đã mệt nhoài sau những chuyến rong ruổi. Không có chúng thì ta biết làm sao? Có lẽ sẽ được ở gần em hơn, nhưng... mỗi người đều có nơi thuộc về mình.",
    "Selene_0102": "Từ lần cuối gặp nhau đến giờ, em đã đi được một chặng đường dài... nhất là với người chẳng có ngựa kéo xe. Ta khen em đấy; mong mọi chuyến đi sau này của em cũng đều thành công.",
    "Selene_0174": "{#Emph}Chronos phải chết. {#Prev}Ta cảm nhận được em đang tiến gần hơn đến hiện thực mà chúng ta hằng mong đợi. Mong em rút cạn chút ánh sáng cuối cùng còn sót lại trong hắn.",
    "Selene_0319": "Em đã vượt đường xa lên mặt đất, băng qua hành trình gian nan đến ngọn núi của các vị thần, rồi còn sống sót sau cuộc chạm trán với quái vật trỗi dậy từ quá khứ... Em còn phi thường hơn ta tưởng, vì sao nhỏ.",
    "Selene_0087": "Giá mà em được ngắm thế gian từ nơi ta rong ruổi. Có lẽ một đêm nào đó nhé? Ta biết dưới kia có biết bao điều xấu xí, nhưng nhìn từ xa thì chúng cũng khuất đi phần nào.",
    "Selene_0225": "Cảm giác kỳ lạ này... ta nhớ ra rồi: quyền năng của Chaos đang tác động lên quanh ta, dù chỉ âm thầm. Ta tin chuyện này là do em gây ra, chứ chẳng phải ngẫu nhiên.",
    "Selene_0218": "Đêm nay có điều gì đó không ổn... như thể ta không tìm đến em theo ý mình. Hòn Đá Đen Tuyền... ta hiểu rồi. Nó đè nặng lên mọi thứ chúng ta cảm nhận.",
    "Selene_0476": "Đêm nay, ảnh hưởng của Chaos mạnh hơn thường lệ; hành trình đến đích có thể rẽ sang những hướng bất ngờ. Mong ánh sáng của ta vẫn soi đường cho em.",
    "Selene_0096": "Sống cả đời giữa làn sương mù Erebus hẳn khiến em nghĩ thế giới chỉ có bấy nhiêu. Nhưng thế gian rộng lớn hơn nơi đó nhiều. Trước khi hoàn thành nhiệm vụ, em sẽ còn được thấy biết bao điều.",
    "Selene_0164": "Em vốn không thuộc về nơi này, vì sao nhỏ. Dòng máu bị nguyền rủa sẽ cản bước em. Nhưng chính Nyx hẳn hiểu nỗi gian nan ấy; Người cũng từng chống lại lời tiên tri của các Số Mệnh...",
    "Selene_0166": "Ta cảm nhận em đang đến gần ánh sáng của ta hơn. Em đã áp chế lời nguyền do Số Mệnh giáng xuống, thứ trói buộc em với cõi giới của mình. Ta không ngờ chuyện đó làm được... nhưng em thường khiến ta bất ngờ, vì sao nhỏ.",
    "Selene_0165": "Em đã phá kết giới ở cổng dẫn từ Ngã ba Địa Giới lên mặt đất... vượt qua bức màn ngăn cách thế giới em biết với cõi giới ta vẫn ngắm nhìn mỗi đêm. Có lẽ kế hoạch của chúng ta cần đến bước ngoặt này...",
    "Selene_0097": "Chào mừng em đến với mặt đất, vì sao nhỏ. Ta biết em sẽ tự tìm được đường đến đây. Nếu thấy lạc lối, cứ nhìn lên tìm ta. Ta sẽ luôn dõi theo em.",
    "Selene_0167": "Đáng lẽ ta phải chính thức chào mừng em đến với mặt đất, vì sao nhỏ. Một phần trong ta đã biết em sẽ tìm được đường đến đây. Nếu thấy lạc lối, hãy nhìn lên trời.",
    "Selene_0098": "Thành phố Ephyra đã trải qua quá nhiều biến cố. Giá mà em được thấy nơi này khi người dân còn thờ phụng cha mẹ em. Chúng ta sẽ báo thù cho tất cả bọn họ.",
    "Selene_0220": "Ở nơi này, ánh sáng của ta cũng chẳng mạnh hơn dưới kia, vì dù em ở đâu ta cũng chỉ có thể ban cho em chừng ấy. Sứ mệnh của ta là luôn bền bỉ, không đổi thay.",
    "Selene_0219": "Em mang Lửa Ygnium dưới hình hài của Eos. Cô em gái ấy còn non dạ nên chẳng hay biết gì. Mong em ấy cứ vui với những chuyến dạo chơi buổi sớm đến tận mai sau.",
    "Selene_0337": "Với Mạo Diện Áo Choàng Đen, em hẳn đã biết cách dùng Nguyền Sao Sa. Đó là sức mạnh tiềm ẩn của ta; mỗi đêm, em có thể định hình ánh sáng ấy qua Đường Sao.",
    "Selene_0338": "Áo Choàng Đen của ta rực sáng biết bao! Ta thấy em đã đưa sức mạnh của nó lên đỉnh cao. Nó có thể gieo rắc sự hủy diệt khủng khiếp đến nỗi chính ta cũng phải e dè.",
    "Selene_0484": "Em mang Mạo Diện của ta, Lá bài Arcana của ta, lại còn có cả Tia Trăng sao? {#Emph}Ôi{#Prev}, vì sao nhỏ, em cứ là chính mình, chẳng cần trở thành bản sao của ta. Dù vậy, có lẽ lũ ngựa của ta sẽ thích có thêm người cưỡi.",
    "Selene_0155": "Tia Trăng của ta nhiều như sao trời, còn em chỉ có một. Nhưng ta đã đặc biệt chọn tia ấy cho em, để mối gắn kết giữa chúng ta luôn bền chặt.",
    "Selene_0331": "Chừng nào em còn giữ Tia Trăng của ta, ta sẽ nhanh chóng tìm được em; rồi màn đêm sẽ thuộc về chúng ta. Giờ hãy chọn cách em sẽ giành chiến thắng.",
    "Selene_0332": "Em mang theo Tia Trăng duy nhất ta tặng, làm dấu ấn cho mối gắn kết và sức mạnh chung của chúng ta. Chẳng bao lâu nữa em sẽ tỏa sáng như ta, khiến kẻ địch không còn chỗ ẩn nấp.",
    "Selene_0340": "Tia Trăng của em đã sáng rực hơn nhiều trong tay em. Nó sẽ soi đường cho em mãi mãi, sức mạnh cũng đã đạt đỉnh. Cứ cần ta là ta sẽ đến.",
    "Selene_0226": "Ta thường thấy em cầm cặp Song Đao sáng loáng. Ta đã biết ngày nào đó chúng sẽ thức tỉnh và chọn em làm chủ. Mong lưỡi đao nhanh nhẹn ấy áp đảo kẻ thù.",
    "Selene_0227": "Em đang dùng Rìu Nguyệt, lưỡi rìu rộng ánh lên sắc sáng của ta. Hẳn em nghe được khúc ca nó cất lên. Sức mạnh của nó hòa cùng sức mạnh của em.",
    "Selene_0228": "Lửa Âm rất hợp với em... trông chúng chẳng khác nào đôi đuốc của Sư phụ, dù đã bao năm tháng. Dưới hình hài nào, có một ánh sáng dẫn đường bên cạnh cũng thật an lòng.",
    "Selene_0229": "Giờ em đã có Đầu Lâu Bạc Revaal... lời nhắc nhở muôn đời rằng Cái Chết và Nỗi Sợ nên sát cánh trong cuộc chiến của chúng ta. Kẻ nào chạm phải ánh nhìn của nàng thì khốn thay.",
    "Selene_0318": "Áo Choàng Đen... tấm màn của Đêm, cũng là tuyến phòng thủ cuối cùng, giờ đã thuộc về em. Hãy dùng nó thật cẩn trọng... nếu không, sức hủy diệt của nó có thể che khuất cả Mặt Trời.",
    "Selene_0075": "Mỗi lần em gọi ta, ta lại thúc ngựa xuống gần mặt đất hết mức chúng dám. Có lẽ giờ chúng bạo dạn hơn rồi. Hãy dùng thật tốt sức mạnh ta khơi dậy trong em.",
    "Selene_0110": "Ta đã tìm thấy em, dù ánh sáng của ta chỉ còn le lói ở nơi sâu thẳm này. Em đang lần theo con đường bí mật nối giữa cõi của Poseidon và cõi của cha em. Những thứ ẩn náu ở đây chẳng ưa phe nào cả.",
    "Selene_0171": "Bình thường ánh sáng của ta chẳng thể xuyên qua vùng u ám này, nhưng vì em, vì sao nhỏ, ta sẽ chẳng ngại soi thấu cả trời lẫn đất. Cùng nhau, ta và em sẽ giành chiến thắng.",
    "Selene_0170": "Từ chỗ em nhìn, vùng nước kia hẳn như kéo dài vô tận. Nhưng chúng {#Emph}có {#Prev}điểm cuối, và em có cách băng qua thật nhanh. Ta sẽ dõi theo con thuyền, giúp em đi mau hơn.",
    "Selene_0100": "Ở trên trời, ta chẳng phải bận tâm đến chuyện trần thế, chẳng hạn như phải sống chung với nữ thần báo thù. Nemesis chưa bao giờ xem ta như chị em. Cô ta chỉ thừa hưởng sức mạnh từ mẹ mình.",
    "Selene_0460": "Em đã làm hòa với Nemesis, thậm chí còn thân thiết hơn. Có lẽ sâu bên trong, cô ta không giống với vẻ ngoài bấy lâu. Nếu em cho rằng cô ta xứng đáng, với ta thế là đủ, vì sao nhỏ.",
    "Selene_0458": "Em ngày càng trò chuyện nhiều với Moros, con trai Nyx. Ta không thân với cậu ấy. Ta sẽ tin vào cảm nhận của em về cậu ấy; trực giác của ta lúc này chẳng cho biết điều gì.",
    "Selene_0101": "Ta vẫn lo cho người con trai Nyx đang ngủ mãi ở Ngã ba Địa Giới. Cả Sư phụ lẫn ta đều chưa thể đánh thức cậu ấy. Nhưng bệnh nào rồi cũng có thuốc chữa...",
    "Selene_0351": "Từ lâu, nữ phù thủy Circe đã biết ta không chỉ rong ruổi trên trời. Nàng thực hiện phép thuật theo từng tuần trăng; em có thể tin vào sức mạnh nàng ban cho.",
    "Selene_0459": "Thật lạ khi thấy đôi cánh Icarus lướt giữa trời. Ta nhớ em đã khích lệ cậu ấy vượt qua nỗi sợ để bay lên. Ta sẽ dõi theo, đảm bảo cậu ấy không rơi xuống.",
    "Selene_0113": "Ta nghe nói em đã gặp Heracles. Hãy cẩn thận với kẻ đã gây thù chuốc oán với bao người để phụng sự các vị thần. Hắn từng làm điều sai trái với ta, vậy mà vẫn ngang nhiên bước đi dưới ánh sáng của ta...",
    "Selene_0099": "Cyclops Polyphemus mà em từng đối đầu đã trốn trong một hang động sâu đến mức ngay cả ánh bạc của {#Emph}ta {#Prev}cũng không soi tới. Giờ hắn theo phe Chronos. Quá nhiều kẻ đang chống lại các vị thần...",
    "Selene_0176": "Eris Cánh Đen đã thành chướng ngại; đôi khi ả bay cắt ngang đường ta, làm lũ ngựa giật mình. Ta là Con Mắt Đêm mà vẫn chẳng thấy ở ả điều gì đáng quý...",
    "Selene_0464": "Ta từng nghi ngờ mối giao hảo giữa em và Eris, nhưng giờ hiểu rằng em nhìn thấy điều gì đó ở ả mà ngay cả ta cũng không nhận ra. Em thật kiên nhẫn khi chấp nhận một kẻ như vậy.",
    "Selene_0321": "Thuở xưa, khi các thần giao chiến với Chronos, các Titan còn chẳng đoàn kết với nhau. Prometheus... khi ấy hắn đứng về phía Zeus, nhưng giờ thì sao? Mưu đồ của hắn trái ngược với chúng ta. Lại thêm một kẻ cùng giống loài trở thành kẻ thù của ta...",
    "Selene_0463": "Titan Tiên Tri đang âm mưu cùng Heracles. Có lẽ họ đoàn kết vì yêu thương người phàm, hoặc vì có họ hàng với các vị thần. Ta cứ tưởng họ sẽ là đối thủ của nhau, chứ không phải của em.",
    "Selene_0347": "Artemis đã cho Olympus biết những điều họ cần về em, rồi giờ đang đi khắp khu rừng của em. Mong sau khi sóng gió qua đi, Chị Em Ánh Bạc chúng ta sẽ lại được vui vầy.",
    "Selene_0483": "Ta cảm nhận Lá bài Arcana mang dấu ấn của mình đang ảnh hưởng đến em. Cứ để phép thuật tuôn chảy, mong Nguyền nào em thi triển cũng đưa em đến vinh quang.",
    "Selene_0168": "Em đã thấy Đường Sao và cảm nhận được mối liên hệ giữa sức mạnh của ta với em. Dù đôi khi Đường Sao đôi ngả, chúng vẫn thường dẫn ta và em về cùng một điểm.",
    "Selene_0079": "Nhớ nhé, vì sao nhỏ: phép thuật được ánh sáng của ta khơi dậy cần em chủ động tập trung; thiếu ý chí của em, nó chẳng có tác dụng. Khi cần, đừng ngần ngại sử dụng.",
    "Selene_0055": "Món quà phép thuật này không đến từ ta, mà từ bên trong em. Tuy vậy, ánh sáng của ta quả thực đánh thức tiềm năng sẵn có. Đó là bí mật mà ngay cả người phàm trên mặt đất cũng biết.",
    "Selene_0216": "Những chuyến rong ruổi bất tận trên trời cho ta dư thời gian để thấu hiểu ánh sáng của mình. Giờ đây, ta có một Nguyền phù hợp với mọi dịp, mọi tuần trăng. Em cũng sẽ có chúng.",
    "Selene_0231": "Em đã quá quen với các Nguyền của ta rồi, vì sao nhỏ. Chắc hẳn giờ em đã có một hai món mình thích nhất. Có lẽ em sẽ còn khám phá thêm nhiều khía cạnh mới của chúng.",
    "Selene_0169": "Cuối cùng em cũng nhìn thấy Lời Thề Vô Hình... Đêm nay thật khác thường, chưa đêm nào trong suốt bao thời đại sánh được. Cứ như Bóng Tối đang thấm vào {#Emph}mọi thứ...",
    "Selene_0359": "Đêm nay em có thể thực hiện Di huấn Màn Đêm, dù nỗi Sợ ngày càng lan rộng theo từng Lời Thề sẽ khiến thử thách khó vượt qua hơn. Ta sẽ chứng kiến tất cả.",
    "Selene_0076": "Nếu sức mạnh của Olympus đủ dùng, các vị thần đã giải quyết xong tình cảnh này. Thời Gian đang chống lại chúng ta, nhưng chính lúc này là thời khắc Chị Em Ánh Bạc đã chuẩn bị từ lâu.",
    "Selene_0480": "Vì vinh quang của Chị Em Ánh Bạc, vì sao nhỏ.",
    "Selene_0004": "Mong ánh sáng của ta soi đường em và làm kẻ thù lóa mắt.",
    "Selene_0005": "Giờ đây, ta chỉ tỏa sáng vì em, vì sao nhỏ.",
    "Selene_0006": "Chị em mình sẽ mãi cùng nhau tỏa sáng, vì sao nhỏ.",
    "Selene_0007": "Cho đến ngày Chị Em Ánh Bạc có thể buông vũ khí.",
    "Selene_0008": "Ta nghe tiếng em gọi và mang ánh sáng đến đây.",
    "Selene_0009": "Ta là Con Mắt Đêm, và sẽ luôn dõi theo em.",
    "Selene_0010": "Ta đã giáng xuống, và ánh sáng của ta lại thuộc về em.",
    "Selene_0011": "Ánh sáng của ta đang mạnh nhất; em muốn dùng thế nào cũng được.",
    "Selene_0012": "Dù ánh sáng lúc này đang nhạt dần, ta vẫn còn đủ để chia sẻ với em.",
    "Selene_0013": "Lũ ngựa của ta cũng vui lòng được nghỉ ngơi đôi chút.",
    "Selene_0014": "Ta thấy rõ sức mạnh tiềm ẩn trong em...",
    "Selene_0015": "Đêm quang đãng, ngựa ta sung sức; sức mạnh đôi ta vô song.",
    "Selene_0016": "Đêm tối rồi; ngựa ta cần nghỉ. Nhưng ta vẫn có thể chia cho em chút sức mạnh còn lại.",
    "Selene_0017": "Ánh sáng của ta đang nhạt dần, nhưng ta vẫn luôn để dành một phần cho em.",
    "Selene_0018": "Đã là Chị Em Ánh Bạc, sức mạnh của ta cũng là của em.",
    "Selene_0019": "Hãy nhận lấy ánh sáng của ta, rồi tỏa rạng như chính ta.",
    "Selene_0039": "Ngựa ta đang sung sức, sức mạnh của ta đạt đỉnh; chẳng mấy chốc sức mạnh của em cũng vậy.",
    "Selene_0020": "Gian nan chỉ là một chặng đường; ta và em sẽ vượt qua như vượt qua bầu trời.",
    "Selene_0021": "Bầu trời đêm mới mở ra khởi đầu mới, phải không em?",
    "Selene_0022": "Em đã gọi ta, và giờ ánh sáng rực rỡ của ta thuộc về em.",
    "Selene_0023": "Màn đêm bao phủ đôi ta; hãy cùng thắp sáng bóng tối này.",
    "Selene_0024": "Ánh bạc của ta lại thuộc về em, muốn dùng thế nào cũng được.",
    "Selene_0025": "Mong mọi dự định của em được giấu kín trong ánh sáng của ta.",
    "Selene_0026": "Ta và em lại bí mật gặp nhau giữa đêm khuya.",
    "Selene_0027": "Ôi, ánh bạc của em rực rỡ biết bao khi được ánh sáng của ta soi tỏ.",
    "Selene_0028": "Vòng tuần hoàn của chúng ta chẳng bao giờ kết thúc, phải không, em gái?",
    "Selene_0029": "Mỗi khi em có dịp gọi ta đến, ta đều vui lòng.",
    "Selene_0031": "Kẻ thù ẩn mình trong bóng tối, nhưng không thể trốn khỏi chúng ta.",
    "Selene_0032": "Có vẻ em cần sức mạnh của ta hơn cả ta rồi, vì sao nhỏ.",
    "Selene_0033": "Ta thấy em rồi, vì sao nhỏ. Bất cứ khi nào cần, ta sẽ luôn ở bên em.",
    "Selene_0034": "Ta chẳng cần ánh sáng mới biết Sư phụ đã huấn luyện em chu đáo.",
    "Selene_0035": "Kiên nhẫn và bền chí nhé, em gái. Đây, nhận lấy.",
    "Selene_0036": "Sức mạnh của ta đang ở đỉnh cao, khiến ta suýt thấy thương hại kẻ thù...",
    "Selene_0037": "Bắt đầu chặng hợp tác mới thôi, vì sao nhỏ.",
    "Selene_0038": "Đêm lại tối dần, nhưng em đã có chút ánh sáng ta ban cho.",
    "Selene_0040": "Ngay giữa Vực Erebus tối tăm nhất, ta vẫn nghe và thấy em, vì sao nhỏ.",
    "Selene_0041": "Ánh sáng của ta có thể xuyên qua mặt đất, soi thẳng đến chỗ em.",
    "Selene_0042": "Thành Ephyra chào đón em trở lại, dù nơi này chẳng còn như xưa.",
    "Selene_0043": "Ta sẽ luôn soi sáng hành trình của em đến ngọn núi của các vị thần.",
    "Selene_0478": "Chào em gái Ánh Bạc, hãy ngắm lại ánh sáng dẫn đường của ta.",
    "Selene_0491": "Chúng ta quan sát tất cả những gì xảy ra.",
    "Selene_0492": "Sức mạnh của chúng ta lớn nhất khi không ai hay biết.",
    "Selene_0493": "Bất cứ khi nào cần ta, ta sẽ đến bên em.",
    "Selene_0494": "Ta và em hãy cùng tỏa sáng, hôm nay và mãi mãi.",
    "Selene_0495": "Sứ mệnh của ta là luôn bền bỉ và đáng tin cậy.",
    "Selene_0496": "Chị Em Ánh Bạc không bao giờ nhường quyền kiểm soát.",
    "Selene_0497": "Cùng nhau, ta và em sẽ giành chiến thắng.",
    "Selene_0498": "Ta hít thở, đổ máu, nghỉ ngơi rồi lại bắt đầu.",
    "Selene_0499": "Ánh sáng của chúng ta chẳng bao giờ tắt; trăng non rồi sẽ lại lên.",
    "Selene_0500": "Đêm nào cũng khác với mọi đêm ta từng biết.",
    "Selene_0490": "Bền chí mới là chìa khóa dẫn đến chiến thắng.",
    "Melinoe_0486": "Hỡi Mặt Trăng, người bạn thủy chung suốt bao đêm của con, con xin dâng Người chút lễ vật nhỏ nhoi này!",
    "Melinoe_1733": "Chị làm em vinh dự quá.",
    "MelinoeField_1934": "Nàng đã lạc khỏi đường mình... \n\n {#Emph}Hỡi Titan nữ vĩ đại, Con Mắt Đêm, \n {#Emph}Con khẩn cầu Người giáng xuống, ban cho con sức mạnh!",
    "Selene_0103": "Nyx kể với ta nhiều điều về anh trai em, vì sao nhỏ. Ta cũng xa cách anh trai mình, Helios, thần Mặt Trời. Đôi khi ta làm chậm bước ngựa để ngắm anh ấy soi rọi mặt đất. Ta nghĩ chúng ta chẳng có mấy chuyện để nói với nhau.",
    "Selene_0104": "Có lẽ một buổi sáng nào đó em sẽ gặp Eos trên mặt đất, vì sao nhỏ. Nàng đẹp đến nỗi người phàm cũng ngưỡng mộ. Nhưng ta chưa bao giờ thân thiết với nàng. Nàng chỉ xuất hiện chốc lát rồi lại biến mất.",
    "Selene_0336": "Hãy nhìn Mạo Diện Xinth mà ta từng sử dụng, vì sao nhỏ; có lẽ một ngày nào đó ta sẽ dùng lại. Thuở ấy, ánh sáng của ta khiến ai nấy khiếp sợ, cho đến khi ta nhận ra cách tiếp cận kín đáo hiệu quả hơn. Nhưng em không cần phải nương tay.",
    "Selene_0339": "Mạo Diện của Mẹ Nyx trên Áo Choàng Đen... Ta biết Người từng sử dụng Xinth, nhưng chưa bao giờ tận mắt chứng kiến, vì Người có thể gạt cả ánh sáng của {#Emph}ta{#Prev} sang bên. Thật vinh dự khi Mạo Diện ấy đã hiện ra với em.",
    "Selene_0345": "Những Mạo Diện bí ẩn của Vũ khí Màn Đêm... Ta hiểu chúng đến từ những vị thần xa xôi, cả những nữ thần bóng tối... tất cả đều bí ẩn, một số có lẽ vẫn chưa tìm được người sử dụng. Biết đâu chúng còn có chung một quy luật sâu xa hơn...",
    "Selene_0173": "Em đã đối đầu với Titan nơi vực sâu nhất... ta đã biết chuyện đó trước khi Sư phụ xác nhận em tiêu diệt được hắn; ta vẫn luôn tin em sẽ làm được. Nếu sinh lực hắn giống như cát, em mới lấy đi một hạt thôi; rồi cuối cùng sẽ lấy được {#Emph}tất cả.",
    "Selene_0370": "Em đã tiêu diệt Chronos ở một thời đại khác...? Hay là {#Emph}từ{#Prev} một thời đại khác, với sự trợ giúp của chính Titan ấy. Quyền năng của hắn ẩn chứa bao điều bí ẩn. Nhưng nếu cần làm vậy để thời gian của chúng ta lại tự do trôi tới, cứ tiến hành đi.",
    "Selene_0371": "Typhon không còn là mối đe dọa với chúng ta, vậy mà em còn đang cùng Titan Chronos bảo đảm hắn sẽ chẳng bao giờ có thể trở thành mối đe dọa nữa sao? Vậy thì cứ thế đi; là Chị Em Ánh Bạc, chúng ta bảo vệ cõi giới bằng mọi cách.",
    "Selene_0224": "Gần đây ta cảm thấy có thứ gì kéo mình về phía Ngã ba Địa Giới, rồi nhận ra đó là Hòn Đá Đen Tuyền. Vậy là nó đã thức tỉnh... trông như một Con Mắt, nhưng cổ xưa hơn ta nhiều, nhìn ra từ vực thẳm vô tận.",
    "Selene_0160": "Em phải ở đúng nơi mình đang đứng. Những trận chiến của em dưới Âm phủ ảnh hưởng đến cuộc chiến đang diễn ra trên này. Nhưng cứ để mặt đất cho các vị thần và ta. Đừng xao nhãng vì cánh cổng Ngã ba Địa Giới lên mặt đất đã bị phong ấn.",
    "Selene_0465": "Em đã rèn luyện đến mức đánh thức được cả Hypnos đang ngủ say mãi sao? Mẹ cậu ấy, Nyx, báo rằng cậu đã trở lại vị trí của mình, dù còn bao việc tồn đọng phải xử lý...",
    "Selene_0330": "Nữ phù thủy Medea đã học cách che khuất ánh sáng của ta, tạo ra nhật thực mỗi khi cần. Sau đó chúng ta trò chuyện và từ đó làm hòa. Kết hợp lời nguyền của nàng với Nguyền của ta, em sẽ khiến kẻ thù khiếp sợ.",
    "Selene_0462": "Tấm da sư tử Heracles đang khoác lên mình từng thuộc về một sinh vật thân thiết với ta. Ta căm ghét hắn, dù khi ấy hắn chỉ làm theo lệnh các vị thần, những kẻ muốn thử lòng trung thành của hắn. Nhưng giờ ta đã bỏ lại cơn giận phía sau.",
    "Selene_0461": "Thật lạ khi Polyphemus vụng về và Medea lại hợp tác, dù nguyên nhân là Lời Thề Đối Thủ. Nhưng lạ hơn là Cyclops ấy trở thành người chăn cừu thứ hai ta biết có thói quen ngủ li bì...",
    "Selene_0344": "Hai Titan Chronos và Prometheus đã lập liên minh, nhưng họ chẳng giống nhau lắm. Prometheus muốn một thế giới nơi người phàm không phải phục tùng thần linh sao? Chính hắn phải biết điều ấy sẽ chẳng bao giờ thành hiện thực.",
    "Selene_0348": "Chẳng điều gì thoát khỏi mắt Chị Em Ánh Bạc: ta ở trên trời; nữ thần săn bắn trên mặt đất; em ở dưới lòng đất; Phù thủy Ngã ba Địa Giới đứng giữa các cõi. Giờ chúng ta không chỉ quan sát mà còn hành động.",
    "Selene_0161": "Sứ mệnh của Chị Em Ánh Bạc là âm thầm phụng sự ý chí của Đêm. Olympus chẳng biết đến chúng ta; chẳng biết nữ thần săn bắn của họ là một trong chúng ta; chẳng biết sứ giả của họ cũng phục vụ chúng ta. Hãy giữ bí mật này.",
    "Selene_0360": "Đêm nay tối tăm khác thường, Nỗi Sợ đã lan đến mọi ngóc ngách của các cõi giới; là do em gây ra bằng Lời Thề, phải không? Vậy hãy cẩn thận, vì sao nhỏ, chẳng ai cứu được em khỏi những lựa chọn của chính mình.",
    "Selene_0361": "Ban đầu ta tưởng giác quan mình đánh lừa, nhưng mỗi đêm trôi qua ta càng chắc chắn... em đã hoàn thành tất cả Di huấn trong Lời Thề...! Ý chí của Đêm tạm thời đã được thực hiện. Sức bền bỉ của em khiến ta khâm phục.",
    "Selene_0073": "Em thật may mắn khi được Odysseus, người lữ khách nay đây mai đó, chỉ dạy. Ta từng dõi theo mọi gian truân của người phàm ấy, từ chiến trận đến những chuyến hải hành. Một số chuyện kể về ông có tô vẽ, nhưng không phải tất cả. Ông ấy thật thú vị.",
    "Selene_0059": "Olympus chẳng biết sức mạnh thật sự của ta hay của em. Mà như vậy cũng tốt. Chúng ta mạnh nhất khi hoạt động trong bóng tối, khi bị xem thường. Em đồng ý chứ?",
    "Selene_0074": "Chúng ta sẽ giúp Đức Vua và Nữ hoàng chính thống của Âm phủ giành lại ngai vàng. Ta chỉ biết cha em qua lời Nyx, nhưng từng gặp mẹ em khi bà đến thăm Olympus. Em có phong thái vương giả giống mẹ lắm, vì sao nhỏ.",
    "Selene_0082": "Bầu trời đêm rộng lớn cho ta tầm nhìn thuận lợi, và ta thấy rõ mọi gian khó em đang trải qua. Hãy nhớ rằng gian nan chỉ là một chặng đường. Hãy tìm niềm vui trong nhịp điệu của nó.",
    "Selene_0485": "Ai trong chúng ta cũng trải qua những giai đoạn khác nhau của đời mình. Còn ta thì đổi giai đoạn thường xuyên hơn hầu hết mọi người... vì ta luôn trân trọng sự bền vững, trong một kiếp sống mà điều duy nhất bền vững chính là đổi thay.",
    "Selene_0232": "Giờ ta đã chìm hẳn trong bóng tối; trăng non mở ra một khởi đầu mới. Hãy nương màn đêm che chở mà tiến đến mục tiêu của em.",
    "Selene_0070": "Em đã mất quá nhiều sinh lực rồi. Có lẽ lần này ta đến muộn mất. Nhưng chừng nào em còn đứng vững, em vẫn có thể vận dụng quyền năng lớn lao mà ta soi rọi trong em.",
    "Selene_0071": "Em đã bị thương nhiều rồi, vì sao nhỏ. Đau đớn dường như vốn là một phần trong vòng tuần hoàn đời ta. Ta không thể xóa bỏ nó, nhưng em có thể học cách gác nó sang bên.",
    "Selene_0072": "Em đang bị thương; ánh sáng của em cũng yếu dần, vì sao nhỏ. Đừng nản lòng. Ánh sáng của chúng ta chẳng bao giờ tắt. Trăng non rồi sẽ lại lên.",
    "Selene_0468": "Đêm nay kẻ thù đã khiến em đổ quá nhiều máu. Chẳng bao lâu nữa em sẽ hồi phục, nhưng cho đến lúc ấy, đừng để mất thêm giọt nào; hãy cố sống sót.",
    "Selene_0320": "Một buổi tối nữa lại mở ra bao khả năng. Ta đang trở về từ rạng đông, không thể ở lại lâu; hành trình đêm nay của em cũng bắt đầu rồi. Nào, ta và em hãy cùng tỏa sáng, hôm nay và mãi mãi.",
    "Selene_0083": "Màn đêm buông xuống, cũng là lúc nhiệm vụ của em bắt đầu. Ta sẽ dẫn em vào bóng tối ấy, hướng đến chiến thắng không thể tránh khỏi... và cái chết.",
    "Selene_0084": "Ta đến bên em ngay từ đầu vòng tuần hoàn này, soi sáng từng bước trên đường em đi. Con đường trông có vẻ quen thuộc thôi, nên hãy cẩn thận.",
    "Selene_0085": "Khi ánh ngày tắt trên mặt đất, chúng ta bắt đầu tỏa sáng. Ta sẽ đánh lạc hướng kẻ thù, còn em tiến gần hơn đến kết cục mà Chị Em Ánh Bạc đã thề sẽ biến thành hiện thực.",
    "Selene_0222": "Một đêm mới đang chờ đón. Ta sẽ phủ bóng tối để tiếp thêm sức mạnh và an ủi em. Hãy chọn phép thuật có ích nhất nhé.",
    "Selene_0230": "Chronos có thể chờ, vì hắn chính là Thời Gian. Em dồn sức tấn công quân đội của hắn trên mặt đất để làm chậm bước tiến của hắn. Trong lúc đó, em cũng ngày càng mạnh hơn.",
    "Selene_0469": "Ta đã quen tìm em dưới Âm phủ đến mức đôi khi vẫn ngạc nhiên khi thấy em trên mặt đất. Nơi này dễ chịu hơn với ta, nhưng lại khó khăn hơn cho em, phải không?",
    "Selene_0470": "Cuối cùng em cũng trở về cõi bóng tối sau bao đêm dưới bầu trời rộng mở. Vì việc cần làm, em nên ở nơi mình thuộc về, thay vì để ta ở đúng chỗ của ta.",
    "Selene_0471": "Ta hiểu điều em đang định làm. Titan Chronos vừa chịu thêm một thất bại, đây là cơ hội giúp Olympus trong cơn nguy khốn. Vậy hãy tỏa sáng vì các vị thần.",
    "Selene_0473": "Em đủ sức đối đầu cả quái vật như Typhon; Titan Chronos hẳn đã biết rõ điều đó. Có lẽ nghĩ đến ngày em tìm đến, hắn sẽ phải khiếp sợ.",
    "Selene_0474": "Ít ra đêm qua em cũng đánh lạc hướng Typhon rất tốt. Em sẽ còn cơ hội đánh bại hắn, có lẽ sau khi hạ Titan Chronos tối nay.",
    "Selene_0475": "Đêm này qua đêm khác, chiến thắng của em cứ chồng chất. Ta mong chẳng bao lâu nữa em sẽ giành thêm một chiến thắng. Có ánh sáng của ta, em sẽ dễ dàng đảm bảo kết quả ta và em mong muốn.",
    "Selene_0482": "Người phàm thường kính sợ hoặc tôn thờ chúng ta, rồi kể cho nhau nghe những chuyện khiến ta thành vĩ đại hơn hoặc tầm thường hơn thực tế. Ta thôi trách họ rồi; họ còn biết làm gì khác chứ?",
    "Selene_0350": "Đức Vua vĩ đại của các vị thần Olympus đã ban cho em một phần sức mạnh sấm sét. Chừng đó hẳn đã quá đủ, nhưng ta và em đừng để bất cứ điều gì xảy ra ngoài dự tính.",
    "Selene_0092": "Em nhận được Ân huệ của Nữ hoàng Hera, chuyện hiếm đấy. Thỉnh thoảng bà ấy tâm sự với ta lúc tắm. Gần đây bà ấy kín đáo hơn... mà tất cả chúng ta cũng vậy.",
    "Selene_0090": "Sức mạnh của thần biển đã chảy trong em rồi sao? Poseidon cho rằng chỉ mình ông ấy kiểm soát thủy triều. Ta chẳng trách ông ấy. Ông ấy không biết, cũng chẳng hiểu ảnh hưởng của ta.",
}

source = (SRC / "_LootData_Selene.en.sjson").read_text(encoding="utf-8-sig")
result = apply_translation_to_sjson(source, {k: {"DisplayName": v} for k, v in translations.items()})
target = TR / "_LootData_Selene.en.sjson"
target.parent.mkdir(parents=True, exist_ok=True)
target.write_text(result, encoding="utf-8")
sys.stdout.reconfigure(encoding="utf-8")
print(f"_LootData_Selene: {len(translations)} câu đã dịch")
