# -*- coding: utf-8 -*-
import json
import os

tips_dict = {
  "TipsTitle_000": "Góc Du Lịch: Tiện Ích Spocco Square",
  "Tips_000": "Sau một ngày dài chơi thể thao, bạn có thể dễ dàng đi mua sắm,\năn uống tại nhà hàng hoặc làm việc ở bất kỳ khu vực nào.",
  "TipsTitle_001": "Góc Du Lịch: Trang Phục Chính Thức",
  "Tips_001": "Có 8 màu trang phục thể thao chính thức dành cho tất cả mọi người.\nHãy tham gia trận đấu với màu sắc yêu thích của bạn!",
  "TipsTitle_002": "Góc Du Lịch: Dụng Cụ Thể Thao Chính Thức",
  "Tips_002": "Mỗi môn đều có sẵn dụng cụ thi đấu tiêu chuẩn (vợt, bóng...).\nHãy thử sức với môn thể thao mới và trải nghiệm chúng nhé!",
  "TipsTitle_003": "Góc Du Lịch: Sportsmate",
  "Tips_003": "Những người yêu thích tranh tài tại Spocco Square\nđược gọi thân mật là \"Sportsmate\".",
  "TipsTitle_004": "Góc Du Lịch: Nhạc Nền",
  "Tips_004": "Nhạc nền tại mỗi khu vực thi đấu được chọn lọc kỹ càng\nđể phù hợp với tinh thần của từng môn thể thao.",
  "TipsTitle_005": "Góc Du Lịch: Vật Phẩm Hợp Tác",
  "Tips_005": "Một số vật phẩm là sản phẩm hợp tác với các cửa hàng tại\nSpocco Square. Chúng chỉ mở bán có thời hạn, hãy nhớ kiểm tra\nmỗi tuần nhé!",
  "TipsTitle_006": "Góc Du Lịch: Viện Công Nghệ Thể Thao",
  "Tips_006": "Tại Viện Công Nghệ Thể Thao gần sân tennis, các nhà khoa học đang\nphát triển các bức tường trong suốt giúp giữ bóng đá không bay ra ngoài.",
  "TipsTitle_007": "Góc Du Lịch: Công Nghệ Thể Thao Tương Lai",
  "Tips_007": "Khi chơi Quần Vợt một mình, sân đấu tối tân của Spocco Square\ncó thể tạo ra đồng đội hình chiếu ba chiều (hologram) cho bạn!",
  "TipsTitle_008": "Góc Du Lịch: Xe Buýt Trung Chuyển",
  "Tips_008": "Cứ mỗi 15 phút sẽ có một chuyến xe buýt màu đỏ\nchạy đưa đón giữa các khu vực thi đấu.",
  "TipsTitle_009": "Góc Du Lịch: Biểu Ngữ Trận Đấu",
  "Tips_009": "Mỗi khu vực đều treo biểu ngữ đặc trưng của môn thể thao đó.\nHãy để ý quan sát trước khi trận đấu bắt đầu hoặc khi xem lại pha bóng!",
  "TipsTitle_010": "Góc Du Lịch: Vật Phẩm Giới Hạn",
  "Tips_010": "Sau mỗi trận đấu, bạn sẽ tích lũy điểm để nhận các vật phẩm giới hạn!\nThu thập chúng để tùy biến nhân vật theo phong cách riêng.",
  "TipsTitle_011": "Góc Du Lịch: Khu Vực Bóng Chuyền",
  "Tips_011": "Có một phòng trưng bày nghệ thuật ngay bên dưới sân thi đấu.\nĐây là chủ đề tuyệt vời để bắt chuyện với đồng đội đấy!",
  "TipsTitle_012": "Góc Du Lịch: Khu Vực Bóng Đá",
  "Tips_012": "Khu vực này có cả sân lớn và sân nhỏ.\nĐứng ở rìa sân này bạn có thể nhìn thấy sân kia đấy.",
  "TipsTitle_013": "Góc Du Lịch: Khu Vực Cầu Lông",
  "Tips_013": "Chủ quán Cafe Buttons cực kỳ mê mèo! Nhưng nếu thấy mèo của quán,\nxin đừng cho ăn nhé (chúng đang theo chế độ ăn đặc biệt).",
  "TipsTitle_014": "Góc Du Lịch: Khu Vực Bóng Chuyền",
  "Tips_014": "Khi du khách muốn thưởng thức một tách đồ uống nóng ấm cùng\ncuốn sách hay, tiệm sách humhum books là điểm đến lý tưởng nhất!",
  "TipsTitle_015": "Góc Du Lịch: Khu Vực Cầu Lông",
  "Tips_015": "Quán cafe tại đây được cải tạo từ một thùng container chở hàng!\nRất thích hợp cho những ai mê không gian nhỏ nhắn, ấm cúng.",
  "TipsTitle_016": "Góc Du Lịch: Khu Vực Cầu Lông",
  "Tips_016": "Chi nhánh thứ hai của tiệm Ice Cream Volley nằm tại khu này.\nBạn có biết chi nhánh đầu tiên ở đâu không?",
  "TipsTitle_017": "Góc Du Lịch: Khu Vực Quần Vợt",
  "Tips_017": "Sau những pha giao bóng nảy lửa, các tay vợt thường ghé ngay\nquán Lotus Juice Bar cạnh sân! Quán có nhiều món sinh tố thơm ngon\nvà súp tốt cho sức khỏe.",
  "TipsTitle_018": "Góc Du Lịch: Khu Vực Bóng Đá",
  "Tips_018": "Cảm hứng thiết kế khu bóng đá là \"nơi hội tụ văn hóa và thể thao\".\nThư viện nhìn ra sân có một góc rất lớn về lịch sử thể thao.",
  "TipsTitle_019": "Góc Du Lịch: Khu Vực Bóng Đá",
  "Tips_019": "Màn hình lớn cạnh thang máy trình chiếu các video quảng bá\ncho các cửa hàng tại Spocco Square.",
  "TipsTitle_020": "Góc Du Lịch: Khu Vực Chambara",
  "Tips_020": "Khách sạn Spocco có 25 phòng nghỉ sang trọng. Những chiếc giường êm ái\nlà nơi lý tưởng để ngả lưng sau một ngày dài thi đấu hết mình!",
  "TipsTitle_021": "Góc Du Lịch: Khu Vực Chambara",
  "Tips_021": "Nhà kho gạch đỏ nơi đặt võ đài Chambara đã được xây dựng\ntừ 100 năm trước khi khu vực này còn là một cảng biển sầm uất.",
  "TipsTitle_022": "Góc Du Lịch: Khu Vực Chambara",
  "Tips_022": "Khi võ đài Chambara trung tâm được tháo dỡ để bảo trì, hồ nước\nbên dưới đôi khi trở thành nơi biểu diễn bơi nghệ thuật.",
  "TipsTitle_023": "Góc Du Lịch: Khu Vực Quần Vợt",
  "Tips_023": "Thảm cỏ quanh sân Quần Vợt là nơi dạo bộ được yêu thích.\nNằm trên bãi cỏ, bạn có thể nghe thấy tiếng bóng nảy vui tai trên sân.",
  "TipsTitle_024": "Góc Du Lịch: Khu Vực Quần Vợt",
  "Tips_024": "Có các thiết bị bay không người lái (drone) hoạt động 24/7\nđể vớt những quả bóng tennis vô tình rơi xuống hồ nước quanh sân.",
  "TipsTitle_025": "Góc Du Lịch: Khu Vực Bowling",
  "Tips_025": "Khu Bowling nằm ngay trong trung tâm thương mại. Du khách thường\ntranh thủ ghé làm vài ván khi đang đi mua quà lưu niệm!",
  "TipsTitle_026": "Góc Du Lịch: Khu Vực Bowling",
  "Tips_026": "Sân bowling có một giếng trời lớn bằng kính,\ngiúp bạn vừa ném bóng vừa tận hưởng ánh nắng tự nhiên ngập tràn!",
  "TipsTitle_027": "Góc Du Lịch: Khu Vực Bóng Chuyền",
  "Tips_027": "Nhà thi đấu bóng chuyền được cải tạo từ một nhà kho lớn.\nÁnh nắng ấm áp rọi qua trần kính tạo nên không gian tuyệt đẹp.",
  "TipsTitle_028": "Góc Du Lịch: Khu Vực Bowling",
  "Tips_028": "Ghế sofa tại sân bowling là nơi lý tưởng để thư giãn và theo dõi trận đấu.\nDu khách còn có thể gọi đồ ăn và thức uống phục vụ tận nơi.",
  "TipsTitle_029": "Góc Du Lịch: Khu Vực Bowling",
  "Tips_029": "Cửa hàng Mount & Co. cạnh sân bowling là nơi chuyên cung cấp\ndụng cụ dã ngoại, cắm trại và thuyền du lịch.",
  "TipsTitle_030": "Góc Du Lịch: Quảng Trường Trung Tâm",
  "Tips_030": "Quảng trường trung tâm với biểu tượng chữ \"S\" lớn có quầy lễ tân\nđón tiếp du khách và các phòng thay đồ tiện nghi cho vận động viên.",
  "TipsTitle_031": "Nắm Vững Cơ Bản!",
  "Tips_031": "Nếu muốn học hoặc ôn lại cách điều khiển cho từng môn,\nhãy xem \u000e\u0000\u0003\u0002\u0001Cách chơi\u000e\u0000\u0003\u0002 trong phần \u000e\u0000\u0003\u0002\u0001Tùy chọn\u000e\u0000\u0003\u0002.",
  "TipsTitle_032": "Dân Chuyên Cũng Cần Nghỉ Ngơi",
  "Tips_032": "Ngay cả khi đã lên chuyên nghiệp, bạn vẫn có thể tạm nghỉ thi đấu xếp hạng\nbằng cách vào \u000e\u0000\u0003\u0002\u0001Cài đặt người dùng\u000e\u0000\u0003\u0002 trong mục \u000e\u0000\u0003\u0002\u0001Tùy chọn\u000e\u0000\u0003\u0002.",
  "TipsTitle_033": "Giải Đấu Đẳng Cấp",
  "Tips_033": "Mỗi môn thể thao đều có một Giải Chuyên Nghiệp riêng.\nLiệu bạn có đủ tự tin lên chuyên nghiệp ở tất cả các môn?",
  "TipsTitle_034": "Mục Tiêu Hạng A!",
  "Tips_034": "Hạng Chuyên Nghiệp càng cao thì việc thăng hạng càng khó.\nHãy bắt đầu từ Hạng E và nỗ lực vươn lên Hạng A danh giá nhé!",
  "TipsTitle_035": "Danh Hiệu Độc Nhất Vô Nhị",
  "Tips_035": "Nghe đồn rằng bạn sẽ nhận được một danh hiệu cực kỳ đặc biệt\nnếu đạt Hạng A ở tất cả các môn thuộc Giải Chuyên Nghiệp.",
  "TipsTitle_036": "Vật Phẩm Mới Mỗi Tuần",
  "Tips_036": "Trang phục, phụ kiện và dụng cụ mới được cập nhật vào mỗi tuần.\nNếu chơi đều đặn vào dịp cuối tuần, bạn sẽ không bỏ lỡ món nào đâu!",
  "TipsTitle_037": "Ưu Đãi Có Thời Hạn",
  "Tips_037": "Mỗi bộ sưu tập vật phẩm chỉ mở khóa trong vòng 3 tuần.\nHãy nhanh tay sở hữu những món đồ yêu thích trước khi hết hạn nhé!",
  "TipsTitle_038": "Đừng Bỏ Lỡ Bộ Sưu Tập!",
  "Tips_038": "Có tin đồn rằng sau khi hết thời hạn 3 tuần, những vật phẩm đó\nsẽ rất lâu sau mới có cơ hội xuất hiện trở lại.",
  "TipsTitle_039": "Bí Mật Của Danh Sách Quà",
  "Tips_039": "Vật phẩm mở bán trong tuần của bạn có thể khác với người chơi khác,\nnhưng nếu kiên trì thi đấu, bạn sẽ sưu tầm được trọn bộ.",
  "TipsTitle_040": "Thú Vị Về Danh Hiệu",
  "Tips_040": "Danh hiệu của đối thủ sẽ hiển thị theo ngôn ngữ của họ.\nNếu thử dịch ra, có thể bạn sẽ phát hiện những biệt danh siêu hài hước đấy!",
  "TipsTitle_041": "Tìm Trận Cực Nhanh",
  "Tips_041": "Bạn có thể chọn cùng lúc 3 môn trong \u000e\u0000\u0003\u0002\u0001Chơi trực tuyến\u000e\u0000\u0003\u0002,\u000e\u0000\u0003\u0002\u0001 \u000e\u0000\u0003\u0002hoặc chọn\n\u000e\u0000\u0003\u0002\u0002Ngẫu nhiên \u000e\u0000\u0003\u0002để tìm kiếm đối thủ nhanh chóng hơn.",
  "TipsTitle_042": "Cài Đặt Tay Thuận",
  "Tips_042": "Để đổi tay thuận cho từng môn thể thao, hãy vào mục\n\u000e\u0000\u0003\u0002\u0001Cài đặt người dùng\u000e\u0000\u0003\u0002 trong phần \u000e\u0000\u0003\u0002\u0001Tùy chọn\u000e\u0000\u0003\u0002.",
  "TipsTitle_043": "Chờ Một Chút Đã!",
  "Tips_043": "Nhấn \u000e\u0000\u0003\u0002\u0000\u000e\u0000\u0003\u0002\u0002\u000e\u0000\u0003\u0002\u0000 \u000e\u0000\u0003\u0002để tạm dừng trận đấu trong chế độ \u000e\u0000\u0003\u0002\u0001Chơi trên cùng một máy\u000e\u0000\u0003\u0002.\nKhi tạm dừng, bạn có thể bắt đầu lại hoặc thay đổi luật chơi.",
  "TipsTitle_044": "Khi Mãi Không Thắng Nổi...",
  "Tips_044": "Đường tắt để tiến bộ nhanh là hãy quan sát kỹ đối thủ.\nTự hỏi bản thân xem: \"Làm sao họ lại đánh được cú bóng hiểm như vậy?\"",
  "TipsTitle_045": "Lên Đồ Lấy Lại Tinh Thần",
  "Tips_045": "Những lúc thua 3 ván liền và cảm thấy nản lòng, cách tốt nhất là\n\u000e\u0000\u0003\u0002\u0002đổi mới diện mạo \u000e\u0000\u0003\u0002và quay lại sân đấu với khí thế như một tân binh rực lửa!",
  "TipsTitle_046": "Sàn Đấu Thời Trang Thực Thụ",
  "Tips_046": "Dù có thể thua trận đấu, nhưng biết đâu bạn đã thắng cuộc thi thời trang?\nĐôi khi thay đổi góc nhìn sẽ tiếp thêm động lực mới cho bạn đấy.",
  "TipsTitle_047": "Phải Chăng Là Kỳ Phùng Địch Thủ?",
  "Tips_047": "Mỗi đối thủ bạn gặp ĐỀU CÓ THỂ là tri kỷ định mệnh trên sàn đấu,\nmở ra chuỗi ngày so tài đầy kịch tính khó quên suốt đời. Hoặc cũng có thể không!",
  "TipsTitle_048": "Đang Chờ Lọt Vào Mắt Xanh?",
  "Tips_048": "Các tuyển trạch viên Giải Chuyên Nghiệp luôn âm thầm theo dõi mọi trận đấu.\nBạn càng thi đấu nhiều, cơ hội được chú ý càng cao.",
  "TipsTitle_049": "Chụp Ảnh Lưu Niệm Đáng Nhớ",
  "Tips_049": "Nhấn\u000e\u0000\u0003\u0002\u0002  \u000e\u0000\u0003\u0002trên Joy-Con (L) để chụp màn hình. Hãy lưu giữ lại những\nkhoảnh khắc vinh quang rực rỡ nhất hoặc cả những pha ngã đau buồn cười.",
  "TipsTitle_050": "Chăm Sóc Bản Thân",
  "Tips_050": "Đừng quên nghỉ ngơi sau một thời gian thi đấu nhé. Uống chút nước,\năn nhẹ một lát — chúng tôi luôn sẵn sàng khi bạn trở lại!",
  "TipsTitle_051": "Độc Đáo Như Chính Bạn",
  "Tips_051": "Bạn có thể ghép tối đa hai danh hiệu theo bất kỳ thứ tự nào,\ntạo ra vô số cách xưng hô thú vị. Hãy thử nghiệm những cách ghép bất ngờ nhất!",
  "TipsTitle_052": "Tắt Tem Cảm Xúc Để Tập Trung",
  "Tips_052": "Nếu không muốn nhìn thấy tem biểu cảm trong trận đấu, bạn có thể\ntắt chúng trong phần \u000e\u0000\u0003\u0002\u0001Cài đặt người dùng\u000e\u0000\u0003\u0002 ở mục \u000e\u0000\u0003\u0002\u0001Tùy chọn\u000e\u0000\u0003\u0002.",
  "TipsTitle_053": "Thích Gì Dùng Nấy",
  "Tips_053": "Việc đổi các dụng cụ thi đấu như vợt hay kiếm không làm ảnh hưởng\nđến chỉ số thi đấu, nên cứ thoải mái chọn món đồ bạn thấy đẹp mắt nhất!",
  "TipsTitle_054": "Muốn Luyện Tập Một Mình?",
  "Tips_054": "Bạn có thể chơi một mình với máy CPU trong chế độ \u000e\u0000\u0003\u0002\u0001Chơi trên cùng một máy\u000e\u0000\u0003\u0002.\nRất lý tưởng để rèn luyện kỹ năng theo nhịp độ của riêng bạn.",
  "TipsTitle_055": "Bói Vui: Môn Thể Thao May Mắn Của Bạn...",
  "Tips_055": "Bóng Đá!\n\nCó thể bạn sẽ chọn được vị trí hoàn hảo để sút tung lưới...",
  "TipsTitle_056": "Bói Vui: Môn Thể Thao May Mắn Của Bạn...",
  "Tips_056": "Bóng Đá!\n\nHôm nay rất thích hợp để tập trung chuyền bóng kiến tạo cho đồng đội...",
  "TipsTitle_057": "Bói Vui: Môn Thể Thao May Mắn Của Bạn...",
  "Tips_057": "Bóng Đá!\n\nBiết đâu bạn sẽ nhận được một đường chuyền tuyệt đẹp từ người bạn thầm thích...",
  "TipsTitle_058": "Bói Vui: Môn Thể Thao May Mắn Của Bạn...",
  "Tips_058": "Bóng Chuyền!\n\nĐồng đội tốt là người luôn sẵn sàng nhử bóng cho nhau dứt điểm...",
  "TipsTitle_059": "Bói Vui: Môn Thể Thao May Mắn Của Bạn...",
  "Tips_059": "Bóng Chuyền!\n\nHôm nay là ngày đẹp trời để quan sát sân đấu trước khi đập bóng...",
  "TipsTitle_060": "Bói Vui: Môn Thể Thao May Mắn Của Bạn...",
  "Tips_060": "Bóng Chuyền!\n\nHãy gửi một chiếc tem biểu cảm để khích lệ tinh thần đồng đội nhé.",
  "TipsTitle_061": "Bói Vui: Môn Thể Thao May Mắn Của Bạn...",
  "Tips_061": "Cầu Lông!\n\nDù loạt cầu giằng co có kéo dài đến đâu, cũng đừng bao giờ nản chí!",
  "TipsTitle_062": "Bói Vui: Môn Thể Thao May Mắn Của Bạn...",
  "Tips_062": "Cầu Lông!\n\nHôm nay là một ngày tuyệt vời để tung ra những cú Bỏ Nhỏ hiểm hóc...",
  "TipsTitle_063": "Bói Vui: Môn Thể Thao May Mắn Của Bạn...",
  "Tips_063": "Cầu Lông!\n\nHãy chúc mừng đối thủ bằng một chiếc tem biểu cảm thật tinh tế.",
  "TipsTitle_064": "Bói Vui: Môn Thể Thao May Mắn Của Bạn...",
  "Tips_064": "Quần Vợt!\n\nCơ hội tung cú đập bóng uy lực chắc chắn sẽ sớm xuất hiện thôi.",
  "TipsTitle_065": "Bói Vui: Môn Thể Thao May Mắn Của Bạn...",
  "Tips_065": "Quần Vợt!\n\nCó thể hôm nay bạn sẽ tung ra liên tiếp những cú giao bóng tên lửa?",
  "TipsTitle_066": "Bói Vui: Môn Thể Thao May Mắn Của Bạn...",
  "Tips_066": "Quần Vợt!\n\nCách duy nhất dẫn đến thất bại là bạn không chịu vung vợt đánh bóng.",
  "TipsTitle_067": "Bói Vui: Môn Thể Thao May Mắn Của Bạn...",
  "Tips_067": "Chambara!\n\nHãy thử thách bản thân bằng một loại kiếm bạn chưa từng sử dụng.",
  "TipsTitle_068": "Bói Vui: Môn Thể Thao May Mắn Của Bạn...",
  "Tips_068": "Chambara!\n\nDù đánh trúng đối thủ liên tiếp, cũng đừng vội vàng tấn công quá đà nhé.",
  "TipsTitle_069": "Bói Vui: Môn Thể Thao May Mắn Của Bạn...",
  "Tips_069": "Chambara!\n\nKhông gì giúp kiếm sĩ trưởng thành nhanh bằng một trận thắng suýt sao trong gang tấc.",
  "TipsTitle_070": "Bói Vui: Môn Thể Thao May Mắn Của Bạn...",
  "Tips_070": "Bowling!\n\nHãy tưởng tượng các con ki là bạn bè người thân, và quả bóng là một cái ôm!",
  "TipsTitle_071": "Bói Vui: Môn Thể Thao May Mắn Của Bạn...",
  "Tips_071": "Bowling!\n\nCầu chúc cho cú ném của bạn không gặp phải thế chẻ ki (split) khó nhằn nhé.",
  "TipsTitle_072": "Bói Vui: Môn Thể Thao May Mắn Của Bạn...",
  "Tips_072": "Bowling!\n\nHãy nhớ rằng các con ki cũng đang sợ hãi bạn y hệt như bạn sợ chúng vậy.",
  "TipsTitle_073": "Chế Độ 2 Người Không Tính Điểm Chuyên Nghiệp",
  "Tips_073": "Sẽ không có lời mời gia nhập Giải Chuyên Nghiệp trong chế độ 2 người chơi.\nNhững ai đã có hạng cũng sẽ không bị tăng hay trừ điểm, nên cứ thoải mái vui chơi!",
  "TipsTitle_074": "Hình Phạt Khi Cố Ý Ngắt Kết Nối",
  "Tips_074": "\u000e\u0000\u0003\u0002\u0002Cố tình \u000e\u0000\u0003\u0002ngắt kết nối hoặc có hành vi phá hoại trong trận đấu\ncó thể làm giảm điểm xếp hạng của bạn và bị tạm thời đình chỉ thi đấu.",
  "TipsTitle_075": "Hướng Dẫn Tham Quan: Khu Vực Golf",
  "Tips_075": "Sân golf nằm trên một hòn đảo ngoài khơi gần Spocco Square.\nChỉ mất 30 phút đi cano cao tốc từ bến cảng là tới nơi.",
  "TipsTitle_076": "Hướng Dẫn Tham Quan: Khu Vực Golf",
  "Tips_076": "Du khách không chơi golf vẫn có thể tận hưởng cắm trại sang trọng\nvà những bãi biển riêng tư tuyệt đẹp tại đây.",
  "TipsTitle_077": "Hướng Dẫn Tham Quan: Khu Vực Golf",
  "Tips_077": "Khu vực này hợp tác thiết kế với sân golf Đảo Wuhu nổi tiếng.\nĐịa hình sân giữ nguyên thiết kế, nhưng quán cafe khoét vào vách đá thì hoàn toàn mới lạ.",
  "TipsTitle_078": "Bói Vui: Môn Thể Thao May Mắn Của Bạn...",
  "Tips_078": "Golf!\nĐó là lối tắt xuyên qua rặng cây... hay chỉ là mơ mộng hão huyền?",
  "TipsTitle_079": "Bói Vui: Môn Thể Thao May Mắn Của Bạn...",
  "Tips_079": "Golf!\nĐừng sợ những cơn gió. Cứ thuận theo tự nhiên mà gạt bóng!",
  "TipsTitle_080": "Bói Vui: Môn Thể Thao May Mắn Của Bạn...",
  "Tips_080": "Golf!\nMay mắn luôn mỉm cười với những tay gạt bóng táo bạo.",
  "TipsTitle_081": "Nếu Thắng Liên Tục Tại Giải Chuyên Nghiệp...",
  "Tips_081": "Mỗi trận thắng sẽ tăng cơ hội ghép bạn với đối thủ ở thứ hạng cao hơn.\nHãy tiếp tục leo lên đỉnh vinh quang!",
  "TipsTitle_082": "Thách Đấu Quán Quân",
  "Tips_082": "Trong \u000e\u0000\u0003\u0002\u0001Chơi trên cùng một máy\u000e\u0000\u0003\u0002, khi đến màn hình \"Độ mạnh CPU\"\nvà nhấn 【 \u000e\u0000\u0003\u0002\u0002 +  + \u000e\u0000\u0003\u0002 】 hoặc 【 \u000e\u0000\u0003\u0002\u0002 +  +  \u000e\u0000\u0003\u0002】tại nút \"OK\"...",
  "TipsTitle_083": "Kiểu Tóc Biến Đổi Theo Mũ",
  "Tips_083": "Khi bạn đội mũ hoặc phụ kiện đầu, kiểu tóc của bạn có thể tự thay đổi.\nBiết đâu bạn sẽ bất ngờ trước vẻ ngoài mới lạ và cuốn hút đấy!",
  "TipsTitle_084": "Tái Phát Hành Vật Phẩm Cũ",
  "Tips_084": "Trong \u000e\u0000\u0003\u0002\u0001Chơi trực tuyến\u000e\u0000\u0003\u0002,\u000e\u0000\u0003\u0002\u0001 \u000e\u0000\u0003\u0002nếu bạn thu thập đủ toàn bộ vật phẩm đang mở bán,\nnhững món đồ trong quá khứ bạn từng bỏ lỡ sẽ xuất hiện lại (chỉ 1 lần mỗi tuần).",
  "TipsTitle_085": "Vật Phẩm Đặc Biệt",
  "Tips_085": "Nếu đáp ứng các điều kiện đặc biệt, bạn có thể nhận được \u000e\u0000\u0003\u0002\u0002vật phẩm hiếm\u000e\u0000\u0003\u0002.\nHãy thử thách bản thân với những mục tiêu đầy gian nan nhé.",
  "TipsTitle_086": "Vật Phẩm Đặc Biệt: Chơi Cùng Máy",
  "Tips_086": "Nếu bạn đánh bại CPU Cường Địch (Powerhouse) hoặc đạt điểm kỷ lục trong môn Bowling\nhay vòng Golf 18 lỗ...",
  "TipsTitle_087": "Đồng Tâm Hiệp Lực",
  "Tips_087": "Nếu bạn thường xuyên tham gia \u000e\u0000\u0003\u0002\u0001Chơi trực tuyến \u000e\u0000\u0003\u0002ở chế độ 2 người chơi,\nđôi khi bạn sẽ nhận được một vật phẩm kỷ niệm đặc biệt đấy...",
  "TipsTitle_088": "Trải Nghiệm Chơi Golf Chân Thực Hơn",
  "Tips_088": "Nếu bạn chọn \u000e\u0000\u0003\u0002\u0001Chơi trên cùng một máy \u000e\u0000\u0003\u0002hoặc \u000e\u0000\u0003\u0002\u0001Chơi cùng bạn bè\u000e\u0000\u0003\u0002 và nhấn\n【\u000e\u0000\u0003\u0002\u0002  +  + \u000e\u0000\u0003\u0002 】 hoặc 【 \u000e\u0000\u0003\u0002\u0002 +  +  \u000e\u0000\u0003\u0002】tại biểu tượng môn \"Golf\"...",
  "TipsTitle_089": "Bói Vui: Môn Thể Thao May Mắn Của Bạn...",
  "Tips_089": "Bóng Rổ!\n\nChìa khóa dẫn đến chiến thắng là ném rổ dứt khoát, không do dự.",
  "TipsTitle_090": "Bói Vui: Môn Thể Thao May Mắn Của Bạn...",
  "Tips_090": "Bóng Rổ!\n\nNếu bị đối phương kèm chặt, hãy chuyền ngay cho đồng đội.",
  "TipsTitle_091": "Hướng Dẫn Tham Quan: Khu Vực Bóng Rổ",
  "Tips_091": "Sân bóng rổ trên tầng thượng này có tầm nhìn bao quát toàn bộ Spocco Square.\nRất tuyệt vời để chơi bóng trong khi tận hưởng làn gió biển mát rượi.",
  "TipsTitle_092": "Hướng Dẫn Tham Quan: Khu Vực Bóng Rổ",
  "Tips_092": "Thư giãn tại quán cafe ngoài trời. Bạn có thể xuất trình thẻ khán giả\nđể nhận tối đa 2 ly đồ uống miễn phí.",
  "TipsTitle_093": "Hướng Dẫn Tham Quan: Khu Vực Bóng Rổ",
  "Tips_093": "Để chào mừng lễ khánh thành sân tại Viện Công Nghệ Thể Thao,\nsẽ có một buổi hướng dẫn ném rổ mang tên \"Vào Rổ Tuyệt Đối!\""
}

def main():
    src_file = r"working/extracted_texts/USen/ProgramMsg__Tips.msbt.json"
    dst_file = r"translations/vi/ProgramMsg__Tips.msbt.json"
    
    with open(src_file, "r", encoding="utf-8") as f:
        src_data = json.load(f)
        
    out_data = {}
    missing = []
    for k, v in src_data.items():
        if k in tips_dict:
            out_data[k] = tips_dict[k]
        else:
            missing.append(k)
            out_data[k] = v
            
    os.makedirs(os.path.dirname(dst_file), exist_ok=True)
    with open(dst_file, "w", encoding="utf-8") as f:
        json.dump(out_data, f, ensure_ascii=False, indent=2)
        
    print(f"Translated ProgramMsg__Tips.msbt.json: {len(out_data)} entries. Missing: {len(missing)}")

if __name__ == "__main__":
    main()
