# -*- coding: utf-8 -*-

translations_100_200 = {
  "Flipendo_gameplay_desc": "Có thể khiến đồ vật và kẻ địch lộn nhào lên xuống. Nhờ thời gian hồi chiêu ngắn, bùa chú này rất thích hợp để thực hiện các đòn tung hứng đầy sáng tạo. Khả năng lập tức lật ngược vật thể cực kỳ thích hợp để giải đố hoặc khai thác điểm yếu của một số kẻ địch nhất định.",
  "FT_HW_PotionsClass": "Lớp Học Độc Dược",
  "FT_HW_PotionsClass_desc": "Phòng học Độc Dược của Giáo sư Sharp.",
  "Gear_Dark_SpellDamage_1": "Không Thể Tha Thứ I",
  "Gear_Dark_SpellDamage_1_desc": "Tăng sát thương gây ra lên các mục tiêu đang chịu ảnh hưởng của lời nguyền.",
  "Gear_Dark_SpellDamage_2": "Không Thể Tha Thứ II",
  "Gear_Dark_SpellDamage_2_desc": "Tăng đáng kể sát thương gây ra lên các mục tiêu đang chịu ảnh hưởng của lời nguyền.",
  "Gear_Dark_SpellDamage_3": "Không Thể Tha Thứ III",
  "Gear_Dark_SpellDamage_3_desc": "Tăng vượt trội sát thương gây ra lên các mục tiêu đang chịu ảnh hưởng của lời nguyền.",
  "Gear_GenDam_HeavySpell_1": "Tập Trung I",
  "Gear_GenDam_HeavySpell_1_desc": "Tăng sát thương của tất cả các bùa chú gây sát thương.",
  "Gear_GenDam_HeavySpell_2": "Tập Trung II",
  "Gear_GenDam_HeavySpell_2_desc": "Tăng đáng kể sát thương của tất cả các bùa chú gây sát thương.",
  "Gear_GenDam_HeavySpell_3": "Tập Trung III",
  "Gear_GenDam_HeavySpell_3_desc": "Tăng vượt trội sát thương của tất cả các bùa chú gây sát thương.",
  "Gear_SpecDam_Bombarda_1": "Thuốc Nổ I",
  "Gear_SpecDam_Bombarda_1_desc": "Tăng sát thương Bùa Nổ Công Phá (Bombarda).",
  "Gear_SpecDam_Bombarda_2": "Thuốc Nổ II",
  "Gear_SpecDam_Bombarda_2_desc": "Tăng đáng kể sát thương của \"Bùa Nổ Công Phá (Bombarda)\".",
  "Gear_SpecDam_Bombarda_3": "Thuốc Nổ III",
  "Gear_SpecDam_Bombarda_3_desc": "Tăng vượt trội sát thương của \"Bùa Nổ Công Phá (Bombarda)\".",
  "Gear_SpecDam_Confringo_1": "Phá Hủy I",
  "Gear_SpecDam_Confringo_1_desc": "Tăng sát thương \"Bùa Nổ Súng (Confringo)\".",
  "Gear_SpecDam_Confringo_2": "Phá Hủy II",
  "Gear_SpecDam_Confringo_2_desc": "Tăng đáng kể sát thương của \"Bùa Nổ Súng (Confringo)\".",
  "Gear_SpecDam_Confringo_3": "Phá Hủy III",
  "Gear_SpecDam_Confringo_3_desc": "Tăng vượt trội sát thương của \"Bùa Nổ Súng (Confringo)\".",
  "Gear_SpecDam_Crucio_1": "Tàn Nhẫn I",
  "Gear_SpecDam_Crucio_1_desc": "Tăng sát thương Lời Nguyền Tra Tấn (Crucio).",
  "Gear_SpecDam_Crucio_2": "Tàn Nhẫn II",
  "Gear_SpecDam_Crucio_2_desc": "Tăng đáng kể sát thương của Lời Nguyền Tra Tấn (Crucio).",
  "Gear_SpecDam_Crucio_3": "Tàn Nhẫn III",
  "Gear_SpecDam_Crucio_3_desc": "Tăng vượt trội sát thương của Lời Nguyền Tra Tấn (Crucio).",
  "Gear_SpecDam_Diffindo_1": "Xé Rách I",
  "Gear_SpecDam_Diffindo_1_desc": "Tăng sát thương \"Bùa Cắt Sâu (Diffindo)\".",
  "Gear_SpecDam_Diffindo_2": "Xé Rách II",
  "Gear_SpecDam_Diffindo_2_desc": "Tăng đáng kể sát thương của \"Bùa Cắt Sâu (Diffindo)\".",
  "Gear_SpecDam_Diffindo_3": "Xé Rách III",
  "Gear_SpecDam_Diffindo_3_desc": "Tăng vượt trội sát thương của \"Bùa Cắt Sâu (Diffindo)\".",
  "Gear_SpecDam_Expelliarmus_1": "Tước Khí I",
  "Gear_SpecDam_Expelliarmus_1_desc": "Tăng sát thương Bùa Giải Giới (Expelliarmus).",
  "Gear_SpecDam_Expelliarmus_2": "Tước Khí II",
  "Gear_SpecDam_Expelliarmus_2_desc": "Tăng đáng kể sát thương của Bùa Giải Giới (Expelliarmus).",
  "Gear_SpecDam_Expelliarmus_3": "Tước Khí III",
  "Gear_SpecDam_Expelliarmus_3_desc": "Tăng vượt trội sát thương của Bùa Giải Giới (Expelliarmus).",
  "Gear_SpecDam_Imperio_1": "Thao Túng I",
  "Gear_SpecDam_Imperio_1_desc": "Gây thêm sát thương lên mục tiêu chịu Lời Nguyền Độc Đoán (Imperio).",
  "Gear_SpecDam_Imperio_2": "Thao Túng II",
  "Gear_SpecDam_Imperio_2_desc": "Tăng đáng kể sát thương gây ra lên các mục tiêu chịu ảnh hưởng của Lời Nguyền Độc Đoán (Imperio).",
  "Gear_SpecDam_Imperio_3": "Thao Túng III",
  "Gear_SpecDam_Imperio_3_desc": "Tăng vượt trội sát thương gây ra lên các mục tiêu chịu ảnh hưởng của Lời Nguyền Độc Đoán (Imperio).",
  "Gear_SpecDam_Incendio_1": "Bỏng Rát I",
  "Gear_SpecDam_Incendio_1_desc": "Tăng sát thương Bùa Lửa (Incendio).",
  "Gear_SpecDam_Incendio_2": "Bỏng Rát II",
  "Gear_SpecDam_Incendio_2_desc": "Tăng đáng kể sát thương của Bùa Lửa (Incendio).",
  "Gear_SpecDam_Incendio_3": "Bỏng Rát III",
  "Gear_SpecDam_Incendio_3_desc": "Tăng vượt trội sát thương của Bùa Lửa (Incendio).",
  "GEN_SpellLoadouts_1": "Kiến Thức Bùa Chú I",
  "GEN_SpellLoadouts_1_desc": "Đã thêm một bộ bùa chú mới.",
  "GEN_SpellLoadouts_1_Gamepad_desc": "Đã thêm một bộ bùa chú mới. Giữ {CM_GamePad_RightTrigger} và nhấn theo một hướng trên <img src=\"NX_dpad\"/> để chuyển đổi giữa các bộ bùa chú đã mở khóa.",
  "GEN_SpellLoadouts_1_MKB_desc": "Đã thêm một bộ bùa chú mới. Sử dụng {Generic_Scroll} để cuộn giữa các bộ bùa chú đã mở khóa, hoặc dùng {AM_Loadout1} {AM_Loadout2} {AM_Loadout3} {AM_Loadout4} để chuyển đổi các bộ khác nhau.",
  "GEN_SpellLoadouts_1_requirements": "Điều kiện mở khóa tài năng: Hoàn thành nhiệm vụ \"Luyện Tập Bùa Chú\".",
  "GEN_SpellLoadouts_2": "Kiến Thức Bùa Chú II",
  "GEN_SpellLoadouts_2_desc": "Đã thêm một bộ bùa chú mới.",
  "GEN_SpellLoadouts_2_Gamepad_desc": "Đã thêm một bộ bùa chú mới. Giữ {CM_GamePad_RightTrigger} và nhấn theo một hướng trên <img src=\"NX_dpad\"/> để chuyển đổi giữa các bộ bùa chú đã mở khóa.",
  "GEN_SpellLoadouts_2_MKB_desc": "Đã thêm một bộ bùa chú mới. Sử dụng {Generic_Scroll} để cuộn giữa các bộ bùa chú đã mở khóa, hoặc dùng {AM_Loadout1} {AM_Loadout2} {AM_Loadout3} {AM_Loadout4} để chuyển đổi các bộ khác nhau.",
  "GEN_SpellLoadouts_2_requirements": "Điều kiện mở khóa tài năng: Đạt cấp độ tối thiểu 10.",
  "GEN_SpellLoadouts_3": "Kiến Thức Bùa Chú III",
  "GEN_SpellLoadouts_3_desc": "Đã thêm một bộ bùa chú mới.",
  "GEN_SpellLoadouts_3_Gamepad_desc": "Đã thêm một bộ bùa chú mới. Giữ {CM_GamePad_RightTrigger} và nhấn theo một hướng trên <img src=\"NX_dpad\"/> để chuyển đổi giữa các bộ bùa chú đã mở khóa.",
  "GEN_SpellLoadouts_3_MKB_desc": "Đã thêm một bộ bùa chú mới. Sử dụng {Generic_Scroll} để cuộn giữa các bộ bùa chú đã mở khóa, hoặc dùng {AM_Loadout1} {AM_Loadout2} {AM_Loadout3} {AM_Loadout4} để chuyển đổi các bộ khác nhau.",
  "GEN_SpellLoadouts_3_requirements": "Điều kiện mở khóa tài năng: Đạt cấp độ tối thiểu 20.",
  "Glacius": "Bùa Đóng Băng (Glacius)",
  "Glacius_desc": "Làm đóng băng kẻ địch, mục tiêu bị đóng băng sẽ phải chịu thêm sát thương.",
  "Glacius_gameplay_desc": "Làm đóng băng kẻ địch, mục tiêu bị đóng băng sẽ phải chịu thêm sát thương.",
  "Hamlet_Bainburgh_MercuryPotion": "Thư Harriet gửi Lorne",
  "Hamlet_Bainburgh_MercuryPotion_desc": "Bức thư Harriet gửi cho anh trai Lorne, trong thư bà bày tỏ sự lo ngại về mức độ an toàn khi vợ của Lorne sử dụng thủy ngân lỏng để tiến hành các thí nghiệm độc dược.",
  "Hint_AccioReminder": "Bùa Triệu Tập (Accio)",
  "Hint_AccioReminder_desc": "\"Bùa Triệu Tập (Accio)\" có thể kéo các mục tiêu có móc kéo Accio về phía bạn.",
  "Hint_AssignNewSpells": "Gán Bùa Chú Mới",
  "Hint_AssignNewSpells_desc1": "Gán bùa chú mới {UMGActionScreenToggle}",
  "Hint_CCSpells": "Bùa chú khống chế có thể đánh tan bùa khiên màu vàng.",
  "Hint_Incendio": "Sử dụng các bùa chú gây sát thương cao như \"Bùa Lửa (Incendio)\" để nhanh chóng hạ gục kẻ địch.",
  "Hint_IncendioVines": "\"Bùa Lửa (Incendio)\" có thể đốt cháy mạng nhện và dây gai.",
  "Hint_Leviosobreakingshield": "Hãy thử dùng \"Bùa Bay Lơ Lửng (Levioso)\" để phá vỡ khiên của kẻ địch.",
  "Hint_PNP_AccioPlatforms": "\"Bùa Triệu Tập (Accio)\" có thể kéo các bục đã được ếm bùa lại gần.",
  "Hint_ReparoReminder": "Bùa Sửa Chữa (Reparo)",
  "Hint_ReparoReminder_desc": "\"Bùa Sửa Chữa (Reparo)\" có thể dùng để sửa chữa các đồ vật bị hư hỏng trong môi trường.",
  "Hint_RevelioLostPages": "Trang Cẩm Nang Phù Thủy",
  "Hint_RevelioLostPages_desc": "Sử dụng \"Bùa Hiện Hình (Revelio)\" để tìm kiếm các trang Cẩm Nang Phù Thủy.",
  "Hint_RevelioReminder": "Bùa Hiện Hình (Revelio)",
  "Hint_RevelioReminder_desc": "{RevelioButton} Bùa Hiện Hình (Revelio)",
  "HintWrongSpell": "Sử dụng bùa chú tương ứng để phá vỡ khiên chắn",
  "HM_JPippensPotions": "Tiệm Độc Dược J. Pippin",
  "HM_JPippensPotions_desc": "Cửa hàng cung cấp đa dạng các loại độc dược và nguyên liệu pha chế.",
  "HOG_Class_Potions": "Lớp Học Độc Dược",
  "HOG_Class_Potions_desc": "Phòng học nơi học sinh tiếp thu kỹ nghệ pha chế các hỗn hợp ma thuật.",
  "HOG_PotionsClassroom": "Phòng Học Độc Dược",
  "HOG_PotionsClassroom_Desc": "Hầm ngục u tối được dùng làm phòng học môn Độc Dược.",
  "Hogwarts_PotionsClassroom_SharpOfficeNote": "Bản Ghi Nhớ của Bộ Pháp Thuật"
}

if __name__ == '__main__':
    print(f"Loaded {len(translations_100_200)} keys.")
